### ISSUE TITLE
The first case and death in input is not reflected in new_deaths and new_cases in full_data.csv

### ISSUE THREAD

**Issue by mathiastj** [owid/covid-19-data#1]
Examples:

- Philipines, 2020-02-02

From deaths.csv: 1 new death

Entry in full_data.csv:

| date | location | new_cases | new_deaths | total_cases | total_deaths | 
| --- | --- | --- | --- | ---| --- | 
| 2020-02-02 | Philippines | 1 |   | 2 | 1 | 

- Singapore 2020-01-24

From cases.csv: 1 new case

Entry in full_data.csv:

| date | location | new_cases | new_deaths | total_cases | total_deaths | 
| --- | --- | --- | --- | ---| --- | 
2020-01-24 | Singapore |   |   | 1 |  

- Vietnam 2020-01-24

From cases.csv: 2 new cases

Entry in full_data.csv:

| date | location | new_cases | new_deaths | total_cases | total_deaths | 
| --- | --- | --- | --- | ---| --- | 
2020-01-24 | Vietnam |   |   | 2 |

**Comment by danielgavrilov** [comment]
Thanks for reporting @mathiastj! 

We don't have this issue with the [dataset from the ECDC](https://github.com/owid/covid-19-data/tree/master/public/data/ecdc), which we've recently switched to. 

The WHO dataset we are no longer maintaining and will stay the way it is unfortunately.
