### ISSUE TITLE
Spain tests data

### ISSUE THREAD

**Issue by GermanCM** [owid/covid-19-data#10]
Dear team,

As I can see in https://github.com/owid/covid-19-data/tree/master/public/data/testing there are no Spain tests data source, can you give me some more info about it? Is there a reason fir this lack of data?

Thanks in advance,
Germán

**Comment by edomt** [comment]
Hi Germán,

So far we haven't found (or received) any reliable information on COVID-19 tests in Spain, hence the absence of the country in our own dataset. If you know a good source, we'd be more than happy to include Spain as it's such an important case in this context.

Edouard

**Comment by GermanCM** [comment]
Dear @edomt the numbers of covid tests per country I found including Spain (although not as a time series evolution) are these ones: https://www.worldometers.info/coronavirus/#countries do you have any reference/opinion about this page?

**Comment by edomt** [comment]
Hi German,
Unfortunately Worldometers is collecting very low-quality data, and their estimate for Spain (355,000) in particular is based on unconfirmed data. See here: https://twitter.com/MaxCRoser/status/1248593099380666369
Edouard
