### ISSUE TITLE
Peru incremental batch update

### ISSUE THREAD

**Issue by lucasrodes** [owid/covid-19-data#1012]
Just some thoughts on the vaccination data update for Peru, which currently runs a bit slow mainly due to the fact that a large CSV file needs to be downloaded.

I have found and tested two alternatives to vaccination update:

- **API call**: https://gis.minsa.gob.pe/WebApiRep2/api/ActVacunasResumen/ResumenFasePublico (needs header)
- **HTML scraping**: https://www.gob.pe/vacunacovid19

Pros: Reduce time it takes for current Peru automation to run (no large file downloaded)
Cons: Corrections of past days' numbers would not be possible.

Not sure if it would be worth it. Just posting it here so we keep this issue in mind (and eventually might decide to keep it batch or go for incremental).

**Comment by edomt** [comment]
They seem to be making many corrections to past days (e.g. your update this morning impacted data all the way back to 2021-02-15), so _ideally_ we'll stick to batch as long as possible.
