### ISSUE TITLE
Gibraltar has more than 100% population vaccinated once?

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#1013]
My App gave me an error when I looked at the Gibraltar data. I traced it to the file "vaccinations.csv" and extract the lines below. If you look at the items 3rd from right which is "people_vaccinated_per_hundred" which is a percentage I think. I see the value is "100.85" which is more than the whole. I may have misunderstood what the figure is and if so, my apologies. 

location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,**people_vaccinated_per_hundred**,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
Gibraltar,GIB,2021-04-10,63671,33979,29692,654,190,188.99,**100.85**,88.13,5639

**Comment by lucasrodes** [comment]
Hi @zizwiz, 
Nice catch, thanks for reporting. 

Apparently, there the number of administered vaccinations ([source data reference](https://twitter.com/GibraltarGov/status/1380850508752125957)) exceeds our [value for Gibraltar's population ](https://github.com/owid/covid-19-data/blob/master/scripts/input/un/population_2020.csv).

We'll be reviewing it.

**Comment by lucasrodes** [comment]
For now, we will be leaving these as it is. Note that a country may vaccinate more people than residents there are.

Thanks for reporting
