### ISSUE TITLE
Vaccinations: Japan has moved its data

### ISSUE THREAD

**Issue by awh-tokyo** [owid/covid-19-data#1019]
The automated collection has been retrieving data from https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/vaccine_sesshujisseki.html but there is currently a note:

> ※４月１２日以降の接種回数などについては、首相官邸ホームページをご覧ください。

For vaccination counts etc. after April 12th, view the Prime Minister Office's home page

The Prime Minister Office's home page for vaccinations is located at https://www.kantei.go.jp/jp/headline/kansensho/vaccine.html

So far, they don't seem to be publishing any data besides a daily total count of injections, without specifying per-day or whether they're first or second doses.

I don't know if this is enough data to automate anymore, but if so, the text to scrape is at the top of the page:

これまでのワクチン総接種回数（令和３年４月１２日）

医療従事者等：1,689,453回
高齢者：1,139回

令和３年 is the current year (next year will be 令和４年), and ４月１２日 is the date (April 12 in this case).  The numbers given are the total injections to date, both first and second shots.  The first number is for medical professionals; the second is for elderly.  That is, the correct total vaccinations to date is the sum of both numbers.

I hope they will publish the data in an easier-to-use way soon.

**Comment by awh-tokyo** [comment]
The first and second shot data (for medical professionals; seniors just started today and therefore all only have one shot) have been published in the Prime Minister Office's twitter:  https://twitter.com/kantei_vaccine/status/1381586088712564743

**Comment by edomt** [comment]
Thank you @awh-tokyo! And yes, please let us know if you come across a better/more detailed format at some point :)

**Comment by AnnaNishino** [comment]
@edomt 
Hi, FYI the prime minister office has just published the excel data;
https://www.kantei.go.jp/jp/headline/kansensho/vaccine.html

医療従事者等 (https://www.kantei.go.jp/jp/content/IRYO-vaccination_data.xlsx) = vaccinations to the medical professionals
高齢者 (https://www.kantei.go.jp/jp/content/KOREI-vaccination_data.xlsx) = vaccinations to the elderly

The sum of both numbers should be the whole vaccination for a certain day.

**Comment by awh-tokyo** [comment]
@AnnaNishino 

Good find; I've been updating their webpage and twitter feed since last night looking for it.

I'm not convinced that the data is correct for the elderly vaccinations yet.  The data listed for Tuesday says 1,179 shots and Monday says 1,563 shots, but on Monday night they published 1,179 as Monday's figure.

**Comment by AnnaNishino** [comment]
Thank you for pointing out!

I have talked to the prime minister office over the phone, and they said that those excel files are subject to change since the latest numbers are as of 5PM (the medical professionals) or 7PM at a certain day, so if the data comes after that time, it should be counted as the vaccinations for the date inoculated, NOT the date submitted.

I hope they mention this note somewhere in the webpage as well.

**Comment by edomt** [comment]
Thank you both very much! We've now migrated our data collection to the two Excel files.
