### ISSUE TITLE
high negative value for GBR

### ISSUE THREAD

**Issue by felixgolcher** [owid/covid-19-data#103]
Thank you for all the data!

I know there may occur negative values for new cases due to corrections. But some are really high, especially one for the United Kingdom. Is there a special explanation for that, or is it just a _very_huge_ correction?

The line in owid-covid-data.csv is currently line 27526: `GBR,Europe,United Kingdom,2020-07-03,283757.0,-29726.0,...`.

**Comment by johnfmaner** [comment]
The readme mentions why negative numbers may occur:

https://github.com/owid/covid-19-data/tree/master/public/data#our-data-sources

**Comment by edomt** [comment]
Hi @felixgolcher!

Yes, this is "just" a huge data correction, unfortunately. The ECDC is working with the UK government to see how to best adjust the time series. See this tweet for more information: https://twitter.com/_HannahRitchie/status/1278991659083214848

Edouard
