### ISSUE TITLE
UK daily cases is Negative?

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#1038]
Sorry to bother you again but my app gives me an error with UK daily cases. Not sure the error is yours but probably where the data originates from. 

I look at 

covid-19-data/public/data/jhu/total_cases.csv

and then as shown in the small sample below on 09 April 2021 UK had -4787 cases. I shortened the part below by just extracting the data to show you as the whole file is much larger.

  | United Kingdom cases |
Date            | Total       | Daily
06/04/2021 | 4379033 |  
07/04/2021 | 4381830 | 2797
08/04/2021 | 4384954 | 3124
09/04/2021 | 4380167 | -4787
10/04/2021 | 4382880 | 2713
11/04/2021 | 4384610 | 1730

Thanks for the data and all your work.

**Comment by edomt** [comment]
Hi @zizwiz 

It seems like a negative data correction was indeed published by the UK government on April 9.
We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues

**Comment by zizwiz** [comment]
Just in case anyone else sees the same artifact, after some digging with help from @edomt and from Johns Hopkins University I find the origin of the issue @ https://coronavirus.data.gov.uk/details/whats-new relevant bit extracted below. Thanks for the help. 

Looks like this will remain with the negative cases.

9 April
Change to case reporting in England
The way cases are reported has changed. Cases that have been identified through a positive rapid lateral flow test will be removed for people who took Polymerase Chain Reaction (PCR) tests within 3 days that were all negative. Cases of this type that were previously reported were removed from the cumulative total, reducing the total by 8,010. Newly reported numbers of cases for the UK and England were unaffected by the removal of these. Historical published date totals have not been changed.

Newly reported cases at regional and local authority level within England are calculated as the daily change in the total number of cases. This means that for 9 April 2021, these show significantly lower numbers or zero, and should not be considered as the actual number of new cases reported on that date. Details of the changes and numbers of newly reported cases for 9 April 2021 are available in csv (wide format) and csv (long format).
