### ISSUE TITLE
How to read the CSV file 

### ISSUE THREAD

**Issue by Joyning-cn** [owid/covid-19-data#104]
I have downloaded the data file ，but I don't any UNITS by the columns , at "cvd-death-rate" , I don't understand why the number would be 5xx .  I thought it should be a percent.

**Comment by edomt** [comment]
Hi @Joyning-cn 

We've updated our [codebook](https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data-codebook.md) to better describe this variable:

> Death rate from cardiovascular disease in 2017 (annual number of deaths per 100,000 people)

Edouard
