### ISSUE TITLE
US vaccinations discrepency

### ISSUE THREAD

**Issue by jarnold231** [owid/covid-19-data#1045]
Hi there, 

Looking at US vaccination data:

Total vaccinations = 192,282,781
People vaccinated = 122,295,530
People fully vaccinated = 75,322,283

Seems there's a discrepency of 5.3 million or so. Can you clarify why this difference exists, previously been running these numbers and hadn't seen such a high level of difference.

Thanks
Jake

**Comment by edomt** [comment]
Hi @jarnold231 

The US is using the J&J vaccine, which is a 1-dose vaccine, so the general equivalence of `total_vaccinations` = `people_vaccinated` + `people_fully_vaccinated` doesn't apply to the US data.

You can find the latest full data from the CDC here: https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/us_states/input/cdc_data_2021-04-14.csv

**Comment by jarnold231** [comment]
Would a more accurate way to understand this be:

`total_vaccinations` - `people_fully_vaccinated` = people receiving 1 dose of a two dose regimen?

**Comment by edomt** [comment]
Yes, that one should work in theory!
