### ISSUE TITLE
negative values for new cases,deaths and tests

### ISSUE THREAD

**Issue by nagarajbhat** [owid/covid-19-data#105]
Just noticed a few negative values for new cases, new deaths, and new tests, while I was exploring the data.
Especially a big downward spike for United kingdom on July 3rd for new cases. Is this a mistake?

![owid_covid_issue](https://user-images.githubusercontent.com/5552885/87536401-605c7c00-c6dc-11ea-9a05-6465b3d5fe1b.png)

(The graph is plotted using plotly express)

Here is the list of ids with negative values - 
![owid_covid_negativeid](https://user-images.githubusercontent.com/5552885/87539005-8552ee00-c6e0-11ea-97da-bafd54b6f1b0.PNG)

data source - https://ourworldindata.org/coronavirus-source-data

**Comment by edomt** [comment]
See #66
