### ISSUE TITLE
Segregate per country the % of the population vaccinated with each specific vaccine. 

### ISSUE THREAD

**Issue by macgahe** [owid/covid-19-data#1079]
In UAE ,even though 49.27% of the population has been vaccinated more than 70% of them were with Sinopharm vaccine, while the rest have had the Pfizer shot.

It is widely known Sinopharm vaccine effectiveness is really poor and still the WHO is reviewing  it.. Meaning that, because 49% of the population has been vaccinated, DOES NOT MEAN the herd immunity will be reached, mostly because the herd immunity is a combination about people vaccinated + how effective is the vaccine.. 

Having said that, I reckon herd immunity day's calculator should consider more than how many people have just only been vaccinated

**Comment by edomt** [comment]
Hi @macgahe 

I don't think that the UAE currently makes available data disaggregated by type of vaccine.

I'm not sure what you mean by "herd immunity day's calculator" — we don't have anything like this on the site?
