### ISSUE TITLE
Mexico vaccination data has some inconsistencies

### ISSUE THREAD

**Issue by Tecuidas** [owid/covid-19-data#1083]
Hi there!

I was looking mexican chart in ourworldindata.org and I found that Mexico has fewer people vaccinated on April 15 than two days before. Which seemed completely insane to me. I came to consult the data here and I see that there was some misinterpretation of the source. Where the doses that arrived to Mexico this week were confused with the total doses applied. As you can see on "IMAGE 1".
![IMAGE 1](https://user-images.githubusercontent.com/82689279/115136147-b1ceca00-9fd2-11eb-9bad-f4d7d2c509e1.png)
At the end of the same site, you can find a PDF with all the detailed information, which is always in the same format and thus be able to avoid those misunderstandings due to the language. As "IMAGE 2"
![IMAGE2](https://user-images.githubusercontent.com/82689279/115136270-86001400-9fd3-11eb-9fa8-47ba8d4a1331.png)
The necessary data is as shown in IMAGE 3 and IMAGE 4
![IMAGE 3](https://user-images.githubusercontent.com/82689279/115136729-9665be00-9fd6-11eb-95a9-6a3120b5570c.png)
![IMAGE 4](https://user-images.githubusercontent.com/82689279/115136746-ad0c1500-9fd6-11eb-878d-3c07270a89f5.png)
In addition to remembering that CanSino vaccines are being applied in Mexico, so people_vaccinated + people_fully_vaccinated isn't equal to total_vaccinations. That error in people_vaccinated may have been repeated since CanSino vaccines started.

Thanks
Jesus

**Comment by lucasrodes** [comment]
Hi @Tecuidas,
This is really helpful. Thanks for reporting in such detail.

I'll see if I can automate the data import from Mexico this week.
