### ISSUE TITLE
Tests performed for Russia

### ISSUE THREAD

**Issue by ttyusupov** [owid/covid-19-data#11]
Hello, 

Is it possible to add tests performed for Russia as well into https://github.com/owid/covid-19-data/tree/master/public/data/testing ? 

There are official everyday reports since March, 25: https://xn--80aesfpebagmfblc0a.xn--p1ai/ofdoc/#reports

**Comment by ttyusupov** [comment]
https://xn--80aesfpebagmfblc0a.xn--p1ai/ofdoc/reports/

**Comment by edomt** [comment]
Hi @ttyusupov 
Russia has just been added to our dataset: https://ourworldindata.org/covid-testing
Thanks,
Edouard

**Comment by ttyusupov** [comment]
Great, thanks @edomt !

**Comment by bourov** [comment]
Hi guys, I don’t see Russia available anymore, it was there yesterday but not now — how do I see it again?

**Comment by ttyusupov** [comment]
Hi @edomt , I also don't see Russia anymore at https://ourworldindata.org/grapher/full-list-total-tests-for-covid-19

**Comment by bourov** [comment]
> Hi @edomt , I also don't see Russia anymore at https://ourworldindata.org/grapher/full-list-total-tests-for-covid-19

Looks like it was removed in this [commit](https://github.com/owid/covid-19-data/commit/3e4007ff521fbdc744461750056e7dd44ae647b4) but not sure why

**Comment by edomt** [comment]
Hi @bourov and @ttyusupov 
We temporarily removed the Russian time series as we wanted to find more precise figures (the official PDF reports only gave vague estimates). Somebody pointed us to the right resource, so the time series is back now!
Edouard
