### ISSUE TITLE
Cansino not included in pakistan's data Pakistan

### ISSUE THREAD

**Issue by pakistanimoon** [owid/covid-19-data#1108]
Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V

Except these please add Cansino by China in list, pakistan started vaccinating from it and remove AstraZeneca as it si not started yet.

**Comment by edomt** [comment]
Thank you, we'll correct this today.

**Comment by pakistanimoon** [comment]
Now CoronaVac also arrived and being administered.

**Comment by pakistanimoon** [comment]
i can also create an API through which you can get actually administered vaccien data.
