### ISSUE TITLE
Some records start too early

### ISSUE THREAD

**Issue by Bost** [owid/covid-19-data#1113]
For the vast majority of the countries the records start with 2020-01-21. However this is not the case for:
```
| country code | country     | extra records | first record |
| PE           | Peru        |            16 |   2020-01-06 |
| KR           | South Korea |             1 |   2020-01-21 |
| TW           | Taiwan      |             6 |   2020-01-16 |
| AR           | Argentina   |            21 |   2020-01-01 |
| TH           | Thailand    |            18 |   2020-01-04 |
| MX           | Mexico      |            21 |   2020-01-01 |
```
(The numbers and/or dates may be "off-by-one", since my time zone is Central European Summer Time)

Please consider removing these early records, since they are all just zeros anyway.

**Comment by edomt** [comment]
Hi @Bost 

These rows are actually not empty: they have data in the testing metrics such as `total_tests`. They correspond to countries which had started to test their populations early in the pandemic, but without having identified any cases yet.
