### ISSUE TITLE
Reformatting dates to make their chronological and alphabetical orderings the same.

### ISSUE THREAD

**Issue by c0deface** [owid/covid-19-data#113]
Currently, the "date" column contains dates formatted as either MM/DD/YYYY, M/DD/YYYY, or M/D/YYYY. Because the number of digits given to the month or day is not consistent, and because the year is specified last, the alphabetical and chronological orderings of the column are different. For example, 6/10/2020 comes before 6/6/2020. 

When creating a graph over time, I had to first reformat every date to the YYYY/MM/DD format so that the alphabetical and chronological orderings were the same. Could you reformat the dates in the original spreadsheet itself?

**Comment by edomt** [comment]
Hi @c0deface 

Which files exactly in the repo are you working with?

Edouard

**Comment by c0deface** [comment]
I'm working with owid-covid-data.csv.

**Comment by edomt** [comment]
@c0deface I'm not sure why this is happening, but I suspect that whatever software you're using to download/open the file is reformatting the dates. If you look at the raw file directly (https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv), the dates are all in standard ISO format.

**Comment by c0deface** [comment]
Yeah you're right. I was opening them in Excel, which is what was likely reformatting them to make them more human-readable.
