### ISSUE TITLE
Missing country data

### ISSUE THREAD

**Issue by fibke** [owid/covid-19-data#1169]
As of April 25, the following countries have started vaccinating:

COM, TJK, LBR, GNB, COD (date from WHO website eg https://covid19.who.int/region/afro/country/km

YEM: https://www.reuters.com/business/healthcare-pharmaceuticals/yemen-starts-covid-19-vaccination-campaign-2021-04-20/

**Comment by edomt** [comment]
Thank you!

We're discussing with the WHO how to best pull the data that they seem to receive directly from government - hopefully we'll start showing it very soon.
