### ISSUE TITLE
Data of Persistent Symptoms in Patients After COVID-19

### ISSUE THREAD

**Issue by jiaqili0803** [owid/covid-19-data#117]
Hi, we are a Research Group from The U.S.-China Health Summit. Our research is to understand the rehabilitation of COVID-19 infection and its influencing factors.

Can I find data about "Persistent Symptoms in Patients After COVID-19" here? or could you please give us any support?

Thank you so much for your help!

**Comment by edomt** [comment]
Hi @jiaqili0803 

There seems to have been a few recent articles on the subject:
https://jamanetwork.com/journals/jama/fullarticle/2768351
https://www.cdc.gov/mmwr/volumes/69/wr/mm6930e1.htm
https://theconversation.com/heres-what-we-know-so-far-about-the-long-term-symptoms-of-covid-19-142722
https://www.practiceupdate.com/content/persistent-symptoms-after-acute-covid-19/103996

Other than that, it is very unlikely that we'll be able to publish data on persistent symptoms in this GitHub repo, as this data is rarely available publicly or in a format suitable to our work.

Edouard

**Comment by jiaqili0803** [comment]
Hi @edomt 

The articles are helpful. Thanks for your help!

Jiaqi
