### ISSUE TITLE
Grenada's updates

### ISSUE THREAD

**Issue by JuanaPalotes** [owid/covid-19-data#1174]
Hi, I found 10 updates from the country, so I decided to make a new issue
Format: Total doses, 1st dose, 2nd dose. Source
- February 23th: 1200, 1200, 0. https://gov.gd/grenadians-support-covid-19-vaccination-programme
- March 14th: 8424, 8424, 0. https://m.facebook.com/HealthGrenada/photos/a.570448523487244/978161829382576/?type=3&source=48
- March 29th: 10,084, 10,084, 0. https://gov.gd/sites/default/files/egov/COVID-dashboard.pdf
- April 3th: 10,373, 10,371, 2. https://gov.gd/sites/default/files/egov/covid-dashboard.pdf
- April 8th: 10,717, 10,712, 5. https://gov.gd/sites/default/files/egov/COVID%2019-dashboard-8-apr.pdf
- April 9th: 10,878, 10,858, 20. https://gov.gd/sites/default/files/egov/COVID19-dashboard-9-apr.pdf
- April 11th: 10,911, 10,891, 20. https://gov.gd/sites/default/files/egov/covid-dashboard-19-10apr.pdf
- April 16th: 11,497, 11,388, 109. https://gov.gd/sites/default/files/egov/covid-19-dashboard-16apr.pdf
- April 19th: 11,731, 11,537, 194. https://gov.gd/sites/default/files/egov/COVID19-dashboard-19apr.pdf
- April 22th: 12,764, 11,779, 985. https://m.facebook.com/HealthGrenada/photos/a.570448523487244/1001278877070871/?type=3&source=48

Notes: 
- March 29th and April 3th have a similar URL, but they redirect to different PDFs
- April 11th URL says that it's from 10th April, but PDF's date indicates April 11th

Have a nice day! :)

**Comment by edomt** [comment]
Awesome, thank you @JuanaPalotes! We'll add this today :)
