### ISSUE TITLE
Checklist for COVID-19 Testing Data: Italy

### ISSUE THREAD

**Issue by pitmonticone** [owid/covid-19-data#12]
My colleague [Riccardo](https://github.com/Ricvalp) and I have created [this github page](https://pitmonticone.github.io/covid-italy/owid-testing-italy.html) to answer each question in your checklist for COVID-19 testing data with all the documentation at our disposal. 

We believe it might be useful.

Thank you so much for you phenomenal work!

**Twitter**: 
* [Pietro Monticone](https://twitter.com/PietroMonticone)
* [Riccardo Valperga](https://twitter.com/Riccard91650458)

**Comment by edomt** [comment]
Hi @pitmonticone 
Many thanks to you and Riccardo for providing this! Indeed it was very useful to confirm what we know about the Italian data.
Edouard
