### ISSUE TITLE
United States Data Question

### ISSUE THREAD

**Issue by jerryrou** [owid/covid-19-data#1209]
Hi - Not an issue but a question.
First and foremost thank you for creating this project - excellent data resource!
My question is the following:

In regards to vaccinations for the United States, is there dataset (csv) available which breaks it down into the county level ?
That is, the number of vaccinations (single and full) by State then County.

Thanks again - Jerry

**Comment by edomt** [comment]
Hi @jerryrou 

Thank you! Glad you're finding our work useful :) 

We don't have subnational data on vaccinations here, but the US CDC publishes this that you'll probably find interesting: https://covid.cdc.gov/covid-data-tracker/#county-view
