### ISSUE TITLE
Heads up: the Netherlands changed its estimation model yet again

### ISSUE THREAD

**Issue by Sikerdebaard** [owid/covid-19-data#1216]
Just as a heads up: the model used for estimating the number of people vaccinated has been adjusted. The RIVM states in the article below that the model was too optimistic and was over-reporting about 220k doses. Hence the new numbers, that will hopefully be released today, might be lower than the ones from last week.

https://www.rivm.nl/nieuws/correctie-vaccinatiecijfers-totaal-aantal-prikken-naar-beneden-bijgesteld

**Comment by Sikerdebaard** [comment]
Allright so the new data is in: https://www.rivm.nl/covid-19-vaccinatie/cijfers-vaccinatieprogramma

Now the following problem. The table describes first and second dose but not people vaccinated and people fully vaccinated. So far this has not been an issue, but since the Netherlands started using the Janssen / Johnson & Johnson vaccine, a single-dose vaccine, these numbers will start to make no sense at some point. Would it help if OWID knows the number of Janssen doses administered? There's no hard reported numbers on this but there are estimates on how many doses have been administered.

**Comment by edomt** [comment]
@lucasrodes I think this is the first case of a country where we can no longer calculate `people_fully_vaccinated` based on this data, because we don't know how many J&J vaccines are counted in the total. Therefore, it looks to me like `total_vaccinations` is `4.991.803`, `people_vaccinated` is `3.880.412`, but `people_fully_vaccinated` should be left empty. Do you agree?

**Comment by Sikerdebaard** [comment]
There are estimates on the number of J&J doses administered. But not on the same page. It's a bit hidden in the countries dashboard json. I can generate csv's with the necessary data if required but I would understand if that is not what you want.

**Comment by lucasrodes** [comment]
@edomt I am not sure where J&J might be included; _Eerste dosis_ or _Tweede dosis_?

I have seen some estimates on the J&J administered doses in the liked resource; See image below point 4

![image](https://user-images.githubusercontent.com/18101289/116586250-28dc5a80-a911-11eb-8b03-469ce6412752.png)


Also in the [daily dashboard](https://coronadashboard.rijksoverheid.nl/landelijk/vaccinaties), in the section "Delivered and controlled vaccines & injections in total". Haven't explored the web yet but there may be an API behind it.

I'll try to reach them out

**Comment by Sikerdebaard** [comment]
@lucasrodes @edomt that 8.883 is an estimated number, not a reported number. You can find it in the countries dashboard json.

https://coronadashboard.rijksoverheid.nl/json/NL.json -> vaccine_administered -> last_value -> janssen

The dashboard and the RIVM don't always update on the same day.

**Comment by lucasrodes** [comment]
@Sikerdebaard Do you know what are the differences between fields `vaccine_administered_total`, `vaccine_administered`, and `vaccine_administered_estimated`?

PS. Too bad this API does not have a breakdown by first/second dose.

**Comment by Sikerdebaard** [comment]
@lucasrodes that is correct. 

`vaccine_administered_estimate` is the forecast. 
`vaccine_administered_total` is the estimated and reported number of doses adminsitered.
`vaccine_administered` is `vaccine_administered_total` estimates (not reported) but split out in the different vaccine manufacturers.

**Comment by lucasrodes** [comment]
I am unsure how to proceed. I see two options:

- If we know where J&J counts are included (_Eerste dosis_ or _Tweede dosis_), go for [weekly update](https://www.rivm.nl/covid-19-vaccinatie/cijfers-vaccinatieprogramma). Only report the metrics that we are certain about.
- If we don't know where is J&J included, switch to only report `total_vaccinations` and for that, we may consider using daily updates from the dashboard API (previously cited by @Sikerdebaard https://coronadashboard.rijksoverheid.nl/json/NL.json).

**Comment by Sikerdebaard** [comment]
@lucasrodes in the RIVM page that you have screencapped it is stated that the J&J doses are under the 'Eerste dosis' (first dose) column.

**Comment by lucasrodes** [comment]
@Sikerdebaard I see. Sorry, I did not process that line of text. Therefore @edomt:

> Therefore, it looks to me [...] people_fully_vaccinated should be left empty. Do you agree?

Yes

---

Thanks for the update @Sikerdebaard. Perhaps this will be changed in the next update. I may change the scraper for NL to only use weekly reports to avoid inconsistencies between daily/weekly sources. Hopefully reliable daily vaccination data, broken by 1st/2nd doses and manufacturer will be available soon.

**Comment by Sikerdebaard** [comment]
Thanks for doing the work. Unfortunately at this rate it is likely that all people that want to be vaccinated will get a first shot before a proper data set will be available. It is what it is.

**Comment by lucasrodes** [comment]
Closing this, feel free to re-open if needed
