### ISSUE TITLE
deleted data in excess_mortality.csv for Canada on 20.12.2020

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#1233]
@edomt Can you tell why the 2020-12-20 data row was emptied for Canada in `excess_mortality.csv` with commit b5c410f7c3?

I mean this line: https://github.com/owid/covid-19-data/commit/b5c410f7c3a83838c8fe8583c0aaec162e0187cc#diff-d70b939974b2bb4c15dd375b1701c963aabbe8a3c728e781b23372943d90e236L388

**Comment by lucasrodes** [comment]
Hi @czka,
Thanks for your message.

I just updated the data with the latest available data.


Note that the file [`excess_mortality.csv`](https://github.com/owid/covid-19-data/blob/master/public/data/excess_mortality/excess_mortality.csv) is obtained by slightly processing [this data](https://github.com/owid/owid-datasets/blob/master/datasets/Excess%20Mortality%20Data%20%E2%80%93%20OWID%20(2021)/Excess%20Mortality%20Data%20%E2%80%93%20OWID%20(2021).csv).


Let me know if this solves your issue.

**Comment by czka** [comment]
@lucasrodes The data in question are back indeed. Thank you very much for taking care of this.

Is there any substantial difference between [Excess Mortality Data – OWID (2021).csv](https://github.com/owid/owid-datasets/blob/master/datasets/Excess%20Mortality%20Data%20–%20OWID%20(2021)/Excess%20Mortality%20Data%20–%20OWID%20(2021).csv) and [excess_mortality.csv](https://github.com/owid/covid-19-data/blob/master/public/data/excess_mortality/excess_mortality.csv)?

**Comment by lucasrodes** [comment]
Hi @czka,
Not really, just some minor processing and column renaming.

You can check the details in our import script [excessmortality.py](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/excessmortality.py).

**Comment by czka** [comment]
Got it. Closing the issue.
