### ISSUE TITLE
New Cases Smoothed

### ISSUE THREAD

**Issue by craigthusiast** [owid/covid-19-data#125]
Hi Team OWID, thank you so much for all your efforts and willingness to share your data.

I’m generating charts that show Daily Tests Smoothed vs Daily New Cases. The smoothed data for tests is great for removing the wild fluctuations in the line chart due to days with zero tests reported.

Would it be possible to add a “New Cases Smoothed” column to smooth out that curve too? Many countries have certain days of the week (usually weekends?) where they don’t report cases.

**Comment by edomt** [comment]
Hi @craigthusiast 
Thank you for the suggestion! This is now the case as of this morning.
Edouard

**Comment by craigthusiast** [comment]
@edomt Whoa, that was fast! Thanks so much!

**Comment by craigthusiast** [comment]
@edomt I'm tracking 24 different countries on my website (thanks again for the data!)

I noticed something wonky with the new_cases_smoothed data for Chile (for the dates of June 19th to June 24th). Is the odd data in my database or yours? 
[https://c19charts.com/charts/country/CHL](url)

**Comment by edomt** [comment]
It's in ours—or rather it's in our source's database (the European CDC). On June 18 Peru added 39,179 new cases to its cumulative total, following a change in methodology. You can see the day-by-day figures here: https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&casesMetric=true&interval=daily&smoothing=0&country=~CHL&pickerMetric=location&pickerSort=asc
