### ISSUE TITLE
Cuba Test Data Outlier

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#1258]
Hello,

It seems that Cuba test data jump to an extremely high level after April 28 2021, which does not seem to be correct. This affects many series, such as cumulative test, new test, positive rate and etc.. Would you mind have a look at these series?

**Comment by camappel** [comment]
Hi @RuijingZ, we looked at the series and our testing data matches the reports by the Cuban Ministry of Health, which are published [here](https://salud.msp.gob.cu/). Thank you for your feedback!

April 28: [22,805](https://salud.msp.gob.cu/parte-de-cierre-del-dia-28-de-abril-a-las-12-de-la-noche-2/)
April 29: [22,451](https://salud.msp.gob.cu/parte-de-cierre-del-dia-29-de-abril-a-las-12-de-la-noche-2/)
April 30: [23,384](https://salud.msp.gob.cu/parte-de-cierre-del-dia-30-de-abril-a-las-12-de-la-noche-2/?doing_wp_cron=1620224378.1036961078643798828125)
May 1: [22,237](https://salud.msp.gob.cu/parte-de-cierre-del-dia-1ro-de-mayo-a-las-12-de-la-noche/)
May 2: [22,938](https://salud.msp.gob.cu/parte-de-cierre-del-dia-2-de-mayo-a-las-12-de-la-noche-2/)
