### ISSUE TITLE
what do negative values means? 

### ISSUE THREAD

**Issue by ospinag** [owid/covid-19-data#126]
I have found reported negative values, for instance:

ESP,Europe,Spain,2020-05-25,235400.0,-372.0,26834.0,**-1918.0**,5034.779,-7.956,573.931,-41.023,,,,,44188.0,0.945,81.528,0.012,tests performed,75.46,46754783.0,93.105,45.5,19.436,13.799,34272.36,1.0,99.403,7.17,27.4,31.4,,2.97,83.56

My guess is that those values represent information initially associated to covid, which in a later revision no covid relationship was found? Am I right?

**Comment by ospinag** [comment]
my issue with it is that negative values may reflect the net value instead the actual value (info for the day is lost)

**Comment by edomt** [comment]
Hi @ospinag 
See #66 
Edouard
