### ISSUE TITLE
`vaccine` column in `Germany.csv` is missing J&J

### ISSUE THREAD

**Issue by mathiasbynens** [owid/covid-19-data#1270]
J&J was officially approved on 2021-04-26, and the first administered dose was reported for `date=2021-04-27 pubDate=2021-04-28`.

However, the entries from 2021-04-27 onwards still only say `vaccine='Moderna, Oxford/AstraZeneca, Pfizer/BioNTech'` (with J&J missing):

https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/output/Germany.csv#L123-L128

**Comment by lucasrodes** [comment]
Hi, @mathiasbynens! Thanks for reporting.

This was added in https://github.com/owid/covid-19-data/commit/01f3a69fe76b8cde06aeb36cb13f161c8c9b79a7. Today's update should reflect this.
