### ISSUE TITLE
Disagreement in UK Vaccination Numbers

### ISSUE THREAD

**Issue by OI-GH** [owid/covid-19-data#1302]
https://coronavirus.data.gov.uk/details/vaccinations
suggests a different percentage of people in the UK have been given at least one vaccine than ourworldindata (66.3% vs 51.46% - May 5th).
I may have misinterpreted something but a clarification would be helpful.

**Comment by lucasrodes** [comment]
Hi @OI-GH, 
Thanks for being on this, good to regularly check these numbers.

From what I can see in the cited [official page](https://coronavirus.data.gov.uk/details/vaccinations), the percentage metrics are computed using only part of the population:

> Total percentage of people aged 18 and over who have received a COVID-19 vaccination, shown by date reported. Daily figures include all vaccines that were given up to and including the date shown, and that were entered on the relevant system at the time of extract. Percentages lower than 0.1 will not appear on the chart and show as N/A in data tables.


Our % metrics are per-capita.


Hope this helps,
Kind regards

**Comment by OI-GH** [comment]
Ah great, thanks for the clarification!
