### ISSUE TITLE
Germany Testing Data

### ISSUE THREAD

**Issue by colemanstephen73** [owid/covid-19-data#131]
Hi,

Thanks for everything, great source and has been a massive help to us. I am inquiring about Germany testing data. It has not been updated since 8/16. I was wondering if there is a known issue or is there a delay in publishing at source?

Regards.

**Comment by edomt** [comment]
Hi @colemanstephen73 

Unfortunately that's down to the frequency at which the source publishes updated data: for Germany, the Robert Koch Institut publishes a weekly update every Wednesday, with data up to the preceding Sunday.
So tomorrow's update of our testing dataset will include data up to August 28.

Edouard
