### ISSUE TITLE
Malta data is switched fo 2021-05-06

### ISSUE THREAD

**Issue by wooligan** [owid/covid-19-data#1310]
First: Thanks for the great API! I really appreciate it.

The data from Malta for 2021-05-06 seems switched.
114115 people vaccinated and 251787 people_fully_vaccinated.

**Comment by lucasrodes** [comment]
We source our data from the [Official Open Dataset on COVID19 in Malta from the COVID-19 Public Health Response Team (Ministry for Health)](https://github.com/COVID19-Malta/COVID19-Cases)

I opened the issue https://github.com/COVID19-Malta/COVID19-Cases/issues/5 to track this.

In the meantime, I'd suggest modifying [script](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/src/vax/batch/malta.py) importing this data, so it does not import values after the 5th of May.

**Comment by lucasrodes** [comment]
This has now been fixed
