### ISSUE TITLE
Additional Vaccination Data

### ISSUE THREAD

**Issue by jzamalloa1** [owid/covid-19-data#1314]
Thank you very much for providing such a comprehensive source of vaccination data. Are there plans to include Sputnik V vaccination data as well (or do you know of a source where that can be captured)?

Thanks!

**Comment by lucasrodes** [comment]
Hi @jzamalloa1, we only collect the data by the manufacturer for a limited number of countries at the moment.

However, on our [main vaccinations dataset file](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv) we provide the number of doses administered and people vaccinated considering all manufacturers vaccines being in use.

Also, you can check which vaccines are being used where in [this file](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/locations.csv).
