### ISSUE TITLE
Data  source about tests, cases and deaths in Peru

### ISSUE THREAD

**Issue by jmcastagnetto** [owid/covid-19-data#132]
I am not sure if you are aware that most of the data is not only published in press releases from the Ministry of Health (https://www.gob.pe/minsa#noticias), but also as XLSX files in the "Sala Situacional ..." (a "Situation Room... ") a dashboard maintained by the Ministry of Health.

The "Sala Situacional..." is at: https://covid19.minsa.gob.pe/sala_situacional.asp , and you can get the XLSX files from there.

Also, since early this year, I've been collecting the public data, which includes storing the XLSX files that they publish daily at:

https://github.com/jmcastagnetto/covid-19-peru-data/

In particular the historic XLSX files from the "Sala Situacional...":

https://github.com/jmcastagnetto/covid-19-peru-data/tree/main/minsa-datos

The files from 2020-08-18 are, for example, at: https://github.com/jmcastagnetto/covid-19-peru-data/tree/main/minsa-datos/20200818

There are a couple of data files that might help you and have the following patterns:

- **yyyymmdd/CASOS_ddmmyyyy.xlsx**: contains the number of positives cases detected by PCR and rapid tests, as well as the number total cases and deaths, at the subnational level

- **yyyymmdd/POSITIVIDAD_ddmmyyyy.xlsx**: contains the number of tests applied and the number of those who gave positive at the subnational level

Perhaps with that info you can fill the gaps you've got on testing information for Peru.

Let me know if you need more information or I can be of any help with this.

Cheers

**Comment by jmcastagnetto** [comment]
BTW, comparing the data you have with the one that MINSA has published in the **POSITIVIDAD_ddmmyyyy.xlsx** files, I see very noticeable differences in the number of tests applied

**Comment by jmcastagnetto** [comment]
Also, your data does not seem to match published reports by MINSA, for example, in the press release of 2020-04-08 https://www.gob.pe/institucion/minsa/noticias/112079-minsa-casos-confirmados-por-coronavirus-covid-19-ascienden-a-4-342-en-el-peru-comunicado-n-58, it says:

> 1. Al 08 de abril de 2020 se han procesado muestras para 39 599 personas por COVID-19, obteniéndose, hasta las 00:00h, 4 342 resultados positivos y 35 257 negativos.
> 
> Personas muestreadas: 39 599
>
> Pruebas moleculares: 23,255
> Pruebas (serológicas) rápidas: 16,344

The total number of tests for that date was **39599** but your dataset for that date gives a very different figure: **24410** 

![Tests data for Peru](https://user-images.githubusercontent.com/364668/91501314-f9a9b100-e88a-11ea-8800-b67a694dea14.png)

Similar problems exist for the date for 2020-04-09 (https://www.gob.pe/institucion/minsa/noticias/112117-minsa-casos-confirmados-por-coronavirus-covid-19-ascienden-a-5-256-en-el-peru-comunicado-n-60): **48465** from MINSA vs **25643** from your dataset.

I've compared you data with other dates too, and not one matches the published values given by MINSA.

Is there something I am missing in your definition of `total tests`? I'd like to understand these discrepancies because I'm interested in using your dataset.

**Comment by jmcastagnetto** [comment]
OK, I think I might have found why there is a difference you are using the PCR tests data, but even though they are labelled as, for example, having been reported on 2020-04-08, they correspond to the a note published on 2020-04-09. In that particular example the text of the published note (https://www.gob.pe/institucion/minsa/noticias/112117-minsa-casos-confirmados-por-coronavirus-covid-19-ascienden-a-5-256-en-el-peru-comunicado-n-60) reads: 

> "... Al 09 de abril de 2020 se han procesado muestras para 48 465 personas por Covid-19, ..."

(roughly translated: "... At 09 of april 2020 there had been processed samples for 48 465 people for Covid-19, ...")

Just leaving this here so there is record of this difference.

**Comment by edomt** [comment]
Hi @jmcastagnetto 

Thank you for looking into this!

### On the number of tests

Currently, we aim to include only these PCR tests in our testing dataset. We do this for the following reasons:

1. Our focus is on using testing data to help properly interpret the data we have on confirmed cases and deaths. Case confirmation is generally based on a positive result from a PCR test, in line with WHO recommendations. So including antibody tests in our figures would mean they were less useful for this purpose.
1. Other kinds of test beyond PCR are not yet being widely used. This also means that data on how many of these tests have been conducted is very limited. Including such data in our counts when it is available would reduce the comparability of our data across countries.
1. There are technical differences in how results from these different tests should be interpreted. Current data suggests that other existing testing technologies are subject to very different rates of false positive and false negative results than PCR tests. This is another reason why aggregating the data across these different types of test is not the best way of using testing data to help us understand the epidemic.

For this reason we only want to count molecular/PCR tests for Peru, which means that we cannot use the `POSITIVIDAD_ddmmyyyy.xlsx` files, which unfortunately do not differentiate between types of tests.

### On our more general methodology for Peru

More information is available here: https://ourworldindata.org/coronavirus-testing#peru

> The Peruvian Ministry of Health publishes daily presentation slides on the number of people tested for the coronavirus, explicitly distinguishing between PCR and rapid tests. We only include PCR test figures in our series.

> On dates where presentation slides are unavailable, we use the Ministry’s press releases to supplement the series. Where the dates across the two sources overlap, the number of people tested in the presentation slides are consistently identical to the press release figures for the previous day.

### On the date of testing in our dataset

You indicated that some observations had a 1-day shift compared to our source: this is quite possible, as we initially automated some of our data collection for Peru and part of the time series may have been shifted by 1 day. For current data however, this shift is not present (for example our value for August 18 is 506,901, based on [this report](https://www.dge.gob.pe/portal/docs/tools/coronavirus/coronavirus180820.pdf) for August 18). We will try to fix this when our resources allow it, but in the meantime it should not affect the time series in any significant way.

Edouard

**Comment by jmcastagnetto** [comment]
@edomt Thanks for your thorough and clear response. I got a better idea of the context of your data now.

Also, I see that the original source you were using has not updated the molecular counts for some time. Will try to bother them to see if they start again, or if the distinction you need (and everyone else too) between tests is included in the data files they are putting in their dashboard.

Will let you know if I get news on this front (hopefully soon),

**Comment by jmcastagnetto** [comment]
@edomt : It seems like the original source you were using has started to publish the reports again. There are now reports up 
to August 29th (as of today) at https://www.dge.gob.pe/portal/index.php?option=com_content&view=article&id=678

Keep up the good work and thanks for you effort.

**Comment by jmcastagnetto** [comment]
@edomt : there's been a reorg in the DGE site, the SARS-COV-2 info is now at https://www.dge.gob.pe/portalnuevo/covid-19/vigilancia-prevencion-y-control-del-covid-19/ and in particular: https://www.dge.gob.pe/portalnuevo/covid-19/covid-cajas/situacion-del-covid-19-en-el-peru/ where you'll find the "Archivo - Sala situacional COVID-19" that contains the reports you are using (I think)
