### ISSUE TITLE
how to merge different countries'date

### ISSUE THREAD

**Issue by LesterHoly** [owid/covid-19-data#1321]
Hello, Thank u for your data. But I have a problem when I explore vaccinations csv data. I want to know what did u
do when process date from different country in different timezone to normlize it. Is that utc time? or American time?  Thank u firstly.

**Comment by lucasrodes** [comment]
The date in the [`vaccinations.csv`](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv) reflects the date of the source's last update in **local time**.
