### ISSUE TITLE
Kyrgyz Republic New Coronavirus Death

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#133]
Data for Kyrgyz Republic New Coronavirus Death on AIug 24 seems abnormal. Could you please have a look at it?

**Comment by edomt** [comment]
Hi @RuijingZ 

This data comes directly from the European CDC, so we're not sure what exactly is the reason for this change. However, it seems to correspond to a data correction made by the government. Looking at the [press release for August 17](http://www.med.kg/en/informatsii-2/2535-statistics-on-covid-19-in-kyrgyzstan-as-of-august-17-2020.html), it says:

> The total death toll is 1496 cases, of which 262 from laboratory confirmed and 1234 from clinically & epidemiologically confirmed COVID.    

And the next day, the [press release for August 18](http://www.med.kg/en/informatsii-2/2545-statistics-on-covid-19-in-kyrgyzstan-as-of-august-18-2020.html) says:

> The total death toll is 1053 cases in the republic.  

Following press releases from August 19 to today take this revised count as their basis for the total number of deaths.

Edouard
