### ISSUE TITLE
Change in how Swedish data is reported (Special treatment for Belgium & Sweden)

### ISSUE THREAD

**Issue by bjornpiltz** [owid/covid-19-data#135]
### What happened?
As reported in #134 The Swedish graphs for daily new deaths and daily new cases changed drastically over the weekend. This coincides with Sweden discovering some 3700 false positive tests and needing to revise their numbers.
I don't have screenshots for how OWID looked before the weekend, but based on the data the change looks like this (notice the dip at the end with the new methodology):

![ecdc_changed_methodology@2x](https://user-images.githubusercontent.com/1873764/91691228-94461080-eb67-11ea-8ec5-efde549bf2cc.png)

The change happened in commit ab5fc947cf4fa7194df146698f19d1fa9732e5d6 which touched basically all lines for sweden in [full_data.csv](https://github.com/owid/covid-19-data/blob/ab5fc947cf4fa7194df146698f19d1fa9732e5d6/public/data/ecdc/full_data.csv)

### What does this mean?
This means that OWID is effectively no longer reporting Swedish cases/deaths by the date they were reported to ECDC, but by the date the death actually happened/whatever date they use for cases. This is different to how it was handled when [Spain and Luxemburg ](https://ourworldindata.org/grapher/new-covid-cases-per-million?tab=chart&country=SWE~LUX~ESP)reported negative number of cases.

I realise you get your data straight from ECDC, but I think at the very least, there should be a notice that reporting changed on 08/28 and I think, that there should be a warning that recent days are incomplete for countries reporting this way. (Only Belgium and Sweden as far as I can tell)

**Comment by edomt** [comment]
Hi @bjornpiltz 

Thanks for looking into this. There was at least another instance of this recently: the UK time series was also revised more generally when a large data correction was made by the British government in July. It seems that the decision of the ECDC to revise the time series retrospectively now depends on the availability of the revised retrospective data (while they previously preferred never to revise data).

I've now added a mention of this in our main README to alert our users that this can happen: https://github.com/owid/covid-19-data/commit/8d3c87cb7c2c6ef74c26e3d39e2cb056d2878adf

(And thanks for the well-formatted issue!)

Edouard

**Comment by bjornpiltz** [comment]
Thanks!
That seems like a good solution for now. I just saw that in the latest commit ECDC only modified the last 15 entries for Sweden, so hopefullly they will get back to the old way of just appending values once the corrections are through.

**Comment by bjornpiltz** [comment]
Oh wait, they seem to have rushed this one.
I just saw that they now report a sum of zero deaths from Sweden for the last seventeen days. You should definitely add an annotation for Sweden.

**Comment by edomt** [comment]
@bjornpiltz Have you checked it against the official data? I'm assuming that'll also be the case there.

**Comment by bjornpiltz** [comment]
Yes I have. This is definitely a bug. It is missing some 14 deaths by Swedens own way of counting (by date of death).  It would have been more by the way ECDC counted up until last week (by date reported)
https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa

ECDC is apparently still struggling with the corrections from last week.

**Comment by bjornpiltz** [comment]
Just to illustrate, this is the deaths graph for 08/27, 08/28 and 08/31 (red green and blue, respectively):
![owid](https://user-images.githubusercontent.com/1873764/91869025-ad3ce780-ec75-11ea-88a8-1b101ca81809.png)

Last week Sweden was averaging 4/day and now there have been zero deaths the last seventeen days.

You can [check for yourself](https://gist.github.com/bjornpiltz/1f26daa727adb156735c3ce85683be85).

**Comment by edomt** [comment]
@bjornpiltz The ECDC have now confirmed to us that they're updating the full time series for Sweden every day, based on the official data. Today's update looks like this: https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-12..latest&country=~SWE&deathsMetric=true&interval=daily&smoothing=0&pickerMetric=total_deaths&pickerSort=desc (I assume yesterday's issue with the last 17 days was a temporary problem)

**Comment by bjornpiltz** [comment]
OK, I'm glad that's fixed.

So, I guess a "Methodology changed" annotation is warranted then, since there is a significant lag in deaths reported from Sweden. Based on experience,  a large proportion of deaths won't make it into the current weeks 7-day rolling average because they are back-dated more than a week. 

The test will be to see how [this graph](https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&time=2020-07-31..2020-09-02&country=~SWE&deathsMetric=true&interval=smoothed&smoothing=7&pickerMetric=total_deaths&pickerSort=desc) for the same dates will look in two weeks, when most days are finished.
![coronavirus-data-explorer](https://user-images.githubusercontent.com/1873764/91976946-1e39d900-ed22-11ea-9d76-11128e94c1cb.png)


And [this graph](https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&time=2020-09-02&country=SWE~DNK~DEU&deathsMetric=true&interval=smoothed&perCapita=true&smoothing=7&pickerMetric=total_deaths&pickerSort=desc):
![coronavirus-data-explorer (1)](https://user-images.githubusercontent.com/1873764/91977483-07e04d00-ed23-11ea-8295-15127bf625e0.png)

I assume they will look very different.

**Comment by edomt** [comment]
Our "Methodology change" annotations are meant to inform readers on methodology changes that are visible in the time series because they only affect part of it. Here the methodology change is a completely new way of collecting the data that affects the entire time series retrospectively; therefore the time series is collected in a single way that remains constant.

We've added the following in our readme:
> Alternatively, large changes can sometimes (although rarely) be made to a country's entire time series if the ECDC decides (and has access to the necessary data) to correct values retrospectively.

And already had this too:
> the number of cases or deaths reported by any institution—including the ECDC, the WHO, Johns Hopkins and others—on a given day does not necessarily represent the actual number on that date. This is because of the long reporting chain that exists between a new case/death and its inclusion in statistics.
