### ISSUE TITLE
Why is it include new_tests and new_cases negative value?

### ISSUE THREAD

**Issue by gokhyildiz** [owid/covid-19-data#1365]
Hello there. I have a global covid19 tracker website that I am working on using the OWID dataset. But recently I think/noticed that some columns have inconsistent data. I would like to ask how we should interpret the "new_tests" and "new_cases" columns. In the json file in the code block below, the column types of the "owid-covid-data.xlsx" file represent the maximum and minimum values. Thanks, best regards.

**Note:  "owid-covid-data.xlsx" file was converted from the "owid-covid-data.csv" file.**

![neg1](https://user-images.githubusercontent.com/32950356/118618991-da620380-b7cc-11eb-9a10-ed5bfb27b8f5.png)

![neg2](https://user-images.githubusercontent.com/32950356/118618995-dc2bc700-b7cc-11eb-8faa-50b0897d04c3.png)

`
[{
 "Column Size": "59",
 "Created Date": "18-05-2021 10:53:58",
 "File Name": "owid-covid-data.xlsx",
 "File Size": "21420709 byte",
 "Row Size": "89342",
 "aged_65_older": ["Double", 1.144, 27.049],
 "aged_70_older": ["Double", 0.526, 18.493],
 "cardiovasc_death_rate": ["Double", 79.37, 724.417],
 "continent": "String",
 "date": "String",
 "diabetes_prevalence": ["Double", 0.99, 30.53],
 "extreme_poverty": ["Double", 0.1, 77.6],
 "female_smokers": ["Double", 0.1, 44.0],
 "gdp_per_capita": ["Double", 661.24, 116935.6],
 "handwashing_facilities": ["Double", 1.188, 100.0],
 "hosp_patients": ["Integer", 0, 133214],
 "hosp_patients_per_million": ["Double", 0.0, 1532.573],
 "hospital_beds_per_thousand": ["Double", 0.1, 13.8],
 "human_development_index": ["Double", 0.394, 0.957],
 "icu_patients": ["Integer", 0, 30022],
 "icu_patients_per_million": ["Double", 0.0, 192.735],
 "iso_code": "String",
 "life_expectancy": ["Double", 53.28, 86.75],
 "location": "String",
 "male_smokers": ["Double", 7.7, 78.1],
 "median_age": ["Double", 15.1, 48.2],
 "new_cases": ["Integer", -74347, 905992],
 "new_cases_per_million": ["Double", -2153.437, 18293.675],
 "new_cases_smoothed": ["Double", -6223.0, 826374.286],
 "new_cases_smoothed_per_million": ["Double", -276.825, 4083.5],
 "new_deaths": ["Integer", -1918, 17906],
 "new_deaths_per_million": ["Double", -76.445, 218.329],
 "new_deaths_smoothed": ["Double", -232.143, 14436.143],
 "new_deaths_smoothed_per_million": ["Double", -10.921, 63.14],
 "new_tests": ["Integer", -239172, 2945871],
 "new_tests_per_thousand": ["Double", -23.01, 327.086],
 "new_tests_smoothed": ["Integer", 0, 1903340],
 "new_tests_smoothed_per_thousand": ["Double", 0.0, 92.104],
 "new_vaccinations": ["Integer", 0, 26427035],
 "new_vaccinations_smoothed": ["Integer", 0, 24214867],
 "new_vaccinations_smoothed_per_million": ["Integer", 0, 118759],
 "people_fully_vaccinated": ["Integer", 1, 355172458],
 "people_fully_vaccinated_per_hundred": ["Double", 0.0, 105.54],
 "people_vaccinated": ["Integer", 0, 704865709],
 "people_vaccinated_per_hundred": ["Double", 0.0, 115.48],
 "population": ["Integer", 809, 2147483647],
 "population_density": ["Double", 0.137, 20546.766],
 "positive_rate": ["Double", 0.0, 0.742],
 "reproduction_rate": ["Double", -0.01, 5.72],
 "stringency_index": ["Double", 0.0, 100.0],
 "tests_per_case": ["Double", 1.3, 44258.7],
 "tests_units": "String",
 "total_cases": ["Integer", 1, 163413904],
 "total_cases_per_million": ["Double", 0.001, 175435.191],
 "total_deaths": ["Integer", 1, 3386457],
 "total_deaths_per_million": ["Double", 0.001, 3024.011],
 "total_tests": ["Integer", 0, 433570412],
 "total_tests_per_thousand": ["Double", 0.0, 7096.816],
 "total_vaccinations": ["Integer", 0, 1474710622],
 "total_vaccinations_per_hundred": ["Double", 0.0, 221.01],
 "weekly_hosp_admissions": ["Double", 0.0, 116938.0],
 "weekly_hosp_admissions_per_million": ["Double", 0.0, 2656.911],
 "weekly_icu_admissions": ["Double", 0.0, 4002.456],
 "weekly_icu_admissions_per_million": ["Double", 0.0, 279.224]
}]
`

**Comment by edomt** [comment]
Hi @gokhyildiz 

The number of cases or tests reported on a given day does not necessarily represent the actual number on that date. This is because of the long reporting chain that exists between a new case/test and its inclusion in statistics. *This also means that negative values can sometimes appear when a country corrects historical data, because it had previously overestimated the number of cases/tests.*

In this situation, if a country reports for example a total of 1 million total tests today, but 990,000 tests tomorrow because of a correction, then the daily change tomorrow will be –10,000.
