### ISSUE TITLE
Vaccines in Locations.csv out of date compared with WHO data??

### ISSUE THREAD

**Issue by DrBazUK** [owid/covid-19-data#1368]
@edomt Is there any way to update the vaccines included per country in the locations.csv file?

WHO has a feed [https://covid19.who.int/who-data/vaccination-data.csv](https://covid19.who.int/who-data/vaccination-data.csv) which lists all the vaccinations in use in each country (and some dependent territories). 

As of 18 May, OWID has more vaccines listed than WHO for these countries:

Armenia
Cayman Islands
Guernsey
Kazakhstan
Kenya
Malta
Uzbekistan

There are about 90 countries where WHO>OWID in terms of number of vaccines listed.

I lack the coding experience to help automate a check but wonder if this could be done?

Thanks in advance,
Baz

**Comment by lucasrodes** [comment]
Hi @DrBazUK,
Thanks for your message.

We are aware of WHO listing the vaccines in use per country. We try to regularly check to find potential discrepancies.

We prefer the use of https://covid19.who.int/who-data/vaccination-metadata.csv, as it tells us precisely which vaccines have been accepted and which are in use.

We are currently implementing a series of sanity checks to contrast our data with theirs. Will likely be under [`vax.tracking`](github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/src/vax/tracking/) utils.

**Comment by DrBazUK** [comment]
@lucasrodes many thanks for the confirmation. Hadn't spotted the metadata.csv file but will add it to my own comparison (in Excel)  until I learn enough to do it in a proper data science tool :)

**Comment by lucasrodes** [comment]
The functionality has been added.

You can run 

```
cowid-vax-track missing-vaccines-who --to-csv
```

which will generate the file `vaccines-missing-who.tmp.csv` containing differences in vaccine records in WHO and OWID. I will be examining a bit closer the mismatches these days.


---

**Note:** To run command `cowid-vax-track` make sure you have the [library installed](https://github.com/owid/covid-19-data/tree/master/scripts/scripts/vaccinations/#install-library).
