### ISSUE TITLE
Male Smokers in Peru?

### ISSUE THREAD

**Issue by dbaroncelli** [owid/covid-19-data#137]
I have noticed that for Peru,
you report the percentage of Female Smokers (4.8%),
but not the percentage of Male Smokers.

Were you aware?

**Comment by edomt** [comment]
Hi @dbaroncelli 

Yes, this is "normal" (although not ideal!) as the data for male smokers in Peru is not available in the World Bank's World Development Indicators data.

Edouard

**Comment by edomt** [comment]
(See here for our entry on "Who smokes more, men or women?": https://ourworldindata.org/who-smokes-more-men-or-women)
