### ISSUE TITLE
Add time range in data

### ISSUE THREAD

**Issue by Maya485** [owid/covid-19-data#138]
Add time range in datasets (e.g. 7-day cumulation, 14-day cumulation)

**Comment by edomt** [comment]
Hi @Maya485 
Is there a particular use case that prevents you from calculating those with the existing data? We're trying to be mindful of not adding too many variables to the dataset to keep the file size reasonable. You can get 7-day rolling sums by multiplying any of the 7-day rolling averages by 7.

**Comment by Maya485** [comment]
Thank you for your response. 
Use case: when looking at all countries, the amount of data and the individual calculation it would require, especially since not all countries share their data daily. With more governments trending towards using the 7-day and 14-day roll and with you already having included that to other data, I thought this would be a helpful addition to testing as well.
