### ISSUE TITLE
Multiple occurrence of country in locations.csv

### ISSUE THREAD

**Issue by airmisdata** [owid/covid-19-data#14]
in https://github.com/owid/covid-19-data/blob/master/public/data/ecdc/locations.csv#L50

Curacao appear under 3 names : 

* Curaçao
* Cura̤ao
* Cura̤ao

and so does Czech Republic (with 2 occurrences) https://github.com/owid/covid-19-data/blob/master/public/data/ecdc/locations.csv#L54 
* Czech_Republic
* Czechia

**Comment by danielgavrilov** [comment]
Thanks for reporting @airmisdata, this has now been fixed.
