### ISSUE TITLE
Sort countries by smoothed metrics instead of raw daily numbers in the Data Explorer

### ISSUE THREAD

**Issue by HerbCaudill** [owid/covid-19-data#141]
This probably belongs in another repo, but I haven't been able to find where the COVID Data Explorer is configured - apologies in advance. 

When the country list is sorted by 'New cases (per 1M)', many countries show a zero and therefore drop to the bottom of the list, even though they have a high number of daily cases. 

![image](https://user-images.githubusercontent.com/2136620/93190979-4bd04a80-f744-11ea-943a-942638e609eb.png)

In the case of Spain, this is because data for new cases isn't reported on the weekends, so the country gets a zero value every Saturday and Sunday. 

![image](https://user-images.githubusercontent.com/2136620/93191561-f47eaa00-f744-11ea-84d7-a63c65e78067.png)

A quick fix would be to use the "smoothed" numbers for ordering the countries in this list, instead of the raw numbers.

**Comment by lucasrodes** [comment]
Seems fixed, feel free to re-open
