### ISSUE TITLE
ENH: Add data broken by age group

### ISSUE THREAD

**Issue by Lokeshrathi** [owid/covid-19-data#1416]
If we could also add Age/Age-group in the dataset, that would work out great.
eg: 0-20,20-40,40-60,60-80

**Comment by lucasrodes** [comment]
Hi @Lokeshrathi,
Thanks for your feature request. To better understand the proposal, if possible, could you elaborate a bit more on the following:

- Where would you add this data? That is, to which files?
- Which age ranges would you consider? 
- Do you have some examples of countries providing such data?

Thanks
