### ISSUE TITLE
Fully Vaccinated data is duplicated

### ISSUE THREAD

**Issue by tparis0022** [owid/covid-19-data#1422]
Looking at the data displayed on https://ourworldindata.org/grapher/share-people-fully-vaccinated-covid - The raw data downloaded from that source (linked directly to this dataset in this GitHub Repo) has duplicate data for Uruguay. This appears to be the only country I have found with this issue.

**Comment by lucasrodes** [comment]
Hi @tparis0022, could you elaborate on which data is duplicated?

**Comment by tparis0022** [comment]
Discovered an error in my process. Closing the issue down
