### ISSUE TITLE
Greece testing data

### ISSUE THREAD

**Issue by alksak** [owid/covid-19-data#143]
Thank you for all your effort to make this data available to all of us.

Greece testing data have some errors, let me analyze.

![image](https://user-images.githubusercontent.com/2636241/93631618-937cfd80-f9f4-11ea-8862-36b61008f099.png)

As we can see from the screenshot some dates are correct with the report and some are one day after. I don't know your automate pipeline but the pdf report change filename by Greek authorities without a steady pattern.

The only steady link for daily report is https://eody.gov.gr/0915_briefing_covid19/ where the date in the link is /mmdd_briefing_covid19/

The link for the pdf report that total tests are reported is the first `<a>`  tag at the `<div class="main-container__inner paddingL">`

Maybe this information will help to make the dataset more consistent.

Thank you again!

**Comment by edomt** [comment]
Hi @alksak 

Thank you for spotting this! Our script was indeed using the previous format of the date in the filename (YYYYMMDD), and defaulted to today's date when this date wasn't found. So the recent change to DD-MM-YYYY introduced a few instances of 1-day lags. We've now fixed this, both in the data and in our script.

Thanks again!
