### ISSUE TITLE
Duplications in UK and US figures

### ISSUE THREAD

**Issue by bjtp1954** [owid/covid-19-data#144]
The ECDC CSV dataset for 2020-09-21 contains duplicates. Specifically, every line of the GBR data dated 2020 is duplicated. No other coutries are affected.

**Comment by bjtp1954** [comment]
Sorry, first "countries" not "coutries".
Second, this refers to the OWID COVID-19 dataset.

**Comment by edomt** [comment]
Hi @bjtp1954 

This is due to another issue with the OxCGRT dataset (https://github.com/OxCGRT/covid-policy-tracker/issues/43)—we've now fixed this temporarily, so it should be fine if you download again now.
