### ISSUE TITLE
Update: Pontential date changes for Costa Rica

### ISSUE THREAD

**Issue by JuanaPalotes** [owid/covid-19-data#1446]
Potential new data:
Hi again! On the actual [source](https://www.ccss.sa.cr/web/coronavirus/vacunacion) from the country, at the bottom there is a subtitle called "Vacunación covid-19 por provincia, cantón, dosis de vacunación y fabricante" and if you click on the "Excel" it will download the data in this format. Where I want to get is that the applied vaccines are classified in "Periodo de aplicación" (for example: "12-2020", month-year), and you can make some formulas to obtain the total of doses applied at the end of each month, including 1st doses ("DV1 - PRIMER DOSIS VIDA") and 2nd doses ("DV2 - SEGUNDA DOSIS VIDA").
I've already done the formulas:

- Total doses: (format: month: formula, vaccines applied in the month, accumulated total with previous months)
December: =SUMAR.SI($G$3:$G$14854;"=12-2020";$H$3:$H$14854), 2480, 2480
January: =SUMAR.SI($G$3:$G$14854;"=1-2021";$H$3:$H$14854), 55480, 57960
February: =SUMAR.SI($G$3:$G$14854;"=2-2021";$H$3:$H$14854), 105718, 163678
March: =SUMAR.SI($G$3:$G$14854;"=3-2021";$H$3:$H$14854), 373513, 537191
April: =SUMAR.SI($G$3:$G$14854;"=4-2021";$H$3:$H$14854), 477522, 1014713
May (until 24th, only for verification): =SUMAR.SI($G$3:$G$14854;"=5-2021";$H$3:$H$14854), 443089, 1457802

- 1st doses: (format: month: formula, 1st doses applied in the month, accumulated 1st doses with previous months)
December: =SUMAR.SI.CONJUNTO($H$3:$H$14854;$G$3:$G$14854;"=12-2020";$F$3:$F$14854;"=DV1 - PRIMER DOSIS VIDA"), 2480, 2480
January: =SUMAR.SI.CONJUNTO($H$3:$H$14854;$G$3:$G$14854;"=1-2021";$F$3:$F$14854;"=DV1 - PRIMER DOSIS VIDA"), 42770, 45250
February: =SUMAR.SI.CONJUNTO($H$3:$H$14854;$G$3:$G$14854;"=2-2021";$F$3:$F$14854;"=DV1 - PRIMER DOSIS VIDA"), 71736, 116986
March: =SUMAR.SI.CONJUNTO($H$3:$H$14854;$G$3:$G$14854;"=3-2021";$F$3:$F$14854;"=DV1 - PRIMER DOSIS VIDA"), 205317, 322303
April: =SUMAR.SI.CONJUNTO($H$3:$H$14854;$G$3:$G$14854;"=4-2021";$F$3:$F$14854;"=DV1 - PRIMER DOSIS VIDA"), 341417, 663720
May (until 24th, only for verification): =SUMAR.SI.CONJUNTO($H$3:$H$14854;$G$3:$G$14854;"=5-2021";$F$3:$F$14854;"=DV1 - PRIMER DOSIS VIDA"), 203797, 867517

- 2nd doses: (format: month: formula, 2nd doses applied in the month, accumulated 2nd doses with previous months)
December: =SUMAR.SI.CONJUNTO($H$3:$H$14854;$G$3:$G$14854;"=12-2020";$F$3:$F$14854;"=DV2 - SEGUNDA DOSIS VIDA"), 0, 0
January: =SUMAR.SI.CONJUNTO($H$3:$H$14854;$G$3:$G$14854;"=1-2021";$F$3:$F$14854;"=DV2 - SEGUNDA DOSIS VIDA"), 12710, 12710
February: =SUMAR.SI.CONJUNTO($H$3:$H$14854;$G$3:$G$14854;"=2-2021";$F$3:$F$14854;"=DV2 - SEGUNDA DOSIS VIDA"), 33982, 46 692
March: =SUMAR.SI.CONJUNTO($H$3:$H$14854;$G$3:$G$14854;"=3-2021";$F$3:$F$14854;"=DV2 - SEGUNDA DOSIS VIDA"), 168196, 214888
April: =SUMAR.SI.CONJUNTO($H$3:$H$14854;$G$3:$G$14854;"=4-2021";$F$3:$F$14854;"=DV2 - SEGUNDA DOSIS VIDA"), 136105, 350993
May (until 24th, only for verification): =SUMAR.SI.CONJUNTO($H$3:$H$14854;$G$3:$G$14854;"=5-2021";$F$3:$F$14854;"=DV2 - SEGUNDA DOSIS VIDA"), 239292, 590285

**Comment by JuanaPalotes** [comment]
Some date changes:
If you add this data, there will be some inconsistencies, this is because most of the firsts updates have the report date but not the day of data cutoff:
(Format: Date of report, date of cutoff, source, part where says date of cutoff)
- 2021-01-08, 2021-01-07, [source](https://www.ccss.sa.cr/noticias/servicios_noticia?9-751-personas-recibieron-primera-dosis-de-vacuna-para-evitar-la-covid19), "La subárea de Vigilancia Epidemiológica de la Caja Costarricense de Seguro Social (CCSS) informó que se han aplicado un total de 9 751 vacunas contra la covid-19 de acuerdo con los reportes recogidos desde el 24 de diciembre hasta el **siete de enero** de 2021"
- 2021-01-15, 2021-01-14, [source](https://www.ccss.sa.cr/noticias/servicios_noticia?ccss-registra-24-859-vacunas-contra-la-covid19-aplicadas), "La Caja Costarricense de Seguro Social (CCSS) registra la aplicación de 24 859 vacunas contra la covid-19 desde que inició esta jornada el 24 de diciembre anterior, esto según datos de la institución actualizados al cierre de este **jueves 14 de enero**."
- 2021-01-25, 2021-01-22, [source](https://www.ccss.sa.cr/noticias/servicios_noticia?ccss-ha-colocado-48-128-vacunas-contra-la-covid-19), "La Caja Costarricense de Seguro Social (CCSS) registra 48 128 vacunas contra la covid-19 aplicadas según consta en los registros del módulo SIVA del Expediente Digital Único en Salud (Edus) al **Viernes 22 de Enero del 2021**."
- 2021-02-01, 2021-01-29, [source (different)](https://www.ccss.sa.cr/noticias/servicios_noticia?11-838-personas-ya-cuentan-con-su-esquema-de-vacunacion-completo-contra-la-covid), "Once mil ochocientas treinta y ocho personas ya recibieron la segunda dosis contra la covid, por lo que ya completaron su esquema de vacunación contra esta enfermedad; así lo reflejan los datos registrados al **viernes 29 de enero** en el sistema informático de vacunación (SIVA) de la Caja Costarricense de Seguro Social (CCSS)."
- 2021-02-08, 2021-02-05, [source (different)](https://www.ccss.sa.cr/noticias/servicios_noticia?costa-rica-registra-75-113-dosis-de-vacunas-aplicadas-contra-la-covid19), "La Caja Costarricense de Seguro Social (CCSS) registra, con corte del **5 de febrero de 2021**, un total de 75 113 dosis vacunas contra la covid aplicadas desde que se inició este proceso el 24 de diciembre anterior."
- 2021-02-22, 2021-02-19, [source (different)](https://www.ccss.sa.cr/noticias/servicios_noticia?ccss-sobrepasa-las-100-mil-vacunas-aplicadas), "Según los datos del Sistema Integrado de Información en Vacunas (SIVA) al **cierre del viernes anterior** (...)"
- 2021-03-01, 2021-02-26, [source (reduced URL)](https://www.ccss.sa.cr/noticias/salud_noticia?ccss-registra-149-812-vacunas-aplicadas-contra-la-covid-19), "Los funcionarios de la Caja Costarricense de Seguro Social (CCSS) han registrado la colocación total de 149 812 vacunas contra la covid-19, alcanzando una tasa de aplicación nacional de 2,90 por cada 100 habitantes; esto según el Sistema de Información en Vacunación (SIVA) al **26 de febrero del 2021**."

Note that the update from 2021-01-03 doesn't have a cutoff date, so it makes inconsistencies with the proposed data for 2020-12-31 (2480 > 2455), I wrote to Dra. Leandra Abarca (labargom@ccss.sa.cr or savepide@ccss.sa.cr) from the Subárea de Vigilancia Epidemiológica but didn't receive an official answer

**Comment by JuanaPalotes** [comment]
Query:
As Costa Rica was accepted like the 38th country to enter the OCDE, I was wondering if it is possible to add the country to the list displayed when clicking on "OCDE" in the homepage of covid-19 vaccinations of OWID? [source](https://www.oecd.org/costarica/oecd-welcomes-costa-rica-as-its-38th-member.htm)

**Comment by lucasrodes** [comment]
Hi @JuanaPalotes,
Thanks for your contribution and your dedication, this is really helpful.

Before reviewing this, just to make sure that I understand your points, can you confirm that you would like to correct the values for:

1) the last day of the month (first comment)
2) some specific dates (second comment)


Regarding OCDE acceptance, we'll have to update few things. We'll let you know when this is done

**Comment by JuanaPalotes** [comment]
Nice @lucasrodes ,
1. Yes, my idea is to add new updates at the end of each month (December 31st, January 31st, February 28th, March 31st and April 30th)
2. Right again, put the cutoff date in order to reduce inconsistencies

Just forgot to say: the document from which this data is obtained, is not updated weekly like the rest of things (since April 12nd when it was uploaded, May 26th was the first time it was updated)

**Comment by JuanaPalotes** [comment]
Just noticed more discrepancies between previously reported data and this document (only February's interpretation doesn't have problems with total, 1st and 2nd doses), I'll be attentive to whether these variations remain or are solved in future versions of the file; if you have time, I recommend you to send an e-mail to labargom@ccss.sa.cr 👍😅

**Comment by JuanaPalotes** [comment]
Now the file seems to be inaccesible, so only possible date changes remain

About this, [Presidency](https://www.presidencia.go.cr/comunicados/2021/06/ccss-registra-colocacion-de-2-331-030-vacunas-contra-covid-19/) also said that the latest update is from June 21st and not from June 22nd as it says on the web:
- "Los equipos vacunadores de la Caja Costarricense de Seguro Social (CCSS) registran la colocación de 2 331 030 vacunas contra la covid-19, según datos del Sistema Integrado de Vacunas (SIVA) con corte al **lunes 21 de junio de 2021**."
