### ISSUE TITLE
pymysql.err.OperationalError

### ISSUE THREAD

**Issue by Hadi14ua** [owid/covid-19-data#145]
Trying to run the code but here is the problem that I am facing:

pymysql.err.OperationalError: (1045, "Access denied for user 'Mr.Hadi'@'localhost' (using password: NO)")

Would you please guide me to solve this problem?

**Comment by edomt** [comment]
Which file exactly are you trying to run? These scripts are uploaded to GitHub for transparency and versioning purposes, but they're configured to work with our internal database and can't really be executed on another user's machine. Are you trying to reproduce something in particular?

**Comment by Hadi14ua** [comment]
Thank you for replying to my message. Now I am working on research related to covid-19. I was trying to run your code to reproduce the results. Also I was tryig to see if I can run your algorithm for the current data ie data till September 2020.

**Comment by edomt** [comment]
It really depends on which script you're trying to execute; they will not work without a database to connect to and to insert the data into. I don't think there's an easy for you to simply run our code without reading it and understanding what it does first.
