### ISSUE TITLE
France and EU total_cases after 5/19

### ISSUE THREAD

**Issue by bluewildcats** [owid/covid-19-data#1451]
Beginning on 2021-05-20 Daily total_cases for FRA and OWID_EUN declines by 364,082.  
total_cases[date] should equal total_cases[date-1] + new_cases[date]

iso_code      date     total_cases  new_cases
FRA        2021-05-27   **5,697,076**    13,933
FRA        2021-05-26   **5,683,143**    12,657
FRA        2021-05-25   **5,670,486**     3,155
FRA        2021-05-24   **5,667,331**     2,230
FRA        2021-05-23   **5,665,101**     9,704
FRA        2021-05-22   **5,655,397**    12,611
FRA        2021-05-21   **5,642,786**    12,803
FRA        2021-05-20   **5,629,983**    15,415
FRA        2021-05-19   5,978,650    19,057
FRA        2021-05-18   5,959,593    17,223
FRA        2021-05-17   5,959,593     3,351
FRA        2021-05-16   5,959,593    13,948

**Comment by edomt** [comment]
Thanks @bluewildcats 
This has now been fixed.
