### ISSUE TITLE
Vaccination reports for Gibraltar exceeding population?

### ISSUE THREAD

**Issue by WorldSEnder** [owid/covid-19-data#1453]
While toying around with the data and writing a [personal visualization](https://github.com/WorldSEnder/vis_covid_vacc) I noticed that Gibraltar has reported a higher amount of people vaccinated versus their estimated population size. As of now, this is the only outlier country in this regard.

[The data](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Gibraltar.csv#L102) suggests 38990 people (partially) vaccinated, versus the [expected population](https://github.com/owid/covid-19-data/blob/master/scripts/input/un/population_2020.csv#L80) of 33691.

This is not necessarily caused by bad data, of course, maybe someone has additional insight into their vaccination program, e.g. are they offering it to foreigners?, which could explain this difference. I am mainly opening this issue to try to explain the outlier.

**Comment by lucasrodes** [comment]
Hi @WorldSEnder,
Thanks for your message and interest in the data.

Gibraltar, as well as other regions in the world, are offering vaccines to non-residents.

For the case of Gibraltar, some references:
- https://www.politico.eu/article/vaccine-victory-within-gibraltars-reach/
- https://www.wsj.com/articles/post-covid-vaccine-life-in-gibraltar-11619617033

You can find more details under our [FAQs](https://ourworldindata.org/covid-vaccinations#frequently-asked-questions)

**Comment by WorldSEnder** [comment]
Thanks for your very fast reply. Citing the referenced politico article, for anybody discovering this issue later, Gibraltar specifically, it states

> But Gibraltar is not only vaccinating its own residents. About 10,000 Spanish nationals who are registered as frontier workers are eligible for a jab too.

In hindsight, I should have found the linked issue, my bad for missing it, but the additional links are very welcome.

**Comment by lucasrodes** [comment]
No problem, @WorldSEnder

It was also not that clear in the previous issue. Thanks for raising it again!
