### ISSUE TITLE
number of fully vaccinated people in DC 

### ISSUE THREAD

**Issue by vvtatarskii** [owid/covid-19-data#1462]
For some reason number of fully vaccinated per one hundred in DC drops from 7.54 on 2021/02/21 to 4.41 on 2021/02/22

2021-02-21,
District of Columbia,162674.0,225125.0,109045.0,**7.54**,23.05,53244.0,15.45,31.9,3034.0,5909.0,8373.0,0.7232021-02-22
District of Columbia,164207.0,225125.0,71399.0,**4.41**,23.27,31114.0,10.12,31.9,1533.0,5757.0,8157.0,0.729

**Comment by edomt** [comment]
Hi @vvtatarskii 
See https://github.com/owid/covid-19-data/issues/698
