### ISSUE TITLE
Unable to find the valid source in CDC website

### ISSUE THREAD

**Issue by BIRAN** [owid/covid-19-data#1472]
Hi Madam or Sir,

I am using this dataset in my research project. https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/us_state_vaccinations.csv

This dataset is not trackable on the CDC website now. The only similar dataset is US county-level vaccination data. Does anyone know why? Please let me know if I missed anything.

**Comment by BIRAN** [comment]
Here is the link of the CDC website: https://data.cdc.gov/browse?q=covid%20vaccination&sortBy=relevance

**Comment by edomt** [comment]
Hi @BIRAN 

The dataset itself doesn't seem to be on https://data.cdc.gov. We get the data from https://covid.cdc.gov/covid-data-tracker/#vaccinations. You can either:

- Scroll down to "Data Table for COVID-19 Vaccinations in the United States" and click "Download Data"
- You can also get it in JSON format here: `https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data`

We store historical versions of the file here: [scripts/scripts/vaccinations/us_states/input](https://github.com/owid/covid-19-data/tree/master/scripts/scripts/vaccinations/us_states/input)

**Comment by BIRAN** [comment]
Thank you so much! My mistake!
