### ISSUE TITLE
Missing 05-31 vaccination data on all the states

### ISSUE THREAD

**Issue by tichx** [owid/covid-19-data#1483]
In the latest commit 29dc695, all the states' May 31 vaccination data were erased. It was available previously.

**Comment by edomt** [comment]
Hi @tichx 

The data for May 31 was not erased (it never existed). It seems that the CDC didn't update its data on May 31, therefore there is a jump from May 30 to June 1 in the data. You can see the complete list of source files [here](https://github.com/owid/covid-19-data/tree/master/scripts/scripts/vaccinations/us_states/input).
