### ISSUE TITLE
Vaccinations in New Caledonia, Pfizer, *not* AstraZeneca

### ISSUE THREAD

**Issue by DrBazUK** [owid/covid-19-data#1488]
Hi team,
I see that New Caledonia is reported as having AstraZeneca according to the earlier source (SPC.int) but the government of New Caledonia are not using AstraZeneca but rather Comirnaty from Pfizer/BioNTech according to: [https://gouv.nc/info-vaccination/pour-qui](https://gouv.nc/info-vaccination/pour-qui)
"New Caledonia has doses of the Comirnaty © vaccine produced by Pfizer / BioNTech which requires two injections 21 days apart."

Could this be updated in the Locations.csv?

Many thanks in advance,
Baz.

**Comment by lucasrodes** [comment]
Thanks for reporting this. We will be changing it accordingly.
