### ISSUE TITLE
Pitcairn Island data

### ISSUE THREAD

**Issue by Forrest-J** [owid/covid-19-data#1493]
The data for Pitcairn Island doesn't seem to be corroborated by the linked source: [https://www.visitpitcairn.pn/blog/index.html](https://www.visitpitcairn.pn/blog/index.html)

The post only says that the entire population is to receive vaccines, and doesn't say that they all have. The post also does not specify when the campaign began.

_Originally posted by @Forrest-J in https://github.com/owid/covid-19-data/issues/230#issuecomment-851050820_

**Comment by edomt** [comment]
We expected the blog to be updated to confirm this information. Because it still hasn't been updated, for now we'll temporarily remove Pitcairn from the data.
