### ISSUE TITLE
How to access past datasets?

### ISSUE THREAD

**Issue by Silvanoxx** [owid/covid-19-data#1497]
Sorry for the silly question but I am running a risk assessment math model on the Covid-19 datasets and I am looking for past 'owid-covid-data' files for the last 6 months. Where should I look?

thank
Sil

**Comment by lucasrodes** [comment]
Hi @Silvanoxx,
Thanks for your interest.

Not sure I understand your question, but if what you want is to check older versions of [owid-covid-data.csv](https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv) file, you can check the [commit history](https://github.com/owid/covid-19-data/commits/master/public/data/owid-covid-data.csv).
