### ISSUE TITLE
Ascension Island data

### ISSUE THREAD

**Issue by Forrest-J** [owid/covid-19-data#1499]
On Ascension Island, as of March 25, 798 first doses and 3 second doses of AstraZeneca have been administered: [https://www.ascension.gov.ac/covid-19-vaccination-campaign-continues](https://www.ascension.gov.ac/covid-19-vaccination-campaign-continues)

Ascension is part of the British Overseas Territory of Saint Helena, Ascension and Tristan da Cunha. Saint Helena is already counted in the current vaccinations dataset.

Google seems to incorrectly use the data for Saint Helena to represent the whole of Saint Helena, Ascension and Tristan da Cunha.

_Originally posted by @Forrest-J in https://github.com/owid/covid-19-data/issues/230#issuecomment-850856002_

**Comment by lucasrodes** [comment]
Thanks, @Forrest-J!

The data has been added to Saint Helena and will be visible in the next data update.

**Comment by Forrest-J** [comment]
Even though the data has been added the source doesn't seem to be cited right now.

**Comment by lucasrodes** [comment]
Hi @Forrest-J,
Thanks for your message.

The thing is that our current setup does not allow for multi-source records. We will note this down as a potential feature to add in future releases.

**Comment by Forrest-J** [comment]
Will the record be renamed to "Saint Helena, Ascension and Tristan da Cunha" instead, since just "Saint Helena" is inaccurate and not representative.

**Comment by lucasrodes** [comment]
Thanks for your message, @Forrest-J.

We have this in our roadmap, along with other country names (see Timor, which should be Timor-Leste).

The way our code is structured at the moment, these changes are not simple as there are several files implied. We will let you know once we fix this.
