### ISSUE TITLE
New deaths per million is same as all death per mission

### ISSUE THREAD

**Issue by arsalan993** [owid/covid-19-data#15]

**Comment by HannahRitchie** [comment]
Hi! What files in particular are you looking at? 

total_deaths_per_million.csv and new_deaths_per_million.csv ? The figures are not the same in these files.

Thanks!

**Comment by arsalan993** [comment]
In new_deaths_per_million data should be of today ..  but in in both file data is from 

2019-12-31 till this day.

https://github.com/owid/covid-19-data/blob/master/public/data/ecdc/total_deaths_per_million.csv
https://github.com/owid/covid-19-data/blob/master/public/data/ecdc/new_deaths_per_million.csv

**Comment by HannahRitchie** [comment]
Ah, I see the confusion.

The total_deaths_per_million is the cumulative total of deaths from 2019-12-31 (i.e. the sum of the new_deaths_per_million).

new_deaths_per_million is the daily new death total on each individual day since the start of the pandemic.

**Comment by arsalan993** [comment]
Thank you very much
