### ISSUE TITLE
Exact specification of the source and reporting entity

### ISSUE THREAD

**Issue by rtxgold** [owid/covid-19-data#1505]
For Romania you automatically take the data from the datelazi.ro website but this site is not the government website it is only in partnership with a non-governmental organization and the government does not enter the data on that platform and has no responsibility for the data provided if they are correct or not. It should not be specified as the source "Government of Romania" but exactly source datelazi.ro or the NGO full name in order not to mislead or create confusion. Thank you.

**Comment by lucasrodes** [comment]
Thanks for noticing this, @rtxgold!
We have fixed this and will be visible in next data update!
