### ISSUE TITLE
Taiwan vaccination data invalid

### ISSUE THREAD

**Issue by 09F911029D74E35BD84156C5635688C0** [owid/covid-19-data#1509]
The data currently set for Taiwan is incorrect.

I'm not sure why a bunch of valid data here was changed, source of data is not clear. https://github.com/owid/covid-19-data/commit/aea4ce7c4c598fcb30f24911c52eff54308a8984

And last two days it's using wrong number. It's not number of doses used but number of doses distributed. The number of doses used is second column from right.

https://www.cdc.gov.tw/File/Get/03NYc86FqS29vHvC2kmdwg (unfortunately file is replaced daily)

![data](https://user-images.githubusercontent.com/62552264/120898889-84f87400-c65f-11eb-9a79-a8f2034f6916.png)

Current file displays correct value for last two days.

* June 4 - 678,418
* June 3 - 624,132

The rest of the data from the commit above should be restored.

You can compare values from this magazine - https://web.cw.com.tw/covid-live-updates-2021-en/index.html (file is https://web.cw.com.tw/covid-live-updates-2021-en/data/taiwan-vaccinations.csv)

**Comment by lucasrodes** [comment]
Thanks @09F911029D74E35BD84156C5635688C0,
There was a bug in that commit indeed. Thanks for reporting. It has been fixed in e70ea8ef97efeb7e860dac749b4b6379cc9be1cb
