### ISSUE TITLE
New Zealand wrong data

### ISSUE THREAD

**Issue by RiccardoBorchi** [owid/covid-19-data#152]
The number of total cases of New Zealand is wrong. Today I think it should be more than 1.800, not 1.515.

**Comment by RiccardoBorchi** [comment]
Hi @edomt,

this is strange. Other websites and source (like Johns Hopkins University) report, for yesterday, 1.872 total cases and 1.808 recovered.

Why this incongruence?

**Comment by edomt** [comment]
The ECDC's total for today is still in line with what the NZ government is publishing: https://www.health.govt.nz/news-media/media-releases/2-new-imported-cases-covid-19

> 14 October 2020 (...) Our total number of confirmed cases of COVID-19 is 1,518, which is the number we report to the World Health Organization. 

I don't know where JHU is getting its data from, but it seems to be in contradiction with the official report.
