### ISSUE TITLE
vaccinations.csv -- csv file or xml file?

### ISSUE THREAD

**Issue by B-LIE** [owid/covid-19-data#1530]
I'm downloading file https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations/vaccinations.csv to my computer, and try to open the downloaded file in Excel.

In Excel (and Notepad++), this file appears to be an XML-file???

If I click on "raw" on the web page, or click on "download" on the web page, the data appear as cav data. 

What is wrong?

**Comment by lucasrodes** [comment]
Hi @B-LIE,
Could you describe a bit more on which error you are getting?

The file you refer to is a standard CSV file, so it should be easily imported into such software.

I just tested, and works fine in pandas:

```python
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv")
```

**Comment by B-LIE** [comment]
Sorry for slow response... I just got my first Phizer dose.

I'm using Julia, and the following procedure has worked fine for data from Johns Hopkins University:

```julia
url_covid_vaccinated = "https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv"
download(url_covid_vaccinated,"covid_vaccinated_global.csv")
```
When I open file "covid_vaccinated_global.csv" in, e.g., Notepad++, the file looks as follows:

```` 






<!DOCTYPE html>
<html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
...
```
This is not a standard `csv` file. 

I have downloaded  `csv` files from web pages before (e.g., Johns Hopkins), and they look similar to the "raw" display in your web page.

**Comment by lucasrodes** [comment]
Congrats on the vaccine!

You should use the "raw" link. Change the part in the link where it says `blob` for `raw`:

```julia
url_covid_vaccinated = "https://github.com/owid/covid-19-data/raw/master/public/data/vaccinations/vaccinations.csv"
download(url_covid_vaccinated,"covid_vaccinated_global.csv")
```

**Comment by B-LIE** [comment]
Hm... there is a slight difference in the `url` in your example, and in my example. I have used the `url` that appears at the top of the web page when I open your system:
![Uploading image.png…]()

**Comment by B-LIE** [comment]
Ah, now it works. I just used the wrong `url`. Thanks.
