### ISSUE TITLE
South africa statistics not updating

### ISSUE THREAD

**Issue by 19reubens** [owid/covid-19-data#1534]
Hi there,
South african statistics havent updated since the 22nd of may.

**Comment by lucasrodes** [comment]
Hi @19reubens,
South Africa has started administering Pfizer/BioNTech, hence combining single-shot and two-dose vaccine schemes.

Therefore, with the current publicly made data, we cannot estimate the number of people who have received at least one dose or that are fully vaccinated. 

However, we are reporting the total number of doses administered (metric `total_vaccinations`), which you can find in this graph: https://ourworldindata.org/explorers/coronavirus-data-explorer?Metric=Vaccine+doses&Interval=Cumulative&Relative+to+Population=true&Align+outbreaks=false&country=~ZAF.
