### ISSUE TITLE
Vaccinations.csv: Missing data for Thailand

### ISSUE THREAD

**Issue by limyeeqing126** [owid/covid-19-data#1543]
Hi Team, thanks for your effort in providing quality vaccinations data. For Thailand, there are few missing data from 27 May to 9 June. The people vaccinated, fully vaccinated and total vaccination data are not fully updated in Vaccinations.csv file but in facts the Thailand local source has updated the pdf file, is the data not valid to be published in OWID or miss data capture from the local pdf file. For example, you may refer to the [link]https://ddc.moph.go.th/uploads/ckeditor2//files/Daily%20report%202021-06-05.pdf) for 4 June 2021 data. 

For European Union vaccinations data, I have tried to sum up the EU27 countries vaccinations data but the results are not tally with the OWID_EUN data, could you advise me on this? 
[EU sample..xlsx](https://github.com/owid/covid-19-data/files/6645937/EU.sample.xlsx)

Thank you!

**Comment by lucasrodes** [comment]
Hi @limyeeqing126,
Thanks for reporting this. Data for Thailand has been added and will be available on our website in the next general data update.

**Comment by lucasrodes** [comment]
I have moved your EU question to issue #1547. Consider issuing different issues for different questions.
