### ISSUE TITLE
New data available for Germany

### ISSUE THREAD

**Issue by immertroll** [owid/covid-19-data#155]
There is a new publication from RKI from 14.10.2020 with new data.
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Okt_2020/2020-10-14-en.pdf?__blob=publicationFile

**Comment by edomt** [comment]
Thank you, this will be included in today's update.

**Comment by immertroll** [comment]
Can I support you in any way or is an issue the only way?

**Comment by edomt** [comment]
Thanks for offering! We feed the data via our own internal input system, so there's not much you can do to add data yourself. But by all means, if you spot that a new report for Germany is available but isn't in our data 2-3 days after publishing, feel free to notify us here, and we'll check (you can use this same issue #155, I'll get a notification every time).
Thank you!

**Comment by immertroll** [comment]
There is a new report from RKI from 27.10. :-)
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Okt_2020/2020-10-21-de.pdf?__blob=publicationFile
