### ISSUE TITLE
Jump in world vaccinated percentages

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#1555]
In the file https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv I see a large unexplained jump in the world percentage 1st vaccinated and fully vaccinated between 9 and 10 June which is out of line with the daily data in the rest of the file. 

World,OWID_WRL,2021-06-09,2260607175,**946225318**,483695316,39097638,34101188,29.0,12.14,6.21,4375
World,OWID_WRL,2021-06-10,2299138296,**1579801960**,713425895,38531121,34568947,29.5,20.27,9.15,4435

I cannot see an explanation for the jump, maybe I am not lookin gin correct place, so just querying if the data is correct. Maybe it is analysed differently now?

Thanks for all your work in getting the stats etc. and making them available

**Comment by zizwiz** [comment]
Looking through the items logged I think this is connected to 

_Huge spike in secondary vaccinations in Asia on 2021-06-10 #1551_

If so please ignore this and close it.

Thanks.

**Comment by edomt** [comment]
Yes, that's the same issue :)
