### ISSUE TITLE
Republic of Korea (South Korea) using Janssen vaccine

### ISSUE THREAD

**Issue by DrBazUK** [owid/covid-19-data#1558]
@edomt & colleagues, just mentioning that South Korea now appears to be using the J&J vaccine according to this press release:
[https://www.mfds.go.kr/brd/m_99/view.do?seq=45420&srchFr=&srchTo=&srchWord=&srchTp=0&itm_seq_1=0&itm_seq_2=0&multi_itm_seq=0&company_cd=&company_nm=&Data_stts_gubun=C1009&page=1](https://www.mfds.go.kr/brd/m_99/view.do?seq=45420&srchFr=&srchTo=&srchWord=&srchTp=0&itm_seq_1=0&itm_seq_2=0&multi_itm_seq=0&company_cd=&company_nm=&Data_stts_gubun=C1009&page=1).

Also this public-facing site confirms 4 vaccines in use: [https://ncv.kdca.go.kr/menu.es?mid=a10119000000](https://ncv.kdca.go.kr/menu.es?mid=a10119000000)

Pfizer and Biontech | Moderna* | AstraZeneca | Janssen Johnson&amp;Johnson

KCDA now lists Janssen doses along with Pfizer and AstraZeneca:
[http://www.kdca.go.kr/board/board.es?mid=a20501000000&bid=0015&list_no=713681&act=view](http://www.kdca.go.kr/board/board.es?mid=a20501000000&bid=0015&list_no=713681&act=view)

Kind regards,
Barry

**Comment by edomt** [comment]
Hi @DrBazUK 

Thank you for letting us know!
We could try to build a scraper that reads reports such as http://www.kdca.go.kr/board/board.es?mid=a20501000000&bid=0015&list_no=713681&act=view, but it would break if they change the format. By any chance, do you know if either MFDS or KDCA is publishing a CSV/XLSX file anywhere with the same data?

**Comment by DrBazUK** [comment]
> [...]By any chance, do you know if either MFDS or KDCA is publishing a CSV/XLSX file anywhere with the same data?

Not that I've seen on my research to date... will keep an eye out but more likely is that we'll watch for the changes and simply flag to you when we identify them.

**Comment by edomt** [comment]
Thank you! Fixed in ed638f8ed7f79e0d865682a1ca7667dff3a1ae24
