### ISSUE TITLE
Lithuania Data is weird on 10/16/2020

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#156]
Hello, Lithuania data has a very large increase yesterday, which does not seem right. Would you mind check he validity of the new figures? Thanks!

**Comment by garas** [comment]
`Lithuania - samples tested,2020-10-16,LTU,http://sam.lrv.lt/lt/naujienos/koronavirusas,Ministry of Health,,7908628,8777398,3224.269,2905.137,1135246,417.019,7001.517,0`

7908628 should be 8628.

---

I see you are missing testing data for weekends. Ministry of Health website doesn't update data on weekends.

Vilnius University map collects testing data for weekends too.
https://osp.maps.arcgis.com/apps/opsdashboard/index.html#/e27574647d6f41ddaf7ed28a7587f6b5

JSON data can be retrieved from ArcGIS [FeatureServer](https://services.arcgis.com/XdDVrnFqA9CT3JgB/ArcGIS/rest/services/covid19_statistics/FeatureServer/0/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=data+desc&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=html&token=) for this map. You could backfill weekend data from here (field `Atlikta_testų_per_d_`).

**Comment by edomt** [comment]
Well spotted, thanks! This is due to a typo in the source data: https://sam.lrv.lt/lt/naujienos/koronavirusas (8777398 instead of 877398). We'll fix it now.

**Comment by RuijingZ** [comment]
Thank you for fixing it. But today, Lithuania data on 10/16/2020 went back to the wrong numbers again

**Comment by RuijingZ** [comment]
> Well spotted, thanks! This is due to a typo in the source data: https://sam.lrv.lt/lt/naujienos/koronavirusas (8777398 instead of 877398). We'll fix it now.

Thank you for fixing it. But today, Lithuania data on 10/16/2020 went back to the wrong numbers again
