### ISSUE TITLE
Test Data: Germany

### ISSUE THREAD

**Issue by ylitviakova** [owid/covid-19-data#1561]
In this week's release, something is going on with the Germany testing data: it appears this week's data omitted the week of January 10, 2021 (in last week's release it was 37,248,234 cumulative total and 444.575 cumulative total per thousand). So all the weeks have moved, and it appears as if the latest data for Germany is still from May 31, 2021 -- should be around June 5-6, 2021. Is that correct?

**Comment by lucasrodes** [comment]
Thanks for reporting,
We introduced an error in the conversion from week number to date. It has been solved now.
