### ISSUE TITLE
Data for Slovakia are incorrect

### ISSUE THREAD

**Issue by wdfeww** [owid/covid-19-data#157]
Hello, it seems like your data for the Slovak republic are not correct. Here is my comparison
![Screen Shot 2020-10-19 at 10 54 14 AM](https://user-images.githubusercontent.com/22939457/96426915-31373880-11fe-11eb-94ca-8ced61acc915.png)
Data of Slovakia are shifted by two days.
Slovakia government website where you can find statistics of coronavirus on Slovak territory: https://korona.gov.sk/en/coronavirus-covid-19-in-the-slovak-republic-in-numbers/
REST endpoint to fetch the latest data:
GET: https://mapa.covid.chat/map_data 
you can find data in the _**chart**_ array
![Screen Shot 2020-10-19 at 11 25 45 AM](https://user-images.githubusercontent.com/22939457/96427059-5e83e680-11fe-11eb-9b9e-331b95a36128.png)

_NOTE: date format is dd-MM-YYYY_

**Comment by edomt** [comment]
Thank you @wdfeww. We've now changed our collection method for the testing data to use this endpoint instead.

For the cases however, there is unfortunately not much we can do to fix this. We source our data directly from the European Centre for Disease Prevention and Control, and report it without making alterations to its original cases and death figures.

**Comment by wdfeww** [comment]
Hi @edomt, can you please also update **COVID-19 dataset** that is presented here in GitHub. I can see that there is some job that is updating tables every hour but columns that describe covid testing are empty for Slovakia.
![Screen Shot 2020-10-20 at 9 19 07 AM](https://user-images.githubusercontent.com/22939457/96553620-b6c9ef80-12b5-11eb-904f-bf9f3df5fc57.png)
?

**Comment by edomt** [comment]
These columns are all for the testing dataset—we run testing updates around 3 times per week (usually Monday/Wednesday/Friday).
