### ISSUE TITLE
data file missing 

### ISSUE THREAD

**Issue by jparra0419** [owid/covid-19-data#1574]
The file "population-thousands.csv" from the "input"  folder is missing. This file is  read by all the python notebooks that are in the  this folder. These notebooks are:  who,   and jh_generate.  The name of the file  "population-thousands.csv"  appears in several places in the notebooks. Without  this file is impossible to run the codes. However, if this file has been replaced by "population_2020.csv" that is in the "input" folder , it will be nice to  report it   to the community. If this is the case it will require to  update  the notebooks that contain the file.
Thank you,
Jparra014
joparram@yahoo.com      l

**Comment by edomt** [comment]
Hi @jparra0419 

The notebooks you mention (`who` and `jh_generate`) date all the way back to the start of the pandemic, and haven't been used/maintained for many months. Our data on confirmed cases and deaths now comes from Johns Hopkins University, and is processed by [`jhu.py`](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/jhu.py)
