### ISSUE TITLE
Testing data for Cyprus

### ISSUE THREAD

**Issue by finnwoelm-sdsn** [owid/covid-19-data#158]
Dear OWID team,

Thank you for the fantastic work! ❤️ We make heavy use of it for the [data portal and database of the Lancet COVID-19 Commission](data.covid19commission.org/).

Our colleagues in Cyprus alerted us to the availability of official testing data for their country and asked if it could be included in the database. The data is prepared by the Ministry of Health and seems to be updated daily. Unfortunately, the website is only available in Greek, but the CSV file is completely in English.

Page URL: https://www.data.gov.cy/node/4617?language=en
Dataset URL (latest version as of today): https://www.data.gov.cy/sites/default/files/CY%20Covid19%20Open%20Data_45.csv

![image](https://user-images.githubusercontent.com/55237550/96457272-d9a9c480-121f-11eb-9171-e37b616e7011.png)

![image](https://user-images.githubusercontent.com/55237550/96457609-48871d80-1220-11eb-8a53-f349819054b7.png)

Test units appear to be "tests performed".

Do you think this can be added? Let me know if we can help in any way and thanks again for this fantastic resource!

Greetings from Paris,
Finn

**Comment by edomt** [comment]
Hi Finn,
Thank you very much for this! I've just added Cyprus to our dataset, and it will go live within the next few hours.
Greetings from Paris,
Edouard

**Comment by finnwoelm-sdsn** [comment]
Amazing! 🙌 And thank you for your fantastic coverage of France's COVID-19 situation on Twitter 😊
