### ISSUE TITLE
Incomplete vaccination data for South Africa

### ISSUE THREAD

**Issue by TheRealDudeX** [owid/covid-19-data#1580]
The data from 17 May is incomplete for South Africa. I created a table below that contains the accurate data. This is sourced from the Department of Health press releases.

Things to note:

1. From 23 May onwards the data that is supplied is for the previous day up to midnight (23:59:59). Before that the data was accurate up to the time of the daily press release would was normally in the afternoon at various times. As such the protocol became more consistent from 23 May.
2. The amount of Johnson and Johanson vaccines was over inflated up to and including the 24 May, so you will see in the data below that the amount decreases on 24 May. The minister explained this was due to a data verification process to correct the data. This is stated in the 24 May press release.
3. From 3 June 2021 the department supplied the report in pdf and not html anymore. The full updated report is published daily on https://sacoronavirus.co.za/latest-vaccine-statistics/, but this report changes daily so it can't be used for historical data. An infographic is kept for historical purposes and is published on the URL's I included below. The infographic below doesn't include the vaccinations per gender, province and manufacturer like the full report does, but because Johnson and Johnson is not administered anymore for the time being it is easy to infer the number of Pfizer doses (total vaccinations as per infographic - Number of Johnson and Johnson vaccines). For verification of the fact that Johnson and Johnson is not administered you can see that the amount of Johnson and Johnson vaccinations is still the same on the current full report ( https://sacoronavirus.co.za/latest-vaccine-statistics/) as it was on the 24 May press release.

|location |	date | vaccine | source_url | total_vaccinations | people_vaccinated | people_fully_vaccinated | Johnson&amp;Johnson | Pfizer/BioNTech First Dose |
-- | -- | -- | -- | -- | -- | -- | -- | --
| South Africa | 2021-05-17 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-17-may-2021/ | 478733 | 478733 | 478733 | 478733 | 0	    
| South Africa | 2021-05-18 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-18-may-2021/ | 519139 | 519139 | 479768 | 479768 | 39371	
| South Africa | 2021-05-19 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-19-may-2021/ | 558170 | 558170 | 480665 | 480665 | 77505	
| South Africa | 2021-05-20 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-20-may-2021/ | 597406 | 597406 | 480665 | 480665 | 116741	
| South Africa | 2021-05-21 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-21-may-2021/ | 642382 | 642382 | 480665 | 480665 | 161717	
| South Africa | 2021-05-22 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-23-may-2021/ | 647983 | 647983 | 480665 | 480665 | 167318	
| South Africa | 2021-05-23 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-24-may-2021/ | 651628 | 651628 | 479768 | 479768 | 171860	
| South Africa | 2021-05-24 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-25-may-2021/ | 700904 | 700904 | 479768 | 479768 | 221136	
| South Africa | 2021-05-25 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-26-may-2021/ | 761903 | 761903 | 479768 | 479768 | 282135	
| South Africa | 2021-05-26 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-27-may-2021/ | 828204 | 828204 | 479768 | 479768 | 348436	
| South Africa | 2021-05-27 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-28-may-2021/ | 898955 | 898955 | 479768 | 479768 | 418187	
| South Africa | 2021-05-28 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-29-may-2021/ | 963876 | 963876 | 479768 | 479768 | 484108	
| South Africa | 2021-05-29 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-30-may-2021/ | 968319 | 968319 | 479768 | 479768 | 488551	
| South Africa | 2021-05-30 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-31-may-2021/ | 970448 | 970448 | 479768 | 479768 | 490680	
| South Africa | 2021-05-31 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-1-june-2021/ | 1045104 | 1045104 | 479768 | 479768 | 565336	
| South Africa | 2021-06-01 | Johnson&amp;Johnson, Pfizer/BioNTech | https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-2-june-2021/ | 1117569 | 1117569 | 479768 | 479768 | 637801	
| South Africa | 2021-06-02 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/03/update-on-covid-19-03rd-june-2021/ | 1193352 | 1193352 | 479768 | 479768 | 713584	
| South Africa | 2021-06-03 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/04/update-on-covid-19-04th-june-2021/ | 1266893 | 1266893 | 479768 | 479768 | 787125	
| South Africa | 2021-06-04 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/05/update-on-covid-19-05th-june-2021/ | 1336547 | 1336547 | 479768 | 479768 | 856779	
| South Africa | 2021-06-05 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/06/update-on-covid-19-06th-june-2021/ | 1343433 | 1343433 | 479768 | 479768 | 863665	
| South Africa | 2021-06-06 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/07/update-on-covid-19-07th-june-2021/ | 1350245 | 1350245 | 479768 | 479768 | 870477	
| South Africa | 2021-06-07 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/08/update-on-covid-19-08th-june-2021/ | 1433730 | 1433730 | 479768 | 479768 | 953962	
| South Africa | 2021-06-08 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/09/latest-confirmed-cases-of-covid-19-in-south-africa-9-june-2021/ | 1525271 | 1525271 | 479768 | 479768 | 1045503	
| South Africa | 2021-06-09 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/10/latest-confirmed-cases-of-covid-19-in-south-africa-10-june-2021/ | 1619011 | 1619011 | 479768 | 479768 | 1139243	
| South Africa | 2021-06-10 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/11/latest-confirmed-cases-of-covid-19-in-south-africa-11-june-2021/ | 1690026 | 1690026 | 479768 | 479768 | 1210258	
| South Africa | 2021-06-11 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/12/latest-confirmed-cases-of-covid-19-in-south-africa-12-june-2021/ | 1767415 | 1767415 | 479768 | 479768 | 1287647	
| South Africa | 2021-06-12 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/13/latest-confirmed-cases-of-covid-19-in-south-africa-13-june-2021/ | 1773417 | 1773417 | 479768 | 479768 | 1293649	
| South Africa | 2021-06-13 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/14/latest-confirmed-cases-of-covid-19-in-south-africa-14-june-2021/ | 1777288 | 1777288 | 479768 | 479768 | 1297520	
| South Africa | 2021-06-14 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/15/latest-confirmed-cases-of-covid-19-in-south-africa-15-june-2021/ | 1871987 | 1871987 | 479768 | 479768 | 1392219	
| South Africa | 2021-06-15 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/16/latest-confirmed-cases-of-covid-19-in-south-africa-16-june-2021/ | 1965812 | 1965812 | 479768 | 479768 | 1486044	
| South Africa | 2021-06-16 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/17/latest-confirmed-cases-of-covid-19-in-south-africa-17-june-2021/ | 1974099 | 1974099 | 479768 | 479768 | 1494331	
| South Africa | 2021-06-17 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/18/latest-confirmed-cases-of-covid-19-in-south-africa-18-june-2021/ | 2069346 | 2069346 | 479768 | 479768 | 1589578	
| South Africa | 2021-06-18 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/19/latest-confirmed-cases-of-covid-19-in-south-africa-19-june-2021/ | 2137071 |  2137071|479768 | 479768 | 1657303
| South Africa | 2021-06-19 | Johnson&amp;Johnson, Pfizer/BioNTech | https://sacoronavirus.co.za/2021/06/20/latest-confirmed-cases-of-covid-19-in-south-africa-20-june-2021/ | 2141624 | 2141624 |479768 | 479768 | 1661856

**Comment by edomt** [comment]
Thank you very much @TheRealDudeX - we've now patched the data with all this.
