### ISSUE TITLE
Add new vaccins for Bangladesh

### ISSUE THREAD

**Issue by Shapod** [owid/covid-19-data#1582]
Bangladesh began mass vaccination with Pfizer-BioNTech and Sinopharm doses.

https://corona.gov.bd/storage/press-releases/June2021/ZaKrbsspsXDZCGzO1Gm9.pdf

https://bdnews24.com/en/detail/health/1904304

**Comment by lucasrodes** [comment]
Hi @Shapod,
Do you have any insights on when BBIVP-Corv vaccine started to be in use?

**Comment by Shapod** [comment]
@lucasrodes from 19-06-21

https://www.thedailystar.net/coronavirus-deadly-new-threat/news/vaccination-sinopharm-starts-across-the-country-2113849

**Comment by lucasrodes** [comment]
Thanks @Shapod
