### ISSUE TITLE
Philippine Vaccinations

### ISSUE THREAD

**Issue by zacjove** [owid/covid-19-data#1584]
Here is a bunch of dates for the philippine data.
some places that are updated frequently that I like to reference are:

- herdimmunity.ph
- https://news.abs-cbn.com/spotlight/multimedia/infographic/03/23/21/philippines-covid-19-vaccine-tracker
- https://en.wikipedia.org/wiki/COVID-19_vaccination_in_the_Philippines
- https://twitter.com/PIADesk (for PIA, their dates are usually off by 1 day compared with other sources)

March 18
total_vaccinations: 292,677
people_vaccinated: 292,677
source:

April 14
total_vaccinations: 1,312,356
people_vaccinated:
source: https://www.facebook.com/pia.gov.ph/posts/4555443401149817

April 15
total_vaccinations: 1,371,057
people_vaccinated:
source: https://www.facebook.com/pia.gov.ph/photos/a.494688130558718/4559460250748132/

April 16
total_vaccinations: 1,429,807
people_vaccinated:
source: https://www.facebook.com/pia.gov.ph/photos/a.494688130558718/4562453890448768/

April 18
total_vaccinations: 1,477,757
people_vaccinated: 1,279,223
source: https://cnnphilippines.com/news/2021/4/19/Vaccines-effectivity-COVID-variants.html

April 19
total_vaccinations: 1,507,547
people_vaccinated:
source: https://www.facebook.com/pia.gov.ph/posts/4568170459877111

April 22
total_vaccinations: 1,666,687
people_vaccinated:
source: https://www.facebook.com/pia.gov.ph/posts/4576477452379745

April 23
total_vaccinations: 1,732,359
people_vaccinated:
source: https://www.facebook.com/pia.gov.ph/posts/4582410855119738

April 28
total_vaccinations: 1,849,566
people_vaccinated:
source: https://www.facebook.com/pia.gov.ph/posts/4595097587184398

May 4
total_vaccinations: 2,065,235
people_vaccinated: 1,744,649
source: https://www.facebook.com/OfficialDOHgov/posts/4385880774756474

May 21
total_vaccinations: 3,956,292
people_vaccinated: 3,030,579
source: https://twitter.com/PIADesk/status/1396066495629725699?s=20

May 23
total_vaccinations: 4,169,905
people_vaccinated:
source: https://twitter.com/PIADesk/status/1396761951519215618?s=20

May 26
total_vaccinations: 4,666,358
people_vaccinated:
source: https://twitter.com/PIADesk/status/1397755138027102208?s=20

May 27
total_vaccinations: 4,862,358
people_vaccinated:
source: https://twitter.com/PIADesk/status/1398465090475769859?s=20

June 1
total_vaccinations: 5,382,172
people_vaccinated:
source: https://twitter.com/PIADesk/status/1400019004064886785?s=20

June 2
total_vaccinations: 5,517,523
people_vaccinated: 4,174,416
source: https://twitter.com/PIADesk/status/1400315466728361989?s=20

June 4
total_vaccinations: 5,828,735
people_vaccinated: 4,343,914
source: https://twitter.com/PIADesk/status/1401094755350552581?s=20

June 5
total_vaccinations: 5,907,255
people_vaccinated: 4,386,467
source: https://twitter.com/PIADesk/status/1401469126724395008?s=20

June 9
total_vaccinations: 6,470,776
people_vaccinated: 4,724,263
source: https://twitter.com/PIADesk/status/1402840966675918850?s=20

June 10
total_vaccinations: 6,614,417
people_vaccinated:
source: https://twitter.com/PIADesk/status/1403215870470414340?s=20

June 12
total_vaccinations: 6,870,054
people_vaccinated: 5,014,582
source: https://twitter.com/PIADesk/status/1403985801533263875?s=20

June 15
total_vaccinations: 7,368,309
people_vaccinated: 5,392,859
source: https://www.facebook.com/PIAMetroManila/posts/with-a-total-of-7368309-vaccine-doses-administered-the-philippines-remained-2nd-/1729450897238448/

June 17
total_vaccinations: 7,848,392
people_vaccinated: 5,783,258
source: https://www.facebook.com/487921351235396/posts/4756186687742153/

June 19
total_vaccinations: 8,222,759
people_vaccinated: 6,102,625
source: https://twitter.com/PIADesk/status/1406777852091985922?s=20

**Comment by zacjove** [comment]
Also, the data for fully vaccinated seems to be missing for the philippines. did you move to a new system or something?
![Screen Shot 2021-06-22 at 11 37 26 AM](https://user-images.githubusercontent.com/78060017/122859234-41378700-d34e-11eb-9dd6-6277c612b430.png)

**Comment by lucasrodes** [comment]
Hi @zacjove,
Thank you very much for your reports, these are really helpful!

I just added this data to our data for the Philippines.

On your second comment, there was a small bug in our data, where the metric of `people_fully_vaccinated` was not being reported. It has now been fixed and should be live in next data update. Thanks for reporting this, too!
