### ISSUE TITLE
Kuwait vaccination data sources may not be correct

### ISSUE THREAD

**Issue by adamredfern92** [owid/covid-19-data#1594]
Hi

It has been brought to me attention that some news sites may be using the data on my site (covidvax.live) that predicts a current vaccination count based off current vaccinations rates and reporting this as actual data.

As my site uses your data as a source it has then become self fulfilling! It might be a good idea to check the Kuwait data and use only official sources.

Unfortunately it seems the Kuwaiti government is not being upfront with vaccinations numbers so it is hard to tell what is genuine.

From your data, it could be this is the most recent update from the MoH 

https://twitter.com/drayalsanad/status/1376585974948499459

Thanks

**Comment by lucasrodes** [comment]
Hi @adamredfern92,
Thanks for raising this issue. Do you have any pointers to which sources that we have used for Kuwaiti data rely on covidvax.live?

Also if you have any pointer to official reports by the Kuwaiti government, that would be extremely helpful.


Thanks for your time and help!

**Comment by adamredfern92** [comment]
Unfortunately it's hard to tell. 

https://twitter.com/drayalsanad/status/1376585974948499459 

This one on March 29th seems to come from a Ministry of Health spokesperson.

All others since then seem to come from various news outlets - the articles themselves often don't say where the Info comes from, or vaguely refer to "sources". I'm relying on google translate though so it's hard to confirm. 

https://alqabas.com/article/5847851-الصحة-تدرس-دمج-اللقاحات 

This one may be genuine as the number is quite a bit higher than my website would have been predicting at the time, but again it still seems to quote "Health sources" rather than the MoH or the Government. 

From official sources, the information given only seems to be referring to doses per day rather than overall numbers which obviously doesn't help. This (from the Center For Government Communication) apparently says they have been administering 43,000 doses a day.

https://www.instagram.com/p/CQKAdxJMf7B/

**Comment by adamredfern92** [comment]
@lucasrodes 

Ministry of health have made an official update:

As of 03/07/21

Total Doses: 2,375,455
At least 1 dose: 1,452,148
2 doses: 923,307

https://twitter.com/kuwait_moh/status/1411777117713543173?s=21

**Comment by lucasrodes** [comment]
Thanks, @adamredfern92! Adding this entry and removing previous ones that are not consistent with this value.

**Comment by adamredfern92** [comment]
@lucasrodes thanks for updating, the date should be the 3rd of July not 21st June however!

**Comment by lucasrodes** [comment]
Corrected!
