### ISSUE TITLE
Southeast Asia countries

### ISSUE THREAD

**Issue by Ltn123456** [owid/covid-19-data#1595]
> And is it possible to sum up the 11 Southeast Asia countries data to create a Southeast Asia data? The region has a population of more than 600 million, nearly 700mil, higher than European Union, North America and South America

Please open a separate issue

_Originally posted by @lucasrodes in https://github.com/owid/covid-19-data/issues/1592#issuecomment-866764029_

**Comment by lucasrodes** [comment]
Hi @Ltn123456,
While worth exploring and you definitely have a point on the relevance of the region (both in terms of population but other factors, too), we currently do not have de resources to develop new aggregate regions.

However, we have noted this down.

For completeness, we currently have different world region definitions (you can check this at https://ourworldindata.org/world-region-map-definitions). For this project, we are using the first definition in the aforementioned resource.
