### ISSUE TITLE
issue in Peru data: on some days more cases than tests?

### ISSUE THREAD

**Issue by dbaroncelli** [owid/covid-19-data#160]
If you browse the data of Peru, you can see that
on most days, the new cases number is bigger than the new tests number

**Comment by edomt** [comment]
Hi @dbaroncelli 
Peru includes positive antibody tests in their figures for confirmed cases, which impacts the data published by the European CDC (our source for case and death data). Our testing figures—which exclude antibody tests—are thus not an appropriate comparison in these instances: on this basis there can be more cases than tests, which is not possible. For this reason, we do not calculate the positive rate or number of tests per confirmed case for Peru.
