### ISSUE TITLE
Missing vaccination data for Denmark since late May

### ISSUE THREAD

**Issue by KarenB-N** [owid/covid-19-data#1617]
The Danish data is published in two tables, one shows cases, testing, death etc.

The other file, here's the link, shows vaccination data;https://experience.arcgis.com/experience/1c7ff08f6cef4e2784df7532d16312f1  

![image](https://user-images.githubusercontent.com/86575212/123560189-b82eae80-d798-11eb-9d76-28329c8141fa.png)

Påbegyndt vaccinerede  means first dose given; Færdigvaccinerede means finish vaccinated, i.e, two jabs. M means male and K means female

**Comment by lucasrodes** [comment]
Hi @KarenB-N,
Thanks for your message.

Denmark started using single-dose vaccine Johnson&Johnson, hence the total number of doses is no longer equal to `Påbegyndt vaccinerede` + `Færdigvaccinerede`. We are looking into ways to add this metric.

We are reporting people vaccinated and people fully vaccinated, you can check the corresponding charts [here](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&pickerSort=desc&pickerMetric=total_vaccinations&Metric=People+vaccinated&Interval=Cumulative&Relative+to+Population=true&Align+outbreaks=false&country=~DNK) and [here](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&pickerSort=desc&pickerMetric=total_vaccinations&Metric=People+fully+vaccinated&Interval=Cumulative&Relative+to+Population=true&Align+outbreaks=false&country=~DNK).

**Comment by KarenB-N** [comment]
Hi Lucas, I’m sorry to contradict you but the Johnson and Johnson vaccine is not used in Denmark, https://www.sst.dk/en/English/news/2021/The-Danish-COVID-19-vaccine-rollout-continues-without-the-COVID-19-vaccine-from-Johnson-Johnson Sundhedstyrelsen - the Health Authority – confirmed on 25 June https://www.sst.dk/da/corona/COVID-19-vacciner-i-Danmark/Johnson-Johnson that the J+J vaccine would continue not to be used. The two vaccines used in Denmark are Moderna and Pfizer so the official data sources I provided remain relevant to vaccine data. Kind regards Karen Sent from Mail for Windows 10 From: Lucas Rodés-GuiraoSent: 28 June 2021 00:06To: owid/covid-19-dataCc: KarenB-N; MentionSubject: Re: [owid/covid-19-data] Missing vaccination data for Denmark since late May (#1617) Hi @KarenB-N,Thanks for your message.Denmark started using single-dose vaccine Johnson&Johnson, hence the total number of doses is no longer equal to Påbegyndt vaccinerede + Færdigvaccinerede. We are looking into ways to add this metric.We are reporting people vaccinated and people fully vaccinated, you can check the corresponding charts here and here.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by lucasrodes** [comment]
Hi @KarenB-N,
Thanks for raising this. 

I am now a bit confused, as Denmark is reporting J&J administered doses in their [dashboard](https://experience.arcgis.com/experience/1c7ff08f6cef4e2784df7532d16312f1) (see upper right chart).

Also, J&J numbers are reported in the daily zip files (first [download zip file](https://files.ssi.dk/covid19/vaccinationsdata/zipfil/vaccinationsdata-dashboard-covid19-27062021-qplb), e)

**Comment by KarenB-N** [comment]
Hi Lucas, I’ve looked into it. Although the Astra Zeneca and Janssen vaccines are not used in the official programme, they have been available since 20 May as selective vaccinations by individuals. They require a doctor’s advice who decides that in the individual case the risk is outweighed by the benefits. Here’s the legal text:2.2 TilvalgsordningenI tilvalgsordningen kan tilbydes vacciner som har opnået markedsføringstilladelse fra Europa-Kommissionen, men som ikke generelt anbefales af Sundhedsstyrelsen jf. afsnit 2.1. For disse vacciner er grundlaget for den konkrete lægefaglige vurdering og ordination de krav og principper, der er beskrevet i nærværende vejledning samt vaccinernes produktresuméer.Selvom Sundhedsstyrelsen ikke i den aktuelle danske situation generelt kan anbefale de vacciner, der tilbydes i tilvalgsordningen, er det vigtigt at understrege, at grundlaget for godkendelsen fra Europa-Kommissionen er en generel vurdering af, at fordelene ved vaccinerne set i forhold til bekæmpelse af COVID-19 overstiger risikoen, og at Sundhedsstyrelsen er enig i denne generelle vurdering. Samtidig kan der ud fra en konkret lægefaglig vurdering, også i den aktuelle danske situation, være tilfælde, hvor lægen skønner, at fordelene for den enkelte borger overstiger risikoen.Sundhedsstyrelsen kan for disse vacciner ikke angive konkrete anbefalinger for anvendelsen, herunder valg af målgrupper, men styrelsen vil sikre tilgængeligt og opdateret fagligt informationsmateriale om dokumentation for vaccinernes effekt og sikkerhed, der kan bruges af lægen som supplement til produktresuméerne. Would you like me to look into how the one shot vaccine is reported in the dashboard – as I read the language? Take care Karen Sent from Mail for Windows 10 From: Lucas Rodés-GuiraoSent: 28 June 2021 11:12To: owid/covid-19-dataCc: KarenB-N; MentionSubject: Re: [owid/covid-19-data] Missing vaccination data for Denmark since late May (#1617) Hi @KarenB-N,Thanks for raising this.I am now a bit confused, as Denmark is reporting J&J administered doses in their dashboard (see upper right chart).Also, J&J numbers are reported in the daily zip files (first download zip file, e)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by hpgjg** [comment]
> I am now a bit confused, as Denmark is reporting J&J administered doses in their [dashboard]

> Will try to reach them so they can clarify

J&J is being used, but not in the general mass vaccination program. J&J can be given after an individual doctor's consultation.

A company (Practio) has been contracted by the government to handle this.

The 25 June statement is about authorities being asked by the political system to reevaluate if J&J should be introduced into the general mass vaccination program.

**Comment by lucasrodes** [comment]
Total vaccinations now being reported for the latest entries. We will backfill to previous entries in the upcoming days.

The process has been implemented based on https://github.com/owid/covid-19-data/issues/1593#issuecomment-867040707.
