### ISSUE TITLE
New Jersey Vaccination data not updated in 5 days

### ISSUE THREAD

**Issue by mysticalphoenix** [owid/covid-19-data#1629]
The NJ COVID-19 vaccination data hasn't been updated since June 24th, 5 days ago. Every other state has been updated in the past 1 day. Glitch? Please fix.

**Comment by edomt** [comment]
Hi @mysticalphoenix 

Things seem fine in the file:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/7103774/124127093-9b85c580-da7b-11eb-9ce1-4a9c484839ac.png">

Feel free to reopen this issue if needed, but for now I'll close it.

**Comment by mysticalphoenix** [comment]
![Screenshot_20210701-114638_Chrome](https://user-images.githubusercontent.com/86654814/124153467-759ff700-da62-11eb-9271-591bde0f2e0b.jpg)

It still says Last updated 8 days ago and June 24 on Google. The file is not linked correctly with the COVID vaccine tracker for New Jersey.

https://www.google.com/search?q=covid+vaccine+tracker

**Comment by mysticalphoenix** [comment]
> Hi @mysticalphoenix
> 
> Things seem fine in the file:
> 
> <img alt="image" width="278" src="https://user-images.githubusercontent.com/7103774/124127093-9b85c580-da7b-11eb-9ce1-4a9c484839ac.png">
> 
> Feel free to reopen this issue if needed, but for now I'll close it.

I don't know how to reopen the issue. Please see screenshot above and the direct link to the issue. Thanks!

**Comment by edomt** [comment]
@mysticalphoenix Your screenshot comes from the integration of our data on Google Search, on which we have no control. There must be something wrong on their end.
