### ISSUE TITLE
Extending excess deaths

### ISSUE THREAD

**Issue by J-Dunn** [owid/covid-19-data#164]
The new excess death data is a great addition. 

Would it be possible to extend it backwards for context? 

The tail of last year's flu deaths overlaps slightly with the start of COVID19 and it is important to see shape and magnitude of recent years' flu excess deaths to understand relative significance of COVID. 

Excess deaths has been the  classic way to assess the impact of influenza epidemics and there is a large peak most years. Seeing at least the 2019 excess deaths would help to put the magnitude of COVID in context. 

About 1/80 of the population dies each year of one cause or another ( assuming a median age of death of 80 y.o.), many of diseases such as influenza or covid which those close to the end are unable to resist.  Excess deaths towards the end of this year may well go below average since the baseline is the typical "average" flu death toll. 

Having a broader window is essential to correctly viewing this data in context.  Hopefully that will not be too difficult to add since you have already done the hard work of finding the relevant data sources. 

This is an excellent project and fills some of the gaps  left by ECDC only giving "cases" and deaths.  Great work, many thanks.

**Comment by edomt** [comment]
@J-Dunn We have now extended our excess mortality file with more columns with data from previous years, which should let you run the analysis you're describing: https://github.com/owid/covid-19-data/blob/master/public/data/excess_mortality/excess_mortality.csv

**Comment by J-Dunn** [comment]
Thanks for being so quick in picking this up. That's very helpful. 

I can guess by the magnitude that this is excess deaths for 7d period but this does not seem to be documented anywhere. It may be good to document what the date represents.  Is it the last day or mid point of the 7d period;  a Friday ? Are the source data arranged as week 1 , week 2 , etc. ? It's detail but it would be nice to have this documented. 


You may wish to add a line to the change log as well. 

Thanks again.

**Comment by edomt** [comment]
Dates refer to the last day in each reporting week for most but not all countries. For a more detailed description of the HMD data, including week date definitions, see the HMD metadata file at https://www.mortality.org/Public/STMF_DOC/STMFmetadata.pdf.

**Comment by J-Dunn** [comment]
Many thanks for the reply and extra info. 

Is it possible to include the rest of the historic data?  It is not very logical to crop each of the previous years' data at the current limit this year's data.   An important part of the context of the current epidemic in each country is to see the peak in excess deaths in previous years which has been traditionally attributed to influenza.

**Comment by edomt** [comment]
We're working on adding this.

**Comment by J-Dunn** [comment]
Many thanks for being responsive to these requests. They make the dataset much more useful. 
![excess_FR_2010-2020](https://user-images.githubusercontent.com/9969512/100551204-1a611880-3277-11eb-8f2b-1b3d54426ecc.png)
