### ISSUE TITLE
Vaccine name inconsistency: "Sinopharm/Beijing" and "BBIBP-CorV"

### ISSUE THREAD

**Issue by dbaroncelli** [owid/covid-19-data#1656]
The same vaccine is written sometimes as
"Sinopharm/Beijing"
and sometimes as
"BBIBP-CorV"

**Comment by lucasrodes** [comment]
Hi @dbaroncelli,
Thanks for your message.

Could you provide examples for this?

**Comment by dbaroncelli** [comment]
For example here:
https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Mauritius.csv
it's written as "Sinopharm/Beijing"
and then as "BBIBP-CorV"

while here:
https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Serbia.csv
is always writtern as "Sinopharm/Beijing"

I suspect you forgot to replace it in the old records

**Comment by lucasrodes** [comment]
Thanks again for raising this.

This appears to be happening in countries where we source the data from WHO. As WHO only reports the latest data I can't check the historical data. It seems that _BBIBP-CorV_ was wrongly labelled as _Sinopharm/Beijing_.

Will review the country files stemming from WHO (see script [who.py](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/src/vax/incremental/who.py) for more details)

**Comment by dbaroncelli** [comment]
So are you considering those as two separate vaccines?

I thought it's the same:
https://en.m.wikipedia.org/wiki/BBIBP-CorV

**Comment by zizwiz** [comment]
Please ignore if you already know this but as far as vaccine naming goes it can be difficult to work out what each country calls a vaccine. I usually refer back to the lists collated at https://covid19.trackvaccines.org/

**Comment by edomt** [comment]
Solved by 2aa3cce8d95562877fbce9cffc25ad16490b8608
