### ISSUE TITLE
United Arab Emirates: no updated info about "people_vaccinated" and "people_fully_vaccinated"

### ISSUE THREAD

**Issue by dbaroncelli** [owid/covid-19-data#1660]
The United Arab Emirated government publishes the updated percentage of the people vaccinated and fully vaccinated:
https://covid19.ncema.gov.ae/en

but in the Owid repository the latest update is over 2 months ago:
https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv

**Comment by lucasrodes** [comment]
Thanks for reporting. Support for people vaccinated / people fully vaccinated has been added in 996f693cd9199d6f142da8ea1870ea0ccb7dddaf and will be available in our visualisations and public datasets in the next update.

**Comment by dbaroncelli** [comment]
The change seems to be about Saudi Arabia and not United Arab Emirates.

**Comment by lucasrodes** [comment]
Hi @dbaroncelli! Sorry for that, got confused with my backlog.

At the moment the `Vaccination Percentage` box is empty. Also, if the number of people vaccinated is provided as a percentage, we should find out which census number they are basing their computations. 

Again, sorry for my confusion.

**Comment by adamredfern92** [comment]
They have the % of people vaccinated & fully vaccinated on this page:
https://fcsc.gov.ae/en-us/Pages/Covid19/UAE-Covid-19-Updates.aspx 

They also have values for doses per 100 so we can work out the population they are using.

15,534,207 / 157.06 * 100 = 9,890,620 (this is very close to the number you guys are using)

So therefore 74% at least 1 dose ~ 7,319,059
and 64% with 2 doses ~ 6,329,997 

Only issue is this does not seem to add up assuming they are using only 2 dose vaccines...

**Comment by lucasrodes** [comment]
Thanks for the research, @adamredfern92! 

Will let you know when this is live

**Comment by lucasrodes** [comment]
Added metrics `people_vaccinated` and `people_fully_vaccinated`. Will be live from the daily data update on the 6th of June.

**Comment by humaidq** [comment]
@adamredfern92 I can confirm. Some people are receiving 3rd (and even 4th dose, if they are taking Pfizer, as long as 6 months have passed from taking Sinopharm).
