### ISSUE TITLE
Vaccine batch numbers

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#1669]
Please feel free to close this as it is not strictly an issue more a discussion. 

In UK last week I learnt that some of the vaccines given out are not approved for use in EU and therefore do not count towards you vaccine passport. Seems that a technicality has arisen. The AZ vaccine that is made in UK is approved but the same AZ vaccine made in India is not. UK imported many doses from India a few months ago. If you got one of the Indian made doses then the EU will at this time not recognize it. 

We know from your good data what vaccines are being given in a country but do we know where the vaccines are made? I suspect the above issue will also be an issue in other countries not just the UK/EU in the months to come as the vaccine roll out gets to more parts of the world.

**Comment by lucasrodes** [comment]
Hi @zizwiz,
Thanks for raising this.

We currently do not track the country or facility of production of the vaccines. We note this down as something to take into account in the future.

Thanks once again!
