### ISSUE TITLE
Strange hospital admissions numbers for Portugal

### ISSUE THREAD

**Issue by Jimvy** [owid/covid-19-data#1670]
Hello!

I think there is a problem with the "weekly new hospital admissions" numbers for Portugal: I think they are actually daily admissions (probably averaged), and not weekly, because these numbers are too low compared to other countries and compared to the instantaneous number of hospitalized patients.

Example of incoherent data: during the December-February wave, hospital admissions numbers are given to be around 60 admissions per week per million people.
However, the number of COVID-19 patients in hospital are given to be around 600 per million people at the worst peak.
That would mean the average patient would have spent around 10 weeks for treatment at the hospital, as a crude estimate. That seems extremely high and unlikely. If the numbers are however weekly-averaged hospital admissions per day, then the numbers are more reasonable.
Another example: on 17/01, according to the numbers in the dataset, there were 4889 patients in the hospital, and one week after 6117, so an increase of 1228 patients. So, I would expect around 1200 admissions, assuming no patient died or was discharged that week. But according to the dataset, there were at most 889 admissions, relatively not enough.

(Sanity check: compare that to Belgium (my home country): during the October-November wave, hospital admissions were around 300 per million people, and the number of COVID-19 patients was around 600 per million people, giving a crude estimate of 2 weeks of hospital stay for the average patient, which is closer to the actual numbers (page 23 of https://covid-19.sciensano.be/sites/default/files/Covid19/COVID-19_Hospital_epidemiology_Part_1.pdf).)

I'm not sure about this, especially as I didn't find any kind of dashboard or dataset from the SNS or the Ministry of Health with the hospitalization numbers, so feel free to dismiss this if I'm mistaken. :)

**Comment by pjfsilva** [comment]
Portugal has a daily report that includes hospitalizations: https://covid19.min-saude.pt/relatorio-de-situacao/

if you click on those, it's the number at the bottom of first page "Internamento" which means people in hospitals and 'Internamento em UCI' that means in intensive care units. Currently we have 603 people hospitalized. 

There is an important point: we don't know the full flow of people to hospitals. That means, we don't know how many went to hospital and how many come out. That number is just a snapshot for that day. It's impossible to know how many people were admitted and/or released for hospitals on a given day or week, we just know that on Sunday hospitals had X people and on Wednesday they had Y.

I'm just clarifying of what data Portugal provides, if it helps you in your analysis. I haven't analyzed the dataset to check if it's correct.

**Comment by davipt** [comment]
pjfsilva is correct. The hospitalisation numbers are daily snapshots of how many people are in the hospital the prior day.

https://github.com/dssg-pt/covid19pt-data/blob/master/data.csv

internados_uci is how many people in intensive care
internados_enfermaria is how may people in the hospital but not in ICU
internados is the sum of both

For example in a day that official numbers says internados went from 100 to 105 and uci from 20 to 25, it may mean five persons went straight to uci, but can also mean anything else like 10 entered the hospital, five went from regular bed to uci, five left. Impossible to know.

For completeness, the same applies to "ativos" (daily snapshot of how many people are still considered infected and haven't yet recovered (or died, hopefully not), independent if they're at home recovering, or at the hospital.

This is sometimes confusing. Some numbers are accumulators (confirmed), some are daily diffs (confirmed_new), some are daily counts. People tend to mix them up.
