### ISSUE TITLE
Variants Dataset

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#1672]
Hello OWID team,

I am looking at covid-variants.csv, but I could not find any explanation in Read_Me part of these fields: num_sequences, perc_sequences, num_sequences_total. I thought num_sequences_total is the cumulative data of num_sequences, but data could not be added up. Also, I am not sure about the perc_sequences filed. May I ask for the definition of each field?

**Comment by lucasrodes** [comment]
Hi @RuijingZ,
Just added a [README](https://github.com/owid/covid-19-data/tree/master/public/data/variants/README.md) file.

Please let me know if you have any additional questions.

**Comment by RuijingZ** [comment]
> Hi @RuijingZ,
> Just added a [README](https://github.com/owid/covid-19-data/tree/master/public/data/variants/README.md) file.
> 
> Please let me know if you have any additional questions.

Thank you so much!
