### ISSUE TITLE
Decreasing number of cumulative vaccinations in US State Data

### ISSUE THREAD

**Issue by williamlief** [owid/covid-19-data#1692]
I am seeing instances with decreasing vaccination numbers in the [US State Data](https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/us_state_vaccinations.csv?raw=true) from one day to the next. Here are the number of cases I've found for each variable with a few examples. Do you have any insight into what might be occurring? Thank you. 

- `total_vaccinations`: 14 cases (e.g. Illinois from 2021-04-13 to 2021-04-14)
- `total_distributed`: 36 cases
- `people_vaccinated`: 34 cases (e.g. Connecticut from 2021-01-22 to 2021-01-23)
- `people_fully_vaccinated_per_hundred`: 13 cases
- `total_vaccinations_per_hundred`: 13 cases
- `people_fully_vaccinated`: 19 cases (e.g. Vermont from 2021-05-26 to 2021-05-27)
- `people_vaccinated_per_hundred`: 30 cases
- `distributed_per_hundred`: 19 cases

```
# R code to pull pairs of dates with decreasing data for all cumulative variables
library(dplyr)
library(purrr)

dat <- read.csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/us_state_vaccinations.csv?raw=true")

find_drops <- function(var, dat) {
  
  dat %>% 
    select(.var = var, everything()) %>% 
    arrange(location, date) %>% 
    group_by(location) %>% 
    mutate(drop = .var < lag(.var)) %>% 
    filter(drop == TRUE | lead(drop) == TRUE) %>% 
    ungroup()
  
}


vars <- c("total_vaccinations", "total_distributed", "people_vaccinated",
          "people_fully_vaccinated_per_hundred", "total_vaccinations_per_hundred", 
          "people_fully_vaccinated", "people_vaccinated_per_hundred", "distributed_per_hundred")
names(vars) <- vars

cases <- map_dfr(vars, find_drops, dat = dat, .id = ".var_name") 

```

**Comment by edomt** [comment]
Hi @williamlief 
This is likely a correction from the source.

We source the data from US CDC, (see here https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data).

We import that data with little to no processing (see our [script](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/us_vaccinations.py)), hence we assume that these spikes are due to data corrections in the source.
