### ISSUE TITLE
Problems with latest update in data of vaccinations in Portugal

### ISSUE THREAD

**Issue by matiasfreitasguimaraes** [owid/covid-19-data#1695]
In the latest update, 2, 3, and 4 of July for Portugal losted your daily numbers, probably because of an issue. I don't know if that is expected, but in older versions that data exist.

**Comment by edomt** [comment]
@lucasrodes I removed these rows yesterday because they made the series non-monotonic. Maybe they'll have fixed it today?

**Comment by lucasrodes** [comment]
The values for `total_vaccinations` and `people_vaccinated` from 2021-07-05 are not consistent with the ones on 2, 3 and 4th of July. Also, `people_fully_vaccinated` from 2021-07-05 is not consistent with 2021-07-03 and 2021-07-04

|date      |total_vaccinations|people_vaccinated|people_fully_vaccinated|vaccine                                                      |location|source_url                               |
|----------|------------------|-----------------|-----------------------|-------------------------------------------------------------|--------|-----------------------------------------|
|2021-07-01|8980456.0         |5660609.0        |3585089.0              |Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech|Portugal|https://github.com/dssg-pt/covid19pt-data|
|2021-07-02|9164837.0         |5754219.0        |3675860.0              |Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech|Portugal|https://github.com/dssg-pt/covid19pt-data|
|2021-07-03|9331044.0         |5837423.0        |3758863.0              |Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech|Portugal|https://github.com/dssg-pt/covid19pt-data|
|2021-07-04|9469559.0         |5909634.0        |3825167.0              |Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech|Portugal|https://github.com/dssg-pt/covid19pt-data|
|2021-07-05|9173720.0         |5740878.0        |3720680.0              |Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech|Portugal|https://github.com/dssg-pt/covid19pt-data|
