### ISSUE TITLE
Is it okay to remove Sinovac vaccine from Singapore data?

### ISSUE THREAD

**Issue by onmyouji** [owid/covid-19-data#1696]
Few days ago, Singapore government decided to omit Sinovac shots from COVID-19 vaccination tally https://www.reuters.com/world/asia-pacific/singapore-not-counting-sinovac-shots-covid-19-vaccination-tally-2021-07-07/

Is it okay to remove Sinovac entry for Singapore from here? https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/locations.csv

**Comment by edomt** [comment]
Hi @onmyouji 

From the article it seems that, for now at least, Sinovac is still administered:

> Following an emergency use approval by the World Health Organization (WHO), Singapore began allowing designated private clinics to offer the Sinovac shot, CoronaVac, from mid-June. Singapore had a stock of 200,000 CoronaVac doses which the clinics could draw on. 

> As of July 3, just over 17,000 people had received one dose of CoronaVac, and authorities say that demand for the vaccine appeared to taper off after an initial rush. 

Therefore for now we'll keep it on the list. If at some point it stops being administered completely, then we'll remove it.
