### ISSUE TITLE
Testing data updated in Ireland

### ISSUE THREAD

**Issue by benteo01** [owid/covid-19-data#17]
72,000 tests now completed in Ireland as of 13/04/2020
- Paul Reid, CEO of Health Service Executive

Source: 
https://www.rte.ie/news/coronavirus/2020/0413/1130184-coronavirus-ireland/

**Comment by edomt** [comment]
Hi @benteo01, thanks for sending this. We have updated our time series for Ireland yesterday, with the new official figure of 90646.
