### ISSUE TITLE
Testing data removed?

### ISSUE THREAD

**Issue by tseyanglim** [owid/covid-19-data#170]
Hi, I noticed several countries' testing data seems to have been removed from the [main testing datasets](https://github.com/owid/covid-19-data/tree/master/public/data/testing) in the last couple of weeks - most notably Argentina, but also Albania, Armenia, Azerbaijan, Bosnia, Kyrgyzstan, and possibly a few others.

What happened to the data for these countries / why was it removed?

**Comment by edomt** [comment]
Hi @tseyanglim 

To ensure the quality and reliability of our testing data, we've decided to remove the testing data (and only the testing data, not the cases & deaths data) for Argentina from our dataset for the time being, as the official figures aggregated by the government don't seem to be of sufficient quality to correctly reflect the extent of the testing done in the country.

In particular, it has recently emerged (as explained here: https://clarin.com/sociedad/testeos-coronavirus-argentina-advierten-negativos-cuentan-dispara-tasa-positividad_0_cwU6GT_cu.html) that many negative tests weren't being recorded in several provinces, including large ones such as Santa Fe and Córdoba. This has created a bias driving the positive rate upwards, up to 75% a few days ago when we made the change.

The government had announced a few days before that it would implement a new system to make sure that all tests were being correctly recorded in all provinces. It has also reacted to our own announcement of this change, by reiterating that they were working on making the correct data available ASAP. It's not clear however whether this will also correct the historical data retrospectively.

Data for other countries you mentioned (Albania, Armenia, Azerbaijan, Bosnia, Kyrgyzstan), on the other hand, has never been part of our testing dataset.

Edouard
