### ISSUE TITLE
Any data about variants?

### ISSUE THREAD

**Issue by Silvanoxx** [owid/covid-19-data#1700]
Thank you for the great work you are doing. I need to find data about variants, in particular delta. Namely the % of new cases per variant. This is an important parameter for my country to decide whether to open the borders and to whom. Are there any plans for this or any hints of where can I find that for the whole world?

**Comment by vi-enne** [comment]
Hi, 
% of new cases per variant depends strongly on how many cases are sequenced and how may of those sequences are then shared.
It is very challenging to find data that for the whole world that are reliable.

Inviting to extreme caution, you can consult the [GISAID initiative](https://www.gisaid.org/) and [outbreak.info](https://outbreak.info/).
Please take a look at the [Caveats & Limitations page](https://outbreak.info/situation-reports/caveats).

I hope it helps!

**Comment by lucasrodes** [comment]
Hi,
As @vi-enne points out, we currently provide the file [covid-variants.csv](https://github.com/owid/covid-19-data/blob/master/public/data/variants/covid-variants.csv) with bi-weekly analysis of variants share of sequenced samples.

We also provide some charts on our website:
- [COVID-19 sequences by variant](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&pickerSort=desc&pickerMetric=total_vaccinations&Metric=Variants&Interval=Cumulative&Relative+to+Population=true&Align+outbreaks=false&country=BRA~CAN~FRA~DEU~IND~ITA~ISR~MEX~GBR~USA~OWID_WRL)
- [Share of COVID-19 sequences that are the delta variant](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&pickerSort=desc&pickerMetric=total_vaccinations&Metric=Delta+variant+%28share%29&Interval=Cumulative&Relative+to+Population=true&Align+outbreaks=false&country=BRA~CAN~FRA~DEU~IND~ITA~ISR~MEX~GBR~USA~OWID_WRL)
