### ISSUE TITLE
Vaccinations: Italy added new field that impacts administered vaccinations and fully vaccinated

### ISSUE THREAD

**Issue by vi-enne** [owid/covid-19-data#1701]
In the official repository for Italy, a new field `pregressa_infezione` has been added to the following files
`anagrafica-vaccini-summary-latest`, `somministrazioni-vaccini-latest`, `somministrazioni-vaccini-summary-latest`, as you can see from the [Changelog.md](https://github.com/italia/covid19-opendata-vaccini/blob/5ea9319170eee2b2018e23e072821ec07c1a4654/Changelog.md) (in Italian).

People who recovered from Covid-19 are considered to be fully vaccinated with a single dose.

As discussed in [this issue](https://github.com/italia/covid19-opendata-vaccini/issues/179), the values of the field `pregressa_infezione` need to be summed to `prima_dose` and `seconda_dose` in order to have the total number of administered vaccinations. Also, the number of fully vaccinated people should be adjusted accordingly.

Thanks.

**Comment by edomt** [comment]
Hi @vi-enne 

Thank you for letting us know! This has now been fixed (the data will be updated tomorrow morning).

Regarding people fully vaccinated, for now we've decided to stick to the same definition for all countries. You can find more information at [here](https://ourworldindata.org/covid-vaccinations#frequently-asked-questions).

<img width="577" alt="image" src="https://user-images.githubusercontent.com/7103774/125176112-38113b80-e1d1-11eb-970c-b1f4625ad5db.png">

(We may revisit this in the future if needed.)

**Comment by vi-enne** [comment]
Thanks!
It makes sense to have a definition that is coherent for all countries.
