### ISSUE TITLE
Complete  Dataset JSON file broken

### ISSUE THREAD

**Issue by go4cas** [owid/covid-19-data#1711]
The complete data set JSON file (https://covid.ourworldindata.org/data/owid-covid-data.json) has been broken after the latest update:

<img width="386" alt="Screenshot 2021-07-13 at 14 06 10" src="https://user-images.githubusercontent.com/12674784/125448720-b3af8526-d0bd-4107-87c7-7c727cc65ae3.png">

**Comment by edomt** [comment]
Thank you @go4cas, this should now be fixed. Let me know if you have any other issue.

**Comment by go4cas** [comment]
Thanks, @edomt! All sorted now!
