### ISSUE TITLE
How to update the "Source information country by country" table

### ISSUE THREAD

**Issue by limbero** [owid/covid-19-data#1724]
Couldn't figure exactly how that table is produced, but Sweden should have Moderna listed under Vaccines, not just `Oxford/AstraZeneca, Pfizer/BioNTech`.

**Comment by edomt** [comment]
Hi @limbero 
Do you know when the vaccinations with Moderna started in Sweden?

**Comment by limbero** [comment]
If I'm reading things right, it was approved in Sweden automatically when approved by the EMA on 2021-01-06. Sweden doesn't do per manufacturer jab statistics, but the first delivery was during week 2 (jan 11-17).

**Comment by edomt** [comment]
Thanks! Fixed in 9cac86e87e81b7213779ffbe8a94778d088d6780
