### ISSUE TITLE
Covid-19 sequences by variant bar graph reorders columns every week

### ISSUE THREAD

**Issue by corneliusroemer** [owid/covid-19-data#1728]
The way covid variants are displayed in the bar graph right now is not so good. The column order changes every week, there seems no clear logic why some countries go to the top or the bottom or move around. Countries should stay put and not move around.

Reproduce: Go to this link and click on play at the bottom left https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2021-07-12&pickerSort=desc&pickerMetric=total_cases&Metric=Variants&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=GBR~IRL~DEU

![2021-07-16 14 27 01](https://user-images.githubusercontent.com/25161793/125948042-95e078fa-7146-497f-bc57-807132dd8dd4.gif)

**Comment by lucasrodes** [comment]
Hi @corneliusroemer,
Thanks for reporting this.

We will be adding soon a functionality to set a sorting configuration in our charts. See https://github.com/owid/owid-grapher/pull/962 for more details.

Once live, this should help to fix this.

**Comment by lucasrodes** [comment]
Hi @corneliusroemer,
We just updated our variants chart to sort countries by delta variant share.

Hope this helps.
