### ISSUE TITLE
README KOREAN

### ISSUE THREAD

**Issue by Bon-a** [owid/covid-19-data#173]
Hello, I am a Korean college student who wants to contribute to an open source project.
There is no Korean translation in README of your project, so it can be difficult for Korean GitHub users to contribute to the project.
I would like to help Korean users who want to contribute to your project by translating README.
Can I translate README of your project into Korean?
I will wait for your answer.

**Comment by edomt** [comment]
Hi @Bon-a
Thank you for your offer, but this repository receives visits from many countries, and we cannot accommodate README translation for all languages, so we'll keep things to English for now.
Edouard
