### ISSUE TITLE
French Polynesia using different vaccines

### ISSUE THREAD

**Issue by DrBazUK** [owid/covid-19-data#1730]
Dear team,
Many thanks for the huge efforts expended in keeping this truly valuable resource running.

I have been relying on this data set for over 18 months now and am truly thankful for all that you are doing.

One small issue in relation to Polynesia Francaise (French Polynesia) is that they are using Pfizer and Johnson & Johnson and not Oxford/AstraZeneca as listed in the locations.csv.

This can be verified using the Sante Publique latest update available from: [https://www.service-public.pf/dsp/wp-content/uploads/sites/12/2021/07/BEH-N52.pdf](https://www.service-public.pf/dsp/wp-content/uploads/sites/12/2021/07/BEH-N52.pdf)

I hope that this is helpful in updating the vaccines in use.

Kind regards,
Barry.

**Comment by edomt** [comment]
Thank you Barry!
