### ISSUE TITLE
Test data: Vietnam (2)

### ISSUE THREAD

**Issue by Ltn123456** [owid/covid-19-data#1734]
I don't know whether you are going to close #1589 or not , so I start a new issue. 

* 24 June: 5,502,282  (https://luatvietnam.vn/y-te/bao-cao-942-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-204347-d6.html)
* 25 June: 5,563,394 (https://luatvietnam.vn/y-te/bao-cao-945-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-204346-d6.html)
* 26 June: 5,637,018 (https://luatvietnam.vn/y-te/bao-cao-955-bc-byt-tinh-hinh-covid-19-va-ket-qua-phong-chong-dich-204443-d6.html)
* 27 June: 5,697,124 (https://luatvietnam.vn/y-te/bao-cao-971-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-204536-d6.html)
* 28 June: 5,768,173 (https://luatvietnam.vn/y-te/bao-cao-972-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-204541-d6.html)
* 29 June: 5,843,599 (https://luatvietnam.vn/y-te/bao-cao-976-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-204588-d6.html)
* 30 June: 5,901,491 (https://luatvietnam.vn/y-te/bao-cao-984-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-204681-d6.html)
* 1 July: 5,974,010 (https://luatvietnam.vn/y-te/bao-cao-991-bc-byt-204800-d6.html)
* 2 July: 6,043,378 (https://luatvietnam.vn/y-te/bao-cao-992-bc-byt-bo-y-te-204798-d6.html)
* 3 July: 6,106,854 (https://luatvietnam.vn/y-te/bao-cao-993-bc-byt-204799-d6.html)
* 4 July: 6,176,528 (https://luatvietnam.vn/y-te/bao-cao-999-bc-byt-204878-d6.html)
* 5 July: 6,229,245 (https://luatvietnam.vn/y-te/bao-cao-1016-bc-byt-205073-d6.html)
* 6 July: 6,318,334 (https://luatvietnam.vn/y-te/bao-cao-1017-bc-byt-205074-d6.html)
* 7 July: 6,386,721 (https://luatvietnam.vn/y-te/bao-cao-1027-bc-byt-205223-d6.html)
* 8 July: 6,477,010 (https://luatvietnam.vn/y-te/bao-cao-1034-bc-byt-205250-d6.html)
* 9 July: 6,536,391 (https://luatvietnam.vn/y-te/bao-cao-1035-bc-byt-205251-d6.html)
* 10 July: 6,601,850 (https://luatvietnam.vn/y-te/bao-cao-1040-bc-byt-205387-d6.html)
* 11 July: 6,635,926 (https://luatvietnam.vn/y-te/bao-cao-1055-bc-byt-205501-d6.html

**Comment by Ltn123456** [comment]
* 13 July: 6,803,573 (https://luatvietnam.vn/covid/bao-cao-1054-bc-byt-205500-d6.html)

**Comment by Ltn123456** [comment]
I think you guys made some mistakes here. Why there is negative number?
blob:https://ourworldindata.org/bfca1be9-75aa-4afa-828f-e8af93f1aac0

**Comment by Ltn123456** [comment]
I also suggest changing "Vietnam General Department of Preventive Medicine" to "Ministry of Health (Vietnam)"

**Comment by edomt** [comment]
cc @camappel

**Comment by Ltn123456** [comment]
* 16 July: 7,030,670 (https://luatvietnam.vn/y-te/bao-cao-1067-bc-byt-205705-d6.html)
* 17 July: 7,107,970 (https://luatvietnam.vn/y-te/bao-cao-1069-bc-byt-205728-d6.html)

**Comment by Ltn123456** [comment]
* 14 July: 6,877,936 (https://luatvietnam.vn/y-te/bao-cao-1066-bc-byt-205689-d6.html)

**Comment by Ltn123456** [comment]
* 18 July: 7,171,844 (https://luatvietnam.vn/y-te/bao-cao-1074-bc-byt-205801-d6.html)

**Comment by camappel** [comment]
Thank you again for your contributions - these will be included in this week's update
