### ISSUE TITLE
Can't run cowid-vax

### ISSUE THREAD

**Issue by pandres95** [owid/covid-19-data#1738]
Quick question: do you somehow know why the `cowid-vax` tool is not working on my machine? Basically, I get this weird error when trying to authenticate against Google for accessing Sheets APIs, even though I created credentials that worked with the last commit on my fork.

Did something change in the `gsheets` helper library?

I need this urgently to debug and fix the ongoing issues with `colombia.py`, since it looks like no one trusts anymore as a reliable source (and I get why, those government idiots 😅).

![Screenshot 2021-07-18 at 9 23 34 PM](https://user-images.githubusercontent.com/2502577/126093927-ae62b34a-3b40-4cec-94ac-7634905c8c76.png)

<img width="1680" alt="Screenshot 2021-07-18 at 9 23 30 PM" src="https://user-images.githubusercontent.com/2502577/126093923-de22a1c9-ed4e-4c2b-bb5a-f4ba29d929ae.png">

cc/ @lucasrodes

**Comment by edomt** [comment]
Hi @pandres95 

We haven't changed anything recently, so there shouldn't be any issues, I think. :) 
Are you simply running the usual `cowid-vax -c colombia get` ?
Maybe try reinstalling your virtualenv from scratch with run `pip install -e .`
