### ISSUE TITLE
Interpreting Manufacturer Data

### ISSUE THREAD

**Issue by ianconrad** [owid/covid-19-data#1743]
For the manufacturer based [data](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations-by-manufacturer.csv), I'm noting that it looks like in just July we are reaching about >320 million total vaccinations for the United States, summing Pfizer, Moderna and J and J. This doesn't seem like it can be correct just considering that the US has a population of ~328 million. Am I interpreting this wrong?

**Comment by edomt** [comment]
Hi @ianconrad 

The US has indeed administered 338 million doses so far: https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&pickerSort=asc&pickerMetric=location&Metric=Vaccine+doses&Interval=Cumulative&Relative+to+Population=false&Align+outbreaks=false&country=~USA

For vaccines that require multiple doses, each individual dose is counted. As the same person may receive more than one dose, the number of doses can be higher than the number of people in the population.

**Comment by ianconrad** [comment]
Is there any way to get a count by manufacturer of people having received atleast one vaccine? I didn't find any other data file relating manufacturers and vaccination counts thus far

**Comment by lucasrodes** [comment]
You may want to review the official US CDC API file:

https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data

You will find fields:

- `Series_Complete_<manufacturer>`: People that were fully vaccinated using vaccine of type `<manufacturer>`.
- `Administered_<manufacturer>`: Number of doses administered of type `<manufacturer>`. 

Note that this only contains data (national and per state) for the last reported date. If you want historical data, you can check our backups of the original data (https://github.com/owid/covid-19-data/tree/master/scripts/scripts/vaccinations/us_states/input)
