### ISSUE TITLE
Icelandic case and tests data errors since mid May 2021

### ISSUE THREAD

**Issue by Kalli** [owid/covid-19-data#1747]
The daily case data for Iceland has been incorrectly set to 0 since 2021-05-21 and the [test data ends](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&pickerSort=asc&pickerMetric=location&Metric=Tests&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=ISL) around that same time. I wonder if something changed in the Icelandic reporting format around that time?

I see the OWID case data comes from @CSSEGISandData and I have raised this [issue over there](https://github.com/CSSEGISandData/COVID-19/issues/4394). But wanted to bring it up here too (also the test data seems to be compiled independently of JHU)

## Official Icelandic data - covid.is/data

You can find the official Icelandic covid stats at: https://www.covid.is/data 

<summary>
<details> Screenshot:

![image](https://user-images.githubusercontent.com/465566/126171028-2ff76c17-b324-4b45-a742-e1217f28e689.png)

</details>
</summary>

## Other links 

* [News about press briefing](https://www.ruv.is/frett/2021/07/15/covid-press-briefing) on increasing infection rates from 15.07.21 from RÚV the national broadcaster
* See also reports in this [Twitter thread](https://twitter.com/OurWorldInData/status/1416020311875768323)

Thanks for your time and for all of your hard work on providing this great resource!

**Comment by edomt** [comment]
Thank you @Kalli - this is now fixed

**Comment by Kalli** [comment]
Nice, thanks for the swift response and all your great work!
