### ISSUE TITLE
CoVariants data update does not seem to get run automatically, 11d since last update

### ISSUE THREAD

**Issue by corneliusroemer** [owid/covid-19-data#1748]
I noticed that there has been no data update in 11 days for your variant data. It looks like there may be an error in the script that runs the auto-updater.

There've been 3 updates you've missed so far:
![image](https://user-images.githubusercontent.com/25161793/126366549-c48567cc-2294-400b-972b-2f62969dcee3.png)

https://github.com/hodcroftlab/covariants/commits/master/cluster_tables/all_tables.tsv

**Comment by edomt** [comment]
Thank you @corneliusroemer ! This went unnoticed indeed :) now fixed in 9479a3443020038433915d04e9a00344e93e566e

**Comment by corneliusroemer** [comment]
New data is now available again. Will the owid data bot run automatically?

**Comment by edomt** [comment]
The update has just been pushed.

**Comment by corneliusroemer** [comment]
Great, is it automatic or no, i.e. should I tell you about updates in the future or not?

**Comment by edomt** [comment]
Yes, the script runs daily, so unless something goes wrong you should always see the data being updated within 24 hours :)
