### ISSUE TITLE
Europe aggregated data

### ISSUE THREAD

**Issue by stark71** [owid/covid-19-data#1762]
I am trying to aggregate European country data and validate it against OWID_EUR. I don't get the same results, so I am missing something.

Date: 2021-07-04

ie new_vaccinations
  sum([country.new_vaccinations for country in europe])

|Field|OWID_EUR|Aggregated|Delta|
 --- | --- | --- | ---
|new_vaccinations|2061509.0|1410167.0|651342.0|
|people_fully_vaccinated|2.16676975E8|1.17779704E8|9.8897271E7|
|new_vaccinations_smoothed|4106684.0|2799851.0|1306833.0|
|total_vaccinations|5.21923843E8|2.7463783E8|2.47286013E8|
|people_vaccinated|3.16276053E8|1.73195511E8|1.43080542E8|

I got issues too with percentages

ie people_vaccinated_per_hundred
  sum([country.people_vaccinated_per_hundred * country.population for country in europe]) / europe_total_population

|Field|OWID_EUR|Aggregated|Delta
 --- | --- | --- | --- 
|people_vaccinated_per_hundred|42.24|23.067839954460855|19.172160045539147|
|total_cases_per_million|64832.451|64648.61302382407|183.8379761759279|
|people_fully_vaccinated_per_hundred|28.94|15.686308041117057|13.253691958882944|
|total_deaths_per_million|1481.286|1477.0852636143234|4.2007363856766915|
|total_vaccinations_per_hundred|69.71|36.57883456809135|33.13116543190864|
|new_vaccinations_smoothed_per_million|5485.0|3729.157357751899|1755.8426422481011|

Can you help me to understand my discrepancies?

Thank you.

**Comment by edomt** [comment]
Hi @stark71 

If you run this code, you'll see that on 2021-07-04, the number of `people_fully_vaccinated` for Europe is correctly equal to the sum of the latest `people_fully_vaccinated` for each country in Europe.

```python
import pandas as pd

url = "https://github.com/owid/covid-19-data/raw/master/public/data/owid-covid-data.csv"

df = pd.read_csv(
    url, usecols=["location", "date", "continent", "people_fully_vaccinated"]
)

df = df[df.date <= "2021-07-04"].sort_values("date")

print(df[df.location == "Europe"].tail(1))

df = df[(df.continent == "Europe") & -(df.people_fully_vaccinated.isnull())]
df = df.groupby("location").tail(1)

print(df.people_fully_vaccinated.sum())
```

Maybe this'll help you spot what's wrong?

**Comment by stark71** [comment]
`import pandas as pd

url = "https://github.com/owid/covid-19-data/raw/master/public/data/owid-covid-data.csv"

df = pd.read_csv(
    url, usecols=["location", "date", "continent", "population"]
)

df = df[df.date <= "2021-07-04"].sort_values("date")

print(df[df.location == "Europe"].tail(1))

df = df[(df.continent == "Europe") & -(df.population.isnull())]
df = df.groupby("location").tail(1)

print(df.population.sum())`

I have a discrepancy with population:
7.48680069E8 (OWID_EUR), 7.48680069E8 (Calculated from country data)

That discrepancy changes the output of my data calculations for daily data like icu_patients_per_million, total_cases_per_million, etc.

**Comment by edomt** [comment]
@stark71 The total population for Europe is precalculated [in our population file](https://github.com/owid/covid-19-data/blob/master/scripts/input/un/population_2020.csv).

**Comment by stark71** [comment]
I see, thanks. Somehow computed population (continents and world)  from daily data doesn't match total population from this file.
