### ISSUE TITLE
Ukraine approved Moderna for use and in clinical trials

### ISSUE THREAD

**Issue by rowest** [owid/covid-19-data#1763]
Ukraine approved Moderna for use and in clinical trials recently. Please add this vaccine to the corresponding table:
![изображение](https://user-images.githubusercontent.com/14871737/126853784-df5350fa-9a8a-4321-8255-de95cbeb307f.png)

Source: https://vaccination.covid19.gov.ua/ and also https://health-security.rnbo.gov.ua/vaccination
![изображение](https://user-images.githubusercontent.com/14871737/126853835-18374c6c-662d-4b57-b878-7939bede9466.png)

**Comment by edomt** [comment]
Thank you
