### ISSUE TITLE
Malaysia Official COVID-19 New Positive / Tests / Death / Recovered Data 

### ISSUE THREAD

**Issue by samleong123** [owid/covid-19-data#1764]
Ministry of Health Malaysia just launch their Github repo that stated Malaysia Official COVID-19 New Positive / Tests / Death / Recovered Data 

Repo link : https://github.com/MoH-Malaysia/covid19-public

**Comment by edomt** [comment]
@camappel This'll be a much easier to import testing data :)

**Comment by jhdsvbdukgdhsgc** [comment]
Here's the announcement from Malaysia's MInistry of Health: https://covid-19.moh.gov.my/semasa-kkm/2021/07/moh-open-sourcing-extremely-rich-data-on-the-pandemic-at-github

**Comment by camappel** [comment]
Thank you very much for bringing this to our attention; we will add this source to our pipeline.
