### ISSUE TITLE
Automation for Zimbabwe

### ISSUE THREAD

**Issue by Surveyor-Jr** [owid/covid-19-data#1769]
I was sourcing out some data as I wish to expand the COVID-19 Hub Project for Zimbabwe by creating comparison with other countries on a Global scale and I noticed **Zimbabwe** is not among your automation list. 

For Zimbabwe here is an ArcGIS Feature Service link that I personally update on a daily basis that you could use to retrieve data from and automate your process. 

[https://services9.arcgis.com/DnERH4rcjw7NU6lv/arcgis/rest/services/Vaccine_Distribution_Program/FeatureServer/2/query?outFields=*&where=1%3D1](https://services9.arcgis.com/DnERH4rcjw7NU6lv/arcgis/rest/services/Vaccine_Distribution_Program/FeatureServer/2/query?outFields=*&where=1%3D1)

I hope it helps.  Cheers!

**Comment by edomt** [comment]
Thank you very much @Surveyor-Jr !
