### ISSUE TITLE
Break Out World Vaccination Data

### ISSUE THREAD

**Issue by paulh2202** [owid/covid-19-data#1772]
I think it'd be beneficial to have the world's vaccination data as it's own .csv, for example, in _covid-19-data/public/data/vaccinations/country_data/_.

**Comment by lucasrodes** [comment]
Hi @paulh2202,
Thanks for your request.


Currently, we do not support this, but may do in the future.

For now, you could execute the following in python:

```python
df = pd.read_csv("https://github.com/owid/covid-19-data/raw/master/public/data/vaccinations/vaccinations.csv")
df = df[df.iso_code == "OWID_WRL"]
```
