### ISSUE TITLE
Sputnik V in Vietnam

### ISSUE THREAD

**Issue by Ltn123456** [owid/covid-19-data#1789]
It is reported that Vietnam administered Sputnik V Covid-19 vaccine to around 900 people. According to [this article from MoH](https://moh.gov.vn/tin-tong-hop/-/asset_publisher/k206Q9qkZOqn/content/6-loai-vaccine-phong-covid-19-a-uoc-cap-phep-tai-viet-nam), in mid-March 2021, Vietnam received 2,000 doses of Sputnik V vaccine donated by the Government of the Russian Federation and used it for nearly 900 people. However, we don't know exactly **_when_**. I did some research and it seemed that Russia donated Sputnik V vaccine to Vietnam on 16 March. On [this article](https://vnexpress.net/nga-tang-vaccine-sputnik-v-cho-viet-nam-4249085.html) from VnExpress, Secretary of the Security Council of the Russian Federation Nikolai Patrushev came to Hanoi for Russia-Vietnam security consultations on March 16-17. He handed over a batch of Sputnik V Covid-19 vaccine gifted by his government to Vietnam. The number of doses remained unknown, but an official from the ministry, who requested anonymity, said the batch contained 1,000 doses of the vaccine. I supposed this is the batch in question and what was referred [there](https://moh.gov.vn/tin-tong-hop/-/asset_publisher/k206Q9qkZOqn/content/6-loai-vaccine-phong-covid-19-a-uoc-cap-phep-tai-viet-nam). That official might probably did not know exactly how many doses and said 1,000 when in fact there were 2000 doses. Vietnam approved the vaccine on 23 March ([source](https://www.reuters.com/article/amp/idUSKBN2BF0TG)). So I guess 900 people must have received the first dose around that time. 900*2=1800. I think the rest was for Quality validation?

**Comment by edomt** [comment]
Thank you @Ltn123456
