### ISSUE TITLE
Vaccinations number for Tunisia

### ISSUE THREAD

**Issue by naiferkaisar** [owid/covid-19-data#1795]
Hello,

The update of the vaccinations number for Tunisia are based on Facebook of the Health Ministry. But it is not updated any more. It should be updated based on this site : [https://evax.tn/vaccinationOD.html](url) that belongs to the vaccination program in Tunisia. There is more and better data in this site.

**Comment by samibenabderazak** [comment]
Hi,

Note that the website https://evax.tn/vaccinationOD.html is only accessible through a Tunisian IP address.
I tested accessing it with a VPN that has Tunisian servers and it worked.

**Comment by edomt** [comment]
Hi @samibenabderazak 

Unfortunately, given that this isn't accessible outside of Tunisia, we won't be able to automate our collection based on this address.
