### ISSUE TITLE
Missing data in the Australia vaccination data

### ISSUE THREAD

**Issue by jennywlANU** [owid/covid-19-data#1799]
Hello,
Thank you for compiling this useful data worldwide. I was looking at the Australia.csv file @ covid-19-data/public/data/vaccinations/country_data/Australia.csv and I noticed that there is data missing from line 30 to 99. I would be very grateful if you could tell me why that is and where I could find the remaining data.
Thanks very much.
Best wishes,
Jenny

**Comment by edomt** [comment]
Hi @jennywlANU 

The reason this data is missing is that, for quite a long time, the Australian government was only reporting the total number of vaccinations performed in the country, without any breakdown between 1st and 2nd doses. Therefore it was impossible to calculate `people_vaccinated` and `people_fully_vaccinated` at the time.

**Comment by jennywlANU** [comment]
Thanks very much @edomt for the clarification. Much appreciated :) Keep safe.
Best wishes,
@jennywlANU
