### ISSUE TITLE
Vietnam change its testing data location

### ISSUE THREAD

**Issue by caltaojihun** [owid/covid-19-data#18]
On 12 April, the [website](https://ncov.moh.gov.vn/) on coronavirus by Vietnamese MoH was updated, making the number of tests no longer appear when first loading.
Actually they are still providing this number, just not very obvious. We'll have to click the "Infographic Việt Nam" (red button) lower in the page to see the testing number. As of morning 15 April, this has increased to 132,771 people tested.
The source of the image is [here](https://suckhoedoisong.vn/Covid-19-cap-nhat-moi-nhat-lien-tuc-n168210.html) (it's also by the MoH, not sure why they post it on a second website)

**Comment by edomt** [comment]
Thank you! We'll start updating the time series for Vietnam again, starting today.
