### ISSUE TITLE
Pakistan data column mismatch

### ISSUE THREAD

**Issue by Rizwan-Qamar** [owid/covid-19-data#1801]
It seems like the data is being inserted in wrong column.
The data going into people_partly_vaccinated column should be going into people_vaccinated column.

**Comment by edomt** [comment]
Thank you @Rizwan-Qamar 
Note that due to the current display of the government dashboard and the use of a 1-dose vaccine in Pakistan (CanSino), we're no longer able to report `people_fully_vaccinated`.
