### ISSUE TITLE
Hungary vaccination data

### ISSUE THREAD

**Issue by fibke** [owid/covid-19-data#1802]
Updated information is available on first and second dose vaccination

See [here](https://koronavirus.gov.hu//cikkek/5-millio-628-ezer-beoltott-26-az-uj-fertozott-elhunyt-ket-beteg).

**Comment by edomt** [comment]
Hi @fibke 

See https://github.com/owid/covid-19-data/issues/230

> For countries that are already included in our data, most of our imports are automated and will collect the latest number when we update our dataset. If you don't see the latest number appear in our data, please wait at least 24 hours before suggesting it here.
