### ISSUE TITLE
Pakistan vaccination data

### ISSUE THREAD

**Issue by fibke** [owid/covid-19-data#1803]
Latest observations currently lack information on full vaccination.

This [page](https://ncoc.gov.pk/covid-vaccination-en.php) though provides the latest information on both first and second dose vaccination.

Note that there is no information that distinguishes between 1- and 2-dose protocols.

**Comment by edomt** [comment]
Hi @fibke 

As you wrote, because Pakistan uses 1-dose vaccines but the reported data doesn't break down the information by 1-dose and 2-dose vaccines, it's impossible for us to infer more than `people_vaccinated` and `total_vaccinations` at the moment.

**Comment by fibke** [comment]
Thanks @edomt.

The latest date for which OWID has the full series on total_vaccinations, people_vaccinated and people_fully_vaccinated for Pakistan is June 16. Total_vaccinations at that time were 11 million. 

Note that the WHO publishes later information for all three series, with total_vaccinations at 25 million. Their site doesn't publish the date when the information was collected, but based on your series for total_vaccinations this must have been around July 27.

Source: https://covid19.who.int/region/emro/country/pk. 

Would be good to update that.

Interestingly, if we derive single-protocol vaccination as people_vaccinated + people_fully_vaccinated - total_vaccinations, we get 670 thousand for June 16 (latest OWID data point for all three variables) and 0 for late July (WHO data point).

Cheers,
Philip

**Comment by edomt** [comment]
> Note that the WHO publishes later information for all three series

As far as we know, the WHO doesn't publish any data on `people_fully_vaccinated`, but maybe we've missed a new dataset somewhere? The dataset we use only has `TOTAL_VACCINATIONS` and `PERSONS_VACCINATED_1PLUS_DOSE`.
@fibke

**Comment by fibke** [comment]
@edomt 

Apparently it does. From https://covid19.who.int/region/emro/country/pk:

<img width="223" alt="Screen Shot 2021-08-05 at 4 28 20 AM" src="https://user-images.githubusercontent.com/69641575/128318303-769752d5-0e77-417e-b97d-d2005171989f.png">

**Comment by edomt** [comment]
This looks to me like they're simply subtracting "persons vaccinated" from "doses administered" to try to calculate "fully vaccinated". We basically do the same calculation in our script that takes data from the WHO.

But that method is inaccurate for countries that use 1-dose vaccines, which includes Pakistan (CanSino).

**Comment by fibke** [comment]
It could well be, but if the source is authoritative (WHO may have received supplementary data from the authorities and will check with Samira on this), might as well report it -- as you did for China. 

Indeed, the China data published on OWID for June 10 is calculated on the same basis, implying single-dose protocols are 0 even though they are reported to administer single-dose protocol vaccine CanSino.
