### ISSUE TITLE
Error in Algeria's vaccination data?

### ISSUE THREAD

**Issue by fibke** [owid/covid-19-data#1804]
Algeria [reported](https://www.elkhabar.com/press/article/190912/%D9%87%D8%B0%D8%A7-%D9%87%D9%88-%D8%B9%D8%AF%D8%AF-%D8%A7%D9%84%D9%85%D9%84%D9%82%D8%AD%D9%8A%D9%86-%D8%A8%D8%A7%D9%84%D8%AC%D8%B2%D8%A7%D8%A6%D8%B1/) on 7/29 that is has vaccinated 3,421,279 people, of which 2,696,467 with 1 dose and 724,812 with 2 doses. Algeria only administers 2-dose protocols.

Therefore, total_vaccinations should equal 2,696,467 + 2* 724,812 = 4,146,091 and not 3,421,279.

**Comment by edomt** [comment]
Thank you @fibke
