### ISSUE TITLE
France fully vaccinated data is wrong

### ISSUE THREAD

**Issue by tristanguigue** [owid/covid-19-data#1806]
France fully vaccinated data is currently taken from 
https://www.data.gouv.fr/fr/datasets/r/b273cf3b-e9de-437c-af55-eda5979e92fc

Which only contains first and second dose data. It should be merged with https://www.data.gouv.fr/fr/datasets/r/fa4ad329-14ec-4394-85a4-c5df33769dff which contains the number of fully vaccinated people (`n_cum_complet`)

The difference is quite large (around 3 millions) as people are considered fully vaccinated in France if they have had Covid and have received a single dose.

**Comment by edomt** [comment]
See #1791
