### ISSUE TITLE
MINSA (Perú) ha corregido datos de vacunación hoy (2021-08-05)

### ISSUE THREAD

**Issue by jmcastagnetto** [owid/covid-19-data#1811]
@lucasrodes 
Se ha detectado que MINSA ha hecho muchas correcciones a datos, con respecto a lo que se había publicado en días anteriores.

Adjunto un par de capturas de pantalla, mostrando algunas de las diferencias notadas (usando daff + git), y el resúmen de los totales por dosis con los datos mas recientes (que ya están en mi repositorio)

![diferencias](https://user-images.githubusercontent.com/364668/128453757-2a393ec3-3ec1-49c2-9eca-3d5d8c57cc5b.png)

![resúmen](https://user-images.githubusercontent.com/364668/128453769-fee930ff-ac60-40d5-afb3-4b276168b3d9.png)

Detalles de las diferencias detectadas están en: https://gist.github.com/jmcastagnetto/02dd42a6d131d922ca0eb615d8c059b3

**Comment by edomt** [comment]
Gracias @jmcastagnetto!
