### ISSUE TITLE
Israel third-dose vaccinations

### ISSUE THREAD

**Issue by fibke** [owid/covid-19-data#1814]
Israel has started dose-3 vaccinations, reporting already 349 thousand third doses administered.

Will OWID report on these separately?

Will the definition of people_vaccinated and people_fully_vaccinated be altered to take into account booster shots?

**Comment by edomt** [comment]
Hi @fibke 

We've started to collect these third doses as part of `total_vaccinations`.

For now, we have decided that `people_fully_vaccinated` will keep the same definition, i.e. it describes the number of people who have received the intended number of doses in the vaccination protocol (i.e. 2 in Israel with Pfizer).

We are thinking of how to best incorporate this into our dataset, but the most likely thing is that we will soon add a `total_boosters` variables, counting the number of doses administered beyond the prescribed protocol.

**Comment by fibke** [comment]
Thanks @edomt.

Makes sense to add a variable counting booster doses. For completeness, you could also consider introducing a variable measuring those who have been vaccinated fully under the protocol and have also received a booster - even though that would simply be the sum of people_fully_vaccinated and total_boosters, it would be helpful nonetheless.

**Comment by Stonivor** [comment]
Hi,

Now we are starting injecting the 4th dose in Israel, any idea how the data will be reported on OWID?

Thanks

**Comment by edomt** [comment]
> Now we are starting injecting the 4th dose in Israel, any idea how the data will be reported on OWID?

For now, we don't plan on releasing new metrics. `total_boosters` is defined as `Total number of COVID-19 vaccination booster doses administered (doses administered beyond the number prescribed by the vaccination protocol)`, therefore a second booster (or fourth dose) will also be counted in it.

**Comment by fibke** [comment]
Hope you will at a later point reconsider that, Edouard. Keeping track of the vaccination cycle in the dose space is helpful in measuring the extent to which populations are effectively covered by vaccination. 

On Jan 5, 2022, at 14:27, Edouard Mathieu ***@***.***> wrote:

﻿
Now we are starting injecting the 4th dose in Israel, any idea how the data will be reported on OWID?

For now, we don't plan on releasing new metrics. total_boosters is defined as Total number of COVID-19 vaccination booster doses administered (doses administered beyond the number prescribed by the vaccination protocol), therefore a second booster (or fourth dose) will also be counted in it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by edomt** [comment]
That's what the "For now" is here for :) 
This is all very speculative right now. The only known country with 4th doses is Turkey, and they don't make the necessary data available.

In the long run, I have my doubts that differentiating between dose 4, dose 5, dose 6, dose 7, etc. will be really that useful. On top of being difficult to handle technically, dose numbers will become very chaotic as people also get infected and countries come up with different policies (e.g. 1 infection = 1 dose).

What could matter much more is:
- either the cumulative number of doses received, which is basically `total_vaccinations_per_hundred`
- and/or the number of doses administered in the last X months (for example, [6 months](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Vaccine+doses&Interval=6-month+rolling+total&Relative+to+Population=true&Color+by+test+positivity=false&country=~ISR))

But for now I have a hard time seeing how it'll be really useful to know that country X has administered a certain % of _specifically_ 6th doses, and country Y a certain % of _specifically_ 7th doses.

**Comment by fibke** [comment]
In the long run indeed it doesn’t make sense. But we’re entering only the second year of the global vaccination campaign. The distinction continues to be meaningful particularly given that several countries have barely started the primary cycle. 

In the long run some other measure is needed. Total boosters won’t be useful as we would lump boosters of several cycles. Providing different vaccines converge on a similar cycle the measurement could anchor itself to that (as in boosters over the course of X months as suggested). 

My guess is that increasingly the relevance of the dose space measurements will be lost and we will eventually need to rely primarily on indicators in the people space (eg share of people with updated vaccinations in the last X months). 

On Jan 5, 2022, at 16:29, Edouard Mathieu ***@***.***> wrote:

﻿
That's what the "For now" is here for :)
This is all very speculative right now. The only known country with 4th doses is Turkey, and they don't make the necessary data available.

In the long run, I have my doubts that differentiating between dose 4, dose 5, dose 6, dose 7, etc. will be really that useful. On top of being difficult to handle technically, dose numbers will become very chaotic as people also get infected and countries come up with different policies (e.g. 1 infection = 1 dose).

What could matter much more is:

either the cumulative number of doses received, which is basically total_vaccinations_per_hundred
and/or the number of doses administered in the last X months (for example, 6 months)
But for now I have a hard time seeing how it'll be really useful to know that country X has administered a certain % of specifically 6th doses, and country Y a certain % of specifically 7th doses.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fibke** [comment]
Estonia has a neat approach to report on booster data. See: https://opendata.digilugu.ee/covid19/vaccination/v3/opendata_covid19_vaccination_total.csv

Note the column for VaccinationSeries. If this is 1, then we have the primary vaccine cycle (of 1 or 2 shots depending on protocol). 2 is the first booster series; 3 the second one; 4: the third one.

To get the booster doses, select VaccinationSeries = 2, 3 or 4 and match this with MeasurementType=DosesAdministered.

Estonia's approach is in my view a best-practice way to differentiate between booster series. Perhaps something to consider going forward as you collect data for other countries (assuming that over time most countries will converge to this approach).

See also: https://github.com/owid/covid-19-data/issues/2426#issue-1132990132
