### ISSUE TITLE
Cuba 

### ISSUE THREAD

**Issue by fibke** [owid/covid-19-data#1815]
Cuba has reported 2.74 million doses administered as part of a three-dose protocol.

Unlike the third doses being administered in Israel, the third dose of the Abdala vaccine is not a booster shot. It is part of a three-dose protocol. 

The people_vaccinated and people_fully_vaccinated stats in OWID seem to disregard the third dose, even though the total_vaccinations number includes it.

Would be good to reconcile these numbers.

**Comment by lucasrodes** [comment]
Hi @fibke,
Thanks for your message.

We are aware of this fact and we report Cuban data as follows:

- We compute the number of total doses administered as the sum of first, second and third doses.
- The number of people with at least one dose is equivalent to the number of first doses administered.
- The number of people fully vaccinated is equivalent to the number of third doses administered (this is different than for other countries, where second doses would be used).


As an example, take the last update from 2021-08-03 ([source](https://salud.msp.gob.cu/actualizacion-de-la-vacunacion-en-el-marco-de-los-estudios-de-los-candidatos-vacunales-cubanos-y-la-intervencion-sanitaria/)):

> Al cierre del 3 de agosto se acumulan en el país 10 477 630 dosis administradas con los candidatos vacunales cubanos SOBERANA 02 y SOBERANA Plus, y con la vacuna cubana Abdala.
> 
> Hasta la fecha, 4 456 437 personas han recibido al menos una dosis de uno de los candidatos vacunales cubanos SOBERANA 02 y SOBERANA Plus, y de la vacuna cubana Abdala. De ellas ya tienen segunda dosis 3 275 772 personas y tercera dosis 2 745 421 personas. 
> 

We report this data as:
- `total_vaccinations` = 10,477,630
- `people_vaccinated` = 4,456,437
- `people_fully_vaccinated` = 2,745,421

Hope this helps

**Comment by fibke** [comment]
Thanks @lucasrodes. 

Agreed on this approach and good to differentiate between three-dose protocols (as in Cuba) and two-dose protocols complemented with booster shots (as in Israel, Uzbekistan and other places).
