### ISSUE TITLE
Venezuela using Abdala vaccine

### ISSUE THREAD

**Issue by DrBazUK** [owid/covid-19-data#1829]
Hi team,
Another addition for the vaccines in countries:
[http://mpps.gob.ve/index.php/sala-de-prensa/notnac/1155-venezuela-recibe-de-cuba-primer-lote-de-vacunas-abdala-contra-la-covid-19](http://mpps.gob.ve/index.php/sala-de-prensa/notnac/1155-venezuela-recibe-de-cuba-primer-lote-de-vacunas-abdala-contra-la-covid-19)

Venezuela is now using the Abdala vaccine (from Cuba) in addition to the other vaccines previously announced.

Hope this helps,
Barry.

**Comment by lucasrodes** [comment]
Thanks, @DrBazUK,
Now reporting Abdala in the data
