### ISSUE TITLE
Taiwan using new vaccine (EUA for Medigen Vaccine Biologics Corporation)

### ISSUE THREAD

**Issue by DrBazUK** [owid/covid-19-data#1834]
Hi team,
some more information from my colleagues:

Taiwan’s domestically developed two-dose protein subunit type vaccine, MVC-COV1901, by Medigen Vaccine Biologics Corporation has been approved for EUA and production. [https://www.cdc.gov.tw/En/Bulletin/Detail/SEd8rAKMzywG_b92N6z8nA?typeid=158](https://www.cdc.gov.tw/En/Bulletin/Detail/SEd8rAKMzywG_b92N6z8nA?typeid=158)
Authorities have now added it to their national vaccine rollout as an option for people aged 20 and above and the first five batches have been produced. [https://www.cdc.gov.tw/En/Bulletin/Detail/5NuaA-4jqd9nSh03MdwiWw?typeid=158](https://www.cdc.gov.tw/En/Bulletin/Detail/5NuaA-4jqd9nSh03MdwiWw?typeid=158)

Not sure if this is too early to be included on the list but it seems to be in use now with registrations and vaccines being administered.

**Comment by lucasrodes** [comment]
Hi @DrBazUK,
Thanks for reporting this. 

For now, nothing has changed - as per reported vaccine types - in the [daily report](https://www.cdc.gov.tw/File/Get/AteHiVbjSPAMjOBE5-ELGA). Probably will be added soon.

We'll follow this to see if they start reporting this vaccine in their daily reports.
