### ISSUE TITLE
US testing data not updated

### ISSUE THREAD

**Issue by miotomita** [owid/covid-19-data#1838]
Hello OWID team,

Thank you always for your ongoing efforts to distribute insightful data. 
It seems US data for positive_rate and tests_per_case have not been updated since July 14.
https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv

Although [CCD COVID Data Tracker Weekly Review](https://www.cdc.gov/coronavirus/2019-ncov/covid-data/covidview/index.html)( [#207](https://github.com/owid/covid-19-data/issues/207)) was under revision, US Department of Health & Human Services keeps updating the numbers on daily basis.
https://healthdata.gov/dataset/COVID-19-Diagnostic-Laboratory-Testing-PCR-Testing/j8mb-icvb

I would greatly appreciate it if you could fix this and restart updating US testing data.

Thank you so much!

**Comment by edomt** [comment]
Thank you @miotomita ! This is now [fixed](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Share+of+positive+tests&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=~USA).

<img width="944" alt="image" src="https://user-images.githubusercontent.com/7103774/128994244-3e555c6e-b21c-474c-b312-984acd160261.png">

**Comment by miotomita** [comment]
Thank you so much for your quick response!
