### ISSUE TITLE
VAX: Data point in China

### ISSUE THREAD

**Issue by Iftimasum1** [owid/covid-19-data#1855]
Actually, when I disable the lines for world and Asia, I can see that there is a single data point for China, which seems to be very close to that delta. Where did the rest of the data go? Or was there no data before, they now published a single number and that simply got added to the Asia-wide and worldwide data for that day? In that case, is there really no better way than to blindly assume that it was all on that day?

_Originally posted by @Fabian42 in https://github.com/owid/covid-19-data/issues/1551#issuecomment-860856826_iftimasum Motali b

**Comment by Iftimasum1** [comment]
> #1

**Comment by lucasrodes** [comment]
Hi @lftimasum1,
Thanks for your message.

Chia has released two data points for metrics `people_vaccinated` and `people_fully_vaccinated`. Therefore, if checking the time-series for China in our explorer for these metrics, only two points will appear.
