### ISSUE TITLE
Western Sahara - covid vaccination 

### ISSUE THREAD

**Issue by ydiki** [owid/covid-19-data#1856]
Western Sahara is currently a disputed territory and the UN considered it as "Non-Self-Governing" territory. However Morocco controls and administers 80-90% of the territory. Sahrawi people are also included in the vaccination campaign administered by Morocco. 

Asking to include this information to Western Sahara covid data.

official sources: 
- https://www.liqahcorona.ma/ar
- http://www.covidmaroc.ma/pages/Accueilfr.aspx

<img width="1210" alt="morocco" src="https://user-images.githubusercontent.com/36400305/129479670-8a643e42-0fc5-4b97-8957-7b81d89f3e5d.png">

**Comment by ydiki** [comment]
Hello @edomt, can you please take a look at this ?

Is it possible to put a remark or a comment on Western Sahara to include this information ?
You can check the history of Western Sahara conflict on UN site: https://minurso.unmissions.org/chronology-events

Regards.

**Comment by edomt** [comment]
Hi @ydiki 

The issue is that unless the government publishes specific data with the number of vaccinations in Western Sahara, we can't simply add a row for `Western Sahara` with the numbers for Morocco, as it would lead to double-counting all vaccinations in Morocco.

**Comment by ydiki** [comment]
Hello @edomt,

Thank you for your response and for all the work, I appreciate it.

I understand the issue, the Moroccan government publishes data as W. Sahara being part of the kingdom.
Therefore, the solution would be to adapt the map like Google Maps does, otherwise leave it like this with "no data" forever.
because Western Sahara is not an independent country and there is no border between Morocco and W. Sahara.

Regards.
