### ISSUE TITLE
Open data on deaths in Peru, including those from COVID-19 (SINADEF)

### ISSUE THREAD

**Issue by jmcastagnetto** [owid/covid-19-data#186]
There is an open dataset, that has information on the causes of death including those related to having had COVID-19 (confirmed and suspected). This dataset can help you estimate excess deaths for this cause. It is published by the Ministry of Heatlth of Peru at the URL: https://www.datosabiertos.gob.pe/dataset/informaci%C3%B3n-de-fallecidos-del-sistema-inform%C3%A1tico-nacional-de-defunciones-sinadef-ministerio

I've been tracking that dataset for quite some time, and in have some preliminary cleanup code in https://github.com/jmcastagnetto/sinadef-peru-fallecimientos, in particular I've extracted the list of all terms used in the columns related to causes of death (see: https://github.com/jmcastagnetto/sinadef-peru-fallecimientos/blob/main/datos/causas_reportadas_sinadef.csv)

In my repo I got a simple graph that tries to show (using a very naive criteria) how the COVID-19 has impacted deaths.

![fallecimientos-por-semana](https://user-images.githubusercontent.com/364668/99546231-382fa300-2984-11eb-943d-58b8c511c1ee.png)

**Comment by edomt** [comment]
Thank you @jmcastagnetto. We source our excess mortality data directly from the Human Mortality Database, and our team doesn't have the resources at the moment to add countries one by one from national sources.
