### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by msgoussi** [owid/covid-19-data#1860]
Is it possible to share which countries falls under "Low income", "Lower middle income",  "Upper middle income", "High income"?
Thansk

**Comment by lucasrodes** [comment]
Hi @msgoussi,
Thanks for your message.

We use the definitions by the World Bank. You can find these [here](https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups).
