### ISSUE TITLE
Definitions Missing for OWID_ ISO Codes

### ISSUE THREAD

**Issue by bsullins** [owid/covid-19-data#1862]
Apologies if I just am bad at searching but no where have I been able to find the definition for all of the Locations with an ISO code beginning with OWID_

Posting this as an issue since I recently did some analysis using this data set ( covid-19-data/scripts/input/un/population_2020.csv ) and was surprised to see "South America" listed separately from all the countries in South America and the number of "New Deaths" lower. 

Can anyone help shed light on this or is there a better way we can label these Locations so there's less confusion?

**Comment by lucasrodes** [comment]
Hi @bsullins,
Thanks for your feedback.

At the moment there is no section addressing this, so we will try to add some descriptions in this regard in the upcoming weeks. 

For the time being, some preliminary definitions:

The field `ISO code` contains [ISO 3166-1 alpha-3](https://www.iso.org/iso-3166-country-codes.html) codes. Some entities that we include may not have an associated standardized ISO code. Therefore, we use custom codes starting with `OWID_`.

### Continents
Groups countries in continents, as defined in https://ourworldindata.org/grapher/continents-according-to-our-world-in-data:

- OWID_AFR	Africa
- OWID_ASI	Asia
- OWID_EUR	Europe
- OWID_OCE	Oceania
- OWID_SAM	South America
- OWID_NAM	North America

### Other regions/countries
UK countries:

- OWID_ENG	England
- OWID_NIR	Northern Ireland
- OWID_SCT	Scotland
- OWID_WLS	Wales

Other locations with no ISO code
- OWID_KOS	Kosovo
- OWID_CYN	Northern Cyprus

### Other groupings
- OWID_EUN	European Union: Aggregates all metrics all countries that are members of the European Union.
- OWID_WRL	World: Aggregates all metrics for all countries.

World Bank income groups ([ref](https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups))
- OWID_HIC	High income
- OWID_LIC	Low income
- OWID_LMC	Lower middle income
- OWID_UMC	Upper middle income

**Comment by bsullins** [comment]
Thanks for the clarification. Is it that these locations under the OWID_ codes are only the countries without a standard ISO code? 

The results here for example show both Brazil and Argentina having more "new cases" than "South America" of which both countries are in. 

https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Confirmed+cases&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=South+America~BRA~ARG

So if the OWID_SAM included all countries in South America, it would need to be a cumulative total and obviously that's not what the data is showing. 

Thanks for the help!

**Comment by lucasrodes** [comment]
Hi @bsullins,
Thanks for your message.

You are comparing percentage values. The percentage of vaccinated in South America does not necessarily have to be higher than the one in Brazil, Argentina or any other country. Consider the following example: Brazil has vaccinated all its population (100%) but all other South American countries have not started vaccinating their population (0%). As a consequence, South America as its whole won't have a 100% of its population vaccinated but a lower number.

To check the absolute values (and not percentages) uncheck the box "Relative to Population", or click [this link](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Confirmed+cases&Interval=7-day+rolling+average&Relative+to+Population=false&Align+outbreaks=false&country=South+America~BRA~ARG).


Hope this helps

**Comment by bsullins** [comment]
Okay got it, that makes sense. Could I propose somewhere that we add a field for "Location Type" to easily identify these buckets (eg. OWID_) from the regular ISO countries?
