### ISSUE TITLE
Dataset grouped by epi week and age range (Vaccination, COVID-19, Perú)

### ISSUE THREAD

**Issue by jmcastagnetto** [owid/covid-19-data#1864]
@lucasrodes 

I've added to my repo some CSVs that group by epi, dosis, and age range (quintiles, deciles, and the ranges you are using) the number of people vaccinated in Perú.

The file with the OWID age groups is at: https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/main/datos/vacunas_covid_rangoedad_owid.csv

That CSV has 2 more groups that I think you are not using ("(Missing)" and the range from "0-17" years) and which you can ignore. 

Let me know if this data is useful to you.

**Comment by lucasrodes** [comment]
Hi @jmcastagnetto,
Thanks for your work.

I have checked the age data (https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/main/datos/vacunas_covid_rangoedad_owid.csv), and it looks great. Note, however, that we are only able to import percentage values at the moment for age data. More on our format can be found [here](https://github.com/owid/covid-19-data/blob/master/scripts/docs/vaccinations/CONTRIBUTE.md#Age-group-data).

**Comment by jmcastagnetto** [comment]
Hi @lucasrodes 

I also got the population estimates by age that MINSA and INEI published, so I've added a couple of columns containing the population estimate per age group, and the percent of the cummulative count for each group. 

Still not exactly in the final format you use, but close. If this will be useful and you are going to use it, I will make some changes to generate the exact format you are using for this metric.

**Comment by jmcastagnetto** [comment]
OK, had some time in between meetings this morning, and got the file in the format you can use. 

When you can, check https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/main/datos/vacunas_covid_rangoedad_owid.csv

Let me know if there is something else I can do to help.

**Comment by lucasrodes** [comment]
Thank you very much for your work, @jmcastagnetto. 

This should be easily added to our vaccination age pipeline. I Will let you know once it is merged.

**Comment by lucasrodes** [comment]
@lucasrodes Code added to add age data for Perú. Thanks!
