### ISSUE TITLE
France: Vaccination data doesn't match with source

### ISSUE THREAD

**Issue by marcelpauly** [owid/covid-19-data#1867]
In France the vaccination data seem not to match the official source: https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1/

For example, the latest dataset by the government shows 39.5 million fully vaccinated people (68.4%) but the OWID dataset has 35.8 million (53.1%) in it. [French media](https://www.lemonde.fr/les-decodeurs/article/2020/05/05/coronavirus-age-mortalite-departements-pays-suivez-l-evolution-de-l-epidemie-en-cartes-et-graphiques_6038751_4355770.html) uses the official data, as well. What's the explanation for the difference?

**Comment by CovidMexico** [comment]
Here [#1791](https://github.com/owid/covid-19-data/issues/1791)

**Comment by marcelpauly** [comment]
Sorry, didn't see that. Thanks!
