### ISSUE TITLE
Open Data on hospital beds in Peru (during the COVID-19 health emergency)

### ISSUE THREAD

**Issue by jmcastagnetto** [owid/covid-19-data#187]
SUSALUD, a dependency of the Ministry of Health of Peru, has been publishing (for some time now) a dataset on the beds used and free at hospitals in Peru, including ICU beds and those with respirators used to treat COVID-19 patients.

The dataset is at: http://datos.susalud.gob.pe/dataset/data-hist%C3%B3rica-del-registro-de-camas-diarias-disponibles-y-ocupadas-del-formato-f5002, and might help you in estimates of the saturation levels of healths services.

If it can be useful, I got preliminary and simple cleaning code at: https://github.com/jmcastagnetto/proceso-datos-susalud-camas/, including some quick graphs like the evolution of use of respirators by Department (our main subnational division).

![uso-ventiladores-departamento](https://user-images.githubusercontent.com/364668/99547437-8beebc00-2985-11eb-957c-dab0926b5fcf.png)

**Comment by edomt** [comment]
Thank you @jmcastagnetto. Similarly to the excess mortality data, we source our hospital & ICU data directly from the European CDC, and our team doesn't have the resources at the moment to add countries one by one from national sources.
