### ISSUE TITLE
18 august booster data turkey

### ISSUE THREAD

**Issue by cvr000** [owid/covid-19-data#1872]
hello, something does not seem to add up for 18 august, where booster shots should be 7259939 according to my calculation (booster shots=total shots-number fully vaccinated - number vaccinated).  All earlier dates are fine.  great to see the booster data online.

**Comment by edomt** [comment]
Hi @cvr000 
We're taking this data directly from the table at the bottom of the page, rather than calculating it:

![image](https://user-images.githubusercontent.com/7103774/130209707-e7895184-8938-47c6-8c7a-fb7716feccc8.png)
