### ISSUE TITLE
Swedish split reporting

### ISSUE THREAD

**Issue by limbero** [owid/covid-19-data#1878]
Hi, not sure if you are aware, but as of tuesday Swedish numbers [here](https://fohm.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/statistik-och-analyser/statistik-over-registrerade-vaccinationer-covid-19/) are presented split by age. OWID appears to use the number from table 2, but that doesn't include people below 18 years of age. To do that one needs to sum with numbers from table 3a. I don't understand the codebase well enough to PR in the next few days but I can help review and explain.

**Comment by lucasrodes** [comment]
Hi @limbero,
Thanks for reporting this! 

I just fixed this in 3022110.

**Comment by vikdork** [comment]
@edomt 
Sweden has no merged the two tables into one, again :(.
Should i open a new issue or do we reopen this one?
ping @limbero @lucasrodes

**Comment by limbero** [comment]
Not sure of protocol, but was just about to report this myself.

**Comment by lucasrodes** [comment]
Hi, 
Thanks for reporting.

Looking into this!

**Comment by lucasrodes** [comment]
Fixed @limbero @vikdork.

Will be live in next update
