### ISSUE TITLE
Switzerland New COVID-19

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#188]
Hello, thank you for updating COVID-19 data.
I found that since 9/20/2020, Switzerland new COVID-19 cases has a report pattern that Sunday and Monday new cases are shown as 0. is that the correct pattern of how Switcherland reports?

**Comment by edomt** [comment]
Hello @RuijingZ 
Yes, similarly to a few other countries (mostly in Europe), Switzerland does not report on weekends, but only on weekdays. So the case counts for Sunday and Monday are always set to 0 by the European CDC.
