### ISSUE TITLE
Singapore vaccination numbers no longer updated/inaccurate

### ISSUE THREAD

**Issue by fourjr** [owid/covid-19-data#1882]
# Context
Singapore's National Vaccination Programme (NVP - not a real acronym just for the ease of this issue) contains the Pfizer-BioNTech/Comirnaty and Moderna vaccines. ([MOH](https://www.moh.gov.sg/covid-19/vaccination/faqs---safety-and-efficacy-of-the-covid-19-vaccine))

The Sinovac vaccine is under the Special Access Route (in the above article as well as [MOH FAQ1](https://www.moh.gov.sg/covid-19/vaccination)) and categorised under WHO Emergency Use Listing (WHO EUL) vaccines.

[See Wikipedia's explanation on SG vaccination programme](https://en.wikipedia.org/wiki/COVID-19_vaccination_in_Singapore#Vaccination_programme).

# The Issue
The numbers pulled into [country_data/Singapore.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Singapore.csv) on 2021-08-14 contains vaccination statistics for Pfizer, Moderna and Sinovac. This results in all future data being slightly lower than the total_vaccinations of 2021-08-14 and thus the data is not updated, (code responsible for skipping - [utils/incremental.py](https://github.com/owid/covid-19-data/blob/14dc4c8bca3ce95be3b25d6b0ec6d458f91e1097/scripts/src/cowidev/vax/utils/incremental.py#L187)).

You can calculate the total_vaccinations numbers from the press release on 15 August [here](https://www.moh.gov.sg/news-highlights/details/update-on-local-covid-19-situation-and-vaccination-progress-(15-aug-2021)):  `8399585 (P+M) + 147528 (S) = 8547113`. 8547113 is the number reflected on [country_data/Singapore.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Singapore.csv).

However, the current automation script ([incremental/singapore.py](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/vax/incremental/singapore.py)) pulls numbers directly from the [Ministry of Health dashboard](https://www.moh.gov.sg/covid-19/vaccination). This dashboard does not include vaccination statistics from Sinovac (also categorised as under WHO EUL). The dashboard only shows statistics from the national vaccination programme (Pfizer or Moderna).

As of 19 August ([press release](https://www.moh.gov.sg/news-highlights/details/update-on-local-covid-19-situation-and-vaccination-progress-(20-august-2021))):
```
8,526,565 - total_vaccinations (NVP)
4,459,200 - people_vaccinated (NVP)
4,200,032 - people_fully_vaccinated (NVP)

154,936 - total_vaccinations (WHO EUL)
84,281 - people_vaccinated (WHO EUL)

people_fully_vaccinated  (WHO EUL) is not released but instead a general 77% of population has completed regimen is mentioned and 82% of the population has taken a first dose.

8,681,501 - total_vacccinations (NVP+WHO EUL)
4,543,481 - people_vaccinated (NVP+WHO EUL)
4,266,439 - people_fully_vaccinated (CALCULATED NUMBER of NVP+WHO EUL, based on 4543481/.82*.77)
```

# Solution
The only way I can see to update the numbers with all vaccine providers within the country (both national programme and WHO EUL) is manually using the press releases.

There is no dashboard that has a fixed-layout that we can scrape. The closest thing I can find is the [gov.sg covid-19 latest update page](https://www.gov.sg/features/covid-19) which only features total vaccinations.

I suggest that only the Singapore NVP vaccines be recorded as they are easier to automate or a manual process is used as described above.

**Comment by edomt** [comment]
Many thanks @fourjr — for now I've managed to automate the collection from press releases based on regular expressions. Hopefully they won't change the text between publications!

**Comment by fourjr** [comment]
Sounds good! Thanks for the quick update.
