### ISSUE TITLE
South Africa Data

### ISSUE THREAD

**Issue by AFP1st** [owid/covid-19-data#1884]
Good day wrt issue no #1873

Data for SA still not available.
thanks
![SAData](https://user-images.githubusercontent.com/61959635/130323054-ad2fe997-f614-4e23-953b-2e38d638e1fe.JPG)

**Comment by edomt** [comment]
Hi @AFP1st 
This has now been [fixed](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Share+of+positive+tests&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=~ZAF).

**Comment by AFP1st** [comment]
Thanks - i see the positive rate :)  will the new cases still update as well?

John

**Comment by edomt** [comment]
The new cases are updated each morning, based on [data from Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19/).

**Comment by AFP1st** [comment]
Good morning:
could you please look at new_tests data.  Thanks
![image](https://user-images.githubusercontent.com/61959635/130546866-4466f8df-7eda-49cc-8afd-0d16f64dccf3.png)

**Comment by camappel** [comment]
@edomt I've now added the testing daily change data from [Twitter](https://twitter.com/HealthZA)

**Comment by edomt** [comment]
Thank you @camappel !
@AFP1st This is now fixed.

**Comment by AFP1st** [comment]
Thank you

**Comment by AFP1st** [comment]
Good day.

looks like the data again isn't pulling through.
 Positive rate, new test 

thanks

**Comment by edomt** [comment]
Hi @AFP1st 

We are relying on the data made available by @dsfsi - if you don't see any new data on our side, that's because no new data has been added to their file here: https://github.com/dsfsi/covid19za/blob/master/data/covid19za_timeline_testing.csv

**Comment by edomt** [comment]
Hi @AFP1st 

This data will be updated tomorrow.
