### ISSUE TITLE
Italiy DATA source sospicious

### ISSUE THREAD

**Issue by udedomenico** [owid/covid-19-data#1885]
Not sure where that data comes from although it is claimed the source to be the _Extraordinary commissioner for the Covid-19 emergency,_ numbers do not match with the official data available here: 
https://www.governo.it/it/cscovid19/report-vaccini/

https://github.com/italia/covid19-opendata-vaccini

**Comment by edomt** [comment]
Hi @udedomenico 

I'm not sure what you mean by "suspicious": we indeed rely on the files published on GitHub. You can check our entire code for Italy in [italy.py](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/vax/batch/italy.py).

Note that in our data, fully-vaccinated people are those who have received all doses prescribed by their vaccination regimen (e.g. 2 doses for Pfizer/BioNTech, Moderna, Oxford/AstraZeneca, etc. and 1 dose for J&J, CanSino, etc.). This allows for an optimal comparability between countries. Some countries have alternative definitions, such as having been infected with SARS-CoV-2 in the past and receiving 1 dose of a 2-dose regimen. We currently ignore these to preserve the common definition of fully vaccinated, i.e. all doses required in the vaccine regimen.
