### ISSUE TITLE
Senegal now using Johnson & Johnson in addition to other vax

### ISSUE THREAD

**Issue by DrBazUK** [owid/covid-19-data#1890]
Dear colleagues,
My team brought to my attention that the US Embassy is reporting the arrival and use of J&J vaccination in Senegal:
[https://sn.usembassy.gov/united-states-donates-covid-19-vaccines-for-senegal/](https://sn.usembassy.gov/united-states-donates-covid-19-vaccines-for-senegal/) and this is backed up on the Ministere de la Sante site: [https://www.sante.gouv.sn/mediatheque/phototheques/lancement-du-vaccin-johnson-johnson-au-centre-de-sant%C3%A9-philipe-maguil%C3%A8ne](https://www.sante.gouv.sn/mediatheque/phototheques/lancement-du-vaccin-johnson-johnson-au-centre-de-sant%C3%A9-philipe-maguil%C3%A8ne)

Although I don't believe that the Senegalese MOH is reporting separate vaccines in use, there are reports (photo journals) of ongoing deliveries of the J&J vaccine [https://www.sante.gouv.sn/search/node/johnson](https://www.sante.gouv.sn/search/node/johnson)

I hope this is helpful in updating the vaccines in use.

best regards,
Barry

**Comment by edomt** [comment]
Hi @DrBazUK 

Many thanks for this! For Senegal, we get our data directly from the WHO, and for now their metadata doesn't include anything about J&J in the country, so I'm guessing the government hasn't reported vaccinations done with J&J through their channel. In any case, once the vaccine starts being used, then the vaccine list will be automatically updated.

Edouard
