### ISSUE TITLE
Myanmar using Sinovac

### ISSUE THREAD

**Issue by DrBazUK** [owid/covid-19-data#1895]
Hi team,
colleagues have reported (from within Myanmar) that the Sinovac vaccine is arriving and is in use within the country. Ministry of Health websites are all in Burmese and lack detail but the official Myanmar News Agency has a number of stories covering the use of the vaccine:

[https://www.gnlm.com.mm/covid-19-medical-supplies-continuously-transported-to-regions-states/#article-title](https://www.gnlm.com.mm/covid-19-medical-supplies-continuously-transported-to-regions-states/#article-title)

[https://www.gnlm.com.mm/one-million-units-of-covid-19-vaccines-arrive-from-china-in-second-batch/#article-title](https://www.gnlm.com.mm/one-million-units-of-covid-19-vaccines-arrive-from-china-in-second-batch/#article-title)

Other media covering the same:
[https://elevenmyanmar.com/news/one-million-doses-of-sinovac-vaccines-arrive-in-myanmar](https://elevenmyanmar.com/news/one-million-doses-of-sinovac-vaccines-arrive-in-myanmar)

[https://www.voanews.com/covid-19-pandemic/junta-faces-difficulties-myanmar-vaccination-program](https://www.voanews.com/covid-19-pandemic/junta-faces-difficulties-myanmar-vaccination-program)

Hope this is helpful in updating the vaccines in use.

Best regards,
Baz

**Comment by edomt** [comment]
Thanks, we'll update this!
