### ISSUE TITLE
Missing testing data for Russia since 11-Apr

### ISSUE THREAD

**Issue by MikhailPB** [owid/covid-19-data#19]
Hello,

Can you please return # of tests data for Russia?

It was present in 11-April file but not later.

If needed, # of tests data is available in wiki page:
https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Russia

Thank you

**Comment by edomt** [comment]
Hi @MikhailPB 
We temporarily removed the Russian time series as we wanted to find more precise figures (the official PDF reports only gave vague estimates). Thank you for pointing us to the right resource; the time series is back now!
Edouard
