### ISSUE TITLE
Please correct Daily new confirmed COVID-19 deaths for Russia on Nov 17

### ISSUE THREAD

**Issue by SergRZ** [owid/covid-19-data#190]
Daily new confirmed COVID-19 deaths for Russia on Nov 17:

OWiD data: 745;
[Official data](https://xn--80aesfpebagmfblc0a.xn--p1ai/information/): 303;

**Comment by edomt** [comment]
Dear @SergRZ 
We source our data from the European CDC and do not make changes to it.

For November 19, the ECDC data shows a total of 34,850 deaths: https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&country=~RUS&region=World&deathsMetric=true&interval=total&smoothing=0&pickerMetric=total_cases&pickerSort=desc

This is also the case of the official data: 
![image](https://user-images.githubusercontent.com/7103774/99774381-fe8aa380-2b0d-11eb-9645-240bb1e12da2.png)
