### ISSUE TITLE
Australian Source is NOT the Australian Government

### ISSUE THREAD

**Issue by hmchan2070** [owid/covid-19-data#1905]
covidlive is a site produced by someone from the Australian public but does use sources from the government. I suggest you use government sites to obtain your data. If you continue to use covidlive, suggest you refactor as the data covidlive is showing differs significantly to what you are showing e.g covidlive 1st dose 16+ 55%; 2nd does 16+ 32.8% (28 Aug), ourworldindata 1st dose 44.48% ; 2nd dose 25.64%

**Comment by TrogdorDangerfloof** [comment]
I would agree with @hmchan2070, but for different reasons. If I go to the hospitalisation and ICU data page here on the official health website, https://www.health.gov.au/resources/current-covid-19-cases-in-hospitals-and-intensive-care-units-icus - it tallies up. The reason, I think, that there are discrepancies around this is that govt has changed the way they update and provide the data. There is much fudging of figures here. For example, they are only reporting the screened disability workers from the NDIS Quality and Safeguards Commission workforce, which is a subset of only registered providers and about half the workforce.

**Comment by edomt** [comment]
Hi @hmchan2070 

The figures you mentioned are expressed as the share of vaccinated individuals in the 16+ population only. The figures that we present on Our World in Data are expressed as a percentage of the total population in the country (all ages included).

As far as I can see, https://www.health.gov.au does not offer a full time series updated every day — but maybe I've missed it? The only thing I could find are those daily spreadsheets that only include a snapshot number for the current day: https://www.health.gov.au/resources/publications/covid-19-vaccination-vaccination-data-28-august-2021

In terms of absolute numbers, this morning the covidlive.com.au API has:
- 18,706,627 doses administered, which is exactly the same as the official data
- 11,807,047 people with at least 1 dose, which is slightly more than the 11,724,184 in the official spreadsheet but within <1%
- 6,899,580 people fully vaccinated, which is slightly less than the 6,950,122 in the official spreadsheet but within <1%

**Comment by hmchan2070** [comment]
Hi @edomt. Given that only recently children over 12 are eligible for vaccines, how is it possible that certain countries are showing close to 80% vaccination rates if, as you have indicated, you count the total population? For example, Denmark has only been vaccinating children from 12 years since July. You can ask the Australian Government for data sets - the link is on the health site.

**Comment by edomt** [comment]
Hi @hmchan2070 

I've just checked the consistency of these two metrics between our vaccination dataset and population by broad age group (https://ourworldindata.org/grapher/population-by-broad-age-group?stackMode=relative&country=~ARE), and couldn't find any problem.

For example, Denmark has 75.56% of its population with at least 1 dose, and ~13% of its population under 12 years old.

**Comment by TrogdorDangerfloof** [comment]
You can ask them, but they are not always releasing the data sets that are entirely accurate. If you are making a request, please specify to them the data set you want them to pull the data from, if you know what it is.
