### ISSUE TITLE
Argentina is missing from testing data

### ISSUE THREAD

**Issue by alksak** [owid/covid-19-data#191]
Thanks for the great effort to collect all these data to one place.

Argentina is missing from testing data, is there a specific reason for that?

**Comment by edomt** [comment]
Hi @alksak 

To ensure the quality and reliability of our testing data, we've decided to remove the testing data (and only the testing data, not the cases & deaths data) for Argentina from our dataset for the time being, as the official figures aggregated by the government don't seem to be of sufficient quality to correctly reflect the extent of the testing done in the country.

In particular, it has recently emerged (as explained here: https://clarin.com/sociedad/testeos-coronavirus-argentina-advierten-negativos-cuentan-dispara-tasa-positividad_0_cwU6GT_cu.html) that many negative tests weren't being recorded in several provinces, including large ones such as Santa Fe and Córdoba. This has created a bias driving the positive rate upwards, up to 75% a few days ago when we made the change.

The government had announced a few days before that it would implement a new system to make sure that all tests were being correctly recorded in all provinces. It has also reacted to our own announcement of this change, by reiterating that they were working on making the correct data available ASAP. It's not clear however when this will happen, and whether this will also correct the historical data retrospectively.

Edouard
