### ISSUE TITLE
Germany vaccination data

### ISSUE THREAD

**Issue by jarnold231** [owid/covid-19-data#1915]
Hi there, vaccination data for Germany has been removed for all of August in the latest update. Last week there was data for people_vaccinated and people_fully_vaccinated >22/08/2021 in today's release there is no data from 31/07/2021. Is this a revision or an error?

**Comment by edomt** [comment]
Hi @jarnold231 
Not sure what happened there — the German source was missing all data for August when we did our update this morning, so it was deleted on our side as well. Things seem to back to normal now, so I've just rerun the update.
Thank you for letting us know!

**Comment by jarnold231** [comment]
Thank you!  

Also FYI seem to have a similar issue with Hungary but only for people_fully_vaccinated with no data now from 5/06/2021, but last week there was data for 22/08/2021.
