### ISSUE TITLE
Chile's Latest Covid Delta % Incorrect?

### ISSUE THREAD

**Issue by andrewcooke-isti** [owid/covid-19-data#1918]
Hi,

Recently Our World In Data has been showing that the delta variant in Chile dropped on 23 August (down from 10.3% to 2.3% over 14 days).  This seems unlikely and contradicts [press reports](https://www.biobiochile.cl/noticias/nacional/chile/2021/09/01/variante-delta-muestra-aumento-de-la-circulacion-segun-ultimo-informe-del-isp-llego-a-un-17.shtml) today which give 17%.

The source for all these numbers is probably [this report](https://www.minsal.cl/wp-content/uploads/2021/08/Informe-Vigilancia-Geno%CC%81mica-12.pdf) which, despite the title page saying Aug 22, was released [here](https://www.minsal.cl/nuevo-coronavirus-2019-ncov/informe-epidemiologico-covid-19/) on Aug 30.

However, I can't find any of these numbers in that report.  All I know for certain is that there is a contradiction between your numbers and the headlines in the local press, and that it seems unlikely that delta proportion would actually decrease.

So I think you have a problem, but I am not sure what the fix is.  The source of the low (likely incorrect) value was https://github.com/owid/covid-19-data/commit/2e9f605dbb12eaab4d757f4973083ba58d2bce0f#diff-20fc1df8246274a8eeb5aaefc60cc39e56ddff635e9e2e63f63ee3b41afec9fcR7190

Thanks for all the good work,
Andrew

**Comment by lucasrodes** [comment]
Hi @andrewcooke-isti,
Thanks for your raising this.

We source variants data from GISAID, via https://covariants.org/. From the available data, it seems that the number of sequenced samples in the last update is significantly lower (43) compared to previous ones (of the order of 400). This may have lead to some bias in the percentages, but unsure at the moment.

Even though we have a threshold to only report figures when there are more than 30 sequenced samples (see [num_sequences_total_threshold](https://github.com/owid/covid-19-data/blob/b656c0997ee9b61fa4d530da3afbb36c27c253bf/scripts/src/cowidev/variants/etl.py#L55-L55)), some close to this threshold might still show some noisy behaviour.

**Comment by andrewcooke-isti** [comment]
Ah, OK.  So they on;y had one Delta detection in that bracket.  Noise makes sense.

The newspaper report I linked to, when I read it more carefully, seemed to be self-contradictory, while the main govt report is largely concerned with the distinction between community tests and arriving travellers.  So everything is very confused.

Anyway, feel free to close this.  If I find anything clearer I'll raise it upstream.

**Comment by lucasrodes** [comment]
Thanks!

**Comment by andrewcooke** [comment]
Just for the record this seems to have been fixed.  I still don't understand where the numbers are sourced (at the local gov level) but the current plot shows a steady rise, as expected.
