### ISSUE TITLE
Datasource for PCR-only tests in Portugal (DGS, somewhat like the CDC in Portugal)

### ISSUE THREAD

**Issue by SparkyCola** [owid/covid-19-data#192]
I was looking at the data and noticed that for portugal there's only PCR+Antigene Test data, but none for PCR-only tests while the national health authority ([DGS](https://en.wikipedia.org/wiki/Directorate-General_of_Health)) does provide it in their arcgis viewer on: [https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/](https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/). (Bottom right viewer, shows daily cases "Evolução de Casos Novos" per default, click through the options until you reach "Evolução diária de Testes PCR")

**Comment by edomt** [comment]
Hi @SparkyCola 
The reason we're now collecting PCR+antigen for Portugal is that the country is including both positive PCR _and_ antigen results in the COVID-19 case counts it reports on daily basis. Therefore, to calculate an accurate positive rate, we also need to include both types of tests as the denominator in our calculation.

**Comment by SparkyCola** [comment]
I see, thank you for the explanation, it does make sense. 
I just needed it because I wanted to compare the testing capabilities of Portugal with those of Germany, so I was looking for that data and found it, just wanted to let you know as I thought you might've not been aware of it.
