### ISSUE TITLE
which-vaccines-have-been-administered-in-each-country

### ISSUE THREAD

**Issue by springcomp** [owid/covid-19-data#1924]
The following link breaksdown vaccination data per country and per vaccine type.
https://ourworldindata.org/covid-vaccinations#which-vaccines-have-been-administered-in-each-country

However, it only includes a very small subset of all countries.
Where can we find the data for other countries ?

**Comment by lucasrodes** [comment]
Hi, @springcomp,
Thanks for your message!

We currently report data on vaccination data broken down by vaccine type from a limited number of countries. We usually source this data from government sites, but also from organisations such as the ECDC (https://www.ecdc.europa.eu/en/publications-data/data-covid-19-vaccination-eu-eea) for most European countries.

Whenever possible (i.e. availability of public data on this and team resources) we add new countries to this dataset.

Kind regards
