### ISSUE TITLE
Is there a way to access covid-19 "Recoveries" time series data?

### ISSUE THREAD

**Issue by KelumPerera** [owid/covid-19-data#1926]
I referred CSSE recoveries time series dataset. But it is not updated anymore after 04th August.

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv

Is there any other way to find out this data from 04th August onwards?

Appreciate your inputs

**Comment by lucasrodes** [comment]
Hi @KelumPerera,
Thanks for your message.

We are currently not tracking _recoveries_. Hence I would suggest you post this question in https://github.com/CSSEGISandData/COVID-19/.
