### ISSUE TITLE
Italian numbers do not match

### ISSUE THREAD

**Issue by udedomenico** [owid/covid-19-data#1930]
It seems that your total number of population over 12 is incorrect.
In fact look at the percentage you provide and then compare it to the official WEB Site of the italian government.

62% Fully vaccinated as per your WEB Site:
[(https://ourworldindata.org/covid-vaccinations?country=~ITA)]

71,82 % Fully vaccinated as per Italian Official WEB page:
[(https://www.governo.it/it/cscovid19/report-vaccini/)]

Since the data is the same, that is very likely due to the denominator of your formula (that is the total number of Italians over 12).

**Comment by lucasrodes** [comment]
Hi @udedomenico,
Our per-capita metrics are relative to the **whole** population. Hence, the percentages might be lower than from sources using a population subset to obtain these metrics.
