### ISSUE TITLE
Latest China data on 2021-09-06

### ISSUE THREAD

**Issue by aywi** [owid/covid-19-data#1935]
Source: `截至9月6日，全国累计报告接种新冠病毒疫苗21亿1308.3万剂次，完成全程接种的人数为9亿6972万人。`\
`疫苗接种总人数达到109500万，覆盖全国总人口的77.6%，完成全程接种的有96972万人。`\
(from <http://www.nhc.gov.cn/xcs/s3574/202109/8b207c33c04145e4942ff946b53adc7c.shtml>)

Translation: `As of September 6, a total of 2113.083 million vaccinations of the COVID-19 vaccine have been reported nationwide, and the number of people fully vaccinated is 969.72 million.`\
`The total number of people vaccinated reached 1095 million, covering 77.6% of the country's total population. 969.72 million people have been fully vaccinated.`

Summary:
| location |    date    | total_vaccinations | people_vaccinated | people_fully_vaccinated |
| :------: | :--------: | -----------------: | ----------------: | ----------------------: |
|  China   | 2021-06-10 |          845299000 |         622000000 |                         |
|  China   | 2021-08-12 |         1832450000 |                   |               777046000 |
|  China   | 2021-08-26 |         2003914000 |        1072500000 |               889439000 |
|  China   | 2021-09-06 |         2113083000 |        1095000000 |               969720000 |

**Comment by aywi** [comment]
Close this one in favor of <https://github.com/owid/covid-19-data/issues/230#issuecomment-914423532>.

**Comment by lucasrodes** [comment]
Thanks
