### ISSUE TITLE
Just an FYI - Vaccine Data from Peru (MINSA) is not been updated consistently

### ISSUE THREAD

**Issue by jmcastagnetto** [owid/covid-19-data#1937]
Currently there are two equally official sources for the raw data:

1) https://www.datosabiertos.gob.pe/dataset/vacunaci%C3%B3n-contra-covid-19-ministerio-de-salud-minsa (since April 2021)

2) https://www.datosabiertos.gob.pe/dataset/vacunacion (since the latter part of August 2021)

The second one has been updated regularly, but since Sept 04, it has not changed; and the first one seems to have incomplete data for dates up to Sept 06.

I am asking people at MINSA to see what is happening. Meanwhile the data from my repo cannot be updated until I get some more clarity on the situation. 

Will let you know when I get more details.

@lucasrodes

**Comment by lucasrodes** [comment]
Thanks for letting us know, @jmcastagnetto.
Hopefully, MINSA clarifies on this matter soon.

Kind regards

**Comment by jmcastagnetto** [comment]
@lucasrodes, today's data from MINSA seems to be consistent (had done a quick check only). They have changed the structure of the source, but the total count of entries seem to match the number published yesterday by MINSA (~20.2M dosis, https://twitter.com/Minsa_Peru/status/1435751892064391170)

I've updated my code and generated the summary data you use in my repo.

**Comment by lucasrodes** [comment]
Thank you very much, @jmcastagnetto! This helps us a lot.
