### ISSUE TITLE
South Africa - Vaccination Data needs updating

### ISSUE THREAD

**Issue by krugazul** [owid/covid-19-data#1938]
Hi 

The vaccination data for South Africa is over 3 days old, and needs updating please.   These are the updated values as of the SA Corona virus site - https://sacoronavirus.co.za/latest-vaccine-statistics/

Date = 17:00 - 7 September 2021
total_vaccinations = 13892301
people_vaccinated = Not Available
people_fully_vaccinated = 10218914

**Comment by lucasrodes** [comment]
Thanks. 

FYI, `people_vaccinated` can be obtained by adding the first doses of Pfizer/BioNTech and J&J doses.
