### ISSUE TITLE
Algeria is using jonhson & jonhson vaccine

### ISSUE THREAD

**Issue by yasserkaddour** [owid/covid-19-data#1939]
Hi everyone,
Algeria has received 604,800 doses of the Janssen vaccine from the USA.

Sources:
https://www.aps.dz/sante-science-technologie/126613-covid-19-reception-d-un-don-des-etats-unis-de-604-800-doses-du-vaccin-johnson-johnson
https://www.france24.com/en/live-news/20210826-us-ships-more-than-2-mln-more-covid-vaccines-to-africa

Keep up the good work!

**Comment by lucasrodes** [comment]
Thanks.

Should be reported by the WHO in their next update (we use WHO as our data source for Algeria).
