### ISSUE TITLE
ECDC report ventilator use for ICU utilization in Hungary

### ISSUE THREAD

**Issue by laszlosandor** [owid/covid-19-data#194]
You are not the source but you show numbers for Hungary without any caveat. Hungary reports a daily count of ventilated Covid-19 cases, but not a count for those admitted to the ICU. The ECDC simply mislabels this data as the (otherwise missing) ICU headcount for Hungary.

If you wanted to, you might report an estimate for the discrepancy. A Hungarian cabinet minister blurted out today that the actual ICU headcount was 961, exactly (suspiciously?) 50% more than the reported 640 on ventilators. Your ICU numbers for Hungary could be 50% higher, at least for the fall.

**Comment by laszlosandor** [comment]
Also note that Viktor Orbán revealed this morning that there are 2000 more suspected cases hospitalized than the officially reported number of verified cases. (As severe cases are unlikely too produce false negatives, this also shows huge lags and gaps in the Hungarian testing regimen.) As the ECDC reports no verified influenza in any European hospital, and Hungary reports no verified flu anywhere, these suspected cases are very likely to be Covid patients indeed, so you might seriously consider adjusting (or labeling) the series for Hungary. Orbán talked about around 9500 patients in hospital as of this Friday morning, Nov 27, and he expects the count to breach 10000 imminently.

**Comment by edomt** [comment]
Hi @laszlosandor 

Thank you for notifying us. Do you have a source we could use a reference for this? (e.g. one of these daily reports of ventilated cases)

If needed we can add annotations to our charts so that the time series for Hungary in the ICU data says that the number actually represents ventilated patients.

**Comment by laszlosandor** [comment]
Thanks. There is no direct acknowledgement of the discrepancy (eg, on the ECDC website), but you can cross-check for yourself by looking at the latest ECDC-reported "hospitalizations" and the rudimentary but official government website (with Google Translate):

https://koronavirus.gov.hu/cikkek/5595-fovel-emelkedett-beazonositott-fertozottek-szama-es-elhunyt-151-beteg

Eg, 666 people on ventilators today.

**Comment by edomt** [comment]
Thanks @laszlosandor. We've now added an annotation on our charts: ![covid-icu-patients-per-million](https://user-images.githubusercontent.com/7103774/100917123-0582c000-34d7-11eb-937e-72bc813656f0.png)
