### ISSUE TITLE
Test data: Vietnam (3)

### ISSUE THREAD

**Issue by Ltn123456** [owid/covid-19-data#1940]
19/7 https://luatvietnam.vn/y-te/bao-cao-1091-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-cong-tac-phong-chong-dich-206047-d6.html 7,243,966 

20/7 https://luatvietnam.vn/y-te/bao-cao-1088-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-206003-d6.html 7,336,333 

21/7 https://luatvietnam.vn/y-te/bao-cao-1094-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-206048-d6.html 7,486,705 

22/7 https://luatvietnam.vn/y-te/bao-cao-1100-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-cong-tac-phong-chong-dich-206216-d6.html 7,588,707 

23/7 https://luatvietnam.vn/y-te/bao-cao-1106-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-206224-d6.html 7,687,680 

24/7 https://luatvietnam.vn/y-te/bao-cao-1107-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-206223-d6.html 7,846,017 

 

1/8 https://luatvietnam.vn/y-te/bao-cao-1142-bc-byt-206755-d6.html 8,738,745 

2/8 https://luatvietnam.vn/y-te/bao-cao-1146-bc-byt-206807-d6.html 8,864,535 

 

4/8 https://luatvietnam.vn/y-te/bao-cao-1154-bc-byt-207013-d6.html 9,131,621 

5/8 https://luatvietnam.vn/y-te/bao-cao-1160-bc-byt-bo-y-te-207077-d6.html 9,228,420 

6/8 https://luatvietnam.vn/y-te/bao-cao-1163-bc-byt-207115-d6.html 9,399,692 

 

8/8 https://luatvietnam.vn/y-te/bao-cao-1184-bc-byt-ket-qua-phong-chong-dich-tinh-den-17h00-ngay-09-8-2021-207245-d6.html 9,541,771 

9/8 https://luatvietnam.vn/y-te/bao-cao-1188-bc-byt-tinh-hinh-va-ket-qua-phong-chong-dich-covid-19-207286-d6.html 9,644,837 

10/8 https://luatvietnam.vn/y-te/bao-cao-1192-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-cong-tac-phong-chong-dich-207382-d6.html 9,819,987 

11/8 https://luatvietnam.vn/y-te/bao-cao-1194-bc-byt-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-tinh-den-17h-ngay-12-8-2021-207496-d6.html 9,979,014 

12/8 https://luatvietnam.vn/y-te/bao-cao-1201-bc-byt-2021-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-207592-d6.html 10,108,360 

13/8 https://luatvietnam.vn/y-te/bao-cao-1202-bc-byt-207593-d6.html 10,257,476 

14/8 https://luatvietnam.vn/y-te/bao-cao-1204-bc-byt-2021-ve-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-tinh-den-17h-ngay-15-8-2021-207611-d6.html 10,415,073 

 

16/8 https://luatvietnam.vn/y-te/bao-cao-1214-bc-byt-2021-ve-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-tinh-den-17h-ngay-17-8-2021-207773-d6.html 10,730,443 

17/8 https://luatvietnam.vn/y-te/bao-cao-1217-bc-byt-207842-d6.html 10,939,961 

18/8 https://luatvietnam.vn/y-te/bao-cao-1222-bc-byt-bo-y-te-207896-d6.html 11,140,662 

19/8 https://luatvietnam.vn/y-te/cong-van-1228-bc-byt-2021-ket-qua-cac-bien-phap-trien-khai-cong-tac-phong-chong-dich-207982-d6.html 11,321,808 

20/8 https://luatvietnam.vn/y-te/bao-cao-1234-bc-byt-2021-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-208040-d6.html 11,533,345 

 

22/8 https://luatvietnam.vn/y-te/bao-cao-1241-bc-byt-2021-ve-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-208121-d6.html 11,985,000 

23/8 https://luatvietnam.vn/y-te/bao-cao-1256-bc-byt-2021-ve-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-208179-d6.html 12,002,418 

24/8 https://luatvietnam.vn/y-te/bao-cao-1263-bc-byt-2021-ve-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-208280-d6.html 13,016,830 

25/8 https://luatvietnam.vn/y-te/bao-cao-1269-bc-byt-2021-ve-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-208344-d6.html 13,328,775 

26/8 https://luatvietnam.vn/y-te/bao-cao-1279-bc-byt-2021-tinh-hinh-dich-covid-19-va-ket-qua-cong-tac-phong-chong-dich-208486-d6.html 13,550,586 

27/8 https://luatvietnam.vn/y-te/bao-cao-1280-bc-byt-2021-tinh-hinh-dich-covid-19-va-cong-tac-phong-chong-dich-208469-d6.html 13,682,778 

28/8 https://luatvietnam.vn/y-te/bao-cao-1283-bc-byt-2021-ve-tinh-hinh-dich-covid-19-va-ket-qua-phong-chong-dich-tinh-den-17h-ngay-29-8-2021-208507-d6.html  13,883,618 

29/8 https://luatvietnam.vn/y-te/bao-cao-1291-bc-byt-bo-y-te-208550-d6.html 14,054,969 

30/8 https://luatvietnam.vn/y-te/cong-van-1301-bc-byt-bo-y-te-208642-d6.html 14,332,918 

31/8 https://luatvietnam.vn/y-te/bao-cao-1306-bc-byt-208693-d6.html 14,804,211 

1/9 https://luatvietnam.vn/y-te/bao-cao-1308-bc-byt-2021-tinh-hinh-dich-covid-19-va-ket-qua-cong-tac-phong-chong-dich-208708-d6.html 15,201,879

**Comment by Ltn123456** [comment]
I wonder why #1589 and #1734 have not been added to your testing dataset.

**Comment by camappel** [comment]
The missing dates will be included in the next update. Thanks again for you contributions!

**Comment by camappel** [comment]
Closing this issue; thanks again for your help
