### ISSUE TITLE
Malaysia new COVID-19 Data

### ISSUE THREAD

**Issue by samleong123** [owid/covid-19-data#1946]
Malaysia government has launched a new website for COVID-19 :
https://covidnow.moh.gov.my 

and also more datasets under @MoH-Malaysia covid19-public/epidermic 
https://github.com/MoH-Malaysia/covid19-public/tree/main/epidemic
Including but not limited to :
1. ICU Beds / Ventilators Details
2. Hospital Details
3. COVID-19 Quarantine and Treatment Centre Details 
4. Cases and Testing

All of the data above exclude Cases and Testing will be updated daily by 0200 UTC+8
At least twice weekly for Cases and Testing

and also vaccines types datasets are available under @CITF-Malaysia  CITF-Public/vaccination
https://github.com/CITF-Malaysia/citf-public/tree/main/vaccination
1. Pfizer
2. Sinovac
3. AstraZeneca
4. Cansino

Hopefully, these datasets can increase the efficiency of data update for Malaysia on Our World In Data's Database.

**Comment by lucasrodes** [comment]
Hi @samleong123,
Thanks for your report.

- Testing: We are already using the mentioned source. You can check this in [this script](https://github.com/owid/covid-19-data/blob/066760082cd6e415845b3a5a1f319c600ac40c8b/scripts/scripts/testing/automations/batch/malaysia.py).
- Cases/Deaths: We currently use JHU's data. You can check this in [this script](https://github.com/owid/covid-19-data/blob/d9e92f02828a7eac2176a1f85bcda73dab533a7c/scripts/scripts/jhu.py).
- Vaccinations: We are currently using https://github.com/CITF-Malaysia/citf-public/tree/main/vaccination for our vaccinations dataset. You can check the details in [this script](https://github.com/owid/covid-19-data/blob/e53dfc088886b8e8174c55f96b4038f3c9449928/scripts/src/cowidev/vax/batch/malaysia.py).

As per hospitalizations, we will explore the source you provided and see if it matches our current formatting.


Thanks for reporting all this information,
Kind regards
