### ISSUE TITLE
Data for total_vaccinations for world not updated?

### ISSUE THREAD

**Issue by fibke** [owid/covid-19-data#1947]
It seems the OWID COVID data set updated today for countries. The latest data point is 2021/09/08.

However for total_vaccinations at the global level it shows NA (unlike all previous updates).

Is there an issue with the aggregation? An error?

**Comment by lucasrodes** [comment]
Thanks for the report, @fibke.
The update is coming with a bit of delay today. Working on it at the moment!

**Comment by lucasrodes** [comment]
Updated
