### ISSUE TITLE
Strange update of the vaccination data in Seychelles

### ISSUE THREAD

**Issue by matthias-wyss** [owid/covid-19-data#1955]
Hello,
I noticed a strange update of the vaccination data in Seychelles. This source (https://africacdc.org/covid-19-vaccination/) indicates 139,625 people vaccinated on 2021-09-09, but the previous one (https://en.itoma.io/covid-19/) has indicated 73,777 people vaccinated on 2021-08-09. It is a problem because the population of Seychelles barely reaches 100,000 people, and the overall statistics looks weird with 141% for this country. The previous source (https://en.itoma.io/covid-19/) indicates now on 2021-09-06, 74,719 people vaccinated, which seems more realistic.

**Comment by lucasrodes** [comment]
Thanks @matthias-wyss,
We have switched to https://en.itome.oi/covid-19 source. Planning on automating this soon.

Thanks for your help!
