### ISSUE TITLE
Gibraltar vaccinations per hundred included records greater than 100

### ISSUE THREAD

**Issue by notpeerreviewed** [owid/covid-19-data#1957]
Some records from Gibraltar include data that shows vaccinations per hundred people as being higher than 100. It looks like this only relates to records from Gibraltar.

**Comment by edomt** [comment]
Hi @notpeerreviewed 

See our [FAQ](https://ourworldindata.org/covid-vaccinations#frequently-asked-questions):

> ### Can the value of per-capita metrics exceed 100%?
> The population estimates we use to calculate per-capita metrics are all based on the last revision of the United Nations World Population Prospects. The United Nations estimates may not always reflect the latest censuses or national figures. Additionally, it’s important to bear in mind that in some territories, vaccination coverage may include non-residents (such as tourists and foreign workers). For these reasons, per-capita metrics may sometimes exceed 100%.
