### ISSUE TITLE
South Korea 2021-09-04, 2021-09-05 new case number wrong

### ISSUE THREAD

**Issue by WWolf** [owid/covid-19-data#1958]
Hi,

Based on the official records from South Korea, new cases 2021-09-04 (1,490) and 2021-09-05 (1,375) records are aggregated together as 2,865 on 2021-09-05 in the OWID dataset.

Original raw data published by the Ministry of Health and Welfare:

http://ncov.mohw.go.kr/board/doFileDownload.do?file_name=%EC%BD%94%EB%A1%9C%EB%82%98%EB%B0%94%EC%9D%B4%EB%9F%AC%EC%8A%A4%EA%B0%90%EC%97%BC%EC%A6%9D-19_%ED%99%95%EC%A7%84%ED%99%98%EC%9E%90_%EB%B0%9C%EC%83%9D%ED%98%84%ED%99%A9_210912.xlsx&file_path=/upload/ncov/file/202109/1631406000751_20210912092000.xlsx

What is the process of the correction of the raw dataset?

**Comment by WWolf** [comment]
PS This error seems to have arisen from the JHU dataset: https://github.com/CSSEGISandData/COVID-19/issues/4637#issue-994289625

**Comment by edomt** [comment]
Hi @WWolf 

As you noticed, we source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues
