### ISSUE TITLE
Israel data not corrected

### ISSUE THREAD

**Issue by yuval-harpaz** [owid/covid-19-data#196]
Israel's ministry of health (MOH) publishes data daily in a dashboard. The history is corrected all the time. OWID deaths for Israel seem not to consider these corrections. It is possible to pull the corrected data with a curl command from the dashboard. I'd like to help making OWID data for Israel up-to-date
![image](https://user-images.githubusercontent.com/445416/100535515-59b14a00-3222-11eb-9d9f-790ed8b78f46.png)

**Comment by edomt** [comment]
We are switching today to Johns Hopkins data, which should correct this issue.

**Comment by yuval-harpaz** [comment]
if their source is [csse_covid_19_time_series](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) then they have the same spiky data, raw realtime data with no corrections. Is there a clearer data source for Hohns Hopkins?
![image](https://user-images.githubusercontent.com/445416/100588326-6608d600-32fa-11eb-91cc-390936dcce82.png)

**Comment by edomt** [comment]
There might be a clearer source for Israel specifically, but our system cannot handle country-specific imports (there would be too many countries and sources for our small team to manage).

**Comment by edomt** [comment]
If you want to smooth the data, your best bet is probably to suggest the change directly in the Johns Hopkins repository.

**Comment by yuval-harpaz** [comment]
okay, thanks

**Comment by yuval-harpaz** [comment]
If you ever reconsider, I volunteer to do the maintenance for Israel. I don't mind taking other countries as well.
