### ISSUE TITLE
Bosnia and Herzegovina missing test results data for 07.2020 - 08.2021

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#1960]
In `owid-covid-data.csv` Bosnia and Herzegovina recently has lost most of its records in `new_tests` and `new_tests_smoothed` columns for 08.2020 - 07.2021. Those data were in place only few weeks ago (at least around 21.08.2021). Why were they removed?

**Comment by edomt** [comment]
Thank you @czka - this is now fixed.
