### ISSUE TITLE
Slovakia lockdown stringency data gap

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#1961]
In Slovakia's `owid-covid-data.csv` there's a gap in `stringency_index` record at 2021-08-06 - 2021-08-16.

**Comment by edomt** [comment]
Hi @czka 

The data presented on cOVID policies is taken directly from the OxCGRT project; Our World in Data do not track policy responses ourselves, and do not make additions to the tracker dataset.

These charts are regularly updated based on the latest version of the response tracker.

OxCGRT is an ongoing collation project of live data. If you see any inaccuracies in the underlying data, or for specific feedback on the analysis or another aspect of the project, please contact OxCGRT team: https://forms.office.com/Pages/ResponsePage.aspx?id=G96VzPWXk0-0uv5ouFLPkVPwT6t5-mtCnZ6_s5yQ4ppUME9NOUtYRkxLVldLUVFERTRTMEJSRkZITC4u
