### ISSUE TITLE
Luxembourg fully_vaccinated 

### ISSUE THREAD

**Issue by jarnold231** [owid/covid-19-data#1963]
fully_vaccinated data for Luxembourg has been retrospectively removed. Last week there was an entry for September 6, but all information for August/September is removed in the latest update.

**Comment by edomt** [comment]
Hi @jarnold231 
We've realized this morning that Luxembourg has been using the J&J vaccine since April, which, as far as we can see, makes it impossible to calculate `people_fully_vaccinated` based on the available data.
