### ISSUE TITLE
Luxembourg's people_fully_vaccinated data has been cut off at 2021-04-13 recently 

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#1965]
In https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv the last record in Luxembourg's `people_fully_vaccinated` column is now at 2021-04-13.

Those data were in place only few weeks ago, until Sat Aug 21 at least.

(This issue reminds me off https://github.com/owid/covid-19-data/issues/1921.)

**Comment by edomt** [comment]
see #1963
