### ISSUE TITLE
Add Singapore ICU and Hospitalization Data

### ISSUE THREAD

**Issue by LuminousXLB** [owid/covid-19-data#1970]
Thanks for the fantastic project. I'm surprised to find that the ICU and Hospitalization data of Singapore is not included.
There's an official dashboard https://covidsitrep.moh.gov.sg/ where they publish the whole time series _In ICU_ and _In General Ward_ data (in JSON format at backend) under the _Case Status_ tab.
Hope to see that these data can be included in this project.

Thanks

**Comment by lucasrodes** [comment]
Thanks, @LuminousXLB,
We have added ICU values in c62e4940fcf8a3ef1cb11241513759f4fec0e978

**Comment by LuminousXLB** [comment]
Hi @lucasrodes . Thanks for your work, but the data looks strange.

![coronavirus-data-explorer](https://user-images.githubusercontent.com/23524048/133886890-cd4ba5f0-0b8e-49e0-8e39-8565922da08a.png)

From Sept 7 to Sept 8, the ICU patients drops from 528 to 215. But in the official dashboard, There're only 6 patients in ICU on both Sept 7 and Sept 8.

**Comment by edomt** [comment]
Thank you! Fixed in 4d4894df7276db2630a30761d791ae02eff40106
