### ISSUE TITLE
Add Morocco vaccination source

### ISSUE THREAD

**Issue by driss14** [owid/covid-19-data#1971]
The used link is not updated. 
Use instead this link:
http://www.covidmaroc.ma/Pages/AccueilAR.aspx

**Comment by edomt** [comment]
Hi @driss14 

This link to an error: 
![image](https://user-images.githubusercontent.com/7103774/133751888-0334e896-7121-45e8-8275-f6265c5cf10e.png)

(Possibly it's only accessible from inside Morocco.)
