### ISSUE TITLE
@unguaio Please make sure to take into account our multiple replies about countries already being automated. Your other contributions are very useful, but flagging data that our system will automatically collect adds unnecessary work to our team (as we repeatedly check whether we've forgotten to add these countries to our automation lists).

### ISSUE THREAD

**Issue by unguaio** [owid/covid-19-data#1972]
Yes you're right, I understand the problem and I'm sorry to annoy you with the problem, but I just check and compare your data about total administered doses with the ones in those site, like the African one, and about some countries like Lesotho, Eswatini and Burkina Faso, somehow I cannot either explain, even if they are already automated they show more updated data (aka wider number about total administered doses) --> Our world in data shows a total of 210277 administered doses for Eswatini, 201795 for Lesotho and 166160 for Burkina Faso, while https://africacdc.org/covid-19-vaccination/ reports 279133 for Eswatini, 274415 for Lesotho and 180427 for Burkina Faso, just why if they are already automated?
So, again, I am sorry for boring you with the question, but everytime I just check and compare if those sources show more updated data and report it even if I cannot understand while few countries, already considered as automated for that source, are not really updated automathically! Thank you again for you great work!!

**Comment by edomt** [comment]
Hi @unguaio 

Given that this collection is automated, if these new records don't make it to our output data, that means something else is wrong. There are multiple checks that are performed against the data to make sure it should be imported. In the case of Eswatini, the current data from AfricaCDC shows this:

```
   ADM0_SOVRN ISO_3_CODE  TotAmtAdmi  VacAd1Dose  VacAd2Dose  FullyVacc          VaccApprov
24   Eswatini        SWZ      279133       96175      182958     182958  AstraZeneca    J&J
```

This data doesn't make sense, as it's impossible to have 182,958 fully vaccinated people and only 96,175 people with a first dose.
