### ISSUE TITLE
Data showing as NaN

### ISSUE THREAD

**Issue by tarek-bakri** [owid/covid-19-data#1977]
Hi, the last update was 5hrs ago, and when I checked the data this morning the last date on the dataset file after the update for most is 17/9/21 and is showing  NaN values  for total and new cases/deaths from many countries like Australia and Israel on owid covid-19 dataset.

**Comment by edomt** [comment]
Hi @tarek-bakri 

Yes, that is because the corresponding data had not been published yet by https://github.com/CSSEGISandData/COVID-19/
This is no longer the case.
