### ISSUE TITLE
Subsequent total people_vaccinated count decreases for the state of Ohio.

### ISSUE THREAD

**Issue by tushartify** [owid/covid-19-data#1978]
Count of people partially vaccinated is decreased in the feed from 6254489 on 15 Sept, 2021 to 6240244 on 16 Sept, 2021 6249380 on 17 Sept, 2021 for the US state of Ohio which is unusual as this count should either be static or increase.

https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/us_state_vaccinations.csv

**Comment by edomt** [comment]
Hi @tushartify 

This data comes directly from the US CDC. See #698 for a previous case of this happening. Most likely this means the CDC (or Ohio) made a correction to their data, resulting in a total number of people vaccinated lower than previously thought.
