### ISSUE TITLE
UK Boosters

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#1982]
Just a query and this may not be your end. The UK started boosters a few days ago but nothing is reported in the Country CSV file. Not sure where you get it from but maybe the UK has put this info in a different place to what your script thinks? Maybe UK have not reported it in which case close this. Thanks for all your hard work.

**Comment by edomt** [comment]
Hi @zizwiz 
At this stage, it doesn't seem like any booster data is available in the official UK API.
