### ISSUE TITLE
Problem with Serbia entries ?

### ISSUE THREAD

**Issue by odadoun** [owid/covid-19-data#1984]
Hi,

for instance if you take the first entry 
> SRB,Europe,Serbia,2020-02-26,,,,,,,,,,,,,,,,,,,,,,,16.0,0.002,,,,,,people tested,,,,,,,,,,,,13.89,6804596.0,80.291,41.2,17.366,,14048.881,,439.415,10.08,37.7,40.2,97.719,5.609,76.0,0.806,

As you can see there is this string 'people tested' while it should be empty or a digit format .
Can you confirm there is a problem with this country?
By advance thank you
Regards
Olivier

**Comment by edomt** [comment]
Hi @odadoun 

Please see our codebook: https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-codebook.csv#L35

This field is `tests_units`: Units used by the location to report its testing data. So it is expected that this should be a string.
