### ISSUE TITLE
Clarification on method used to estimate reproduction rate

### ISSUE THREAD

**Issue by guidocioni** [owid/covid-19-data#199]
I just realized that you added a new column `reproduction_rate` in the dataset. In the data description it just says "Real-time estimate of the effective reproduction rate (R) of COVID-19". Can you please clarify how you computed this parameter as there are many different methods out there? Thanks

**Comment by edomt** [comment]
Hi @guidocioni 

Maybe you've missed it but there is a 3rd column in [the codebook](https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-codebook.csv) (but you have to scroll all the way to the right to see it if you're browsing the file on GitHub), with the source of each variable. For `reproduction_rate` the source is Arroyo Marioli et al. (2020). https://doi.org/10.2139/ssrn.3581633

Answers to frequently-asked questions are made available by the authors here: http://trackingr-env.eba-9muars8y.us-east-2.elasticbeanstalk.com/FAQ

**Comment by guidocioni** [comment]
Ups sorry, you're right, I missed the last column on the right. thanks for the clarification
