### ISSUE TITLE
Chronological data?

### ISSUE THREAD

**Issue by bruc314** [owid/covid-19-data#20]
Hi, It would be super useful to have historical data over time in addition to the current cumulative number plus daily change. Not sure if you have that data or not but it would be very powerful.  Thanks!

**Comment by edomt** [comment]
Hi @bruc314 

Is your question about testing data? If so, the file located at https://github.com/owid/covid-19-data/blob/master/public/data/testing/covid-testing-all-observations.csv contains all historical data for each country (cumulative total on each day + daily change on the day), as well as those values per capita.

If your question was about cases/deaths, then the equivalent file is at https://github.com/owid/covid-19-data/blob/master/public/data/ecdc/full_data.csv

Edouard
