### ISSUE TITLE
Covid Data

### ISSUE THREAD

**Issue by AndyGibbsUK** [owid/covid-19-data#200]
Hello

We seem to have lost the HTML link to download the individual sheets for total_cases.csv and total_deaths.csv:

![image](https://user-images.githubusercontent.com/68012529/100620860-d32a6480-3316-11eb-9488-c897c46a9920.png)

Thanks

**Comment by edomt** [comment]
Dear @AndyGibbsUK 

You can find those files in the following directory: https://github.com/owid/covid-19-data/tree/master/public/data/jhu

The direct links to the files you mentioned are:
- https://github.com/owid/covid-19-data/raw/master/public/data/jhu/total_cases.csv
- https://github.com/owid/covid-19-data/raw/master/public/data/jhu/total_deaths.csv

Edouard

**Comment by AndyGibbsUK** [comment]
Thanks very much.

I have now read about the transition from ECDC to JHU so it makes sense.

Andy Gibbs

Email: Andy@broomeproductions.co.uk<mailto:Andy@broomeproductions.co.uk>

Mob +44 7710 140748           Tel +44 1294 829532

This email is intended only to be read or used by the addressee. It is confidential and may contain legally privileged information.
If you are not the intended recipient any use, distribution, disclosure or copying of this email is strictly prohibited.
If you have received this email in error please delete it.
Thank you.
