### ISSUE TITLE
Data for several Caribbean countries gone

### ISSUE THREAD

**Issue by EJeff1** [owid/covid-19-data#201]
When I updated the data today I realized that the data for several Caribbean countries was no longer available, for example, Anguilla, Aruba, Bermuda, British Virgin Islands, Cayman Islands Curacao and more. Curious as to whether or not this was intentional or a temporary mistake.

**Comment by edomt** [comment]
See https://github.com/owid/covid-19-data/issues/197.
Our previous source for confirmed cases and deaths, the European Centre for Disease Prevention and Control (ECDC), announced in November that it would switch from a daily to a weekly reporting schedule from December. Our World in Data therefore had to transition away from the ECDC as a source to continue to provide daily updates of confirmed cases and deaths.

From November 30 onwards, the data for confirmed cases and deaths presented on ourworldindata.org and available in our GitHub repository is sourced from the daily dataset provided by Johns Hopkins University.
This data, as you noted, does not include several Caribbean countries that the European CDC previously included.

The data last sourced from the ECDC remains available as an archive in the ecdc folder.

**Comment by PhillipNM** [comment]
I noticed on the John Hopkins data that these missing countries are in the Country_Region of the United Kingdom as a province_state, is it possible to break these out?

**Comment by edomt** [comment]
See https://github.com/owid/covid-19-data/issues/193

**Comment by PhillipNM** [comment]
Yes, thanks for this
