### ISSUE TITLE
Booster data for Lithuania

### ISSUE THREAD

**Issue by garas** [owid/covid-19-data#2025]
Lithuania had recently added booster dose data, but also changed data structure and script now fails to fetch data.

Manufacturer and dose number data now comes from 2 separate sources.

Manufacturer data:
- https://services3.arcgis.com/MF53hRPmwfLccHCj/ArcGIS/rest/services/covid_vaccinations_by_drug_name_new/FeatureServer/0/query
- where: `municipality_code='00' AND vaccine_name<>'visos'`
- fields: `date,vaccine_name,vaccines_used_day`

Dose data:
- https://services3.arcgis.com/MF53hRPmwfLccHCj/ArcGIS/rest/services/covid_vaccinations_chart_new/FeatureServer/0/query
- where: `municipality_code='00' AND vaccination_state<>'00visos'`
- fields: `date,vaccination_state,all_day`
- field `vaccination_state` will have one of: `01dalinai` - partially, `02pilnai` - fully, `03pakartotinai` - booster.

**Comment by edomt** [comment]
Thank you @garas, this is extremely useful!

**Comment by garas** [comment]
Count of fully vaccinated is decreased after person gets booster dose.

There are now more new boosters than new fully vaccinated, so count had started to decrease, and monotonic series function removed some of data.

People vaccinated = `00visos`
Fully vaccinated = `02pilnai` + `03pakartotinai` 
Boosters = `03pakartotinai`
