### ISSUE TITLE
Missing data for people_vaccinated and people_fully_vaccinated for Qatar

### ISSUE THREAD

**Issue by mkhanka** [owid/covid-19-data#2028]
For Qatar, data for data for people_vaccinated and people_fully_vaccinated is not available from 12th September onward. However, the total_vaccinations count is rising everyday. 

https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv.

Kindly take a look at the issue.

**Comment by edomt** [comment]
Hi @mkhanka 

That is the only data published by Qatar since that date: https://covid19.moph.gov.qa/EN/Pages/Vaccination-Program-Data.aspx
There's a "Percentage of total population to have received vaccine", but we need an absolute count to add to our data.
