### ISSUE TITLE
Variants duplicate for category 'others' and 'non_who'

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#2029]
I noticed that others and non_who have the same data for Djibouti and Togo, which cause the total share of sequences over 100%. Could you take a look them?
![image](https://user-images.githubusercontent.com/68354122/135277549-65cb900d-06f3-47d8-b0ad-7dbaba2feb6f.png)

**Comment by lucasrodes** [comment]
Hi @RuijingZ,
Thanks for your message.

There are two special values for the `variant` field: 

- "others": Includes all variants/mutations other than the ones specifically specified (i.e. not listed in [this table](https://covariants.org/variants)).
- "non_who": Includes all variants/mutations without a WHO label.

Note that "non_who" includes "others" and other variants, i.e. "others" is a subset of "non_who".  As a consequence, the sum of percentages of all categories will exceed 1. You can find [more details here](https://github.com/owid/covid-19-data/blob/master/public/data/variants/README.md).
