### ISSUE TITLE
One day difference in reporting between ECDC and JHU sources?

### ISSUE THREAD

**Issue by RoyceWHowland** [owid/covid-19-data#203]
Up until the Nov. 29 update, the main OWID dataset had full entries for all countries up through the date of the update. Starting yesterday (Nov. 30) with the data source switch swtich, very few countries have an entry on the date of the update. The few countries with an entry have case & death count data showing NA. Is there a date mapping difference going on between the ECDC and JHU sources?

**Comment by edomt** [comment]
Hi @RoyceWHowland 
Indeed, JHU and ECDC have different methods for date assignment in their dataset. JHU assigns each observation to the day of the official government report, while the ECDC sets it to the day when it collected the numbers in the morning.
So, for example, the French numbers reported by the government today (December 2) at 7pm will be reported by JHU as December 2, but as December 3 by the ECDC.
Edouard
