### ISSUE TITLE
Indonesia now using J&J vaccine following delivery from Netherlands

### ISSUE THREAD

**Issue by DrBazUK** [owid/covid-19-data#2032]
Hi gang,
my colleagues continue to find more vaccines in use from official sources.
here's the Indonesian government announcing the arrival of J&J vaccines:
[https://www.kemkes.go.id/article/view/21091100002/vaksin-johnson-johnson-tiba-di-indonesia.html](https://www.kemkes.go.id/article/view/21091100002/vaksin-johnson-johnson-tiba-di-indonesia.html)

Machine translated:
Johnson & Johnson Vaccine Arrives in Indonesia
Published On : Saturday, September 11, 2021 00:00:00, Read : 2,119 Times
Jakarta, September 11, 2021

The Indonesian government received the arrival of the Johnson & Johnson vaccine on Saturday (11/9). The vaccine is the result of cooperation with the Dutch government through a bilateral scheme.

"For the first time, Indonesia received the Johnson & Johnson vaccine amounting to 500 thousand doses," said the Deputy Minister of Health of the Republic of Indonesia, dr. Dante Saksono Harbuwono at a virtual press conference, Saturday (11/9).

In this initial stage, Johnson & Johnson vaccine will be distributed to agglomeration areas on the island of Java, where vaccination coverage is still low.

The Johnson & Johnson vaccine has obtained an emergency use permit or EUA (Emergency Use Authorization) from the POM on September 7, 2021 and will be used for the general public aged 18 years and over with a single dose of 0.5 ml.

And the link to the approval:
[https://pom.go.id/new/view/more/pers/622/SIARAN-PERS-Tambah-Pilihan-Jenis-Vaksin-COVID-19-di-Indonesia--Badan-POM-Terbitkan-EUA-untuk-Janssen-COVID-19-Vaccine-dan-Vaksin-Convidecia.html]
(https://pom.go.id/new/view/more/pers/622/SIARAN-PERS-Tambah-Pilihan-Jenis-Vaksin-COVID-19-di-Indonesia--Badan-POM-Terbitkan-EUA-untuk-Janssen-COVID-19-Vaccine-dan-Vaksin-Convidecia.html)

Have a good one,
Baz

**Comment by lucasrodes** [comment]
Now reporting the updated vaccines
