### ISSUE TITLE
Kosovo population

### ISSUE THREAD

**Issue by Nerdm** [owid/covid-19-data#2033]
I am not sure where you rely on your number for total population of Kosovo on 2020, but it seems off.

According to the World Bank the population (2020) is: 1,775,378 (https://data.worldbank.org/indicator/SP.POP.TOTL?name_desc=false&locations=XK) 

According to our National Statistics Office, estimated population for 2020 is: 1.798.188
https://ask.rks-gov.net/media/6222/vjetari-statistikor-2021f.pdf) (page 35 on the document)

**Comment by edomt** [comment]
Thank you - the population estimate came from the [CIA Facebook](https://www.cia.gov/the-world-factbook/countries/kosovo/), but we'll now use the World Bank estimate.
