### ISSUE TITLE
Tanzania breaks with months of silence and reports >24k cases to WHO

### ISSUE THREAD

**Issue by DrBazUK** [owid/covid-19-data#2034]
It would seem that WHO have received news of some 24,000 cases from Tanzania in recent days.
[https://covid19.who.int/table](https://covid19.who.int/table)
27 Sept 28,846
20 Sept 25,674
13 Sept 1,367
9 Aug - 6 Sept 1,367

I don't have a Government of Tanzania source for this data but wanted to make you aware of WHO reporting in case this can be factored in to your collections. I have also opened a ticket with JHU CSSE on their github for consideration of the same. [https://github.com/CSSEGISandData/COVID-19/issues/4715](https://github.com/CSSEGISandData/COVID-19/issues/4715)

Thanks in advance,
Barry.

**Comment by edomt** [comment]
Hi Barry!
Thanks for the notice. We won't add it separately on our side, so let's hope that JHU catches up and adds it :)
Ed
