### ISSUE TITLE
People fully vaccinated in Texas and US decreased in the last 2 days

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#2035]
People fully vaccinated in Texas and in US decreased in the last 2 days, which does not seem to be correct to a cumulative time series:

![image](https://user-images.githubusercontent.com/68354122/135656670-73bd84e7-b8a8-4454-9abe-f6370e2d5387.png)

The number used to be 185537270 for US and 15993914 for Texas on Sep 29 2021 in yesterday's release.

**Comment by lucasrodes** [comment]
Hi @RuijingZ,
We have fixed this by removing those entries for dates where the numbers were not showing monotonically increasing values. 

Thanks for raising this.
