### ISSUE TITLE
Where can I download data for case fatality rate of COVID-19 by age?

### ISSUE THREAD

**Issue by CholoTook** [owid/covid-19-data#204]
Hello,

I'm looking at the data you have collated here:
https://ourworldindata.org/mortality-risk-covid#case-fatality-rate-of-covid-19-by-age

Is that data set present in your public downloads?

I've been searching the README on this page:
https://github.com/owid/covid-19-data/tree/master/public/data/

but I don't see any reference to it.

I figure I can scrape the data from the PNG, but I'd rather not! ;-)

Many thanks,
Dan.

**Comment by edomt** [comment]
Hi Dan

This chart was made directly in Adobe Illustrator, so there's no underlying data anywhere in our database for it. The data was based on the number of confirmed cases and deaths in each age group as reported by national agencies. The figures came from the [Chinese Center for Disease Control and Prevention (CDC)](https://www.ncbi.nlm.nih.gov/pubmed/32064853?fbclid=IwAR3JCxH50VTfg3Q_02YTLdz2Tk7yBTmt-5oCxE4KlBe0evh7ByK3HPVU-pU) as of 17th February; [Spanish Ministry of Health](https://www.isciii.es/QueHacemos/Servicios/VigilanciaSaludPublicaRENAVE/EnfermedadesTransmisibles/Paginas/InformesCOVID-19.aspx) as of 24th March; [Korea Centers for Disease Control and Prevention (KCDC)](https://www.cdc.go.kr/board/board.es?mid=a30402000000&bid=0030) as of 24th March; and the Italian National Institute of Health, as presented in the [paper by Onder et al. (2020)](https://jamanetwork.com/journals/jama/fullarticle/2763667) as of 17th March.

And obviously one big caveat here is that this data was collected and analyzed very early in the pandemic—it's likely that the same protocols would find different results today.

Ed

**Comment by CholoTook** [comment]
Thanks Ed,

Perhaps the first step to getting updated data is to check the original data file into Git?

I was able to recreate your plot here:
https://github.com/Geromics/covcheck/blob/main/stats/test.r#L51

which may or may not be useful :-)


Many thanks,
Dan.
