### ISSUE TITLE
Irregular Vaccination feed for Uzbekistan

### ISSUE THREAD

**Issue by nickybisht** [owid/covid-19-data#2048]
We are not getting regular updated data for partially and fully vaccinated count on feed for Uzbekistan while official sources provides complete data for partial and fully vaccinated count on daily basis till 28 Sept.

https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv

For eg: partially and fully vaccinated count missing for 22 Sep - 27 Sep

Official source: https://coronavirus.uz/uz/lists/index/3/12

**Comment by lucasrodes** [comment]
Hi @nickybisht,
Thank you for reporting this.

We will be adding this data source for Uzbekistan. Data should be online in the next 24h.
