### ISSUE TITLE
Aruba is missing 

### ISSUE THREAD

**Issue by joselsalmeron** [owid/covid-19-data#205]
Thanks for the awesome effort to collect all these relevant data to one dataset.

Aruba is missing from data, is there a specific reason for that?

**Comment by DrBazUK** [comment]
Hi Jose,
It seems that the shift to Johns Hopkins as the source has removed all the dependent territories from the main time series data.

Previously, the following list were available from ECDC or others:

American Samoa
Anguilla
Aruba
Bermuda
Bonaire Sint Eustatius and Saba
British Virgin Islands
Cayman Islands
Curacao
Falkland Islands
Faroe Islands
French Polynesia
Gibraltar
Greenland
Guam
Guernsey
Isle of Man
Jersey
Montserrat
New Caledonia
Northern Mariana Islands
Puerto Rico
Samoa
Sint Maarten
Turks and Caicos
United States Virgin Islands
Wallis and Futuna

Most of these *are* available in the time series from CSSE but they are not recognised as being "independent"...
The US dependent territories (Puerto Rico, Guam, US Virgin Islands, Northern Mariana Islands) are in the US time series data from CSSE.

Team - are there any plans to "fix" this and reinstate the above territories to the OWID dataset?

Many thanks in advance,
Baz

**Comment by edomt** [comment]
Hi @joselsalmeron 
As described by @DrBazUK this is indeed something we're working on—see #193
