### ISSUE TITLE
Swedish split vaccination reporting ... again

### ISSUE THREAD

**Issue by limbero** [owid/covid-19-data#2075]
12-15 year olds are in their own table at https://www.fohm.se/folkhalsorapportering-statistik/statistikdatabaser-och-visualisering/vaccinationsstatistik/statistik-for-vaccination-mot-covid-19/, Table 3. Also looks like a layout one can expect to change multiple times, since it doesn't include dose 2 yet.

**Comment by limbero** [comment]
@lucasrodes this appears to be fixed? very hard to tell because the raw data is what it is

**Comment by lucasrodes** [comment]
Hi @limbero,
Sorry for the delay in the response.

It seems that now there is just one table at https://www.fohm.se/folkhalsorapportering-statistik/statistikdatabaser-och-visualisering/vaccinationsstatistik/statistik-for-vaccination-mot-covid-19, with data for all ages eligible for vaccination.

Our data combines this table with historical weekly data, available under the _Ladda ner data_ section as an xlsx file.

Data for Sweden should be consistent now. 

Thanks for your feedback!
