### ISSUE TITLE
Puerto Rico Missing

### ISSUE THREAD

**Issue by bramsay8** [owid/covid-19-data#208]
Can no longer find data for Puerto Rico since 11/18/2020

**Comment by DrBazUK** [comment]
Hi @bramsay8 this is down to the change in source from ECDC to JHU which doesn't treat dependent territories as unique locations but rather places them as "provinces or states" under their respective country. See issue #193 for more information about the planned changes.

NB I'm not a developer within the team but have seen similar changes to about 26 locations which JHU treat as dependencies... There are plans to change this in future, assuming that the OWID team can resolve the conflicts...

Best regards,
Baz
