### ISSUE TITLE
Add Malaysia hospital and ICU data

### ISSUE THREAD

**Issue by jlwj51** [owid/covid-19-data#2093]
Malaysia's government provides hospital and ICU data in the same repo you are using for testing data. Can these be added to the dataset? Thanks

Hospital: https://github.com/MoH-Malaysia/covid19-public/blob/main/epidemic/hospital.csv
ICU: https://github.com/MoH-Malaysia/covid19-public/blob/main/epidemic/icu.csv

**Comment by lucasrodes** [comment]
@edomt FYI, I refactored the hospitalisation pipeline in https://github.com/owid/covid-19-data/commit/9e1eacde5eafda840d12f32eee26122951112419.

Find all country scripts [here](https://github.com/owid/covid-19-data/tree/master/scripts/src/cowidev/hosp/sources)

**Comment by edomt** [comment]
Added in 8c8b5e9d506ece1fcea104c4855af44c6967ae8e
Thank you @jlwj51 !
The data will appear in our dataset & charts later today.
