### ISSUE TITLE
Vaccination data by age group from Peru is not showing in OWID charts

### ISSUE THREAD

**Issue by jmcastagnetto** [owid/covid-19-data#2094]
Refs: issue #1864 and commit 2a40909953e4e66687156049f79e88567ab55741

Checked today the data viz for vaccinations at OWID, and somehow it is not showing the vaccination data by age group for Peru. Is there something that I can do to help?

![image](https://user-images.githubusercontent.com/364668/139341717-e9a5a9f5-41de-47aa-81b1-03afdfdf95c7.png)

@lucasrodes

**Comment by lucasrodes** [comment]
Data has been added to the repository. Should be live on the website soon.

Thanks once again for your help!
