### ISSUE TITLE
Testing data: Belarus issue with scraping press releases

### ISSUE THREAD

**Issue by bzki** [owid/covid-19-data#2098]
Hi -- if I notice some potential issue with the scraper, is this the appropriate place to highlight the issue? Apologies if you are already aware of this and do not want GitHub issues created for each problem that is identified. Currently I don't have much experience with scraping, so I may be unable to submit a pull request. 

For Belarus, there are updates in the current testing dataset on [Oct. 21 and Sept. 27](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=desc&pickerMetric=new_cases_smoothed_per_million&Metric=Tests&Interval=Cumulative&Relative+to+Population=false&Align+outbreaks=false&country=~BLR). The source URL suggests there are actually (almost) daily updates with press releases containing the cumulative testing information: https://www.belarus.by/en/press-center/press-release

I wonder if there is some reason the scraper here is not capturing these and if this could be fixed: https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automations/incremental/belarus.R

EDIT: I attempted to run the Belarus.R script. It actually obtains the correct most recent total tests and date for me, so I'm not entirely sure why the last update was Oct. 21. I would think either the Tuesday or Friday testing update would have gotten more recent data points, and I'm unclear as to the reason for the gap between 9/27 and 10/21. 

Thank you for the incredible work you are doing.

Regards,
Behzad

**Comment by camappel** [comment]
Hi Behzad,

Yes, this is where OWID users can provide feedback directly to the data team, and we appreciate your comment.

Belarus testing data are reported in daily press releases. Unstructured data is harder to scrape, and small changes in formatting/language can prevent the scraper from identifying relevant data points, which is probably why some data points are missed.

We are currently in the process of migrating our R scripts to Python, and we will try to improve our scrapers in the process. Perhaps you'd like to have a go yourself! (See Discussion #2099.)

The data point for Oct 29 was included in our last update.

Thank you for your interest in our work.
