### ISSUE TITLE
EU data missing?

### ISSUE THREAD

**Issue by houstonhaynes** [owid/covid-19-data#210]
I just refreshed my site with OWID covid-19-data and nothing is populating for data from Europe. It's like it completely disappeared from the record set. I'm currently working my way back through the code to parse out some other data issues I'm seeing in NA and will be checking this but thought it worth bringing here ASAP
![image](https://user-images.githubusercontent.com/8174976/101651733-3e002d80-39f2-11eb-86fd-063d922da0cb.png)

**Comment by edomt** [comment]
Hi @houstonhaynes 
Today we changed the names of three countries in our files to match their recently-changed official names. Czech Republic has become Czechia, Macedonia has become North Macedonia, and Swaziland has become Eswatini.
I'm guessing that maybe one of those countries was hard-coded in your script?

**Comment by houstonhaynes** [comment]
[I'm doing my own population leveling](https://h3tech.dev/post/covid-datapothecary/) and so joining population from my own file - and because of the hacked method those countries will definitely fall out. 

**BUT** I'm not sure why that would cause ALL of Europe to disappear from the result. I'll do some more spelunking. Thanks for echoing back.

**Comment by houstonhaynes** [comment]
Just confirming here my calculated columns are missing because something botched with the join to my population data.
