### ISSUE TITLE
Bangladesh Testing Data

### ISSUE THREAD

**Issue by hannahhh19** [owid/covid-19-data#2114]
Hi, I would like to check on the update for Bangladesh Testing Data. I noticed the data provide stopped at 2nd October 2021 while the latest data available from http://103.247.238.92/webportal/pages/covid19.php is 8th November 2021. May I know what is the reason you stop updating the data? Many thanks in advance for your kind assistance on my queries!

**Comment by camappel** [comment]
Hello,
Our [old source](https://covid19bd.idare.io/) stopped updating for a while (although it started again recently). The source that you shared looks more reliable, however, so we will switch to that one.
Thank you for your question and making us aware of this new source!
