### ISSUE TITLE
Tests Performed in Brazil

### ISSUE THREAD

**Issue by Javierpedatos** [owid/covid-19-data#2118]
Update of Tests Performed in Brazil

Github: https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-total.csv

WebSite: https://covid19br.wcota.me/en/

**Comment by camappel** [comment]
Test data for Brazil have now been added: https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automated_sheets/Brazil.csv

Thank you for bringing this to our attention.
