### ISSUE TITLE
Information on  Tests Performed from African countries

### ISSUE THREAD

**Issue by Javierpedatos** [owid/covid-19-data#2119]
Here is information about the tests of the African countries. What is not specific is what day is the update, however much of that information is updated weekly and daily. What is not specific is what day is the update, however much of that information is updated weekly and daily.

Source: https://africacdc.org/covid-19/

**Comment by edomt** [comment]
@camappel @lucasrodes Looks like we could get the latest value for each country with the ArcGIS API: https://services8.arcgis.com/vWozsma9VzGndzx7/ArcGIS/rest/services/DailyCOVIDDashboard_5July21_1/FeatureServer/0/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=Country%2CTests_Conducted%2CDate&returnGeometry=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=

If so then we should definitely write a script adapted from [the vaccination one](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/vax/incremental/africacdc.py)! :)
(Not urgent, & probably something to work one together whenever you have time)

**Comment by camappel** [comment]
Fantastic. I think we should work on this after the refactor since that's a big bottleneck. I can add some manually in the meantime.

**Comment by camappel** [comment]
#2251 https://github.com/owid/covid-19-data/pull/2251
