### ISSUE TITLE
Change File Name

### ISSUE THREAD

**Issue by aliaamiri** [owid/covid-19-data#2126]
Maybe the file's name "population_2020.csv" should change to "population_2021.csv", because all the population entries are for 2021.

**Comment by lucasrodes** [comment]
Changed to name `population_latest.csv`. Thanks!

**Comment by edomt** [comment]
@lucasrodes

**Comment by edomt** [comment]
@lucasrodes Is there a particular reason why `population_2020.csv` itself was not deleted? I think we should remove it to avoid confusion.

There are also some links that need to be corrected on the site (in the vaccination FAQ for example) - I'll take care of that.

**Comment by lucasrodes** [comment]
The idea was to keep it for some days before completely deleting it. So we could make sure that there are no broken links.

Thanks!
