### ISSUE TITLE
Hospitalization data missing in USA data beginning Dec 10th.

### ISSUE THREAD

**Issue by NuisanceLevel7** [owid/covid-19-data#213]
Where can I find hospitalization data? Below is an example from 12/13.

FILE: covid-19-data/public/data/owid-covid-data.json.

{'date': '2020-12-13', 'total_cases': 16253219.0, 'new_cases': 190920.0, 'new_cases_smoothed': 213748.143, 'total_deaths': 299168.0, 'new_deaths': 1389.0, 'new_deaths_smoothed': 2403.0, 'total_cases_per_million': 49102.988, 'new_cases_per_million': 576.793, 'new_cases_smoothed_per_million': 645.76, 'total_deaths_per_million': 903.824, 'new_deaths_per_million': 4.196, 'new_deaths_smoothed_per_million': 7.26, 'stringency_index': 71.76}

**Comment by edomt** [comment]
Hi @NuisanceLevel7 
We update our hospitalization & ICU data on a weekly basis (on Thursdays). If you need daily-updated data, you can go directly to our source which is the COVID Tracking Project: https://covidtracking.com/data/national (they have files available in various formats).
