### ISSUE TITLE
owid/covid-19-data excel version

### ISSUE THREAD

**Issue by lmkfin** [owid/covid-19-data#2132]
I pull down this file weekly, I noticed that the updates have be made for the csv, json, etc - but there is no Excel version posted yet.  Will you all still be doing that?  Thanks!!

**Comment by edomt** [comment]
Hi @lmkfin,
Thanks for reporting.

You can find this file at https://covid.ourworldindata.org/data/latest/owid-covid-latest.xlsx. Please refer to the discussion #2082 for all the details.

**Comment by lmkfin** [comment]
Thank you so very much!!
