### ISSUE TITLE
Data files have changed?

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#2133]
I have noticed that some files have changed. The two mentioned below used to have data from Dec 2020. Today both have a blank entry for 08 Dec 2020 then the next entry is a populated entry for 10 Jan 2021. Can we go back to previous data for Dec 2020 or can we remove the blank data entry please.

https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/England.csv
https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Scotland.csv

**Comment by edomt** [comment]
Thanks @zizwiz - the blank row has been removed, but the old data from December has disappeared from the source.
