### ISSUE TITLE
Misinformation from Afghanistan on the WHO website

### ISSUE THREAD

**Issue by Javierpedatos** [owid/covid-19-data#2134]
The first dose information on the Afghanistan dashboard is not correct. As of November 13, 4,016,788 doses have been administered of these 3,187,200 people are fully vaccinated and 829,588 are vaccinated with one dose. Which means that the true information for November 14 is 4,018,197 administered doses, 3,188,609 fully vaccinated and 829,588 people vaccinated with one dose. 

Vaccination Source to November 13: https://reliefweb.int/sites/reliefweb.int/files/resources/weekly-epidemiological-bulletin_w45.pdf

**Comment by edomt** [comment]
Thanks
