### ISSUE TITLE
Some public datasets are using 'old'/out-of-scope, [population] data sources + reality and distortions

### ISSUE THREAD

**Issue by philipswift** [owid/covid-19-data#2135]
https://github.com/owid/covid-19-data/blob/master/public/data/ecdc/locations.csv is a real-world example of stating the population for the UK (United Nations (UNPD?), geo-region 908, LocID 826) as 67886004 when it is being stated as 68207114 elsewhere. 
Additionally, the [population_year] states 2020 for the 67886004 entry when this originally was stated as a 2019 data source from the United Nations.
Checking the source of the data from the United Nations gives the latest figure as an estimate from 2016, even though the latest revision is stated as 2019!
Source: https://population.un.org/wpp/Download/Files/4_Metadata/WPP2019_F02_METADATA.XLSX tab called 'overall', line 3232.
![screenshot extract of UN data sources for the UK ](https://user-images.githubusercontent.com/6306791/142139389-15a64ac3-cb74-4887-906f-04dacfde67dd.PNG)

OWID datasource stated a 'source' but it is a 'standard, not the datasource. Source: https://github.com/owid/covid-19-data/blob/master/scripts/input/un/population_latest.csv line 230 and also states the year as 2021. It is unclear as to whether this is the year of publication or year of harvesting the data.
![screenshot extract of owid-population_latest entries  ](https://user-images.githubusercontent.com/6306791/142140029-9a398cf7-c915-4d74-aed5-17784781307a.PNG)

UN disclaimer uses a 'no-implication' and 'no-expression' caveat. Source: https://population.un.org/wpp/DataSources/826
and more ....http://data.un.org/Host.aspx?Content=UNdataUse
My point is real-world reliability and/or robustness of data sources.

I have just reread GitHub Community Guidelines/Misinformation and disinformation re: distortion of reality (this is so subjective as opposed to objective I ,personally, have no idea why it is stated, at all, in the guidelines)

**Comment by edomt** [comment]
Hi @philipswift 

I find it very difficult to understand this issue. Could you please rephrase it in a way that makes it clear what the issue is?

Please also note that we indicate this in our public README:
> `ecdc`: data from the European Centre for Disease Prevention and Control, related to confirmed cases and deaths—**we have stopped using and updating this data since 30 November 2020.**

**Comment by philipswift** [comment]
Je vais regarder mais je pense que c'est assez clair. C'est peut-être parce
que l'anglais est votre deuxième langue, mais c'est ma langue maternelle.
S'il vous plaît, la communauté open source peut-elle arrêter d'utiliser le
"lisez-moi" comme excuse. Ce n'est pas parce qu'il y a une entrée dans le
fichier readme que les choses sont acceptables. Le Royaume-Uni avait les
mauvais chiffres de population pour les âges. Votre réponse sent
l'inaccessibilité et ne souhaite pas vraiment traiter ce problème. C'est
peut-être parce que les autres craignent de vous offenser et se plient à
vos souhaits ?

I'll have a look however I think it is clear enough. Maybe it is because
English is your second language but it is my native. Please can the
opensource community stop using the 'readme' thing as an excuse. Just
because there is an entry in the readme, does not mean things are
acceptable. The UK had the wrong population figures for ages. Your reply
smacks of unapproachability and not really wishing to deal with this issue.
Possibly it is because others are wary of offending you and just go along
with your wishes?

P

**Comment by edomt** [comment]
The user @philipswift has now been blocked from contributing to this repository. This is an open-source project that welcomes external contributions at all times, but we demand that users keep a respectful tone.
