### ISSUE TITLE
Outdated French vaccination data

### ISSUE THREAD

**Issue by d-qn** [owid/covid-19-data#2136]
It seems that vaccination data for France is wrong or no longer updated. The latest data for France (16 Nov) shows 68.8% of the population fully vaccinated, which is a big stretch from the official number of **76.9%**

Sources: 

- [covidtracker.fr](https://covidtracker.fr/vaccintracker/)
- [Le Monde](https://www.lemonde.fr/les-decodeurs/article/2021/01/29/covid-19-suivez-la-progression-de-la-vaccination-en-france-et-dans-le-monde_6068029_4355770.html)

**Comment by edomt** [comment]
Hi, see #1791
