### ISSUE TITLE
owid-covid-data-last-updated-timestamp.txt not updating

### ISSUE THREAD

**Issue by Ipgnosis** [owid/covid-19-data#2139]
https://github.com/owid/covid-19-data/tree/master/public/data/owid-covid-data-last-updated-timestamp.txt
This file currently contains the string: 2021-11-16T20:58:00 at ~UTC time 2021-11-19T16:00:00
I currently use this file to determine if the data I have downloaded is up to date or not.  For 3 days, it has not been updating, but the covid data is current AFAIK.
![owid-data](https://user-images.githubusercontent.com/18078232/142653064-cb420ee7-b9eb-4e2a-a4b2-4e8d63b3f8dd.png)
.

**Comment by edomt** [comment]
@lucasrodes will know the details, but I think you should use https://github.com/owid/covid-19-data/blob/master/public/data/internal/timestamp/owid-covid-data-last-updated-timestamp.txt instead (the other one is deprecated)

**Comment by lucasrodes** [comment]
Hi @Ipgnosis,
Thanks for your message!

I just updated the file. However, I recommend using the URL covid.ourworldindata.org/data/owid-covid-data-last-updated-timestamp.txt instead, which is equivalent and should be more stable.

**Comment by Ipgnosis** [comment]
Thanks for the guidance @lucasrodes.
