### ISSUE TITLE
vaccine data doesn't match with data source URL

### ISSUE THREAD

**Issue by Stonivor** [owid/covid-19-data#2141]
Hi, 

I have just noticed a discrepancy with vaccination numbers with a specific use case:

**Given** vacination data for France
**When** comparing "People Fully Vaccinated" with the data source (provided by location)
**Then** the numbers don't match, "People Fully Vaccinated"  has 46 million when the official source has 50 million (other columns seem to match.

**Vaccination**:
source: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv
country: France
date: 19/11/2021

**Vaccination Location**:
source: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/locations.csv
country: France

**Comment by edomt** [comment]
see #1791
