### ISSUE TITLE
people_vaccinated_per_hundred is greater than 100

### ISSUE THREAD

**Issue by Stonivor** [owid/covid-19-data#2142]
when looking at https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations-by-age-group.csv
I have noticed that some values are greater than 100 on a per hundred column (i.e. people_vaccinated_per_hundred).

Which would indicate that some countries have vaccinated more than 100% of specific age groups...

![image](https://user-images.githubusercontent.com/24657654/142729053-32680f82-c4bb-456f-a57f-b7d8aac01579.png)

**Comment by edomt** [comment]
Hi @Stonivor 

This matches [the data as made available by the European CDC](https://vaccinetracker.ecdc.europa.eu/public/extensions/COVID-19/vaccine-tracker.html). We previously reported this issue to them, but they said that there isn't much they can do on their end. They use vaccination figures as reported by each European country, and denominators (age group estimates) made available by the statistical office of each country. But in a few cases these numbers don't seem to line up perfectly, and the numerator is higher than the denominator.
