### ISSUE TITLE
US Vaccinations Repeating Values on 11/21/2021

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#2146]
Hello,

It seems like there is no new vaccinations data reported yesterday, which looks abnormal. Could you look into it and fix them?

![image](https://user-images.githubusercontent.com/68354122/142911934-6d090748-9d52-4a7f-ad3f-ab4aead38d0d.png)

**Comment by edomt** [comment]
Hi @RuijingZ 
That is actually what the CDC data looks like currently: https://covid.cdc.gov/covid-data-tracker/#vaccination-demographics-trends
If they fix it on their side, it'll be fixed in our data with tomorrow's update.
