### ISSUE TITLE
Update Dutch testing data daily from source

### ISSUE THREAD

**Issue by EwoutH** [owid/covid-19-data#2149]
Currently the most current testing data for The Netherlands on [Our World in Data](https://ourworldindata.org/coronavirus-testing#the-positive-rate-a-crucial-metric-for-understanding-the-pandemic) is from November 14th, a lag of 9 days, and only updated once a week. This lags could be reduced to only 2 days using the daily data from the Dutch _National Institute for Public Health and the Environment_ ([RIVM](https://www.rivm.nl/en)).

On https://data.rivm.nl/covid-19/ there is a daily updated file available called [COVID-19_uitgevoerde_testen.csv](https://data.rivm.nl/covid-19/COVID-19_uitgevoerde_testen.csv) (also in [json](https://data.rivm.nl/covid-19/COVID-19_uitgevoerde_testen.json)) which lists the number of tests performed and number of tests positive for each Dutch [Safety region](https://en.wikipedia.org/wiki/Safety_region). It updated daily at 15:15 and contains data up to two days prior (so today, November 19th, it contains the data up to November 17th).

It's also the exact data used on the national [coronadashboard](https://coronadashboard.government.nl/landelijk/positief-geteste-mensen) for The Netherlands.
![covid-testing-rate-nl](https://user-images.githubusercontent.com/15776622/142642308-98db1ffa-51a8-48a7-a38e-07195ad72115.png)

------

Marino van Zelst (@mzelst) is doing a lot of awesome data gathering and processing in The Netherlands. His data and code is available on [mzelst/covid-19](https://github.com/mzelst/covid-19). The [parse_tests.R](https://github.com/mzelst/covid-19/blob/master/workflow/parse_tests.R) script is used to read a compressed version of the `COVID-19_uitgevoerde_testen.csv` file from the RIVM listed above and calculate things like the positivity rate.

This data then get's saved in the [percentage-positive-daily-national.csv](https://github.com/mzelst/covid-19/blob/master/data-dashboards/percentage-positive-daily-national.csv) file, which is updated daily (around 15:17 NL time). Sub-national data is also saved, at [percentage-positive-daily-safetyregion.csv](https://github.com/mzelst/covid-19/blob/master/data-dashboards/percentage-positive-daily-safetyregion.csv).

Either the R-script or the daily data generated might be useful for updating OWID. His code is available with a very permissive [CC0-1.0 License](https://github.com/mzelst/covid-19/blob/master/LICENSE).

CC @camappel @edomt.

**Comment by EwoutH** [comment]
@camappel Do you have any idea when you're able to work on this issue?

**Comment by edomt** [comment]
Hi @EwoutH 

I cannot answer directly for @camappel, but our data team deals with many projects and commitments at the same time, and therefore it's almost always impossible to commit to a specific time frame.

**Comment by camappel** [comment]
I hope to work on it soon but I am prioritising other commitments at the moment.

One issue with this new daily source is that the time series begins 1/6/2020, whereas testing in the Netherlands began 8/3/2020 (our weekly time series begins 15/3/2020. Hopefully I can simply append the daily test figures to the weekly test figures when the daily figures start, but I'll need to make sure they are comparable. 

<img width="1658" alt="Screenshot 2021-11-29 at 13 30 25" src="https://user-images.githubusercontent.com/16980052/143876701-a2551b6b-2e37-4c2e-9f65-4da258ae450a.png">

**Comment by EwoutH** [comment]
Thanks for getting back and explaining the process!

Marino van Zelst maintains a file called [all_data.csv](https://github.com/mzelst/covid-19/blob/master/data/all_data.csv) which includes:

- the number of positive tests per day (column `positivetests`), starting from 2020-02-27
- the amount of total tests administered (column `values.tested_total`), starting from 2020-06-01
- the percentage positive (column `values.infected_percentage`), starting from 2020-06-01

Maybe it helps!

**Comment by camappel** [comment]
This is very useful, thank you

**Comment by EwoutH** [comment]
To give some context why this number is so important to us:

1. Today a [national record was reached](https://twitter.com/mzelst/status/1467863486655078404), 26.5% of tests were positive. It was never that high in The Netherlands.
2. The [testing advice changed](https://www.rijksoverheid.nl/onderwerpen/coronavirus-covid-19/nieuws/2021/12/02/corona-gerelateerde-klachten-zelftesten-of-naar-de-ggd) on December 3rd, recommending antigen tests at home more often, decreasing the number of registered PCR tests.
3. The Dutch national [Coronadashboard](https://coronadashboard.rijksoverheid.nl/) stopped reporting this number for an unknown reason (see https://github.com/minvws/nl-covid19-data-dashboard/pull/3843#issuecomment-979766836)

**Comment by camappel** [comment]
Thank you for your message. I am currently in the process of making this change and it will be live soon.

**Comment by EwoutH** [comment]
Awesome, thanks a lot!

**Comment by EwoutH** [comment]
The improvement is astounding:

![ezgif-6-212b2ba81a0c (1)](https://user-images.githubusercontent.com/15776622/144925502-8443d2d9-ca54-4654-8b71-a4985b47e94f.gif)
