### ISSUE TITLE
Country updates dec 16?

### ISSUE THREAD

**Issue by philipncohen** [owid/covid-19-data#215]
No new country data today - is the Hopkins hookup working?

**Comment by edomt** [comment]
Hi @philipncohen 
I'm not sure what you mean. The data has been updated yesterday and today, you can see the history here: https://github.com/owid/covid-19-data/commits/master/public/data/owid-covid-data.csv
(Updates that include new cases & deaths data are labelled as "Automated JHU update")

**Comment by philipncohen** [comment]
Hi, Thanks. Just the reason I was confused is, FYI, when you do the updates you seem to get a very few countries with a record for today's date but no data, while the main data ends yesterday. For example right now there is a record for Canada (and just 10 other countries) for 2020-12-18 but it has missing values for cases and deaths. The data through  2020-12-17 looks complete.
