### ISSUE TITLE
Reproduction Rate for the US

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#2150]
Hello,

The reproduction rate for the US has not been updated since 11/10/2021. Is it possible to have it updated?

![image](https://user-images.githubusercontent.com/68354122/143046383-c36b5c84-25ef-4a40-bcea-e81ae4f48a06.png)

**Comment by edomt** [comment]
Hi @RuijingZ 
We rely on the data made available by https://github.com/crondonm/TrackingR/tree/main/Estimates-Database. I'm guessing that updates should resume soon, but you can open an issue in this repo or write to the author (see the README for their email address).
