### ISSUE TITLE
gaps in people_vaccinated and people_fully_vaccinated

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#2153]
I realize that some gaps in `people_vaccinated` and `people_fully_vaccinated` are inevitable due to varying quality of data sources, but some make me wonder if that's always really the culprit.

Eg. Luxembourg is missing nearly 8 months of `people_fully_vaccinated` data, Singapore and Iceland who I suppose should have decent repoting standards have some gaps in both `people_vaccinated` and `people_fully_vaccinated`, Andorra and San Marino have more gaps than data there, Croatia has a strange 4-weeks gap in `people_fully_vaccinated`, Brazil has got a 2-week gap in both data series recently, etc.

Below are listed all such gaps I spotted, rounded down to a weekly resolution. Could you verify if really neither of these could be due to OWID's processing rather than any other issues?

Albania
24.01-07.02 people_vaccinated
28.02-16.05 people_vaccinated, people_fully_vaccinated

Andorra
28.02-14.03 people_vaccinated
21.03-25.04 people_vaccinated, people_fully_vaccinated
23.05-06.06 people_vaccinated, people_fully_vaccinated
04.07-18.07 people_vaccinated, people_fully_vaccinated
01.08-26.09 people_vaccinated, people_fully_vaccinated
03.10-31.10 people_vaccinated, people_fully_vaccinated

Antigua and Barbuda
21.02-21.03 people_vaccinated
04.04-18.04 people_vaccinated
25.04-09.05 people_vaccinated
25.04-09.05 people_vaccinated
20.06-11.07 people_vaccinated, people_fully_vaccinated

Armenia
04.04-09.05 people_vaccinated
06.06-20.06 people_vaccinated
27.06-11.07 people_vaccinated, people_fully_vaccinated
26.09-17.10 people_vaccinated, people_fully_vaccinated

Azerbaijan
17.01-07.03 people_vaccinated
24.10-14.11 people_vaccinated

Belarus
21.02-14.03 people_vaccinated
14.03-23.05 people_vaccinated, people_fully_vaccinated
13.06-18.07 people_vaccinated, people_fully_vaccinated
01.08-15.08 people_vaccinated, people_fully_vaccinated
24.10-07.11 people_vaccinated, people_fully_vaccinated

Belize
22.08-05.09 people_vaccinated, people_fully_vaccinated
10.10-31.10 people_vaccinated
10.10-14.11 people_fully_vaccinated

Bermuda
14.02-28.02 people_vaccinated, people_fully_vaccinated
11.04-25.04 people_vaccinated, people_fully_vaccinated
02.05-16.05 people_vaccinated, people_fully_vaccinated
20.06-18.07 people_vaccinated, people_fully_vaccinated

Bolivia
26.09-31.10 people_vaccinated, people_fully_vaccinated

Bosnia and Herzegovina
14.02-18.04 people_vaccinated
02.05-23.05 people_vaccinated, people_fully_vaccinated
30.05-08.08 people_vaccinated, people_fully_vaccinated
22.08-31.10 people_vaccinated, people_fully_vaccinated

Brazil
31.10-14.11 people_vaccinated, people_fully_vaccinated

Bulgaria
18.07-01.08 people_vaccinated, people_fully_vaccinated
22.08-14.11 people_vaccinated

Costa Rica
01-08-15.08 people_vaccinated, people_fully_vaccinated 
24.10-07.11 people_vaccinated, people_fully_vaccinated

Croatia
12.09-10.10 people_fully_vaccinated

Cyprus
07.03-04.04 people_vaccinated, people_fully_vaccinated

Dominican Republic
04.04-18.04 people_vaccinated, people_fully_vaccinated

Egypt
31.01-09.05 people_vaccinated

El Salvador
28.02-14.03 people_vaccinated

French Polynesia
04.07-18.07 people_vaccinated, people_fully_vaccinated
07.11-21.11 people_vaccinated, people_fully_vaccinated

Georgia
14.03-04.04 people_vaccinated
11.07-25.07 people_vaccinated, people_fully_vaccinated
24.10-07.11 people_vaccinated, people_fully_vaccinated

Greenland
31.01-07.03 people_vaccinated
07.03-11.04 people_vaccinated, people_fully_vaccinated
07.11-28.11 people_vaccinated, people_fully_vaccinated

Iceland
08.08-29.08 people_vaccinated, people_fully_vaccinated

Iran
21.02-18.04 people_vaccinated
30.05-13.06 people_vaccinated, people_fully_vaccinated
04.07-18.07 people_vaccinated, people_fully_vaccinated
10.10-24.10 people_vaccinated, people_fully_vaccinated

Jamaica
18.04-16.05 people_vaccinated
13.06-11.07 people_vaccinated, people_fully_vaccinated
25.07-08.08 people_vaccinated, people_fully_vaccinated

Kazakhstan
31.01-28.02 people_vaccinated
28.02-11.04 people_vaccinated, people_fully_vaccinated

Kosovo
04.04-18.04 people_vaccinated
25.04-06.06 people_vaccinated
20.06-04.07 people_vaccinated, people_fully_vaccinated

Kuwait
21.02-04.07 people_vaccinated, people_fully_vaccinated

Kyrgyzstan
28.03-02.05 people_vaccinated
02.05-01.08 people_vaccinated, people_fully_vaccinated

Macao
03.10-17.10 people_vaccinated, people_fully_vaccinated
07.11-28.11 people_vaccinated, people_fully_vaccinated

Luxembourg
18.04-07.11 people_fully_vaccinated

Mauritius
07.02-16.05 people_vaccinated
23.05-06.06 people_vaccinated, people_fully_vaccinated
27.06-18.07 people_vaccinated, people_fully_vaccinated

Moldova
08.08-14.11 people_vaccinated
08.08-26.09 people_fully_vaccinated

Monaco
07.03-18.04 people_vaccinated, people_fully_vaccinated
09.05-30.05 people_vaccinated, people_fully_vaccinated
13.06-27.06 people_vaccinated, people_fully_vaccinated
08.08-22.08 people_vaccinated, people_fully_vaccinated

Nicaragua
07.03-18.07 people_vaccinated
18.07-22.08 people_vaccinated, people_fully_vaccinated
10.10-21.11 people_vaccinated, people_fully_vaccinated

North Macedonia
21.02-04.04 people_vaccinated

Oman
31.01-14.02 people_vaccinated, people_fully_vaccinated
28.02-14.03 people_vaccinated, people_fully_vaccinated
25.04-13.06 people_vaccinated, people_fully_vaccinated
20.06-11.07 people_vaccinated, people_fully_vaccinated
25.07-15.08 people_vaccinated, people_fully_vaccinated
05.09-19.09 people_vaccinated, people_fully_vaccinated
03.10-17.10 people_vaccinated, people_fully_vaccinated
31.10-28.11 people_vaccinated, people_fully_vaccinated

Paraguay
17.10-31.10 people_vaccinated, people_fully_vaccinated

Philippines
15.08-14.11 people_vaccinated

Qautar
21.02-02.05 people_vaccinated

Romania
03.10-21.11 people_vaccinated

Russia
17.01-07.03 people_vaccinated
21.03-04.04 people_vaccinated, people_fully_vaccinated
17.10-31.10 people_fully_vaccinated

San Marino
09.05-23.05 people_vaccinated, people_fully_vaccinated
20.06-03.10 people_vaccinated, people_fully_vaccinated
10.10-24.10 people_vaccinated, people_fully_vaccinated
07.11-21.11 people_vaccinated, people_fully_vaccinated

Serbia
14.02-28.02 people_vaccinated, people_fully_vaccinated
20.06-11.07 people_vaccinated, people_fully_vaccinated

Seychelles
11.07-31.10 people_vaccinated, people_fully_vaccinated

Singapore
21.02-07.03 people_vaccinated, people_fully_vaccinated
18.04-16.05 people_vaccinated, people_fully_vaccinated

South Africa
18.04-02.05 people_vaccinated, people_fully_vaccinated
23.05-11.07 people_fully_vaccinated

Thailand
14.03-28.03 people_vaccinated
26.09-10.10 people_vaccinated, people_fully_vaccinated

Uzbekistan
02.05-16.05 people_vaccinated
30.05-08.08 people_vaccinated
30.05-12.09 people_vaccinated, people_fully_vaccinated
12.09-26.09 people_vaccinated

**Comment by edomt** [comment]
Hi @czka

For many countries, some information is not available due to:
- The source not reporting this metric at all
- Or the source reporting the data in a way that makes it impossible to calculate one of the metrics. This is often the cases when a 1-dose vaccine (such as J&J) is used in conjunction with 2-dose vaccines, but the source doesn't report detailed data on doses by manufacturer.

What you see in our database at the moment is the best information at our disposal, for all of these countries (if we had more, we would happily publish it). If you happen to find more data for one or more of these countries, please feel free to open a new issue or pull request with the new data.

**Comment by edomt** [comment]
Hi @czka 

Yes, that's because the open-data file published by Luxembourg doesn't let us calculate `people_fully_vaccinated`, so we sometimes pull the latest figure from the [daily PDF reports](https://data.public.lu/en/datasets/covid-19-rapports-journaliers/#_) so that the variable is empty. This is mainly to make sure that Google doesn't display a very old value for `people_fully_vaccinated` in its search results (which are directly connected to our files).
