### ISSUE TITLE
Fully Vaccinated Data for France seems incorrect.

### ISSUE THREAD

**Issue by gauravjoshijo** [owid/covid-19-data#2161]
As per the feed, total no. of fully vaccinated people for France is 47,022,392, but as per the official source (https://solidarites-sante.gouv.fr/grands-dossiers/vaccin-covid-19/article/le-tableau-de-bord-de-la-vaccination) it is 50,828,858 till now.

Please look into this. Thanks!!

**Comment by edomt** [comment]
see #1791
