### ISSUE TITLE
Portugal booster doses

### ISSUE THREAD

**Issue by trapko91** [owid/covid-19-data#2163]
There is new daily data regarding booster doses that is being released by the government and it's correctly being added to Portugal.csv but "total_vaccinations" is not counting them.

Also, it seems that there is / will be no more data on first or second doses, only people fully vaccinated. That's probably why there is no total count update for 15+ days.

**Comment by trapko91** [comment]
@edomt, I think they corrected total_vaccinations (vacinas) to include boosters on [https://github.com/dssg-pt/covid19pt-data/blob/master/vacinas.csv](url) and they are being counted twice now after your fix (e.g. in 26 Nov there were 100k boosters and total_vaccinations counted 200k.) 

Also, you can get the booster count directly from that csv now (column: **pessoas_reforço**). [https://github.com/ruimgbarros/vacinacao](url) has not updated since Dec 2.

**Comment by lucasrodes** [comment]
Thank you very much, @trapko91
