### ISSUE TITLE
Portugal Total Vaccination 

### ISSUE THREAD

**Issue by hannahhh19** [owid/covid-19-data#2164]
Hi!

May I know how the Portugal Total Vaccination on 15/11/2021 backwards were calculated? Was it resulting from the below 
For example for date 15/11/2021
OWID:
[vaccinations.csv]:[total_vaccinations]:[16833391]

SOURCE:
[vacinas.csv]:[doses]:[15537056]

If this was the case, what is the reason for different values seen? 

Thanks in advance for your help on this!

**Comment by edomt** [comment]
Hi @hannahhh19 

The field `total_vaccinations` also includes the boosters, taken from the last non-missing value in `total_boosters` (in your example, 525,000 boosters).
Note that the booster data is not available in `vacinas.csv`, so we're adding it from another source.
