### ISSUE TITLE
Vaccinations by manufacturer (Peru)

### ISSUE THREAD

**Issue by jmcastagnetto** [owid/covid-19-data#2166]
Looking at the data in https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations-by-manufacturer.csv, I did not find the info for Peru, so I've added another summary to my repo with that data, in case it can be useful to you.

The data file is at: https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/main/datos/vacunas_covid_fabricante.csv

And the data structure is similar to the one you use (I am using one more column: `vaccinations`):

| Campo                | Contenido                                         |
| :------------------- | :------------------------------------------------ |
| `location`           | Peru                                              |
| `date`               | Date (YYYY-MM-DD)                  |
| `vaccine`            | Vaccine manufacturer                           |
| `vaccinations`       | Number of vaccines per manufacturer on date |
| `total_vaccinations` | Accumulated number of vaccines per manufacturer  |

The data is current up to 2021-12-01. Will update again next Sunday.

@lucasrodes

**Comment by lucasrodes** [comment]
Thanks!
