### ISSUE TITLE
Show Greenland data and other countries

### ISSUE THREAD

**Issue by 3dgiordano** [owid/covid-19-data#2167]
I understand currently Hong Kong is separated from China to show the data because is a independent country. 
Would it be possible to separate Greenland from Denmark to do the same?

Today you run it as an independent country but without data, and currently the JHU data exists for them.

What happens is that you add your data to Denmark and leave the data for that country empty.

Today it is a pity that Greenland is not on the map or in the data, there is independent data on them in almost all the data projects from which you get the information.

The line where you could bring Greenland to life at OWID.

https://github.com/owid/covid-19-data/blob/fb39ddfddce187637ed1f46c27d276f4376898bd/scripts/src/cowidev/jhu/__main__.py#L87

The data on JHU for Greenland
https://github.com/CSSEGISandData/COVID-19/blob/7b4e2cefacb27164cb9da45d3e11dc745f11fd34/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv#L105

Since it brings complications to separate or bring to light the data of that country, I did not propose the change in the code.
I leave it as a suggestion to be evaluated.
I really think they could bring visibility to the data from that country and it would be beneficial to many who consume your data.

Regards
David

**Comment by edomt** [comment]
Hi David! Thanks for the suggestion – it's a really good one, but indeed we need to check a few things before doing that (the main obstacle is to make sure we don't double-count cases & deaths in some places).
We'll have a look whenever we have time soon.

**Comment by 3dgiordano** [comment]
I known @edomt some of this thing was talked with @lucasrodes 

The list of the countries with the same situation than can be evaluated to independice the data because is a country with iso and particular data from CSSE and others sources like VAX data exists.

    

> **Aruba VAX Data:True**
> **Hong Kong VAX Data:True**
> **Isle of Man VAX Data:True**
> **British Virgin Islands VAX Data:True**
> **Turks and Caicos Islands VAX Data:True**
> Guadeloupe VAX Data:False
> **Anguilla VAX Data:True**
> **New Caledonia VAX Data:True**
> **Cook Islands VAX Data:True**
> **Montserrat VAX Data:True**
> **Gibraltar VAX Data:True**
> **French Polynesia VAX Data:True**
> Mayotte VAX Data:False
> Martinique VAX Data:False
> **Curacao VAX Data:True**
> Saint Pierre and Miquelon VAX Data:False
> French Guiana VAX Data:False
> **Bermuda VAX Data:True**
> **Wallis and Futuna VAX Data:True**
> **Cayman Islands VAX Data:True**
> **Greenland VAX Data:True**

I made a small example that crosses the list of countries with the CSSE provinces / states so that they can see which countries can be independent of their data and if in OWID exist VAX data for that country in order to be enabled on OWID.

https://gist.github.com/3dgiordano/0c239dadba452a0ab453cf2a99d7cf87

I hope it is useful for the evaluation.

Regards
David

**Comment by lucasrodes** [comment]
Opened issue https://github.com/CSSEGISandData/COVID-19/issues/5051

**Comment by 3dgiordano** [comment]
Hi @lucasrodes and @edomt 

I noticed that you already incorporated some and that the data and looks great in OWID

I was working a little more on the example to be able to keep track of the information that JHU has and that others take advantage of to show the information of countries (Google is one of them).

https://gist.github.com/3dgiordano/0c239dadba452a0ab453cf2a99d7cf87

In order to have the same level of information that people can view on Google, the following things is needed to add:

JHU Province/State that is a County and not is on OWID (Follow the same idea than HK and Greenland, decouple the data)
   Anguilla - VAX Data:True
   Aruba - VAX Data:True
   Bermuda - VAX Data:True
   British Virgin Islands - VAX Data:True
   Cayman Islands - VAX Data:True
   Cook Islands - VAX Data:True
   Curacao - VAX Data:True
   French Guiana - VAX Data:False
   French Polynesia - VAX Data:True
   Gibraltar - VAX Data:True
   Guadeloupe - VAX Data:False
   Isle of Man - VAX Data:True
   Martinique - VAX Data:False
   Mayotte - VAX Data:False
   Montserrat - VAX Data:True
   New Caledonia - VAX Data:True
   Saint Pierre and Miquelon - VAX Data:False
   Turks and Caicos Islands - VAX Data:True
   Wallis and Futuna - VAX Data:True

JHU US Province/State that is a County and not is on OWID
   American Samoa - VAX Data:False
   Guam - VAX Data:False
   Northern Mariana Islands - VAX Data:False
   Puerto Rico - VAX Data:False

The following data is important, the list inside jhu_country_standardized.csv don't have the following match for the renames.
Many countries the data come to life with only update the standardized csv.

JHU Countries that needs renames
   Bonaire, Sint Eustatius and Saba -> Bonaire Sint Eustatius and Saba
   Falkland Islands (Malvinas) -> Falkland Islands
   Macau -> Macao
   Réunion -> Reunion
   Saint Barthelemy -> Saint Barthélemy
   Saint Helena, Ascension and Tristan da Cunha -> Saint Helena
   St Martin -> Saint Martin (French part)
   Sint Maarten -> Sint Maarten (Dutch part)
   United States Virgin Islands -> Virgin Islands

Exist a exotic country, maybe you can add this with the OWID_ iso in the table of countries to list them or add them to International (like the Cruises) or do nothing.

Countries in JHU that not matches (move to international?)
   Summer Olympics 2020

**Comment by 3dgiordano** [comment]
Another thing, the technique of using a merge to perform the renaming was difficult for me to identify and it has no comment.
Maybe you could incorporate a comment or not use merge and use rename or do the operation in a function, that way the intention is better declared in the source code.
https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/jhu/__main__.py#L122

Another thing to consider is that for example the Effective Reproduction Rate data is also based on the JHU data and has exactly the same countries to rename.
https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/megafile/steps/reprod.py
https://github.com/owid/covid-19-data/blob/master/scripts/input/reproduction/reprod_country_standardized.csv

You can verify that the list of change of names are in both parts updated or see to unify and use the same mechanism.
Even if you can see in the example, with Reproductive they use the rename.

I think that not all the countries are present in the reproductive list and is part of the reason why some countries do not have the information of the Re data.

I'm looking to raise this issue also to the team behind the Re calculus to compute the data for these countries hidden behind a grouping so that I can see their Re data in OWID as well.

**Comment by lucasrodes** [comment]
As per the `Re`, I couldn't find any of these regions in https://raw.githubusercontent.com/crondonm/TrackingR.

I am closing this issue. Feel free to open a new one to further discuss other issues or update this discussion.

Thanks,
Kind regards,

**Comment by 3dgiordano** [comment]
Thanks @lucasrodes 🥇 

Awesome!, I see now lots of countries with case and deaths in the COVID-19 Data Explorer.

Regarding Re, I have yet to raise an issue to them so that they follow the same criteria because they also calculate Re by joining islands that are even on another continent, very far from the country where they group and calculate the Re.
I am going to propose to them that they use your code as a reference.

I also leave you this recommendation to evaluate whether to separate in the future, or to find a mechanism for which today are grouped their data on cases and deaths can be consulted, as today the data on hospitalization, vaccination and others are consultable.

Thanks a lot!
Regards
David

**Comment by DrBazUK** [comment]
> 
> Regarding American Samoa, Guam, Northern Mariana Islands and Puerto Rico, we currently group these under the US for all our metrics. Similarly, French Guiana, Guadeloupe, Martinique, Reunion and Mayotte are grouped under France. This is not to say that we won't review this in the future.

Thanks for the effort @3dgiordano, @lucasrodes & @edomt - if there is any possibility of adding these overseas territories of the US and France, could you also comment on this thread as I will monitor it for changes and this will help me anticipate the need to rebuild some of my own visualisations. 

At present I am filling in the "missing" locations from WHO data found [here](https://covid19.who.int/info/). In my case, I'm using WHO for France, UK and US data and this source also provides me American Samoa, French Guiana, Guadeloupe, Guam, Guernsey, Jersey, Martinique, Mayotte, Nauru, Niue, Northern Mariana Islands, Pitcairn Islands, Puerto Rico, Reunion, Saint Barthelemy, Saint Martin, Sint Maarten, Tokelau, Tuvalu and US Virgin Islands.

thanks in advance,
Baz
