### ISSUE TITLE
Publish a latest versione of your database

### ISSUE THREAD

**Issue by sapomnia** [owid/covid-19-data#217]
Would it be possibile to publish the latest version of your data, so that one can built autoudpating maps/viz based upon it? Thanks in advance

**Comment by edomt** [comment]
Hi @sapomnia 
I'm not sure what you mean? Our data is refreshed several times a day, see here: https://github.com/owid/covid-19-data/commits/master/public/data

**Comment by sapomnia** [comment]
I mean a dataset containing only the latest udpate. Like here: https://github.com/pcm-dpc/COVID-19/tree/master/dati-province (you'll need to scroll a little :) )

**Comment by edomt** [comment]
Okay, I understand better, thanks :)
Would you need all metrics from https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv, or only a subset? (They all have different refresh schedules so the "latest version" isn't the same date for all of them.)

**Comment by sapomnia** [comment]
If it's not too much to ask, all metrics would be awesome!

**Comment by edomt** [comment]
This is now available here: https://github.com/owid/covid-19-data/tree/master/public/data/latest
Feel free to let me know if anything doesn't look right in those files!

**Comment by sapomnia** [comment]
Thank you so much. This is so precious!
Riccardo Saporitimobile 3495207868email sapomnia@yahoo.itskype riccardo.saporiti 

    Il venerdì 18 dicembre 2020, 11:17:34 CET, Edouard Mathieu <notifications@github.com> ha scritto:  
 
 


This is now available here: https://github.com/owid/covid-19-data/tree/master/public/data/latest
Feel free to let me know if anything doesn't look right in those files!
