### ISSUE TITLE
ICU Patient

### ISSUE THREAD

**Issue by maximeLpt** [owid/covid-19-data#2172]
Hi All,

I hope you are doing well.
It looks like ICU patients data is realise by batch, could you give us the forward schedule of releases ?

Best Regards

**Comment by lucasrodes** [comment]
Hi,
Thanks for your message.

We update the hospitalization data every day at 13 PM CET. You can check the precise lines that update this data [here](https://github.com/owid/covid-19-data/blob/772ec839db3e52432dacd3bea2d42068308379f7/scripts/scripts/autoupdate.sh#L172-L180).

**Comment by edomt** [comment]
Just adding that for EU countries, we rely on [the data published by the ECDC](https://www.ecdc.europa.eu/en/publications-data/download-data-hospital-and-icu-admission-rates-and-current-occupancy-covid-19), which they only update once a week (usually on Thursdays).
