### ISSUE TITLE
Vaccinations by age group Data Issue/Clarification

### ISSUE THREAD

**Issue by WIT-Vibin-2021** [owid/covid-19-data#2173]
Hi, 
Why the "people_vaccinated_per_hundred" and "people_fully_vaccinated_per_hundred" values are more than hundred?

As per Readme File 
**people_vaccinated**: total number of people who received at least one vaccine dose. If a person receives the first dose of a 2-dose vaccine, this metric goes up by 1. If they receive the second dose, the metric stays the same.
**people_vaccinated_per_hundred**: people_vaccinated per 100 people in the total population of the country.

So  It should be below hundred as per the read me file.

![image](https://user-images.githubusercontent.com/91533254/144845875-4727ea68-6554-4ddc-8117-0bcbe343581e.png)

**Comment by lucasrodes** [comment]
Hi @WIT-Vibin-2021 ,
Thanks for your message.

For the age vaccination data for most European countries, we use [ECDC](https://www.ecdc.europa.eu/en/publications-data/data-covid-19-vaccination-eu-eea) data. They provide the absolute numbers of people vaccinated and the population size of a given age group. We then estimate the percentages.

For instance, for our metric `people_vaccinated_per_hundred`, we divide their metric `FirstDose` by their metric `Denominator`. You can see this in our script [here](https://github.com/owid/covid-19-data/blob/6a81ab481788f99f118cf68d8b2b72f98f92893b/scripts/src/cowidev/vax/batch/ecdc.py#L271).

Having said this, the ratio may exceed 100% for multiple reasons: vaccination of non-residents, old population estimate, etc.

Hope this helps.
