### ISSUE TITLE
Italy ICU patients report is not updated

### ISSUE THREAD

**Issue by chipechop** [owid/covid-19-data#2177]
Hi, 
Italy's ICU patients, ICU admissions, Hospital patients and Hospital admissions informations (e.g: https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&facet=none&pickerSort=asc&pickerMetric=location&Metric=ICU+patients&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=~ITA) are not updated, since November, the 28th, while they should be (I think).

Can you take a look, at this?

Dario

**Comment by edomt** [comment]
Hi Dario,

For EU countries, we rely on the data made available by the ECDC ([link](https://www.ecdc.europa.eu/en/publications-data/download-data-hospital-and-icu-admission-rates-and-current-occupancy-covid-19)). Whenever the data is updated on their side, it'll be updated the same day on our side. And indeed for now their data stops on 2021-11-28.

**Comment by edomt** [comment]
(Note that the ECDC usually updates its dataset on Thursdays.)
