### ISSUE TITLE
South Africa Hospitalisation data

### ISSUE THREAD

**Issue by anonymouszar** [owid/covid-19-data#2178]
Can you include South Africa Hospitalisation data - should be available at www.nicd.ac.za

**Comment by edomt** [comment]
Hi @anonymouszar 

No machine-readable data is made available on www.nicd.ac.za
We currently pull data on hospital admissions from CSIR. See here: https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&facet=none&pickerSort=asc&pickerMetric=location&Interval=7-day+rolling+average&Relative+to+Population=false&Align+outbreaks=false&country=~ZAF&Metric=Hospital+admissions
