### ISSUE TITLE
Issue for germanys numbers on 9th december

### ISSUE THREAD

**Issue by isntfunny** [owid/covid-19-data#2181]
There have been a faulty number reporting in germany for the 8th december (reported on 9th december) and this should be fixed in the data:

A report of the issue can be found here: https://www.n-tv.de/panorama/RKI-meldet-erneut-falsche-Corona-Zahlen-article22987442.html

The new data can be found here: https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4

New cases:  +70.611 
Incidence:  422,3

**Comment by edomt** [comment]
Hi @isntfunny 

We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.

We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues

**Comment by isntfunny** [comment]
Will the data be fixed if the CSSE accepts the faulty data?

**Comment by edomt** [comment]
On cases and deaths, we import JHU CSSE's data directly, so if they keep their data as is, then ours will stay like that as well. If they correct their time series (which they've done in the past for other countries), then ours will be corrected as well.
