### ISSUE TITLE
Vaccination status of Deaths

### ISSUE THREAD

**Issue by mkeywood1** [owid/covid-19-data#2185]
Is there a way to assess %age of deaths of subjects that are vaccinated, vs %age of deaths of subjects that are unvaccinated?

**Comment by mkeywood1** [comment]
I forgot to say, proper awesome job you have all done here. Simply amazing !! :)

**Comment by edomt** [comment]
Hi @mkeywood1 

Thank you!  😊

We have recently published a post on that topic, with data pulled from 4 countries (US, England, Switzerland, Chile), and a list of available resources for other countries: https://ourworldindata.org/covid-deaths-by-vaccination

This isn't a "proper" dataset, so we're not making this available here on GitHub, but if you want you can download the data from each chart on that page by clicking on the `Download` tab.
