### ISSUE TITLE
Meaning of the 2nd column "year"

### ISSUE THREAD

**Issue by Frncsc98** [owid/covid-19-data#2187]
I am analyzing this dataset but i am not able to understand the meaning of the column year. Could anyone help me? thank you very much

**Comment by edomt** [comment]
Hi @Frncsc98 
Which dataset are you looking at?

**Comment by Frncsc98** [comment]
COVID-19 - Vaccinations by manufacturer.csvCOVID-19 - Vaccinations by manufacturer.csv

**Comment by edomt** [comment]
Thanks! You're likely looking at our internal version – you can use [this file](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations-by-manufacturer.csv) instead.
