### ISSUE TITLE
Sweden booster stats

### ISSUE THREAD

**Issue by siggepigge** [owid/covid-19-data#2188]
There are stats (in a separate table) for booster doses on the Swedish official data site, updated Tue-Fri
These figures are not reflected in OWID reporting which have one single datapoint moving along day by day.
Maybe their data standards aren't up to scratch, thought I should report anyway.

Thanks / Jan S

**Comment by lucasrodes** [comment]
Thanks for reporting!
We have improved how we integrate booster data for Sweden.

We hope that in the future FOHM releases booster data as time series, so we can have more stable updates.
