### ISSUE TITLE
Error on total confirmed cases for Chile on 2021-12-10 (duplicates value informed on 2021-12-09)

### ISSUE THREAD

**Issue by elaval** [owid/covid-19-data#2190]
I have just reported this issue on JHU github repository
[https://github.com/CSSEGISandData/COVID-19/issues/5058](https://github.com/CSSEGISandData/COVID-19/issues/5058)

OWDI (JHU) data reports total confirmed cases for chile as:

2021-12-09: 1778370
2021-12-10: 1778370

Actual values are:
2021-12-09: 1778370
2021-12-10: 1779865

This has implications since reports show 0 new cases on 2021-12-10
![coronavirus-data-explorer - 2021-12-18T085627 575](https://user-images.githubusercontent.com/68602/146640183-59e15ddd-136a-4751-b194-8f431d1db041.png)

And the 7 day rolling average for new confirmed cases gets underreported on 2021-12-10 and over reported on 2021-12-17
![coronavirus-data-explorer - 2021-12-18T085707 054](https://user-images.githubusercontent.com/68602/146640230-c1f5e141-674b-4604-9577-a63d0a419748.png)

Thanks

**Comment by edomt** [comment]
Hi @elaval 

Thanks for reporting! We'll monitor how JHU responds to the issue, but on our side whatever is in their file will automatically be replicated in our data.
