### ISSUE TITLE
Which country income classification does this use? 

### ISSUE THREAD

**Issue by ckrf** [owid/covid-19-data#2198]
Thank you for this extraordinary, herculean, vital project. 

Please consider adding to the documentation a statement of which classification scheme is used to assign countries to income levels. Is it the World Bank fiscal year 2022 classification? 

(I worried it was an older year when I saw this page, https://ourworldindata.org/grapher/world-banks-income-groups, which uses the 2016 classification)

**Comment by edomt** [comment]
Hi @ckrf 

Thanks for the question – the groupings are based on the latest World Bank list. You can see the file that is used by our scripts here: https://github.com/owid/covid-19-data/blob/master/scripts/input/wb/income_groups.csv

**Comment by ckrf** [comment]
Thanks @edomt! That's reassuring :-)
