### ISSUE TITLE
straggling country cases

### ISSUE THREAD

**Issue by philipncohen** [owid/covid-19-data#220]
Hi, Thanks. I'm the person who incorrectly complained about not having a daily country update the other day.

I now see the reason I was confused is, FYI, when you do the updates you seem to get a very few countries with a record for today's date but no data, while the main data ends yesterday. For example right now there is a record for just 11 countries for 2020-12-18 but they have missing values for cases and deaths. The data through  2020-12-17 (yesterday) looks complete.

This is what I got a couple minutes ago: 

  |       date      location   totalcases   new_cases   totaldeaths   new_deaths |
. | 2020-12-18       Bahrain          .          .          .          . |
. | 2020-12-18      Bulgaria          .          .          .          . |
. | 2020-12-18        Canada          .          .          .          . |
. | 2020-12-18     Indonesia          .          .          .          . |
. | 2020-12-18        Malawi          .          .          .          . |
. | 2020-12-18   New Zealand          .          .          .          . |
. | 2020-12-18       Nigeria          .          .          .          . |
. | 2020-12-18      Pakistan          .          .          .          . |
. | 2020-12-18        Rwanda          .          .          .          . |
. | 2020-12-18   South Korea          .          .          .          . |
. | 2020-12-18       Ukraine          .          .          .          . |
. | 2020-12-18         World          .          .          .          . |

**Comment by edomt** [comment]
Hi @philipncohen 
That's because our main source of data, Johns Hopkins University, always updates on day D with data for day D–1. So this morning's update adds data on cases & deaths up to December 18. You can sometimes see rows up to day D (December 19) if there is other data for that date, such as tests or vaccinations.
