### ISSUE TITLE
Malaysia vaccination numbers incorrect

### ISSUE THREAD

**Issue by UserFiftyOne** [owid/covid-19-data#2208]
Malaysia's vaccination numbers don't match the number provided by the health ministry. For example this is the data from 25 December:

**OWID:**
People vaccinated: 25,966,167
People fully vaccinated: 25,575,898
Total boosters: 4,841,085

**[Ministry of Health:](https://web.archive.org/web/20211226012609/https://covidnow.moh.gov.my/)**
People vaccinated: 25,974,497
People fully vaccinated: 25,580,473
Total boosters: 5,389,370

**Comment by edomt** [comment]
Hi @UserFiftyOne 

We update our data based on this file published by the Ministry of Health: https://github.com/CITF-Malaysia/citf-public/blob/main/vaccination/vax_malaysia.csv

It is sometimes updated a bit later than the website you linked to, so you may see small differences depending on when we ran our last update.
