### ISSUE TITLE
Add date to latest dataset

### ISSUE THREAD

**Issue by tmikoss** [owid/covid-19-data#221]
Please add `date` filed in the latest dataset, containing the date of included metrics.

I'm trying to update my dataset daily, and would prefer to use the smaller `latest` file, instead of re-downloading the full dataset.

I can assume that `latest` refers to the previous day, but explicit date would help avoid any errors.

**Comment by edomt** [comment]
Hi @tmikoss 
Unfortunately there is no date we can refer to: in the `latest` file, each metric can come from any day in the last 14 days. Usually, all the cases and deaths (and derived) variables will refer to D–1, so December 19 for today.
But the testing data could be sourced from several days earlier, same for the hospital & ICU data, as well as the vaccination data, etc.
If you really need to know what date each observation refers to, then you'll need the full information from the complete`owid-covid-data` file.

**Comment by tmikoss** [comment]
I see, that makes very much sense. Thank you @edomt for the explanation.

I'll continue using the full data file, and let's hope it doesn't continue growing too long.
