### ISSUE TITLE
Latest data do not match other sources (new cases in USA)

### ISSUE THREAD

**Issue by pepe78** [owid/covid-19-data#2211]
latest data downloaded from your page do not match other sources - for example USA over 500,000 daily cases, while website https://www.worldometers.info/coronavirus/country/us has only 300,000 cases
![COVID_death_ratio](https://user-images.githubusercontent.com/27255946/147685242-1ad9afda-182b-4b12-9951-abee2f322842.png)
.

source for graph:
https://github.com/pepe78/covid

**Comment by edomt** [comment]
Hi @pepe78 

We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues

**Comment by pepe78** [comment]
Thanks! Reported:
https://github.com/CSSEGISandData/COVID-19/issues/5112
