### ISSUE TITLE
Brazil testing data not updated since September

### ISSUE THREAD

**Issue by 3dgiordano** [owid/covid-19-data#2213]
Hi everyone, I know you have been working on migrating testing batches from R to Python and there is some great work going on around it.
I understand since November there is a new version of the batch in python of Brazil and that they have even made adjustments in the last week of December.
In any case, the data of tests carried out for Brazil are not yet updated.

I will notify you of the issue in case you simply missed activating the new batch to leave that information online.

https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=earliest..2022-01-01&facet=none&uniformYAxis=0&pickerSort=asc&pickerMetric=location&Metric=Tests&Interval=New+per+day&Relative+to+Population=false&Align+outbreaks=false&country=~BRA

Regards
David

**Comment by camappel** [comment]
Hi David,

Our [source](https://github.com/wcota/covid19br/) for Brazil reports the [cumulative number](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automated_sheets/Brazil.csv) of tests performed, not the daily change. The grapher only calculates daily change when the cumulative total is reported on three consecutive days. A useful metric for testing capacity when the daily change is not available is our calculation of the [7-day rolling average](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2021-06-09..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Tests&Interval=7-day+rolling+average&Relative+to+Population=false&Align+outbreaks=false&country=~BRA) of the number of tests, which interpolates values for missing days.

Thank you for your feedback and I hope you find this information useful.

Regards,
Cam
