### ISSUE TITLE
Testing data for Bolivia

### ISSUE THREAD

**Issue by dquintani** [owid/covid-19-data#2218]
Hi,

We noticed you were taking too long to update testing and positivity data for Bolivia, the last update is from december 24. 

I run [BoliGráfica](https://www.boligrafica.com), a COVID-19 data platform for Bolivia. You are currently using our data for Bolivia's vaccination data.

If you like you can also use our testing data. It is manually transcribed and validated multiple times a week. 

Just use the "Bolivia" column on any of the following datasets:
- Discarded (ie negative tests): https://github.com/dquintani/covid/blob/main/descartados_acumulados.csv
- Cumulative tests (ie positive + negative tests): https://github.com/dquintani/covid/blob/main/pruebas_acum.csv
- Daily tests (eie cumulative tests daily difference): https://github.com/dquintani/covid/blob/main/pruebas_diarias.csv

Thank you and have a great day
-Diego from BoliGráfica

**Comment by camappel** [comment]
Hi @dquintani,

Thank you for bringing this resource to our attention. I have been unable to access the Ministry of Health's [website](https://minsalud.gob.bo/) since Dec 24, hence the date of the last update; are you still using this source?

We will automate our testing data collection using your repository as part of the next update. 

Kind regards and many thanks,
Cam

**Comment by dquintani** [comment]
Hi camappel,

The sources are essentially the same - both are from the government. The Ministry of Health website has been up and down, but you can also check out the daily reports here: https://unidoscontraelcovid.gob.bo/

But I recommend you just use our data. Thank you and have a great day!
-Diegolin

**Comment by camappel** [comment]
@dquintani,

I have automated testing collection for Bolivia using your GitHub repo; thank you very much for your work on preparing this dataset!

I hardcoded data prior to 2020-03-08 since it is currently missing from your repo.

Thank you again for your hard work,
Cam
