### ISSUE TITLE
Testing data for South Korea

### ISSUE THREAD

**Issue by WWolf** [owid/covid-19-data#2219]
JFYI:

Due to the webpage update, ROK publishes now the daily testing data instead of the cumulative one, and as OWID is probably only crawling this metric weekly, all the positivity rate and test date in OWID is not updated.

Official source: http://ncov.mohw.go.kr/en/bdBoardList.do?brdId=16&brdGubun=161&dataGubun=&ncvContSeq=&contSeq=&board_id=

Official test positivity metric is calculated as (covid case of the particular day) / (test numbers of the preceding day).

I do not know whether this goes against the principles of OWID, but these daily cumulative numbers are still recorded at Asia Regional Information Center at Seoul National University (TOTAL_TEST) on the first google sheet:

https://sites.google.com/view/snuaric/data-service/covid-19/covid-19-data

**Comment by lucasrodes** [comment]
@camappel Did #2217 fix this issue?

**Comment by WWolf** [comment]
Although I do not see the update yet, does this https://github.com/owid/covid-19-data/pull/2217 effectively crawl daily data (also considering time zone differences)? 

Also it seems it does not backfill the missing data points and I wonder whether manual pull request to backfill the missing data would be allowed (I can contribute to that).

**Comment by lucasrodes** [comment]
> Although I do not see the update yet, does this #2217 effectively crawl daily data (also considering time zone differences)?

The update of the global files is scheduled to run in the next hours, tops 24 hours. For now, I have updated [the individual file for South Korea](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automated_sheets/South%20Korea.csv) with the last available data point from 2022-01-05.

This part of [the script](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automations/incremental/south_korea.py) parses the reported date from the source (http://ncov.mohw.go.kr/en/bdBoardList.do?brdId=16&brdGubun=161&dataGubun=&ncvContSeq=&contSeq=&board_id=)

https://github.com/owid/covid-19-data/blob/0f7573f52568f6023f8da7df6df2da456ef308bc/scripts/scripts/testing/automations/incremental/south_korea.py#L30-L34

> Also it seems it does not backfill the missing data points and I wonder whether manual pull request to backfill the missing data would be allowed (I can contribute to that).

The update is incremental, as the source only reports the daily figure (not historical data). A Pull request to backfill the missing data would be very much appreciated, should be editing [this file](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automated_sheets/South%20Korea.csv): 

> P.S. I also wonder how the update would affect the test positivity metric as the official stats has a day difference (covid case reported from the day divided by the test numbers of the preceding day)

The positive rate is computed later in the process by dividing the daily new cases by the daily number of tests, all smoothed over a window of 7 days:

https://github.com/owid/covid-19-data/blob/23dcaaad6c63586565e531e15a25f7ed34e528e2/scripts/scripts/testing/generate_dataset.R#L174-L179

---
Hope this helps

**Comment by WWolf** [comment]
Thank you very much for the detailed response @lucasrodes !

As for the backfill, I will take some time to submit a pull request this weekend (also related: https://github.com/owid/covid-19-data/issues/2225 new hospital admissions).

As for the positivity rate, South Korea official way of calculation is again one day shifted between nominator and denominators, although 7 day smoothed average may not introduce too much variation.

**Comment by WWolf** [comment]
I was working on the backfill, and found out that the testing stats that's in OWID is actually only one type of testing stat. In KDCA publishes two types of testing stats, (a) "Number of suspicious report testing" and (b) "Number of testing at temporary screening stations".

The old OWID testing counts essentially is the cumulative count for the first one and excluded the second one. The number of testing were comparable during the last winter (2020-2021), but for this winter, (b) is about 2-3 times more than (a). KDCA also publishes separate stats of positivity rate for (a) and (b), and the positivity rate is smaller for (b).

At the moment, what is being crawled is (a)+(b). How should I backfill the data? The earliest data that I can access (Korean) for (b) is from 2020-12-18, although the (a) data dates back to 2020-01-20.

**Comment by WWolf** [comment]
I have checked this, (a) is indeed **people tested**, but (b) is in Korean language more like **tests performed**.

But given that:

* the official positive rate calculation equation uses (a)+(b) as denominator (nominator being number of cases, that is people that got covid-19)
* individuals rarely get tested visiting multiple temporary screening stations
* there is a separate **tests performed** metric in official stats that is way way higher (2-3 times)

So I believe (a)+(b) could be assigned as **people tested** and once confirmed will go ahead for a pull request!

**Comment by WWolf** [comment]
I found Korean publication record that (b) is also *people tested*.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/531000/148847037-95743325-6141-4d8e-8718-15c2287e166f.png">

So I will go ahead of doing the pull requests (found out small glitches in the series, will fix and request soon).

**Comment by WWolf** [comment]
I have put the pull request for the backfill.

The following graph compares between the original testing stats in OWID (black) and the testing stats sourced from SNU ARIC (only (a)):
![image](https://user-images.githubusercontent.com/531000/148866537-dc1a43ef-e7dc-4294-94f8-300e0e121f5e.png)

The following is (a)+(b) (after 2020-12-18):
![image](https://user-images.githubusercontent.com/531000/148866600-29ebba7a-dfd5-457e-98ac-96b161e18647.png)

There are small discrepancies in numbers and I double checked few official individual reports that indeed official sources sometimes retrospectively change the numbers by a few (less than 10, usually 1-2).

**Comment by camappel** [comment]
Hi @WWolf ,

I just merged your [pull request](https://github.com/owid/covid-19-data/pull/2245).

Thank you very much for your diligent work. I agree, it looks like 'people tested' is the appropriate label, as we prefer to align our data with the official figures. Great job identifying that the old figures did not include (b) also.

I will work on implementing the one day lag to match the official figures soon.

All the best!

**Comment by lucasrodes** [comment]
Hi @WWolf,
I was checking South Korean data and realized that the data pushed in https://github.com/owid/covid-19-data/pull/2245 is quite different compared to the data reported by [Asia Regional Information Center at Seoul National University (TOTAL_TEST)](https://drive.google.com/file/d/1Ht8ktaxhZ91_wtlPe5gEkQLa-QScoA7S/view).

My understanding is that this is due to what you mentioned

> At the moment, what is being crawled is (a)+(b). How should I backfill the data? The earliest data that I can access (Korean) for (b) is from 2020-12-18, although the (a) data dates back to 2020-01-20.

My understanding is that you have obtained the values for (b) manually, from daily updates, computed the cumulative sum and added to the other tests registered in [SNU ARIC's spreadsheet](https://drive.google.com/file/d/1Ht8ktaxhZ91_wtlPe5gEkQLa-QScoA7S/view). Is that right?

Thanks

**Comment by camappel** [comment]
From what I understand:

1. The figures in [Asia Regional Information Center at Seoul National University (TOTAL_TEST)](https://drive.google.com/file/d/1Ht8ktaxhZ91_wtlPe5gEkQLa-QScoA7S/view) only include 'Number of suspicious report testing'
2. The figures in [Asia Regional Information Center at Seoul National University (Testing)](https://docs.google.com/spreadsheets/d/10c9jNi8VnV0YYCfV_7AZrzBY5l18dOFHEJMIJsP4THI/edit#gid=512078862) have both 'Number of suspicious report testing' and 'Number of testing at temporary screening stations' since 2020-12-18
3. We currently scrape the total of 'Number of suspicious report testing' and 'Number of testing at temporary screening stations'

#2245 by @WWolf used (2.) to get (a)+(b) back to 2020-12-18, then (1.) to get just (a) back to 2020-01-20

**Comment by lucasrodes** [comment]
Hi @WWolf, @camappel 
Thank you so much for the explanation. This helps me a lot. 

We are now thinking if we could potentially automate this import, including historical data, which would ensure this is easier to maintain in the future.

We currently have two metrics: 

1. `Cumulative total`: Total number of people tested so far.
2. `Daily change in cumulative total`: Daily number of people tested.

From now on we can proceed as follows to estimate both metrics:

#### Metric `Cumulative total`

- Take `TOTAL_TEST` from [here](https://drive.google.com/file/d/1Ht8ktaxhZ91_wtlPe5gEkQLa-QScoA7S/view)
- Take `임시선별검사소 검사건수` from [this spreadsheet](https://docs.google.com/spreadsheets/d/10c9jNi8VnV0YYCfV_7AZrzBY5l18dOFHEJMIJsP4THI/edit#gid=512078862).

Compute `people tested = TOTAL_TEST + cumulative(임시선별검사소 검사건수)`

#### Metric `Daily change in cumulative total`
Next, for metric 2 we can simply estimate it by taking the daily difference from metric 1 (the pipeline already does this).

---

Finally, you mention that you have added some manual fixes. Ideally, we should encode these in our script. We can see values between 2022-01-02 and 2022-01-07 might have been manually added.

**Comment by WWolf** [comment]
Hi @lucasrodes,

As for the manual fixes, in my pull request https://github.com/owid/covid-19-data/pull/2245/commits/3d630821be1bed6759f7a5765ccdaeec25008dd4 the Source URLs present the actual daily reports (the attached PDFs) that I parsed to fix it. 2021-12-07 is also fixed (this appears to be a human error from the SNU ARIC). I mainly checked this by myself because the main sheet column value difference from (`TOTAL_TEST`) and the one in testing sheet value (`의심신고 검사자 수`) did not match. 

Just my two cents on the sourcing - I am a bit hesitant of the sourcing cumulative numbers, in particular the `TOTAL_TEST` as the representative metric for (a) from SNU. Reason of my hesitance described below(not objection, just for your further information):

(1) I see evidences that the daily values gets revised, typically in a tiny amount but there are glaring revisions, such as 2022-01-02 to 2022-01-07. This happened because of the year change (2021 -> 2022), KDCA misidentified repeated testing that spanned the year 2021 to 2022 as tests on different individuals, although it was repeated testing on same individuals. They put this correction as a footnote in [2021-01-08 daily report](https://www.kdca.go.kr/board/board.es?mid=a20501010000&bid=0015&list_no=718241&cg_code=&act=view&nPage=2), c.f. PDF page 5. 

(2) Accordingly, they revised the weekly cumulative numbers but I strongly suspect that *they did not revise the total cumulative numbers* (that `TOTAL_TEST` tracks). 

(3) As a result, for example, 2022-01-07 difference is not fixed in `TOTAL_TEST` but is somewhat fixed in `Testing` page of SNU ARIC that track KDCA data. As evidence, as of today, KDCA daily report (containing the most up-to-date 2021-01-07 test metric) does have this test value on 2022-01-07 as 72,725 not 96,665. 

(4) The SNU ARIC has it 72,728, 3 test difference which again is a revised value from 2021-01-08 report. So the daily numbers gets corrected over the course of a week in official sources.

(5) I think SNU ARIC caught this revision on 2021-01-08 because the `Testing` sheet update lags typically one day - the *tests performed* metric has an additional one day delay being reported, and the report contains previous 7 days of testing / case metrics that are revised.

(6) In sum, the `TOTAL_TEST` cumulative value has some errors in my opinion that gets aggregated over long period of time and may not be a good way to represet daily testing volume by getting the difference; SNU ARIC also only partially make retrospective revisions (typically one day). 

(7) My suggestion would be, if you choose to track this site, it would be (partially) more stable to source both (a) and (b) metrics from the same sheet "Testing" - the downside would be that it lags one day of update.

Hope this helps!

**Comment by lucasrodes** [comment]
Thanks, @WWolf,
I understand! Thanks for the response.

If we want cumulative numbers, we still may need the values from `TOTAL_TEST` before "2020-12-18", and then add values from "Testing" cumulatively after the aforementioned date.

cc. @camappel

**Comment by WWolf** [comment]
@camappel Hi, it looks like after 2022-01-10, Korea test data is not being updated properly. Probably related to the refactor? https://github.com/owid/covid-19-data/pull/2262

**Comment by WWolf** [comment]
Korea DCA changed the usual daily statistics on testing as of 2022-02-07. New statistics is coming in as of 2022-02-08. Due to the Omicron wave, they have revamped the whole Test&Trace&Isolate strategy. They switched from collecting the `의심신고 검사자 수` and `임시선별검사소 검사건수` and aggregate now into `선별진료소(통합)`. It could be translated something like `Number of testing at screening stations (Aggregate)`. Based on the numbers, it looks like it is still `people tested` not `test performed`.

Below is a screenshot from 2022-02-09 daily report:

![image](https://user-images.githubusercontent.com/531000/153211635-bff31561-84a6-452a-8857-71d20c38446e.png)

The SNU ARIC also made the change by adding an additional column, `선별진료소(통합)`.

**Comment by camappel** [comment]
감사합니다 @WWolf ,

I have addressed this issue in #2424 .

**Comment by WWolf** [comment]
Dear OWID,

It looks like that [SNU ARIC](https://docs.google.com/spreadsheets/d/10c9jNi8VnV0YYCfV_7AZrzBY5l18dOFHEJMIJsP4THI/edit#gid=334130338) terminated aggregating testing stats such that Korean stats are stale as of 2022-06-15 (the reasoning is that the Korean government officially downgraded the disease for "living with covid"). The government official report regarding testing data is still published daily (in Korean), with some revisions for up to weeks. 

I have added to my github repository a testing data which copied over the SNU ARIC data (with some revisions of the last few days due to revisions). As I update semi weekly the [hospitalization data](https://github.com/owid/covid-19-data/issues/2225#issuecomment-1054514679), I will update this as well for your reference (because I am updating roughly weekly, some of the days will have minor discrepancies due to later revisions). Hope this helps. @lucasrodes @camappel 

https://github.com/WWolf/korea-covid19-hosp-data/blob/main/testing.csv
