### ISSUE TITLE
Heads up: planned modification to vaccination data for Peru

### ISSUE THREAD

**Issue by jmcastagnetto** [owid/covid-19-data#2228]
@lucasrodes 

As you are aware, while looking into the issue your reported earlier (https://github.com/jmcastagnetto/covid-19-peru-vacunas/issues/5), I was able to determine that the most recent dataset of vaccinations in Peru, contains information from a mix of sources:

(a) The general vaccination campaign
(b) Clinical studies conducted in 2020 and part of 2021
(c) Peruvians who travel abroad to get vaccinated

In order to be able to try and distinguish (a) from ((b) + (c)), I used the official dates where the first lot of vaccines from each particular manufacturer arrived in Peru, and will be adding a new column: `flag_vacunacion_general`, which will be assigned according to the following criteria:

```
flag_vacunacion_general = if 
  (fabricante == "SINOPHARM" & fecha_vacunacion > 2021-02-07) |
  (fabricante == "PFIZER" & fecha_vacunacion > 2021-03-03) |
  (fabricante == "ASTRAZENECA" & fecha_vacunacion > 2021-04-18) 
then
  TRUE
else
  FALSE
```

For OWID, this change will affect:

- The summary data at: https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/main/datos/vacunas_covid_resumen.csv, where there will be one more column (_vide supra_):

```
$ head -5 vacunas_covid_resumen.csv
fecha_corte,fecha_vacunacion,fabricante,dosis,flag_vacunacion_general,n_reg
2022-01-04,2020-04-27,SINOPHARM,1,FALSE,1
2022-01-04,2020-05-08,PFIZER,2,FALSE,1
2022-01-04,2020-09-09,SINOPHARM,1,FALSE,12
2022-01-04,2020-09-10,SINOPHARM,1,FALSE,2
``` 

- The totals by manufacturer at: https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/main/datos/vacunas_covid_fabricante.csv

```
$ head -5 vacunas_covid_fabricante.csv 
location,date,vaccine,vaccinations,total_vaccinations,flag_vacunacion_general
Peru,2020-04-27,Sinopharm/Beijing,1,1,FALSE
Peru,2020-05-08,Pfizer/BioNTech,1,1,FALSE
Peru,2020-09-09,Sinopharm/Beijing,12,13,FALSE
Peru,2020-09-10,Sinopharm/Beijing,2,15,FALSE
```

It will not affect the summary by age group, at: https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/main/datos/vacunas_covid_rangoedad_owid.csv -- In fact, now that I have this flag, I am excluding from those counts the records that may not correspond to the general vaccination campaign.

I am planning on implementing this change for the dataset that I will be processing next Sunday (2021-01-09)

**Comment by edomt** [comment]
@lucasrodes FYI the new column is here now 🙂
I'll let you decide how to change our script

**Comment by jmcastagnetto** [comment]
Yep, sorry, was doing a change to start using Apache Arrow to store the intermediate results (much better performance than my previous approach), and awhile doing that also committed the code and data for the new flag. 

Should've kept them in two different branches.

Next update will be on Sunday, to be able to get the complete first epiweek of 2022

**Comment by lucasrodes** [comment]
Awesome, Thanks @jmcastagnetto!

Will be adding a filter on our end to only account for vaccination campaign data.

**Comment by jmcastagnetto** [comment]
@lucasrodes 
FYI - MINSA has not updated vaccination data since 2022-02-17. Have just rechecked again today (2022-02-20, 12:15h PET), and still no change.

Sorry for just commenting here, but did not considered that this heads up needed a new issue.

**Comment by lucasrodes** [comment]
Thanks for the heads up @jmcastagnetto!
