### ISSUE TITLE
Add Apple Mobility Trends

### ISSUE THREAD

**Issue by garas** [owid/covid-19-data#223]
Similar to Google Mobility Trends, Apple reports [Mobility Trends](https://covid19.apple.com/mobility) too.

Apple tracks _movement_ (driving/transit/walking) trends, Google tracks _location_ trends, so it doesn't duplicate, but adds additional information.

Apple data is fresher, so it allows faster look at effect after government changes of movement restrictions.

**Comment by rcsmit** [comment]
FYI Here you see the correlation between Apple and Google, with Rt

![image](https://user-images.githubusercontent.com/1609141/109558768-1e047580-7ada-11eb-9e44-9bd156fa4739.png)
