### ISSUE TITLE
Isle of Man cases very high compared to authoritative source

### ISSUE THREAD

**Issue by DrBazUK** [owid/covid-19-data#2231]
Hi Team, I suspect the issue lies with JHU so will also flag on their system but Isle of Man in the feed from JHU appears to be 3-4K higher than the [Ministry of Health](https://covid19.gov.im/general-information/latest-updates/) on the island.

Currently total from JHU is: 17,948 cases, MOH has it at 13,475 and there's no new data on the dashboard since 5/Jan.

Could you investigate?

Thanks in advance,
Baz

**Comment by lucasrodes** [comment]
Hi @DrBazUK,
Thanks for reporting.

I will be closing this thread in favour of the discussion in https://github.com/CSSEGISandData/COVID-19/issues/5163.
