### ISSUE TITLE
owid-covid-data.json seems to be double JSON encoded?

### ISSUE THREAD

**Issue by janole** [owid/covid-19-data#2236]
The data from `https://covid.ourworldindata.org/data/owid-covid-data.json` seems to be double JSON encoded:

```
"{\"AFG\":{\"continent\":\"Asia\",\"location\":\"Afghanistan\",\"population\":39835428.0,\"populatio...
```

Can you have a  look at it?

Cheers & many thanks for your wonderful service,
Ole

**Comment by lucasrodes** [comment]
Hi @janole,
Thank you for reporting this.

I just fixed this. We were precisely double-encoding the file.

**Comment by janole** [comment]
@lucasrodes Thank you very much 👍
