### ISSUE TITLE
Fully vaccinated - Slovakia

### ISSUE THREAD

**Issue by MartinHBA** [owid/covid-19-data#2237]
hello, you are reporting 45% fully vax for Slovakia, based on your description you are calculating from 
https://github.com/Institut-Zdravotnych-Analyz/covid19-data
however seems that it's somehow miscalculated or some problem there. Based on ECDC data (European CDC) collecting daily from all member states,  Slovakia is 48% at the moment, you can use ECDC vaccination data from here:
https://www.ecdc.europa.eu/en/publications-data/data-covid-19-vaccination-eu-eea

**Comment by lucasrodes** [comment]
Hi @MartinHBA,
Thanks for your message.

I answer your points below:

> hello, you are reporting 45% fully vax for Slovakia, based on your description you are calculating from https://github.com/Institut-Zdravotnych-Analyz/covid19-data however seems that it's somehow miscalculated or some problem there.

Based on the [official data provided](https://github.com/Institut-Zdravotnych-Analyz/covid19-data/blob/main/Vaccination/OpenData_Slovakia_Vaccination_Regions.csv), we report the following figures:

- Total number of doses administered: 6,183,563
- People with at least one dose: 2,723,718
- People fully vaccinated: 2,438,400
- Total number of booster doses administered: 1,021,445

Together with the [UNWPP estimate on population](https://population.un.org/wpp/Download/Standard/CSV/) for Slovakia of 5,460,726 we obtain the per-capita metrics.

> Based on ECDC data (European CDC) collecting daily from all member states, Slovakia is 48% at the moment, you can use ECDC vaccination data from here: https://www.ecdc.europa.eu/en/publications-data/data-covid-19-vaccination-eu-eea

We lean towards using official national reports as they usually provide more frequent data updates when compared to ECDC, which reports [twice a week](https://www.ecdc.europa.eu/sites/default/files/documents/Variable_Dictionary_VaccineTracker-04-11-2021.pdf).

I hope that this helps.

**Comment by MartinHBA** [comment]
I now fully understand where is problem, you are using column with doses but taking "fully" from it. this "fully" is based on 2 weeks after 2nd shot of mRNA vaccina and 3 weeks after single shot vaccine Jenssen. This is epidemiology info about "fully protected" individual, not "fully vaccinated" person in terms of having 2 doses. If you take 2 doses and all 1st doses of Jenssen you would see 48% same as ECDC is showing.

**Comment by lucasrodes** [comment]
Hi @MartinHBA,
I am not sure if I understand you correctly, but we currently obtain the number of fully vaccinated people by adding the number of administered second doses and first doses of Janssen (see [here](https://github.com/owid/covid-19-data/blob/d58d1a6ba0ba079b0cd6e79f7dc1393d8a15c76f/scripts/src/cowidev/vax/batch/slovakia.py#L59)).

**Comment by MartinHBA** [comment]
hi @lucasrodes, here is table from file with doses and numbers, if you take 2nd doses of all other vaccines and 1st doses administered of JANSSEN you will get 2,621,728 in total (fully vax) not  2,438,400
![image](https://user-images.githubusercontent.com/49184077/148697541-2fc1854a-6a3e-463d-ae1e-8fa267fafae0.png)

**Comment by lucasrodes** [comment]
Hi @MartinHBA,
Could you share more details on where the table that you share originates from? Which file/URL are you using?

Thanks

**Comment by MartinHBA** [comment]
hi @lucasrodes , it's this one:
https://github.com/Institut-Zdravotnych-Analyz/covid19-data/blob/main/Vaccination/OpenData_Slovakia_Vaccination_AgeGroup_District.csv

**Comment by lucasrodes** [comment]
Thanks for bringing this to our attention, @MartinHBA.

I found a small bug and just corrected it. The data will be live in the next hours, but in the meantime, you can find a preliminary version for Slovakia [here](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/Slovakia.csv).

Thanks once again for your help

**Comment by MartinHBA** [comment]
@lucasrodes thx for updating code. I've closed issue. 
However after  that I've noticed that still your fully vax number is only 2580269, compared to table above is still lot less 🤷‍♂️

**Comment by MartinHBA** [comment]
See last comment pls

**Comment by lucasrodes** [comment]
There appear to be differences in the file that we currently use (https://github.com/Institut-Zdravotnych-Analyz/covid19-data/blob/main/Vaccination/OpenData_Slovakia_Vaccination_Regions.csv) and the one that you cite (https://github.com/Institut-Zdravotnych-Analyz/covid19-data/blob/main/Vaccination/OpenData_Slovakia_Vaccination_AgeGroup_District.csv).

As both come from the same source, I opened an issue in their project and will be closing this thread.

Thanks for your help!

**Comment by MartinHBA** [comment]
hi @lucasrodes , seems they close it with suggestion not to use regions anymore, will you please update your Python code to use different CSV as source?

**Comment by lucasrodes** [comment]
Refactor done in fc4edda83da25fa897ef3b984b1e30e7d6655915

**Comment by MartinHBA** [comment]
@lucasrodes , much appreciated! I love your Python code, nice and sleek ;)
