### ISSUE TITLE
World Total Cases total incorrect

### ISSUE THREAD

**Issue by Desiato66** [owid/covid-19-data#224]
By adding a column and a simple formula you can see that Todays World Case Total does not equal Yesterdays World Total Cases + Todays New Cases. [https://photos.app.goo.gl/KN4xLvCi7oRFvnqM7]

Edit. A similar thing happens with the Total Deaths column for the World when adding the previous days deaths.

**Comment by edomt** [comment]
Hi @Desiato66 
Thank you, this should be fixed now.
