### ISSUE TITLE
dead link to subnational_cases_deaths.zip

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#2241]
The link `https://covid.ourworldindata.org/public/data/jhu/subnational_cases_deaths.zip` in the README.md at https://github.com/owid/covid-19-data/tree/master/public/data is dead.

**Comment by lucasrodes** [comment]
Hi @czka,
Thanks for your mesage.


The correct link is: https://covid.ourworldindata.org/data/jhu/subnational_cases_deaths.zip, without the `public/` part. You can find more details [here](https://github.com/owid/covid-19-data/tree/master/public/data#stable-urls) and in github.com/owid/covid-19-data/discussions/2082

**Comment by czka** [comment]
@lucasrodes Thanks! Now I know. But the [README.md](https://github.com/owid/covid-19-data/blob/master/public/data/README.md?plain=1#L142) still points at that non-existent URL .

Is that as intended? Going to be fixed later maybe?

**Comment by lucasrodes** [comment]
Thanks for reporting this, @czka. I have fixed the link and should be live soon.

**Comment by edomt** [comment]
@lucasrodes I had already fixed it in f65b1f96de8e3364ae04441a23cafeb77b70732e. I'm reverting 308c0ae
