### ISSUE TITLE
JSON data missing in latest update

### ISSUE THREAD

**Issue by sumedhdev** [owid/covid-19-data#2243]
The file `/public/data/owid-covid-data.json` appears to be missing in the latest update. If you could please update this ASAP it would be much appreciated, as my site uses this data to function.

Thank you for the work you do!

**Comment by lucasrodes** [comment]
Hi @sumedhdev, 
Thanks for your message.

The file has been moved to another location and is now exposed via https://covid.ourworldindata.org/data/owid-covid-data.json. You can find more details [here](https://github.com/owid/covid-19-data/tree/master/public/data#stable-urls) and in #2082.

**Comment by sumedhdev** [comment]
Hi @lucasrodes 
Thank you for your reply. I am getting a CORS error trying to access `https://covid.ourworldindata.org/data/owid-covid-data.json`

Error: `No 'Access-Control-Allow-Origin' header is present on the requested resource`

Accessing `https://covid.ourworldindata.org/data/latest/owid-covid-latest.json` is working fine.

Could you please confirm `Access-Control-Allow-Origin: *` is present? 

Thanks

**Comment by lucasrodes** [comment]
How are you accessing the file?

**Comment by lucasrodes** [comment]
We added some changes, let me know if it works @sumedhdev

**Comment by sumedhdev** [comment]
@lucasrodes thank you, it works now :)
