### ISSUE TITLE
Updates to data reported by Israel

### ISSUE THREAD

**Issue by Aric5301** [owid/covid-19-data#2244]
Hi!
Israel has started vaccinating the elderly population and the health staff with a second booster.
Exact data can be fetched from here:
[https://datadashboardapi.health.gov.il/api/queries/vaccinated](https://datadashboardapi.health.gov.il/api/queries/vaccinated)

In addition, with Omicron cases rising rapidly and PCR testing reaching max capacity, Israel now has major use of antigen tests to determine sickness. Exact amount of tests split by PCR and antigen can be fetched from here:
[https://datadashboardapi.health.gov.il/api/queries/testsPerDate](https://datadashboardapi.health.gov.il/api/queries/testsPerDate)

for the total amount of tests performed and the daily positivity rate, use:
[https://datadashboardapi.health.gov.il/api/queries/testResultsPerDate](https://datadashboardapi.health.gov.il/api/queries/testResultsPerDate)

And in general, here's a regularly-updating list of all possible API queries from Israel's dashboard:
[https://github.com/erasta/CovidDataIsrael/blob/master/jsons/dashreq.json](https://github.com/erasta/CovidDataIsrael/blob/master/jsons/dashreq.json)

**Comment by edomt** [comment]
Tagging:
- @lucasrodes for the fourth dose
- @camappel to look into whether this can improve our testing data

**Comment by edomt** [comment]
Hi @Aric5301 

It seems that the government has made a few changes to https://datadashboardapi.health.gov.il/api/queries/patientsPerDate, which we were using for our hospital data.

Out of all the files currently in https://github.com/erasta/CovidDataIsrael/tree/master/out/csv, do you know if/where we can find:
- New hospital admissions (flow of patients)
- Daily hospital occupancy (stock of patients)
- New ICU admissions (flow of patients)
- Daily ICU occupancy (stock of patients)

Thanks!

**Comment by Aric5301** [comment]
Hey. I contacted our health ministry for additional information.
In the meantime:

**Daily hospital occupancy**
Sum over all fields here(countHardStatus, countMediumStatus, countEasyStatus):
[https://datadashboardapi.health.gov.il/api/queries/hospitalizationStatusDaily](https://datadashboardapi.health.gov.il/api/queries/hospitalizationStatusDaily)

**Comment by edomt** [comment]
Great, thank you! Do you think that `countHardStatus` could be considered ICU patients? (Is there a definition somewhere of what hard/medium/easy means?)

**Comment by camappel** [comment]
The testing data collection script for [Israel](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automations/batch/israel.py) has now been updated to extract only _diagnostic tests_; I believe the previous script was scraping figures that included serological tests.

**Comment by Aric5301** [comment]
> Great, thank you! Do you think that `countHardStatus` could be considered ICU patients? (Is there a definition somewhere of what hard/medium/easy means?)

Here's the official definition of hard status:
Patients who have been verified with one or more of the following conditions:
1. Over 30 breaths per minute
2. Saturation lower than 93% without external support or a disturbance to oxygen "turnover" (I'm now sure how to translate it to English)
3. PaO2/FiO2 ratio lower than 300

Also, for now, hard patients count also includes critical patients.

I'm not a doctor so I can't really tell if it means that they are in ICU, all I can do is translate and ask the Israeli MOH (they unfortunately haven't responded to me yet)..
I'll keep looking for alternative sources and keep you up to date!

**Comment by dancarmoz** [comment]
Hi, just giving a couple of cents here, as someone also scraping the Israeli dashboard and in contact with some of the developers:

I think the countHardStatus (and its "flow" value, which is serious_critical_new - "hard" is literally the same word as "serious" in Hebrew, in this sense) are the closest approximations to ICU patients that are likely to be available in the dashboard at least in the near future. Critical condition stock used to be available, which may be closer in meaning, but critical condition flow had not been available so far.

New hospital admissions is not currently available at all, and neither is the daily hospital occupancy. Aric's suggestion for adding up easy/medium/hard to get occupancy is a reasonable approximation, but looking at past data, is not quite exact (possibly some patients are counted in more the one category, if their condition changed during the day?).

According to the dashboard developers, all fields that used to be under the patientsPerDate query should be reinstated soon, including the new/daily hospital occupancies, hopefully by early next week.

**Comment by dancarmoz** [comment]
> The testing data collection script for [Israel](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automations/batch/israel.py) has now been updated to extract only _diagnostic tests_; I believe the previous script was scraping figures that included serological tests.

My understanding is that the (relatively small) difference between the amount of tests results, and numResultsForVirusDiagnosis (available under both testsPerDate and testResultsPerDate, btw), is the number of tests taken by patients already verified with the virus, i.e. they are tested to check for recovery rather than diagnosis of infection. I think serological tests are not reported in the dashboard at all.

(According to dashboard devs, repeating positive results are ignored for 90 days after the latest unignored positive; after 90 days, they are counted as a reinfection.)

**Comment by camappel** [comment]
@dancarmoz Thank you for clarifying!

**Comment by Aric5301** [comment]
Hi.
I still haven't got a reply back from the Israeli MOH, but it seems that updates were made to the API:

**New ICU admissions (flow of patients)**
[https://datadashboardapi.health.gov.il/api/queries/patientsPerDate](https://datadashboardapi.health.gov.il/api/queries/patientsPerDate)
Use _serious_critical_new_.

**Daily ICU occupancy (stock of patients)**
[https://github.com/erasta/CovidDataIsrael/blob/master/out/csv/sickPerDateTwoDays.csv](https://github.com/erasta/CovidDataIsrael/blob/master/out/csv/sickPerDateTwoDays.csv)
Use _amount_ of _critical_, and get "per date" data from this GitHub repository's history folder.

**Daily hospital occupancy (stock of patients)**
[https://datadashboardapi.health.gov.il/api/queries/hospitalizationStatusDaily](https://datadashboardapi.health.gov.il/api/queries/hospitalizationStatusDaily)
Sum over all fields(countHardStatus, countMediumStatus, countEasyStatus). I tested this data with the data displayed on the dashboard as "Currently hospitalized" and it's the same number.

I still can't find data for "New hospital admissions (flow of patients)".

By the way, you can also get the amount of daily _Patients ventilated_ (I saw that you are displaying this data for the UK) from here:
[https://github.com/erasta/CovidDataIsrael/blob/master/out/csv/sickPerDateTwoDays.csv](https://github.com/erasta/CovidDataIsrael/blob/master/out/csv/sickPerDateTwoDays.csv)
Use _amount_ of _breath_, and get "per date" data from this GitHub repository's history folder.
