### ISSUE TITLE
time resolution of Portugal's data in owid-covid-data.csv

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#2258]
I used to blindly assume that all data in `owid-covid-data.csv` are daily. Until a moment ago, when I noticed by accident that few initial Portugal's records (Jan-Feb 2020) are kinda-biweekly.

Is this an error? If it isn't, is Portugal just one exception and all the other countries' data are daily, or are such irregularities to be expected in other places in `owid-covid-data.csv`?

It would be great if a clarification on this could be added to https://github.com/owid/covid-19-data/blob/master/public/data/README.md.

**Comment by lucasrodes** [comment]
Hi @czka,
Thanks for the message.

Could you perhaps elaborate on which metrics/dates you observed this behaviour?

Also, the earliest month that I observe in the dataset for Portugal is March 2020:

`In [1]`
```python
import pandas as pd

url = "https://covid.ourworldindata.org/data/owid-covid-data.csv"
df = pd.read_csv(url)
df[df.iso_code.isin(["PRT"])].date.min()
```
`Out[1]`
```
2020-03-01
```

Thanks!

**Comment by lucasrodes** [comment]
Thanks for getting back, @czka!

As you mention, there was data prior to 2020-03-01 before the automated update ran on 12bed0d48702f6bda10c76fa1d895502a110a226. In previous commits 0f888095042d660bf3bb9e60a98e65392e52fe08 and https://github.com/owid/covid-19-data/commit/06157a01f05f1a2505896ad060b2cba2c6f39937 we changed our source for hospitalizations for Portugal from ECDC to https://github.com/dssg-pt/covid19pt-data/.

So the data points that we were observing prior to 2020-03-01 were likely coming from ECDC hospitalization dataset.


<details closed>
<summary>Experiment</summary>

As a check, the data displayed for Portugal for early 2020 in the old dataset is hospitalization-related.

```python
# Get old dataset
url = f"https://raw.githubusercontent.com/owid/covid-19-data/07d595fa10868985458bcc2a1ee77d2f29a9b2c1/public/data/owid-covid-data.csv"
df = pd.read_csv(url)
# Filter: Only Portugal prior to 2020-03-01
x = df[df.iso_code.isin(["PRT"]) & (df.date<"2020-03-01")]
# Remove all NaN columns
x = x.dropna(how="all", axis=1)
# Display
display(x)
```
</details>

As per

> Still, it did happen that Portugal had this few bi-weekly records. Was it normal or an error? Should I not assume all records in owid-covid-data.csv to be always daily?

The records in `owid-covid-data.csv` correspond to the date under column `date`. Note that, as you may already know, some fields are weekly, like `weekly_icu_admissions`, or cumulative `total_deaths`.

In this example for Portugal, the hospitalization data coming from ECDC was sparse, hence the time gaps.

**Comment by edomt** [comment]
You can expect to always see daily data going forward, because cases, deaths, and vaccinations are counted daily.

What can happen is that at the start of the pandemic, before the counting of cases & deaths began, sometimes there can be individual records for variables such as testing or hospitalizations. But that will very rarely be the case.
