### ISSUE TITLE
Widespread Data Messup Jan 14th

### ISSUE THREAD

**Issue by SimonMac54** [owid/covid-19-data#2259]
Problems in the World and US State vac files. Lots of places where the CSV files jump to  what looks like daily data instead of being cumulative. It appears most in smaller countries, common in States file, and not at all in the biggest countries. Just list the file and you'll see the problem is widespread.  My guess would be that the problem occurs when there is missing data, common in the smaller countries, and this is being filled in a rogue way.

Attached shows example
![Screenshot from 2022-01-14 08-27-33](https://user-images.githubusercontent.com/97726759/149475953-ef6fefb2-5b5c-420e-ab9e-dbd9e1276f1f.png)

Good luck sorting it out

**Comment by edomt** [comment]
Hi @SimonMac54 

This looks like an issue on your side - perhaps with the way you instructed LibreOffice to process the file when opening it? Everything looks fine on our end:

<img width="911" alt="image" src="https://user-images.githubusercontent.com/7103774/149484135-e09617a7-a5cc-4b10-9a38-6d25c65efe0d.png">

**Comment by SimonMac54** [comment]
Real Sorry about that. You are right.
I have imported CSV with a 'merge empty cells' accidently ticked. So empty cells overwritten by other data to the right.
Have imported here and elsewhere so many 100s of times without incident - but there is always a first time.
Have a good day - will close issue
Simon
