### ISSUE TITLE
Sweden: Tests and positivity broke

### ISSUE THREAD

**Issue by bjornpiltz** [owid/covid-19-data#2261]
FYI. Keep up the good work!

![coronavirus-data-explorer (13)](https://user-images.githubusercontent.com/1873764/149501766-ee65261d-1836-47fd-9b4b-b934e899d11b.png)

**Comment by Rouein** [comment]
If only their was an alternative source. The official website of ministry posts only weekly data!

**Comment by lucasrodes** [comment]
Hi @bjornpiltz,
Thanks for reporting.

There was a gap in our data for tests in Sweden. I have back-filled using the [Internet Archive](https://archive.org/) for our current source https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/statistik-och-analyser/antalet-testade-for-covid-19/.


Our live chart has been updated accordingly

![coronavirus-data-explorer(52)](https://user-images.githubusercontent.com/18101289/150969458-f3b74d52-6f1a-4f3c-af21-b800b8257785.png)

**Comment by Rouein** [comment]
I am working on converting the script to python and have created a new data set using https://www.folkhalsomyndigheten.se/ weekly reports to get an accurate Cumulative total.
