### ISSUE TITLE
people_fully_vaccinated Data for Indonesia Not Showing After 14/03/2021

### ISSUE THREAD

**Issue by tllkrmn** [owid/covid-19-data#2267]
Indonesia's people_fully_vaccinated data seem stalled after 14/03/2021.

**Comment by edomt** [comment]
Hi @tllkrmn 

I've fixed our script to calculate `people_fully_vaccinated` until September 2021. After that, vaccination with the J&J vaccine started, and the data reported by the government makes us unable to calculate `people_fully_vaccinated` (the reported metrics are only "first doses" and "second doses", but we could need "unique doses" as well).
