### ISSUE TITLE
Israel: Deaths by vaccination status

### ISSUE THREAD

**Issue by Aric5301** [owid/covid-19-data#2274]
Hi.
Israel reports death by vaccination status:
[https://datadashboardapi.health.gov.il/api/queries/deathVaccinationStatusDaily](https://datadashboardapi.health.gov.il/api/queries/deathVaccinationStatusDaily)

Data is split into three age groups: Above 60 ("מעל גיל 60"), Below 60 ("מתחת לגיל 60"), and whole population ("כלל האוכלוסיה").

- _death_amount_vaccinated_
Absolute number of deaths of people who received their latest dose (2nd, 3rd or 4th) less than 6 months and 1 week ago (two weeks for Moderna vaccines) **or** have recovered from COVID-19 and received at least one dose less than 6 months and 1 week ago (two weeks for Moderna vaccines).

- _death_amount_expired_ = Absolute number of deaths of people who received their 2nd dose more than 6 months and 1 week ago (two weeks for Moderna vaccines) and didn't receive boosters.

- _death_amount_not_vaccinated_ = Absolute number of deaths of people who didn't get a vaccine.

**Comment by edomt** [comment]
Hi @Aric5301 

Thank you! For now we won't be adding new charts to [our existing post](https://ourworldindata.org/covid-deaths-by-vaccination), but I've added Israel to the table at the bottom of the page in case other people want to look into it!
