### ISSUE TITLE
United Kingdom data

### ISSUE THREAD

**Issue by RiccardoBorchi** [owid/covid-19-data#228]
Hello,

why the vaccinations data of United Kingdom are separated?

There are data of Scotland, Galles, Norther Ireland and United Kingdom. Could you merge in one single data for UK?

Thank you.

**Comment by edomt** [comment]
Hi @RiccardoBorchi 

This is already the case, you can find data for the whole of the UK in our files: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv

<img width="505" alt="image" src="https://user-images.githubusercontent.com/7103774/103075181-6465c180-45cb-11eb-9732-62413cd711ef.png">

But we also have separate lines for subnational UK data (although they have been published quite irregularly so far).

**Comment by RiccardoBorchi** [comment]
Hi @edomt,

thank you for your quick reply!

Ok, so the data of United Kingdom are cumulated. In this case, in my application, I have simply to hide the subnational UK data.

Thank you!

Best Regards.

**Comment by salgo60** [comment]
For a non UK person this is confusing. Regarding my [Notebook](https://github.com/salgo60/CoronaVaccinationCheck/blob/main/Check%20Corona%20Vaccination.ipynb)
- We have a total abt. 3229832
- Unique "countries" reported are
![image](https://user-images.githubusercontent.com/14206509/103128987-6eed8d00-4697-11eb-8a2b-f17f4989ea41.png)
 
**OT question:** what is the process to get the numbers from Sweden into your numbers?

Regarding to this [official source](https://www.regeringen.se/artiklar/2020/12/vaccinering-mot-covid-19-inleds-den-27-december/)  are we getting Pfizer/BioNTechs vaccine  9 750 doses and the vaccination will start on 27 dec

**Comment by edomt** [comment]
@salgo60 As soon as numbers become available for Sweden, we'll add them to our data. If you know that numbers have been published somewhere, but you don't see them appear in our data after 24 hours, feel free to open an issue here.
