### ISSUE TITLE
Vax by age: No time series for Czechia?

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2282]
There seems to be an issue here: https://ourworldindata.org/grapher/covid-vaccine-by-age?country=~CZE
(or maybe the ECDC data is really like that?)

**Comment by lucasrodes** [comment]
Thanks for bringing this up! I am looking into it

There appear to be two major issues in the pipeline:

1. Some countries (e.g. France, Slovenia, Italy, etc.) lack updated data. Some countries are discarded as they do not meet some "field requirements". Will try to relax this some all countries have up to date data.
https://github.com/owid/covid-19-data/blob/1ab32361ac2b517e11158e07b1aabe889a8f99d0/scripts/src/cowidev/vax/batch/ecdc.py#L211-L221
2. More strict filters are discarding some entries, most of Czechia's data for instance.
https://github.com/owid/covid-19-data/blob/1ab32361ac2b517e11158e07b1aabe889a8f99d0/scripts/src/cowidev/vax/batch/ecdc.py#L223-L243

**Comment by lucasrodes** [comment]
Should be fixed!

**Comment by edomt** [comment]
All good, thanks :)
