### ISSUE TITLE
Vax by age: sudden drop in Jersey data

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2284]
(Low priority)

Data for Jersey as this weird artifact:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/7103774/150094564-d268b685-c721-4026-b8a7-4cdcbde7b953.png">

**Comment by lucasrodes** [comment]
Fixed and live

![covid-vaccine-by-age](https://user-images.githubusercontent.com/18101289/151226557-f4d9c038-c89d-4682-8760-aca840deceb7.png)
