### ISSUE TITLE
Albania tests

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2289]
Albania is missing about 7 months of test data

**Comment by edomt** [comment]
Hi @Rouein 

Can you please expand on your description of the issue? Do you mean that it's a bug, or that the data is simply missing? (Sadly there a many countries for which there was no official data on testing for part of the pandemic)
If the data exists somewhere, can you please point us to where it is?

Thanks

**Comment by Rouein** [comment]
When I wrote the python script for Albania I tested it and noticed the last data on the sheet is from 2021-06-13 but the link in the R script which I used seems to have updates 3 to 4 times a week.

**Comment by Rouein** [comment]
from here which is the 49th page you can find the next data point(2021-06-14) till today(1st page)

**Comment by Rouein** [comment]
I am able to recover the data I will push as soon as it is finished

**Comment by Rouein** [comment]
The data is recovered now , pending merge.
