### ISSUE TITLE
Australia vaccination by age missing 

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2296]
The website for the Australian Government, Department of health is providing the data for doses administered for all age groups(5-95+):
https://www.health.gov.au/resources/collections/covid-19-vaccination-vaccination-data

**Comment by Aadi1101** [comment]
I want to work on this issue can you assign this issue to me , also I wanted a description for the issue like I know data analysis is expected but want to know more about the same

**Comment by edomt** [comment]
Hi @Rouein 

Can you expand on what you mean by "Australia vaccination data missing"? It seems like our time series are complete here: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Australia.csv

**Comment by Rouein** [comment]
I meant in : https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations-by-age-group.csv

**Comment by Rouein** [comment]
Australian government is providing the data but it is not collect!

**Comment by Rouein** [comment]
Based on what I could see the vaccination data of Australia(Batch) is collected from: https://covidbaseau.com/ 
but even they are providing the age group data.

**Comment by Rouein** [comment]
you can find that data in : https://covidbaseau.com/historical/?title=Vaccinations%20By%20Age%20Group%20and%20State%20First&return=https://covidbaseau.com/vaccinations/
for 1st dose and 
https://covidbaseau.com/historical/?title=Vaccinations%20By%20Age%20Group%20and%20State%20Second&return=https://covidbaseau.com/vaccinations/
for fully vaccinated
