### ISSUE TITLE
Wrong data points for Israel?

### ISSUE THREAD

**Issue by Randl** [owid/covid-19-data#2299]
It appears that number of new cases for Israel lists 0 for 17 and 18 of January and then 243k for 19th. This doesn't fit official data I could find, e.g., https://datadashboard.health.gov.il/COVID-19/general
Possibly somehow two days were not parsed and then all the cases from three days were summed up into 19th?

**Comment by edomt** [comment]
Hi @Randl 

We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues
