### ISSUE TITLE
Current issues with testing scripts

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2301]
[High priority for the week of January 24]

- [x] https://github.com/owid/covid-19-data/pull/2307, https://github.com/owid/covid-19-data/pull/2317
- [x] https://github.com/owid/covid-19-data/pull/2318
- [x] https://github.com/owid/covid-19-data/pull/2302
- [x] Jamaica: not updated since 2022-01-08
- [x] https://github.com/owid/covid-19-data/pull/2305
- [x] https://github.com/owid/covid-19-data/pull/2313
- [x] https://github.com/owid/covid-19-data/pull/2308
- [x] https://github.com/owid/covid-19-data/issues/2261, https://github.com/owid/covid-19-data/issues/2319
- [x] https://github.com/owid/covid-19-data/pull/2310
- [x] #2320, #2322

**Comment by edomt** [comment]
El Salvador fixed in e780e67b895a4e5e2c208ea2666d5f653c53b09d

**Comment by 3dgiordano** [comment]
Hi @edomt 

For Peru I did something
Peru ->  https://github.com/owid/covid-19-data/pull/2302

**Comment by Rouein** [comment]
Hi @edomt,

I checked Laos's source link and it is missing the test data.
I guess it has something with Laos's health ministry [website](http://www.health.gov.la/) being down .

**Comment by 3dgiordano** [comment]
Hi @edomt and @Rouein 
The current source of Laos is a outdated dashboard.

The 2 alternative sources
- The main site (incremental web scrapping)   https://www.covid19.gov.la/index.php
- Official Facebook account (web scrapping + OCR) https://www.facebook.com/CCEH.MoH.Lao/photos

I couldn't find any other alternative source on the internet.

**Comment by Rouein** [comment]
Moldova #2305

**Comment by 3dgiordano** [comment]
Hi @edomt and @Rouein 

I solved how to get all the data from El Salvador.
I'll give you an example of a batch at the end of the day.
It will be an example so that you can see how to process and not have to use scrapping.
I mention it so as not to overlap each other.

Regards

**Comment by Rouein** [comment]
@3dgiordano I am concentrating on Moldova for now

**Comment by Rouein** [comment]
Moldova fully resolved!

**Comment by 3dgiordano** [comment]
El Salvador -> https://github.com/owid/covid-19-data/pull/2307

Inside the PR, I attach the CSV in case it can be useful while evaluating the code.

**Comment by 3dgiordano** [comment]
Hi @edomt and @Rouein

El Salvador -> https://github.com/owid/covid-19-data/pull/2307

Inside the PR, I attach the CSV in case it can be useful while evaluating the code.

**Comment by Rouein** [comment]
&rarr; Libya #2308

**Comment by Rouein** [comment]
Jamaica publishes the data in images.

**Comment by Rouein** [comment]
For Ethiopia the source has stopped at 2021-12-31
an alternative could be collecting total cumulative data incrementally from : https://www.moh.gov.et/site/

**Comment by 3dgiordano** [comment]
Jamaica, the best alternative is to use the same page, by paginating it is possible to get all the images and do OCR on them
the change was from January 9, 2022

https://www.moh.gov.jm/updates/coronavirus/covid-19-clinical-management-summary/

**Comment by Rouein** [comment]
@3dgiordano I thought about the same thing. I wanted to use images before but have been told images do not match the criteria as[ an acceptable format](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/CONTRIBUTE.md#add-a-new-country). I guess it is because it requires adding further dependencies such as `tesseract` to the repo.

**Comment by Rouein** [comment]
Laos #2313

**Comment by camappel** [comment]
Jamaica will now be updated manually

**Comment by Rouein** [comment]
Hi @edomt, 
Since the discussion in #2313 and current fix for Sweden's data, I was wondering if you could make the guidelines more detailed. Do the daily changes have to be continuous? if not, why not just adding the Sweden's  test numbers when published to weeks last day's `daily change in cumulative total`

**Comment by edomt** [comment]
Hi @Rouein 

The most important goal for us when collecting this data is to be able to calculate the 7-day-averaged number of daily tests. So:

- The ideal situation is to collect `Cumulative total`. From it, we can infer intermediate totals (with a linear forward-fill) and create the 7-day average daily series. So in this situation, our dataset will have `Cumulative total` _and_ 7-day, which is perfect.
- The second-best situation, if there is no cumulative total, is to collect `Daily change in cumulative total` _every day_. If the daily number is really present each day, then our script will calculate the 7-day average.
- The "worst" situation is to have an irregular series of `Daily change in cumulative total`. This is basically of little use, because we can't calculate any cumulative total (because some days are missing) and we also can't calculate the 7-day average (because some days are missing).

**Comment by Rouein** [comment]
It would be great if you could copy that in the contribution guidelines!

**Comment by 3dgiordano** [comment]
@edomt @lucasrodes @camappel 
I asked the innovation secretariat of El Salvador if they plan to solve the outdated data in the report per day.
If I have news, I'll let you know.

As an alternative I am using the start page to get the data for the last 126 days.
They can use it to add missing batch data, create an incremental, or update manually.
More info here 
https://github.com/owid/covid-19-data/pull/2307#issuecomment-1021505810

**Comment by Rouein** [comment]
Perhaps a more permanent solution for Sweden #2331.

**Comment by Rouein** [comment]
#2367

**Comment by lucasrodes** [comment]
Issues solved, 
Thanks to everyone for your help and time!
