### ISSUE TITLE
China data

### ISSUE THREAD

**Issue by fibke** [owid/covid-19-data#2304]
OWID reports the following data for China on and around Jan 6:

<img width="745" alt="Screen Shot 2022-01-22 at 10 57 54 AM" src="https://user-images.githubusercontent.com/69641575/150646205-78c3a5ff-31ac-451f-a3f5-dbba27197582.png">

Since total_vaccinations in OWID include shots of all kinds, including boosters, how to interpret this information?

Does it include, for China, boosters only on the day that booster data is published or also on other days? In other words, does the 2.8 billion total_vaccinations value on Jan 5 include boosters or not? How about Jan 7?

Thanks!

**Comment by edomt** [comment]
Hi @fibke

Yes, `total_vaccinations` always include total_boosters.

If it didn't include them when boosters are missing, then you would see `total_vaccinations` increase by much more between Jan 5 and Jan 6 – but it only increases by 7,976,000, while 331 million boosters have been administered.

`total_vaccinations` are reported every day by the Chinese government on the same page. On the other hand, the other metrics are reported infrequently in separate text reports or transcripts of meetings.

**Comment by fibke** [comment]
Thanks Edouard. 

On Jan 22, 2022, at 12:35, Edouard Mathieu ***@***.***> wrote:

﻿
Hi @fibke

Yes, total_vaccinations always include total_boosters.

If it didn't include them when boosters are missing, then you would see total_vaccinations increase by much more between Jan 5 and Jan 6 – but it only increases by 7,976,000, while 331 million boosters have been administered.

total_vaccinations are reported every day by the Chinese government on the same page. On the other hand, the other metrics are reported infrequently in separate text reports or transcripts of meetings.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
