### ISSUE TITLE
Austria: bad case numbers

### ISSUE THREAD

**Issue by mitsuhiko** [owid/covid-19-data#2306]
I noticed today that the numbers for Austria are reported very oddly. The numbers from 19/01/2022, 20/01/2022 and 21/01/2022 are all not matching up with the official data.

**Comment by edomt** [comment]
Hi @mitsuhiko 

We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues
