### ISSUE TITLE
New vaccination data available for Israel

### ISSUE THREAD

**Issue by EladHeller** [owid/covid-19-data#231]
https://www.gov.il/he/departments/news/27122020-01

|location|date      |vaccine        |total_vaccinations|source_url                                        |
|--------|----------|---------------|------------------|--------------------------------------------------|
|Israel  |2020-12-20|Pfizer/BioNTech|7700              |https://www.gov.il/he/departments/news/27122020-01|
|Israel  |2020-12-21|Pfizer/BioNTech|31400             |https://www.gov.il/he/departments/news/27122020-01|
|Israel  |2020-12-22|Pfizer/BioNTech|74000             |https://www.gov.il/he/departments/news/27122020-01|
|Israel  |2020-12-23|Pfizer/BioNTech|134500            |https://www.gov.il/he/departments/news/27122020-01|
|Israel  |2020-12-24|Pfizer/BioNTech|208600            |https://www.gov.il/he/departments/news/27122020-01|
|Israel|2020-12-25|Pfizer/BioNTech|247300|https://www.gov.il/he/departments/news/27122020-01|
|Israel|2020-12-26|Pfizer/BioNTech|279300|https://www.gov.il/he/departments/news/27122020-01|

**Comment by edomt** [comment]
Thank you @EladHeller! We've just updated our data with this number.
(For future updates please use https://github.com/owid/covid-19-data/issues/230)
