### ISSUE TITLE
Austria's test numbers disappeared

### ISSUE THREAD

**Issue by mitsuhiko** [owid/covid-19-data#2320]
It seems like there are no test numbers available for Austria any more.

**Comment by lucasrodes** [comment]
Hi @mitsuhiko,
Thanks for reporting.

Apparently, there was a typo in the source data reporting a zero value for the 2022-01-22. We have fixed this on our end and improved our tools to detect if this were to happen again.

**Comment by camappel** [comment]
Resolved by #2322

**Comment by mitsuhiko** [comment]
Thanks!
