### ISSUE TITLE
people_fully_vaccinated Data for Indonesia is not being updated. 

### ISSUE THREAD

**Issue by gauravjoshijo** [owid/covid-19-data#2323]
People_fully_vaccinated has not been updated regularly since 10th Sept. for Indonesia. Last data updated on 18th Jan 2022. Data is present in[ WHO ](https://ourworldindata.org/covid-vaccinations).
Kindly look into the discrepancy.

**Comment by edomt** [comment]
I'm not sure I understand what the reported issue is. The last data point in our own data is 18 Jan 2022, and the list you gave is to our own website. This last data point comes indeed from the WHO.

**Comment by Rouein** [comment]
I assume he is referring to https://data.covid19.go.id/public/index.html which has a more recent data.
I just checked the api in the script and the json does provide the 2nd doses. 
https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/Indonesia.csv is missing a few second doses data.
perhaps running the script to see if it is corrected. and if not it could be a bug.

**Comment by Rouein** [comment]
Hi @edomt,
I just ran the script on my end and can confirm it is a bug. the 2nd doses in [the data](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/Indonesia.csv) does not get updated or filled even though the data is available in the [API](https://data.covid19.go.id/public/api/pemeriksaan-vaksinasi.json) used.

**Comment by gauravjoshijo** [comment]
Hello, 

Sorry for being unclear. I mistakenly attached a wrong link of WHO there.  I guess Rouein got it. 2nd dose data doesn't get updated as per the real numbers.

**Comment by edomt** [comment]
If we want a full time series for `people_fully_vaccinated`, we would need the API to include either:
- A readily-available count of `people_fully_vaccinated`, correctly calculated depending on the protocol of each vaccine
- Or data disaggregated by vaccine manufacturer, so that we can calculate it ourselves.

**Comment by Rouein** [comment]
@edomt thank you for the detailed explanation I was not aware they were using Johnson&Johnson.

**Comment by Rouein** [comment]
@gauravjoshijo [WHO](https://covid19.who.int/region/searo/country/id)  reports 121,075,830 people are fully vaccinated which is the same as the number available in [the data here](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/Indonesia.csv).

**Comment by lucasrodes** [comment]
Related to https://github.com/owid/covid-19-data/issues/2267

**Comment by FheyderID** [comment]
Hi, 

@edomt  total doses that was administered by J&J was <250K so it is only < 0.01% of total doses given in the country.
![WhatsApp Image 2022-02-04 at 09 52 15 (1)](https://user-images.githubusercontent.com/99102491/152662821-0cde852c-82a1-4592-a910-1f8379052685.jpeg)

J&J is no longer a widely available vaccine in the country.

Please consider reinstating the rule that fully vaccinated = 2 doses.

Also now the Ministry of Health have their own public data that's more detailed which shows 3rd vaccine/booster. Consider adding that too please

https://vaksin.kemkes.go.id/#/vaccines

**Comment by edomt** [comment]
Hi @FheyderID 

Is there detailed data available on how many doses have been used for each type of vaccine? I can't find it on https://vaksin.kemkes.go.id/#/vaccines

**Comment by FheyderID** [comment]
Hi.

The breakdown by vaccine types is an internal data which our Ministry of Health contact shared with us during a working meeting. We will try to advise our MOH contact to update their feed to include the "Fully Vaccinated" curve but as you can imagine this takes time & is not an efficient process. 

For now, is there a way we can arrange to share this data (via email) to you / several of the admins to prove this point?

F

**Comment by edomt** [comment]
Hi @FheyderID 

Based on what you shared initially, but also on the reports made by the Indonesian government to the WHO (where `people_fully_vaccinated` is correctly calculated), it seems true that the difference is negligible.

We'll reinstate the metric based on 2 doses, but yes, as you wrote it would be great if the metric could appear in public dashboards so that the calculation is perfectly accurate.

Thanks!

**Comment by edomt** [comment]
Ideally, it would be great if you could ask your MOH contact for this file to be updated: https://data.covid19.go.id/public/api/pemeriksaan-vaksinasi.json
That's the public API file we use, but at the moment it only includes first and second doses (no boosters).
The dashboard at https://vaksin.kemkes.go.id/#/vaccines is much difficult to extract data from.

For now we'll be using the public file for the time series of first & second doses, and add the latest value for boosters shown on https://vaksin.kemkes.go.id/#/vaccines
