### ISSUE TITLE
Suriname, testing data

### ISSUE THREAD

**Issue by 3dgiordano** [owid/covid-19-data#2338]
Hi all.

I made a process that takes Suriname data from its official site.
I use the Wayback Machine from archive.org to get all the data for the dates the data was captured on archive.org and I detect the days when no new data was reported so as not to report it twice.

I attach the csv with the obtained data to cooperate with the test data.

It is possible to adapt the program to incorporate it into an incremental process to process daily, and if it didn't run for a few days, it also uses the Wayback Machine to get those missing days.

At the moment I am attaching the csv so that you can see how to incorporate the testing data of Suriname, and I see in a PR they propose an incremental version to incorporate into their routines that they run daily.

Regards
David

[Suriname.csv](https://github.com/owid/covid-19-data/files/7943752/Suriname.csv)

cc @camappel @lucasrodes

**Comment by lucasrodes** [comment]
Hi @3dgiordano,
Thanks for the research and the time invested in getting the historic.

We can use your file as a base for an incremental script, that gets the daily data from https://covid-19.sr/.

What was the process to estimate the positive rate? Remember that there is no need to estimate it if JHU daily case data is considered reliable

**Comment by 3dgiordano** [comment]
Hi @lucasrodes 

the positive data exist at the same page.
Nieuwe gevallen vandaag = New cases today
Totaal Testen (24 uur*) = Total Testing (24 hours*)

I prefer to calculate it based on the data reported by the page itself because I make sure that it matches the reported cases with the tests. With JHU it may happen that the information is not synchronized, although it is true it seems to be quite good.
It is calculated after all the data for every day is obtained.
The calc is the same than others routines.
If you want to review how the data is obtained and how was calculated the positive rate, you can view the script.
https://gist.github.com/3dgiordano/a1f4440ff6111d832bc61451a0594a32

Also if you need the routine of the how to parse the data and how to calculate from the actual site you can use the program as a base. Also if you need an example how to process with Wayback Machine you can take ideas from the same script.
