### ISSUE TITLE
Testing data, Djibouti

### ISSUE THREAD

**Issue by ckrf** [owid/covid-19-data#2344]
Djibouti testing (and other) data are available from the health ministry's [Facebook page](https://www.facebook.com/minister.sante.dj) in the form of daily "Pointe de Presse" scanned images.

**Comment by Rouein** [comment]
> Djibouti testing (and other) data are available from the health ministry's [Facebook page](https://www.facebook.com/minister.sante.dj) in the form of daily "Pointe de Presse" scanned images.

Using Images to scrape data needs OCR and makes this repository more complicated. 
I am not sure but I think Africa CDC would be a good source to get Djibouti's Data.

**Comment by camappel** [comment]
Hi @ckrf ,

Thank you for making us aware of this source; it will be useful for backfilling the data.

Yes @Rouein, we can use the Africa CDC to automate data collection.
