### ISSUE TITLE
Removing Deprecated Scripts 

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2347]
It would be a good idea to remove the deprecated scripts such as [south_sudan.R](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automations/incremental/south_sudan.R). and maybe making a txt file to note the alternative sources in case they are needed.

**Comment by lucasrodes** [comment]
Thanks!
We just removed the file. Please raise issues related to python migration in #2099.
