### ISSUE TITLE
Fiji tests backfill

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2350]
Fiji's ministry of health and medical services has stopped updating their table. the last data point available on the table is from 25-07-2021. The rest of the data needs to be filled. For the moment I will write an incremental script to get the data from daily updates which reports number of tests per day and not the cumulative data.

**Comment by Rouein** [comment]
There is picture that has the cumulative total but only daily tests in the text.

**Comment by Rouein** [comment]
#2353

**Comment by camappel** [comment]
I will have to move Fiji to manual once I've backfilled the data as cumulative total is preferable to sporadic daily change. I will email the MoH and hopefully they will report cumulative total in the reports as text as well.

**Comment by Rouein** [comment]
If you could ask them to continue filling [the table](https://www.health.gov.fj/covid-19-updates/) for batch data it would be better

**Comment by lucasrodes** [comment]
Script for Fiji in place
