### ISSUE TITLE
Gap in data for vaccination 

### ISSUE THREAD

**Issue by mkhanka** [owid/covid-19-data#2355]
Location 1: [Romania](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/Romania.csv)
No data for people_vaccinated 2021-09-28
Is it because of J&J single dose or any other calculation issue? 

Location 2: [Burundi](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/Burundi.csv)
2021-11-09 to 2021-11-23 and  on 2021-12-01: no data for people_vaccinated

Location 3: [Mauritania](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/Mauritania.csv)
2021-09-27: no data for people_vaccinated

Location 4:[Eswatini](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/Eswatini.csv)
2021-08-13 to 2021-08-17 no data for people_vaccinated	

Location 5: [Tanzania](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/Tanzania.csv)
2021-10-29 no data for people_vaccinated

Location 6: [Burkina Faso](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/Burkina%20Faso.csv)
2021-10-24 : No data for people_vaccinated

For all the above due to this gap the people_vaccinated > people_fully_vaccinated on these dates(illustrated below), could the data be added here so that the graphs improve?

example: 
![image](https://user-images.githubusercontent.com/87356889/151548093-4fba54c7-ff02-48e9-89f8-dd07952022fd.png)

Google graph using OWID data : 
![image](https://user-images.githubusercontent.com/87356889/151548933-09f1e309-c7f6-4523-af09-0267b72e257e.png)

**Comment by lucasrodes** [comment]
Hi @mkhanka,
Thanks for your help! Some comments are below on each country:

- Romania: See https://github.com/owid/covid-19-data/issues/2174
- Burundi: Thanks for reporting. We have corrected some of the numbers in that period.
- Mauritania: Data point added, thanks!
- Eswatini: Data in the period of 2021-08-13 to 2021-08-17 was only available for people fully vaccinated. Therefore we only reported this metric. See `source_url` field value in datafile [Eswatini.csv](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/Eswatini.csv#L14).
- Tanzania: Data point from the WHO was not consistent with subsequent updates from the same source; hence we deleted the datapoint.
- Burkina Faso: Data point from the WHO was not consistent with subsequent updates from the same source; hence we deleted the datapoint.
