### ISSUE TITLE
fix(tests,russia): script broken

### ISSUE THREAD

**Issue by camappel** [owid/covid-19-data#2356]
`ValueError: 'cumulative_total' can't be lower than currently highers 'Cumulative total' value.`

https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automations/incremental/russia.py

**Comment by lucasrodes** [comment]
Consider using [`make_monotonic()`](https://github.com/g0v/covid-19-data/blob/master/scripts/src/cowidev/testing/utils/utils.py#L4)

**Comment by Rouein** [comment]
This is an incremental script.
Let me have a look it might be jumping the announcement.

**Comment by Rouein** [comment]
#2357
