### ISSUE TITLE
Israel: New daily hospitalization and amount of patients ventilated

### ISSUE THREAD

**Issue by Aric5301** [owid/covid-19-data#2359]
Hi!
Israel's MOH made updates to its API and brought back daily new hospitalizations data.
It can be fetched by summing all three fields here: [https://datadashboardapi.health.gov.il/api/queries/patientsPerDate](https://datadashboardapi.health.gov.il/api/queries/patientsPerDate)
Please note that the first field is currently called _serious_critical_new_ but in reality it corresponds to daily new **hard** patients, not critical.
I guess that they'll fix it in some point so I suggest that you write a script that sums up all three field regardless of their names.

In addition, the daily amount of patients ventilated can be fetched from here:
[https://github.com/erasta/CovidDataIsrael/blob/master/out/csv/updatedPatientsOverallStatus.csv](https://github.com/erasta/CovidDataIsrael/blob/master/out/csv/updatedPatientsOverallStatus.csv)
Use _breath_ field.
Data for specific dates should be taken from [history](https://github.com/erasta/CovidDataIsrael/tree/master/out/history) folder.

**Comment by edomt** [comment]
(closing in favor of #2330)
