### ISSUE TITLE
Stringency Index & Containment and Health Index Calculation

### ISSUE THREAD

**Issue by cansurmeli** [owid/covid-19-data#236]
Hey.

Could someone please provide the exact formulas used to calculate the `stringency index` and `containment and health index` calculation in the policy data for Covid-19.

I'm doing a research on Covid-19 and would really like to know how these two indexes are calculated. I've read in `datapackage.json` that, for instance, the stringency index is the additive score of nine indicators and then resampled to vary in between 0 and 100. Although which nine indicators and how the resampling is done?

Thank you.

**Comment by edomt** [comment]
Hi @cansurmeli 

We import this data directly from the dataset published by the Blavatnik School of Government in this repo: https://github.com/OxCGRT/covid-policy-tracker/

You should find very good documentation over there, but for further questions you can directly ask [on their side](https://github.com/OxCGRT/covid-policy-tracker/issues).
