### ISSUE TITLE
(test, Dominican Republic) need a new source

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2365]
The data has not been updated since `2021-10-26` . The current link cannot be scraped. 
I have found another [source](https://coronavirusrd.gob.do/documentos/boletines/)  but the pdf files available here cannot be converted to text and scraped.

**Comment by Rouein** [comment]
my suggestion : #2373

**Comment by lucasrodes** [comment]
I reached out to government officials to see if they plan on sharing this data in a format other than images-in-pdfs. Hopefully, I will get a response soon!

**Comment by camappel** [comment]
Data collection for the Dominican Republic will be backfilled and manually updated until:

a) the format of data reporting changes, or;
b) we complete issue #2381
