### ISSUE TITLE
Tanzania Covid Data

### ISSUE THREAD

**Issue by Javierpedatos** [owid/covid-19-data#2368]
**The report belongs to the days 15 to 21 January . Tanzania has carried out 427,673 tests since the start of the pandemic, of which 32,920 people have tested positive for coronavirus and 778 people have died.** Total Covid Beds: 4,355 | Total Occupied COVID 19 Beds: 165 | Total ICU Beds 237 | Total Occupied ICU Beds: 21

Vaccination:
3,420,769 Doses Administered
1,553,939 Partiatly Vaccinated
1,866,830 Fully Vaccinated

Report: http://www.moh.go.tz/en/announcements?download=732:covid-19-situation-report-no-19-from-15th-to-21st-january,-2022

**Comment by edomt** [comment]
Thanks
