### ISSUE TITLE
direct links to sources (csv) not updated

### ISSUE THREAD

**Issue by tigrrr** [owid/covid-19-data#237]
Hi, the content in the links, e.g. https://covid.ourworldindata.org/data/ecdc/total_cases.csv is not updated (last data from 29.11.2020)

**Comment by edomt** [comment]
Hi @tigrrr 
See https://github.com/owid/covid-19-data/issues/197

**Comment by edomt** [comment]
Sorry actually, did you mean that one of our links still points to https://covid.ourworldindata.org/data/ecdc/total_cases.csv as data that is supposed to be updated?

**Comment by tigrrr** [comment]
yes, you got the issue in #197 correctly described and located. thanks.
