### ISSUE TITLE
(test, Thailand) : New source needed

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2375]
The current source only provides the data to `2022-01-15`

**Comment by edomt** [comment]
Are you sure that the source is really deprecated? Many countries don't update their testing data every day, especially when they publish full time series.

**Comment by Rouein** [comment]
The current source is a dataset in [Open Government Data of Thailand](https://data.go.th/dataset/9f6d900f-f648-451f-8df4-89c676fce1c4) published for research purposes. In the description of the dataset, it is said that it will be updated weekly. I think instead of updating the dataset, their efforts are towards the new [dashboard](https://ddc.moph.go.th/covid19-dashboard/).  The dashboard however, lacks the test numbers and only provides the positive rate. They might update it in the future and even expose an API for it, as they have for case numbers. (Although, they have not exposed an API for vaccines either.)

**Comment by camappel** [comment]
Up-to-date data available [here](https://docs.google.com/spreadsheets/d/17Zh7D_YGPTmlSw270qSHbTjDKazGibBa/edit#gid=1240930559), which is accessible from [here](https://www3.dmsc.moph.go.th/) under 'Number of tests and reagents for COVID-19 (Thailand Laboratory testing data - weekly summary report) COVID-19 testing'

**Comment by Rouein** [comment]
Great, I will make the script tonight!
