### ISSUE TITLE
feat(scraping): enable image-based data sources

### ISSUE THREAD

**Issue by camappel** [owid/covid-19-data#2381]
Some sources report data using images. If such sources are proven stable, we can consider using OCR engines to process those images and extract the relevant data.

Some potential dependencies to enable this:
- [`pytesseract`](https://github.com/madmaze/pytesseract): Python wrapper around [Google Tesseract](https://opensource.google/projects/tesseract/), an open source ocr engine to extract text from images.
- [`pdf2image`](https://github.com/Belval/pdf2image): Open source library that converts PDFs to images. Useful whenever we find images within PDFs.

These dependencies should be added to [requirements.txt](https://github.com/owid/covid-19-data/blob/master/scripts/requirements.txt).

---
Based on pull request #2373 by @Rouein

**Comment by lucasrodes** [comment]
Probably won't be doing this in the short term. Feel free to re-open if we decide to move in this direction.
