### ISSUE TITLE
new_deaths: "confirmed" or "confirmed and probable"?

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#2386]
Do I understand correctly that OWID's `new_deaths` in `owid-covid-data.csv` is derived from JHU's `Deaths` field, described on https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data?

JHU describes this field as `Deaths: Counts include confirmed and probable (where reported)`. OWID says it's those **confirmed** only though [1], [2]. Which one is correct? Or is my assumption that *OWID's `new_deaths` == JHU's `Deaths`* invalid?

[1]https://github.com/owid/covid-19-data/tree/master/public/data
[2]https://ourworldindata.org/covid-deaths#confirmed-deaths-and-cases-our-data-source

**Comment by edomt** [comment]
Hi @czka

Indeed `new_deaths` comes from JHU – you can see this in [our codebook](https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-codebook.csv).
As far as I know, this inclusion of probable cases/deaths only applies to a small number of countries in the JHU data. I've clarified this in the codebook, thanks!

**Comment by czka** [comment]
@edomt Cool. BTW, do you maybe know whether it's correct to assume that this count includes deaths "from" covid as well as "with" covid?

**Comment by edomt** [comment]
@czka AFAIK most countries count deaths as COVID deaths where COVID has been a contributory cause – so "from".

**Comment by czka** [comment]
@edomt Hmm. You mean Poland too? Eg. according to Polish Ministry of Health (document attached) there were 5102 deaths "from" covid in 2020, whereas OWID's `new_deaths` for 2020 equals 28554. A 5.6-times difference.

![liczba_zgonów_na_sam_kowid_2021](https://user-images.githubusercontent.com/1593918/152137420-90f3e5c4-c0e4-4006-bb47-ff7242216b0f.jpeg)

**Comment by edomt** [comment]
As we don't collect any of this data ourselves, these questions are best addressed to the JHU CSSE team: https://github.com/CSSEGISandData/COVID-19/issues

**Comment by edomt** [comment]
Also of interest to you, perhaps: the [cumulative excess mortality](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..2020-12-31&facet=none&pickerSort=asc&pickerMetric=location&Metric=Excess+mortality+%28count%29&Interval=Cumulative&Relative+to+Population=false&Color+by+test+positivity=false&country=~POL) in 2020 in Poland was 61,074 deaths, suggesting a very large undercounting of deaths, rather than overcounting.

**Comment by czka** [comment]
> Also of interest to you, perhaps: the [cumulative excess mortality](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..2020-12-31&facet=none&pickerSort=asc&pickerMetric=location&Metric=Excess+mortality+%28count%29&Interval=Cumulative&Relative+to+Population=false&Color+by+test+positivity=false&country=~POL) in 2020 in Poland was 61,074 deaths, suggesting a very large undercounting of deaths, rather than overcounting.

Or maybe this excess mortality is due to Poland's hospitalizations in 2020 falling from ~7,6 mln/year as of 2017-2019 [1, 2, 3], to a record low of 5,7 mln in 2020 [4], and proabably even lower in 2021 [5]?

[1]https://stat.gov.pl/obszary-tematyczne/zdrowie/zdrowie/zdrowie-i-ochrona-zdrowia-w-2019-roku,1,10.html, p. 51
[2]https://stat.gov.pl/obszary-tematyczne/zdrowie/zdrowie/zdrowie-i-ochrona-zdrowia-w-2018-roku,1,9.html, p. 41
[3]https://stat.gov.pl/obszary-tematyczne/zdrowie/zdrowie/zdrowie-i-ochrona-zdrowia-w-2017-r-,1,8.html, p. 43
[4]https://stat.gov.pl/obszary-tematyczne/zdrowie/zdrowie/zdrowie-i-ochrona-zdrowia-w-2020-roku,1,11.html, p. 63
[5]https://businessinsider.com.pl/finanse/makroekonomia/koronawirus-czy-sluzba-zdrowia-na-dwie-trzecie-mocy-co-gorsze-zgonow-poza-szpitalem/sq80hzw

**Comment by edomt** [comment]
@czka I'd rather be clear now: given our previous discussion a few days ago about the tone of one of your recent requests, I find this new series of messages to be even less useful to our work, and I'm not sure what you're trying to accomplish by posting them here. This repo is about writing code to collect data on the pandemic. It is _not_ the right place to send pixellated scans of documents supposedly showing that COVID deaths have been overcounted in Poland.

**Comment by czka** [comment]
No problem!
