### ISSUE TITLE
New hospitalization data for Bolivia

### ISSUE THREAD

**Issue by dquintani** [owid/covid-19-data#2391]
Hi all, 

I am part of both [BoliGráfica](www.boligrafica.com) and [Sociedatos](https://github.com/sociedatos), where we collect and communicate COVID-19 data for Bolivia with @mauforonda and @pr0nstar. You are currently using our data for vaccination and testing.

We recently acquired hospitalization data on both a national and sub-national level. It would be great if you could add it to your platform! The data source comes from official hospitalization reports from the government (SNIS-VE). Link: https://github.com/sociedatos/bo-hospitalizados_por_departamento/blob/master/hospitalizados_por_departamento.csv

This .CSV file has three categories for both available hospital beds ("camas habilitadas") and used hospital beds ("hospitalizaciones"):
- ICU (intensive care, or "UCI") 
- IMCUs (intermediate care or treatment, or "UTI") and 
- Normal admissions ("internaciones"), 

... for all 9 subnational levels. The national numbers can be easily calculated by summing all subnational "departamentos". All hospital patients can be summed up by the summing the three admission categories. Occupancy can be calculated by dividing used beds over available beds. I'm sure you can figure it out!
 
As of now, this data covers around 80% of all hospitals in Bolivia, and we are hoping this will gradually increase. It has proven to be quite accurate in following trends in confirmed covid cases. 

If you want, I can create a new dataset with only national data and metrics you measure in your website (hospital patients and ICU patients).

Let me know! Take care,
-Diegolin

**Comment by edomt** [comment]
Thank you @dquintani ! The data is now live - can you please check whether the numbers look okay?
- [Number of COVID-19 patients in hospital](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Hospital+patients&Interval=7-day+rolling+average&Relative+to+Population=false&Color+by+test+positivity=false&country=~BOL)
- [Number of COVID-19 patients in intensive care (ICU)](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=ICU+patients&Interval=7-day+rolling+average&Relative+to+Population=false&Color+by+test+positivity=false&country=~BOL)

**Comment by dquintani** [comment]
Everything looking great, thank you! 

Only one question: Why is this data not included in neither the "hospital admissions" nor "ICU admissions" metrics? Aren't these  simple diffs?

Other than that all is good. Thanks again and take care.

**Comment by edomt** [comment]
Unfortunately, you can't take the diffs to get admissions. If you have 100 patients one day, and 120 patients the next day, doesn't mean that 20 people were admitted. For example, it could be that 30 people were admitted, and 10 people were discharged.
