### ISSUE TITLE
Wrong datapoint for cumulative confirmed deaths in Chile on Oct 7 2021 

### ISSUE THREAD

**Issue by elaval** [owid/covid-19-data#2396]
OWID dataset informs 37755 cumulative deaths in Chile on Oct 7 2021.  Official  reports inform 37533
![image](https://user-images.githubusercontent.com/68602/152191923-0ce87d7d-3578-4f25-84a5-a4cc1ba34799.png)

Chile COVID19 daily report [https://s3.amazonaws.com/gobcl-prod/public_files/Campa%C3%B1as/Corona-Virus/Reportes/07.10.2021_Reporte_Covid19.pdf](https://s3.amazonaws.com/gobcl-prod/public_files/Campa%C3%B1as/Corona-Virus/Reportes/07.10.2021_Reporte_Covid19.pdf)
![image](https://user-images.githubusercontent.com/68602/152192998-f48ae324-8d10-47f3-b992-c0741ea5ff7a.png)

This difference affects report of daily deaths in OWID pages
![image](https://user-images.githubusercontent.com/68602/152193507-d14e234b-6623-4c32-850b-286f0beae4e2.png)

Thanks for your great work and I hope this could be corrected

**Comment by edomt** [comment]
Hi @elaval 

We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues
