### ISSUE TITLE
wrong death count for Israel

### ISSUE THREAD

**Issue by yuval-harpaz** [owid/covid-19-data#2399]
It seems that OWID has been showing deaths by reporting date (blue), and not by death date (orange).
There were changes in the dashboard's back door to the data, but now deaths (by death date) are reported in a new [json](https://datadashboardapi.health.gov.il/api/queries/hospitalizationStatus). 
![image](https://user-images.githubusercontent.com/445416/152527132-05601309-3b44-4e75-9657-2ceb6a14e041.png)
The source above contains other hospital-related measures (I will open a separate issue for other fields), but not cases and tests.
Alternative sources:
@erasta's [table](https://github.com/erasta/CovidDataIsrael/blob/master/out/csv/all_dashboard_timeseries.csv) draws data from the same source, but runs some checks to avoid duplicate rows and includes also cases and tests numbers. This table is updated every 30min by GitHub actions. 
@dancarmoz also maintains a table with the most up-to-date data, [here](https://github.com/dancarmoz/israel_moh_covid_dashboard_data/blob/master/hospitalized_and_infected.csv).
Please let me know if you have questions, requests or issues, I can pass messages to MOH (they are not on GitHub)
The issue is raising waves in Israel, see [here](https://twitter.com/PandemicInfoIL/status/1489575503883288578?s=20&t=O4XCaCcTnU5qraHStL6fUQ), and [here](https://twitter.com/IsraelMOH/status/1489567716260425736?s=20&t=O4XCaCcTnU5qraHStL6fUQ).

**Comment by edomt** [comment]
Hi @yuval-harpaz 

We source our data on confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their own repository: https://github.com/CSSEGISandData/COVID-19/issues
