### ISSUE TITLE
A new source for hospital / ICU data in Israel

### ISSUE THREAD

**Issue by yuval-harpaz** [owid/covid-19-data#2401]
From this morning, the only source for up-to-date data regarding COVID-related hospitalizations is a new table released by Israe's MOH.  you can take the data directly from this [json](https://datadashboardapi.health.gov.il/api/queries/hospitalizationStatus), or via @erasta's [csv](https://github.com/erasta/CovidDataIsrael/blob/master/out/csv/all_dashboard_timeseries.csv) (documenting the history of MOH's  dashboard, including this new json).  The fields for both sources:

- Hospital admissions (flow): newHospitalized
- Hospitalized (stacked): countHospitalized
- ICU admissions (flow): diff(countBreathCum)*
- ICU (stacked): countCriticalStatus

* The definition of Critical is a system failure, most of the time respiratory but sometimes other organs. So "critical" is the closest definition to ICU, but this data is only available for stacked patients. For an approximation to new admissions to ICU you can take the flow of mechanical ventilation, by computing diff for cumulative ventilated (countBreathCum).
I recommend stop using [my source ](https://github.com/yuval-harpaz/covid-19-israel-matlab/blob/master/data/Israel/dashboard_timeseries.csv) for new_hospitalizations (newHospitalized in the new table), because I check for updates manually. I think you should switch to the new table, or take it from @erasta who's got GitHub actions to update the tables automatically from MOH every 30 min, and run some tests to avoid duplicate rows.

**Comment by edomt** [comment]
Thank you @yuval-harpaz. The changes are live, can you please give it a quick review to make sure everything looks okay?

- [Number of COVID-19 patients in hospital](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Hospital+patients&Interval=7-day+rolling+average&Relative+to+Population=false&Color+by+test+positivity=false&country=~ISR)
- [Weekly new hospital admissions for COVID-19](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Hospital+admissions&Interval=7-day+rolling+average&Relative+to+Population=false&Color+by+test+positivity=false&country=~ISR)
- [Number of COVID-19 patients in intensive care (ICU)](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=ICU+patients&Interval=7-day+rolling+average&Relative+to+Population=false&Color+by+test+positivity=false&country=~ISR)
- [Weekly new ICU admissions for COVID-19](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=ICU+admissions&Interval=7-day+rolling+average&Relative+to+Population=false&Color+by+test+positivity=false&country=~ISR) <- this one, in particular, has identical trends compared to the previous data, but lower absolute numbers

**Comment by yuval-harpaz** [comment]
perfect all four
If you want I can check discrepancies for this, compared to the previous ICU admissions
![image](https://user-images.githubusercontent.com/445416/152595897-64934e0b-e540-4134-b129-341cffac6f4f.png)
![image](https://user-images.githubusercontent.com/445416/152596468-860ee436-0133-42bc-970d-9519569dbfa3.png)
![image](https://user-images.githubusercontent.com/445416/152596975-601e7dd2-5ad9-4fed-aabb-c8a23d52f776.png)
![image](https://user-images.githubusercontent.com/445416/152597442-5c19d9d7-1360-4b18-a47d-c57af1abe743.png)

**Comment by edomt** [comment]
Thank you!
