### ISSUE TITLE
fix(vax,slovakia): new value `COMIRNATY;MODERNA` in vaccine column

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2422]
The file for Slovakia has a new value in the vaccine column: `COMIRNATY;MODERNA`. We need to first find out what that means (a sequence of Pfizer then Moderna?) and then fix the script to handle it.

**Comment by lucasrodes** [comment]
Just ran `cowid-vax get -c slovakia` and seems to be working. Perhaps there was a bug in the source file but was solved already. 

Closing the issue for now.
