### ISSUE TITLE
Austria data suddenly only weekly?

### ISSUE THREAD

**Issue by Fabian42** [owid/covid-19-data#2423]
A lot of values for Austria disappeared. My sheet still has some of the ones that I copied from https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv yesterday: https://docs.google.com/spreadsheets/d/1uDTghO_ZYBs5nfs2kDc0Ms6e9bbx7clx_QgkWii7OMY/view#gid=1217945637 (But for some reason I seem to have gotten first vaccinations into it instead of the intended second.)

But now I get this:

```
[fabian@manjaro ~]$ echo -n "$page" | grep "Austria"
Austria,AUT,2021-01-08,31584,31584,1,,,,0.35,0.35,0.0,,,,
Austria,AUT,2021-01-09,,,,,,12212,,,,,1350,12154,0.134
Austria,AUT,2021-01-10,,,,,,12212,,,,,1350,12154,0.134
Austria,AUT,2021-01-11,,,,,,12212,,,,,1350,12154,0.134
Austria,AUT,2021-01-12,,,,,,12212,,,,,1350,12154,0.134
Austria,AUT,2021-01-13,,,,,,12212,,,,,1350,12154,0.134
Austria,AUT,2021-01-14,,,,,,12212,,,,,1350,12154,0.134
Austria,AUT,2021-01-15,117069,116665,403,2,,12212,1.29,1.29,0.0,0.0,1350,12154,0.134
Austria,AUT,2021-01-16,,,,,,12469,,,,,1379,12325,0.136
Austria,AUT,2021-01-17,,,,,,12725,,,,,1407,12496,0.138
Austria,AUT,2021-01-18,,,,,,12982,,,,,1436,12666,0.14
Austria,AUT,2021-01-19,,,,,,13239,,,,,1464,12837,0.142
Austria,AUT,2021-01-20,,,,,,13496,,,,,1492,13007,0.144
Austria,AUT,2021-01-21,,,,,,13752,,,,,1521,13178,0.146
Austria,AUT,2021-01-22,215131,210105,5021,6,,14009,2.38,2.32,0.06,0.0,1549,13349,0.148
Austria,AUT,2021-01-23,,,,,,13013,,,,,1439,12088,0.134
Austria,AUT,2021-01-24,,,,,,12016,,,,,1329,10827,0.12
Austria,AUT,2021-01-25,,,,,,11020,,,,,1219,9567,0.106
[…]
```

There is also an entry for Tuesday this week, otherwise it seems to just be all Fridays. Why remove data?

**Comment by lucasrodes** [comment]
Hi @Fabian42,
Thanks for your message.

We have switched the source for Austria to ECDC in https://github.com/owid/covid-19-data/commit/e515d6c9c1101517a0a761162fdd17706ccbf78a. The motivation behind this change was #2420, i.e. hos Austria reports the doses: 

Consider the case that Person A receives 1 Janssen dose, and six months later another dose BioNTech/Pfizer. The source https://info.gesundheitsministerium.gv.at/opendata/ will report this as:
 
    +1 dose_1 Janssen
    +1 dose_2 BioNTech/Pfizer

We have been doing the conversion to our metrics as: 
- dose_1 => people_vaccinated
- dose_2 and dose_1 janssen => people_fully_vaccinated
- dose_3 and dose_2 janssen => total_boosters

However, this is no longer valid as there might be some "dose_2" that are actually boosters.

**Comment by Fabian42** [comment]
Ah, OK. And Germany never had that problem? I'm using your data for there, too.
