### ISSUE TITLE
Booster data for Estonia are available here

### ISSUE THREAD

**Issue by fibke** [owid/covid-19-data#2426]
OWID database currently shows Estonia as NA for boosters

But the data are available: here:https://opendata.digilugu.ee/docs/#/en/opendata/covid19/vaccination/readme

Specifically: https://opendata.digilugu.ee/covid19/vaccination/v3/opendata_covid19_vaccination_total.csv

Note the column for VaccinationSeries. If this is 1, then we have the primary vaccine cycle (of 1 or 2 shots depending on protocol).  2 is the first booster series; 3 the second one; 4: the third one. 

To get the booster doses, select VaccinationSeries = 2, 3 or 4 and match this with MeasurementType=DosesAdministered.

Estonia's approach is in my view a best-practice way to differentiate between booster series. Perhaps something to consider going forward as you collect data for other countries (assuming that over time most countries will converge to this approach).

However, if you stick to the current approach of lumping all boosters together, you can just add them up.

**Comment by edomt** [comment]
As always, thank you @fibke !
