### ISSUE TITLE
Vaccination data - Bug or feature

### ISSUE THREAD

**Issue by amalic** [owid/covid-19-data#243]
It's actually two issues:
- the year column looks rather like an unique identifier
- some countries have multiple entries (e.g. Bahrein, USA, World, ...)

BTW: Thanks for aggregating and sharing. Happy to help if required.

![Screenshot_20201230-152745](https://user-images.githubusercontent.com/3675484/103357728-32190000-4ab4-11eb-895b-d2ac851a0a3a.png)

**Comment by artdgn** [comment]
I don't *really* know, but I was just looking at those files myself just now and it seems that:
1. https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv is the better formatted version of the file. My guess is that the other files are kept for backwards compatibility (if anyone happens to use them already).
2. If you're just looking for the latest data it seems that https://github.com/owid/covid-19-data/tree/master/public/data/latest has all the latest data aggregated and joined from the other files in the most convenient format.

**Comment by nrazon** [comment]
As previously mentioned on a closed issue that file is used internally.
You need to use vaccinations.csv file not that.

https://github.com/owid/covid-19-data/issues/233

**Comment by edomt** [comment]
Indeed, you should use https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv. The other one is a file for internal use, which I'll move to another folder to avoid confusion.
