### ISSUE TITLE
Bhutan booster data point

### ISSUE THREAD

**Issue by fibke** [owid/covid-19-data#2431]
Bhutan daily booster data is available here: https://www.moh.gov.bt/

Example: https://www.moh.gov.bt/national-situational-update-on-covid-19-321/

Note: authorities report booster share for 18+ population, which per WPP is 66% and can with aggregate population number be transformed into doses administered.

**Comment by lucasrodes** [comment]
Hi @fibke,
Thanks for reporting!

Based on [WPP](https://population.un.org/wpp/Download/Files/1_Indicators%20(Standard)/EXCEL_FILES/5_Interpolated/WPP2019_INT_F02A_1_ANNUAL_POPULATION_INDICATORS_BOTH_SEXES.xlsx), Bhutan's population for 2020 over 18 years is 538,168. Considering the 65.4% people vaccinated with a booster dose from [Government's report](https://www.moh.gov.bt/national-situational-update-on-covid-19-321/), this translates into ca. 0.654 * 538168 = 351962 persons. 

To the best of our knowledge, Bhutan is only administering first boosters, so this can translate into the number of booster doses.

We will be adding this number exceptionally as we do not have any number on the number of boosters for Bhutan. We hope that the reporting of numbers for Bhutan soon becomes simpler (i.e. in absolute numbers, not an image, etc.).
