### ISSUE TITLE
Vaccinations: countries like afghanistan (and several other countries) total vaccinations not consistent with other countries

### ISSUE THREAD

**Issue by looraainne** [owid/covid-19-data#2434]
it will have value for total vaccinations on one day then following days blank. 
https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv

(ex.  on 2-28-21 it is 8,200 but the following days are blank. it should be 8,200 until more added)

**Comment by lucasrodes** [comment]
Hi @looraainne,
Thanks for your message.

We do not forward-propagate values in time for the metric `total_vaccinations`. That is, in the case that you mention, we do know that on the 28th February 2021 there had been 8200 doses administered in Afghanistan, based on [source](https://tolonews.com/index.php/health-170355). However, we can't assure that the number remained the same the next day. 

You can read the definitions of our metrics [here](https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations#vaccination-data).
