### ISSUE TITLE
Administered Data

### ISSUE THREAD

**Issue by Maltob03** [owid/covid-19-data#246]
HI for the total_vaccinations data for Italy does the data reported relate to the doses administered or the doses delivered each day?

**Comment by lucasrodes** [comment]
In #230 it states that data should be administered and not distributed doses.

> We only count administered doses, not distributed doses.

To double-check this I'd inspect the link in column `source_url` in file [Italy.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Italy.csv).

There are two links:

### https://www.invitalia.it/cosa-facciamo/emergenza-coronavirus/notizie/arcuri-alle-18-30-di-oggi-vaccinati-8361-italiani
It states "sono stati già vaccinati 9.803 italiani" (9,803 Italians have already been vaccinated), so administered.

### https://bit.ly/vaccini_covid19
This page provides a box with a number and the text "totale vaccinazioni" (total vaccinations), currently at 84730. As there is a box stating that "dal 30 dicembre al 1 gennaio sono state consegnate 469.950 dosi di vaccino." (469,950 vaccine doses were delivered from 30 December to 1 January.), i.e. a higher number of delivered, I'd assume that the first number refers to administered doses, which is the number I assume has been used.

**Comment by edomt** [comment]
Hi @Maltob03 
Indeed as @lucasrodes has noted, we report administered doses (and we do so for all countries).
