### ISSUE TITLE
fix(test): backfill countries

### ISSUE THREAD

**Issue by camappel** [owid/covid-19-data#2465]
**Automated:**
- [ ] [Gambia](https://github.com/owid/covid-19-data/blob/master/scripts/output/testing/main_data/Gambia.csv): Cumulative total from [this dashboard](https://www.moh.gov.gm/) and these [situation reports](https://www.moh.gov.gm/covid-19-report/) 
- [x] [Antigua and Barbuda](https://github.com/owid/covid-19-data/blob/master/scripts/output/testing/main_data/Antigua%20and%20Barbuda.csv): Cumulative total from [this dashboard](https://covid19.gov.ag/) using [Wayback Machine](https://web.archive.org/web/*/https://covid19.gov.ag/)
- [x] Nepal: Add antigen tests back to 2021-04-21 #2484 
- [ ] [Tanzania](https://github.com/owid/covid-19-data/blob/master/scripts/output/testing/main_data/Tanzania.csv): from [situation reports](http://www.moh.go.tz/en/covid-19-info)
- [ ] [Haiti](https://github.com/owid/covid-19-data/blob/master/scripts/output/testing/main_data/Haiti.csv): from [situation reports](https://www.mspp.gouv.ht/documentation/)

**Manual:**
- [ ] Afghanistan: from [situation reports](http://www.emro.who.int/health-topics/corona-virus/situation-reports.html)
- [ ] Vanuatu: from [situation reports](https://covid19.gov.vu/index.php/surveillance)
- [ ] Dominica
- [ ] Palau: from [facebook](https://www.facebook.com/MHHSPalau)
- [ ] Bonaire: from [facebook](https://www.facebook.com/openbaarlichaamBonaire)

**Comment by Rouein** [comment]
Its actually back to [2021-06-05](https://covid19.mohp.gov.np/covid/englishSituationReport/60bb85e2b1850_SitRep482_COVID-19_05-06-2021_EN.pdf) for Nepal.
I did the backfill back to `2021-04-21` and the numbers didn't add up.
