### ISSUE TITLE
WHO Data doesn't match Uzbekistan's official reports 

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2467]
the current data in `Uzbekistan.csv` : 

```
Uzbekistan,2022-02-06,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, Sputnik Light, Sputnik V, ZF2001",https://covid19.who.int/,40872222,18221843,12598509,
```
the official report from `2022-02-06` :

```
Айни кунгача мамлакатимизда жами 42 546 079 доза вакцинадан фойдаланилди. Улардан:
1-босқич эмланганлар 19 439 989 нафарни,
2-босқичда эмланганлар 14 797 201 нафарни,
3-босқич эмланганлар 8 308 889 нафарни ташкил қилди.
```
rough translation via Google translate:

```
To date, a total of 42,546,079 doses of the vaccine have been used in the country. From them:
19,439,989 people were vaccinated in the first stage,
14,797,201 people were vaccinated in the second stage.
8,308,889 people were vaccinated against stage 3.
```

To my understanding `Sputnik Light` is a 1 dose vaccine while ` ZF2001` is a 3 dose vaccine. Thus , `people_fully_vaccinated` and `total_boosters` can not be calculated from the figures above.
But how is it that `total_vaccinations` and `people_vaccinated` are so far off?

**Comment by edomt** [comment]
Hi @Rouein 

Thanks for raising this issue!

The difference in terms of `total_vaccinations` and `people_vaccinated` is most likely due to a simple delay in reporting. Whoever is in charge of reporting to the WHO in the government of Uzbekistan must have collected some figures from, say, late January, and reported them to the WHO on 2022-02-06, hence the lag.

However, given the lack of detailed data in the official report, and as you said, the impossibility of calculating several metrics, we prefer sticking to the WHO reports for this country.

**Comment by Rouein** [comment]
> Hi @Rouein
> 
> Thanks for raising this issue!
> 
> The difference in terms of `total_vaccinations` and `people_vaccinated` is most likely due to a simple delay in reporting. Whoever is in charge of reporting to the WHO in the government of Uzbekistan must have collected some figures from, say, late January, and reported them to the WHO on 2022-02-06, hence the lag.
> 
> However, given the lack of detailed data in the official report, and as you said, the impossibility of calculating several metrics, we prefer sticking to the WHO reports for this country.

So no need to write a script to collect `total_vaccinations` and `people_vaccinated` from the reports?

**Comment by edomt** [comment]
We already had one but deleted it a couple of weeks ago in favor of the WHO data.

**Comment by Rouein** [comment]
wouldn't WHO data be complementary? The script could provide more frequent data on `total_vaccinations` and vaccine disparity.

**Comment by Rouein** [comment]
We can write a script to place the WHO data in the csv file based on the total vaccination numbers.
