### ISSUE TITLE
fix(vax): duplicate internal timestamp

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2469]
The path to the internal vaccination timestamp has been changed to:

`DATA_TIMESTAMP_VAX_FILE = os.path.join(DATA_TIMESTAMP_DIR, "owid-covid-data-last-updated-timestamp-vaccinations.txt")`
(vaccinations became plural)

So there are now two different timestamp files in https://github.com/owid/covid-19-data/tree/master/public/data/internal/timestamp

**Comment by Rouein** [comment]
The change seems to be from 195475f1c8ee7d5f5a6c15c5ac28d92181128573
