### ISSUE TITLE
different p-score column names in excess_mortality.csv and in its README

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#2477]
https://github.com/owid/covid-19-data/blob/master/public/data/excess_mortality/README.md#excess-mortality-data-from-hmd-and-wmd-that-is-collated-by-our-world-in-data mentions columns named `p_avg_0_14`, `p_avg_15_64` etc., whereas the `excess_mortality.csv` dataset has columns named `p_scores_0_14`, `p_scores_15_64`.

Should the README be updated, or the column names in the dataset?

**Comment by CGiattino** [comment]
@czka Thanks for pointing this out. I've updated the readme file.

**Comment by czka** [comment]
@CGiattino Thank you!
