### ISSUE TITLE
owid-covid-data-last-updated-timestamp.txt not updating

### ISSUE THREAD

**Issue by Ipgnosis** [owid/covid-19-data#2485]
This file hasn't updated for 4 days.

I request this tiny file to avoid clobbering your servers if I have the latest data.  You used to store this on GitHub, then moved to your own servers.  Have you moved it again?

**Comment by lucasrodes** [comment]
Hi @Ipgnosis,
Thanks for your message. Note that files at [`public/data/internal`](https://github.com/owid/covid-19-data/tree/master/public/data/internal) are for internal uses and might not be stable.

Having said this, we have deprecated the file `owid-covid-data-last-updated-timestamp.txt` in favour of `owid-covid-data-last-updated-timestamp-root.txt`.
