### ISSUE TITLE
bug: grapherupdate.sh no longer running automatically

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2489]
### Description

The graph in OWID's website:
![Screenshot](https://user-images.githubusercontent.com/16787454/154942030-dddb2a3b-839e-4d47-8f05-618f67bfc7cb.png)

there seems to be a lot of countries with "no data" although the testing data is collected, collecting pr data if possible could be a solution.

**Comment by Rouein** [comment]
Update: In case of some countries(e.g. Brazil) Although the test data and positive cases(from JHU) are collected, the graph indicates no data is available. And in case of others(e.g. Philippines) rather than showing the last data point available, it indicates no data. It would be a good practice to show the last data point as is the case in Share of people vaccinated against COVID-19 graph.

**Comment by edomt** [comment]
@Rouein For the latter question, we have a "tolerance" system that chooses how many days old a value can be until it stops being shown on the map. It's now harmonized at 10 days for all testing-related metrics.

@camappel will be able to comment more on the first question, but generally, these PRs are removed [here](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/testing_data_corrections.R).

**Comment by Rouein** [comment]
@edomt The charts label : The share of COVID-19 tests that are positive, Feb 17, 2022 doesn't match the data used. The caption indicates the last update was on 21st, but the chert label is 17th. but again if it is 17th, Philippines's last data point is from 12th, that is not 10 days.

**Comment by Rouein** [comment]
The info for the US data doesn't make sense either.
![Screenshot](https://user-images.githubusercontent.com/16787454/155183631-46991dbb-b403-4106-abd2-fcaca851af88.png)

the last data point is not from 12th.

**Comment by Rouein** [comment]
The US data is from 15th now(not the last data point?)
