### ISSUE TITLE
data: Wrong age split "share of people with a COVID-19 vaccines by age"

### ISSUE THREAD

**Issue by Aric5301** [owid/covid-19-data#2490]
### Country

Israel

### Domain

Vaccinations

### Which data is wrong?

Hi. the oldest group age for vaccines by age in Israel should be >90 instead of 90-99. 90-99 was a wrong range in the [repository that is the source for this data](https://github.com/dancarmoz/israel_moh_covid_dashboard_data) but it's now fixed there and should be also fixed on owid. Thanks!

### Why do you think the data is wrong?

Here's a screenshot from the MOH's dashboard:
![image](https://user-images.githubusercontent.com/25414752/154948780-a7554e62-e658-4cd9-ae58-a69a40d56043.png)

**Comment by lucasrodes** [comment]
Thanks for reporting. The fix is now [live on our site.](https://ourworldindata.org/covid-vaccinations#vaccinations-by-age)
