### ISSUE TITLE
Test Counts?

### ISSUE THREAD

**Issue by daveroush** [owid/covid-19-data#25]
I was under the impression from your web site that the dataset included a Test Count column by date for each location.  I can't find test counts anywhere in the downloaded data.  Can you direct me to it please?

**Comment by edomt** [comment]
Hi @daveroush 
Our complete COVID-19 dataset ([csv](https://covid.ourworldindata.org/data/owid-covid-data.csv), [xlsx](https://covid.ourworldindata.org/data/owid-covid-data.xlsx)) includes several columns for tests indeed.
The columns of interest to you should be `location`, `date`, `total_tests`, and `new_tests`. There are also more columns with tests per capita.
Edouard
