### ISSUE TITLE
Timestamp doesn't get updated

### ISSUE THREAD

**Issue by dbaroncelli** [owid/covid-19-data#2502]
The timestamp isn't getting updated. It always reports "2022-02-15T19:18:17":
https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data-last-updated-timestamp.txt

**Comment by Rouein** [comment]
Hi @dbaroncelli,
That timestamp is deprecated and perhaps will be removed soon. The current directory for timestamps is :
https://github.com/owid/covid-19-data/tree/master/public/data/internal/timestamp

**Comment by lucasrodes** [comment]
See  #2485
