### ISSUE TITLE
data: Number of countries

### ISSUE THREAD

**Issue by mohamed-tayeh** [owid/covid-19-data#2507]
### Country

All

### Domain

Vaccinations

### Which data is wrong?

Number of countries

### Why do you think the data is wrong?

I am not entirely sure if this is correct. From a google search, it is mentioned that there are 195 countries world wide, in the vaccination data set there are 235.  Under data sources, it mentioned that the data is from official reports. Any clarification is appreciated

**Comment by lucasrodes** [comment]
We do include some countries that are not member states of the United Nations. Some of these are Taiwan, Niue, the Cook Islands, and other autonomous regions such as Aruba, New Caledonia, etc.

Thanks!
