### ISSUE TITLE
Soberana02

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2510]
### Discussed in https://github.com/owid/covid-19-data/discussions/2476

<div type='discussions-op-text'>

<sup>Originally posted by **Rouein** February 17, 2022</sup>
I realized that in the `checks.py`  `Soberana02` is noted as a 3-dose vaccine. As far as I know `Soberana02` is a 2 dose vaccine and the booster is called `Soberana Plus` which by itself could be a one dose vaccine.
For example in Iran `Soberana Plus` is not yet used and only 2 doses of `Soberana02` are given.</div>

**Comment by lucasrodes** [comment]
Thanks!

**Comment by aywi** [comment]
Another issue is the [data on China](https://github.com/owid/covid-19-data/commits/master) seems never be updated through "data(vax): automated update (get,process)". Is there any additional setting on the server-side? For recent versions, there is no problem in local runs.
