### ISSUE TITLE
data: (vax,TZN)

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2517]
### Country

Tanzania

### Domain

Vaccinations

### Which data is wrong?

The values for `2022-01-21`  as well as vaccine timeline are not correct.

### Why do you think the data is wrong?

The weekly reports contain the manufacturer data for vaccines but they are not complete. According to Africacdc, J&J, Pfizer, Moderna, Sinopharm/Beijing and Sinovac are the vaccines being administered in Tanzania. However, in the reports, detailed data about Sinovac doses are missing. Therefore, when summing J&J doses and second doses of the other vaccines in the document, the resulting number is different from the number people fully vaccinated that is mentioned in the document.

**Comment by lucasrodes** [comment]
Thanks, @Rouein.
I just fixed fully vaccinated and added a data point for the 2022-02-18 (only fully vaccinated metric). I am unsure why Sinovac wouldn't be included in the detailed reports.

**Comment by Rouein** [comment]
Correct the source url, it is pointing to a local file.

**Comment by lucasrodes** [comment]
Solved in https://github.com/owid/covid-19-data/commit/33f3524313ced373aa5442848d8fc46c49c94850
