### ISSUE TITLE
Vaccinations might be too high for Austria

### ISSUE THREAD

**Issue by botic** [owid/covid-19-data#252]
The Austrian Federal Ministry of Health reported "around 6,000" administered doses. A current report in the HEUTE newspaper corrected that number to a total of 4,694 doses [1]. The reporter simply called the nine state representative and asked for the exact numbers and summed them up. I don't see a clear guideline how to deal with this. In my personal opinion I would suggest that 4,694 doses is the correct number. Around 6,000 is the official one.

HEUTE also provided a detailed table of available doses and administered doses:

State | Delivered | Administered
-- | -- | --
Wien | 2,040 | 2,040
Niederösterreich | 2,000 | 2,000
Oberösterreich | 460 | 40
Steiermark | 40 | 40
Burgenland | 130 | 130
Salzburg | 3.996 | 131
Kärnten | 6.400 | 0
Tirol |   | 93
Vorarlberg | 220 | 220
**Total** | **15,286** | **4,694**

To be clear: This is an editorial question / issue: Keep the official number, even if it has been challenged by local news media?

[1] https://story.heute.at/geheimcode-4694/index.html

**Comment by IhorCo** [comment]
Currently thez are too low. The latest stand is 15.905.
https://www.sozialministerium.at/Corona-Schutzimpfung/Corona-Schutzimpfung.html

**Comment by edomt** [comment]
@IhorCo See this tweet from our founder Max: https://twitter.com/MaxCRoser/status/1347223477099618306

We're not sure at all how to understand this sentence:

> Mit Stand 07.01.2021 wurden für 15.905 Personen COVID-19-Impfstoffe ausgeliefert.

**Comment by IhorCo** [comment]
> @IhorCo See this tweet from our founder Max: https://twitter.com/MaxCRoser/status/1347223477099618306
> 
> We're not sure at all how to understand this sentence:
> 
> > Mit Stand 07.01.2021 wurden für 15.905 Personen COVID-19-Impfstoffe ausgeliefert.

Oh..Yoy are right. I missed it. They basically just arrived in the regions which was kind a problem in Austria.

**Comment by botic** [comment]
I expect a serious / stable source of information next week. No details have been provided by government agencies, but as we saw over the last months I expect a simple HTML table on their website.

**Comment by edomt** [comment]
An actual number has been reported now (more or less): https://twitter.com/redouad/status/1348256152786710530
