### ISSUE TITLE
data: 

### ISSUE THREAD

**Issue by gauravjoshijo** [owid/covid-19-data#2527]
### Country

United Kingdom

### Domain

Deaths

### Which data is wrong?

Death Statistics in OWID feed for the UK on 25th Feb and 28th Feb are 121 and 138 whereas when checked on WHO the data of death cases are 74 and 45 respectively. Also on 25th, 26th and 27th accumulated death cases are the same i.e. 161224 which shows new death cases as zero for 26th and 27th Feb.

However, for 26th and 27th Feb, the data is available in WHO. 

WHO: https://covid19.who.int/region/euro/country/gb

Please look into this whether the death statistics are correct or need to be corrected in reference with the source mentioned above like WHO. 

### Why do you think the data is wrong?

Problem may be in data itself.

**Comment by lucasrodes** [comment]
Hi @gauravjoshijo ,

We source our data on confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their own repository: https://github.com/CSSEGISandData/COVID-19/issues
