### ISSUE TITLE
data: (Vax, GIB)

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2528]
### Country

Gibraltar 

### Domain

Vaccinations

### Which data is wrong?

Astrazeneca should be added to vaccines in https://github.com/owid/covid-19-data/blob/16b8ecfc7777adb5bef1693b977e4702f5a349e8/public/data/vaccinations/country_data/Gibraltar.csv

### Why do you think the data is wrong?

https://www.gibraltar.gov.gi/press-releases/oxfordastrazeneca-covid-19-vaccine-1672021-6714
https://healthygibraltar.org/news/sars-cov-2/oxford-astrazeneca-vaccine/

**Comment by edomt** [comment]
Thanks! Will be fixed today
