### ISSUE TITLE
Invalid data in vaccinations-by-manufacturer.csv 

### ISSUE THREAD

**Issue by martin-ludvik-sv** [owid/covid-19-data#2540]
### Country

Uruguay

### Domain

Vaccinations

### Which data is inaccurate or missing?

In file: [vaccinations-by-manufacturer.csv](https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations-by-manufacturer.csv)

E.g.: 
See the bottom lines, which do not have data:
Uruguay,2022-03-06,Oxford/AstraZeneca,89635
Uruguay,2022-03-06,Pfizer/BioNTech,2398276
Uruguay,2022-03-06,Sinovac,3247639
Uruguay,,Oxford/AstraZeneca,89635
Uruguay,,Pfizer/BioNTech,2362759
Uruguay,,Sinovac,3247636

### Why do you think the data is inaccurate or missing?

Either the data is not available, or there is human error, or error of automatic processing of the data.

**Comment by lucasrodes** [comment]
Manually fixed in 50ffd2d27d63fdec5fdebbbf08d3b599c870e8a6 and opened an issue in source https://github.com/3dgiordano/covid-19-uy-vacc-data/pull/4/files to correct it.
