### ISSUE TITLE
share of positive tests for Israel doesn't match MOH report

### ISSUE THREAD

**Issue by yuval-harpaz** [owid/covid-19-data#2542]
in the [chart](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Share+of+positive+tests&Interval=7-day+rolling+average&Relative+to+Population=true&Color+by+test+positivity=false&country=~ISR) of "share of positive tests" Israel is at 11%. 
![image](https://user-images.githubusercontent.com/445416/157185184-d3337d92-5d3d-4e38-bdcf-2f6587908bf1.png)
MOH reports show that we are at 12% if counting PCR+antigen, and at 7% for PCR only. 
![image](https://user-images.githubusercontent.com/445416/157186343-e0d8d603-b7f3-4c43-a9db-2a19d7c28f7c.png)
I suppose this has to do with relying on JH data. I recommend moving to this [json](https://datadashboardapi.health.gov.il/api/queries/testResultsPerDate) for more accurate positive rates

**Comment by lucasrodes** [comment]
Thanks for reporting, @yuval-harpaz!

@camappel, we could use the cited source in the testing pipeline to get positive rates.

**Comment by Rouein** [comment]
Hi @yuval-harpaz, 
Is there any documentation available for the API?

**Comment by yuval-harpaz** [comment]
unfortunately not. the data is displayed on the formal dashboard, where some info is available for percent=positive:
"Percentage of subjects found to be positive for the COVID-19 virus out of all subjects.
subject - a person who underwent a test to detect the virus (excluding tests to determine recovery) in a PCR test or a supervised antigen test (as of 5.1.2022). You can see this info (hebrew) by clicking the (i) symbol ([link to dashboard](https://datadashboard.health.gov.il/COVID-19/general?utm_source=go.gov.il&utm_medium=referral))
![image](https://user-images.githubusercontent.com/445416/157286474-1b21d58d-50f0-4de7-89f1-d639b7e62bbc.png)

**Comment by Rouein** [comment]
@yuval-harpaz 
I cannot tell what the fields: `amount`, `amountVirusDiagnosis`, `amountPersonTested`,`amountMagen` and , `positiveAmount` refer to or what are their units(mostly). As for the positive rate, I cannot tell whether they are using a 7 day moving average or not to be implemented directly. 
If you are familiar with them and could elaborate, I would be thankful.

**Comment by yuval-harpaz** [comment]
Please take a look here first, I will reply with more detail in ~1h
https://github.com/yuval-harpaz/CovidDataIsrael/blob/master/docs/all_dashboard_timeseries.md

**Comment by Rouein** [comment]
> Please take a look here first, I will reply with more detail in ~1h https://github.com/yuval-harpaz/CovidDataIsrael/blob/master/docs/all_dashboard_timeseries.md

I think there are errors here. if you check the data (e.g. `2020-02-21` ), `positiveAmount` divided by `amount` will give you the positive rate.

**Comment by Rouein** [comment]
I experimented with `2020-02-21` data and `positiveAmount` by `amount` is equal to the positive rate. It seems that my assumption is right.

**Comment by yuval-harpaz** [comment]
to get the correct positive rate for antigen + PCR you have to divide the number of positive cases, given in another json [infectedPerDate](https://datadashboardapi.health.gov.il/api/queries/infectedPerDate) under the field "amount", by the number of tests in the json [testResultsPerDate](https://datadashboardapi.health.gov.il/api/queries/testResultsPerDate), amountPersonTested. 
The fields amount, amountVirusDiagnosis and amountPersonTested in this json all refer to different ways to count the number of tests. There are issues with people who get tested twice, people who get tested for recovery some time after positive result and so on. Since Israel's MOH uses amountPersonTested I recommend that.

**Comment by yuval-harpaz** [comment]
I double checked, as you can see, using cases from infectedPerDate and amountPersonsTested from testResultsPerDate produce positiveRate.
![image](https://user-images.githubusercontent.com/445416/157309016-172f7ec6-70cb-4431-9088-e0296a45bf62.png)
By the way, % positive for antigen is misbehaving recently. I would give a thought regarding using PCR only, but I suppose it is best if results are comparable to other countries.
![image](https://user-images.githubusercontent.com/445416/157309490-54d96c76-4d48-432c-abe6-2e477afdedf0.png)

**Comment by Rouein** [comment]
It is now implemented in #2548 waiting for reviews.

**Comment by Rouein** [comment]
The last positive rate data point is 11.2% (7 days moving average). It seems to validate the previous algorithm using JHU data and have been addressed before in (#2244).
Nevertheless, calculating positive rate directly could be beneficial as the batch data will be corrected faster than JHU data.
