### ISSUE TITLE
data: The worldwide Covid New cases and 7-day average data is not matching with WHO.

### ISSUE THREAD

**Issue by tushartify** [owid/covid-19-data#2549]
### Country

World

### Domain

Cases

### Which data is inaccurate or missing?

New case statistics on OWID for World on 2nd Mar, 3rd Mar, 4th Mar and 5th Mar are far off with that on WHO

### Why do you think the data is inaccurate or missing?

OWID Data:

https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/jhu/full_data.csv

New case statistics on OWID for worldwide on 2nd Mar, 3rd Mar, 4th Mar and 5th Mar are 1,651,874, 1,889,345, 1,702,615, 1,363,321 respectively.

WHO:

https://covid19.who.int/

However, for 2nd, 3rd, 4th and 5th March, the data available on WHO are 1,602,527 1,617,490, 1,707,745, 1,636,595 respectively.

We would like you to please take a look at whether the statistics are correct or need to be corrected in reference with the source mentioned above like WHO.

Please note that the issue was not raised on JHU as they do not provide World data for Covid-19

**Comment by edomt** [comment]
Hi @tushartify 

The WHO and JHU have very different data collection methods:
- The WHO collects data in different ways depending on what's available from each national government, including sometimes by date of infection or date of test;
- JHU always collects by date of report.

This means that on any given day, their data will always be different.
Our data for the entity `World` is calculated as the sum of all country entities in the dataset, therefore it's also logical that the result based on the JHU data is different from the WHO.
