### ISSUE TITLE
fix: reimplement calculations with J&J for Bangladesh

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2550]
### Description

`ValueError: Unknown vaccines found {'Johnson'}`

It looks like Bangladesh is now using J&J - therefore we need to check if our calculations are still correct, and modify the script if needed.

**Comment by Rouein** [comment]
I just checked the source link and their calculations seems to be similar to Philippines.Their are reporting J&J vaccine in the second doses metric only.
In short: 
- 1-dose metric translates to partially vaccinated
- 2-dose metric translates to fully vaccinated
- 3-dose metric translates to booster doses

**Comment by Rouein** [comment]
I will be working on it to see if I can extract manufacturer data so that we can calculate people vaccinated as well.

**Comment by lucasrodes** [comment]
@Rouein I am working on this atm!

**Comment by Rouein** [comment]
> @Rouein I am working on this atm!

Great, here is what I learned:
- When you get the soup, in the scripts under ` Highcharts.chart('all_1st_doses_administered', {` and other charts name manufacturer data is available.
- if you POST a payload in the format of  ``` division=&district=&period=LAST_1_MONTH&date_from_all=2020-02-01&date_to_all=2022-03-09&Submit=Search``` (with the dates that you want) and then get the source for that , you can convert the script to batch.
