### ISSUE TITLE
data: Vaccine's administered in Canada

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2551]
### Country

Canada

### Domain

Vaccinations

### Which data is inaccurate or missing?

Vaccine names and timeline.

### Why do you think the data is inaccurate or missing?

Approved Vaccines :https://www.canada.ca/en/health-canada/services/drugs-health-products/covid19-industry/drugs-vaccines-treatments/vaccines.html
Data on J&J doses : https://health-infobase.canada.ca/covid-19/vaccine-administration/
There is column titled unknown vaccines, that could be a combination of Novavax and Covifenz doses.

**Comment by lucasrodes** [comment]
I just reached out to @noahlittle, who maintains our source https://covid19tracker.ca/vaccinationtracker.html (thank you 🙏), so we can double-check the numbers, as it is currently unclear to me how J&J doses are counted by them.

Partly based on their documentation at https://api.covid19tracker.ca/docs/1.0/vaccinations, my understanding is that they provide:
- `total_vaccinations`: All doses administered.
- `total_vaccinated`: People fully vaccinated.
- `total_boosters_X`: Number of booster X doses administered.

**Comment by Rouein** [comment]
> Thanks for the heads up @Rouein
> 
> I just reached out to @noahlittle, who maintains our source https://covid19tracker.ca/vaccinationtracker.html (thank you pray), so we can double-check the numbers, as it is currently unclear to me how J&J doses are counted by them.
> 
> Partly based on their documentation at https://api.covid19tracker.ca/docs/1.0/vaccinations, my understanding is that they provide:
> 
> * `total_vaccinations`: All doses administered.
> * `total_vaccinated`: People fully vaccinated.
> * `total_boosters_X`: Number of booster X doses administered.

The official source is confusing, I cannot understand whether  "unknown vaccines" refers to new vaccines, vaccinated abroad, or not fully reported administered doses.  They have approved both Novavax and Covifenz but there is no info on whether they have been administered yet.  
Hopefully, @noahlittle has an insight.

**Comment by noahlittle** [comment]
Hi there!

The official data is derived from weekly reports submitted by provinces/territories (PTs), but this comes with some caveats as there are different methods and compliance with reporting and many provinces do not report in a timely or complete fashion. The best source for this data is the daily/weekly reports directly released to the public by each PT, which we use for our API. 

When looking at vaccine coverage as in the official link referenced, note the following definitions:

> **Vaccine not reported**: Includes people for whom the vaccine product received was not reported by the province or territory to the Public Health Agency of Canada.
**Vaccine unknown**: Includes people vaccinated with an unspecified vaccine product. This can occur when the name of the vaccine received is missing in the provincial or territorial vaccine registry.

Based on the latest [official federal distribution data](https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection/prevention-risks/covid-19-vaccine-treatment/vaccine-rollout.html) available, as of March 10th, only Pfizer, Moderna, AstraZeneca and Janssen vaccines have been distributed to the provinces for administration. While residents may have received another vaccine outside of the country, these are the only ones that have been distributed for administration within Canada.

I hope that helps!

**Comment by lucasrodes** [comment]
Fixed reported vaccines over time.

Our current reporting of `people_vaccinated` is an underestimate. But due to the low number of J&J doses administered (around 18k), I would say we leave it as it is for now. I talked with @noahlittle and they may add a new variable in their API to correctly estimate `people_vaccinated`.
