### ISSUE TITLE
enhance(tests): automate test data collection

### ISSUE THREAD

**Issue by camappel** [owid/covid-19-data#2553]
List of manually-updated countries to be automated and their sources:

- [x] [Afghanistan](http://www.emro.who.int/health-topics/corona-virus/situation-reports.html): PDF
- [x] [Bahamas](https://www.bahamas.gov.bs/wps/portal/public/gov/government/news/!ut/p/b1/vZfJkqM4EIafpR6AsiQQgqNYbbMjwOCLwyvewAu2WZ5-XBPTMV3dPa45lI1ORGTGp_xzkdQb99LeuJzeNvn0sjmU0_3H_1ic8MB0KBUkRzJECgYxb_DYorwZwLtBdjcA__FR8NnfxEC8-_s29UkfeRbqjXppP7s22sHJDapM1tko9PXQnUehe92PiHixcwHpzV455OKSSxf2iQgj1TBGDm7ramRfJx1JS7nRrWbu7c6xGJ6yel0dCrnYggBXgCmRml0Pc7FE8z2Ty5tk8Ae7JcoQL1REy3S10QU85IOJ5-mic49bSy4wn825Zi2VYgPBPzE-COJRjBB_4S-A_6fxA8AX_qPe-OEWP3bwt8GjNH6VSLd_KJa97G5GfjKLEgAGENCQwQBILuxFvRQIE7Ztj4Nu14VbULdut3BZ5ADQxSDSUubOdFBdVOjocAh10Dq60EaRYTOwQ8y1_UUSxgpVOU-fnn8FeiiS70AVilaMAQPCs4Em9qS7ECTyKUbA9OCrgfxLJTV9Dzw9wk9FIwTfn8Nhb7yZFe_1vHgH75IsQkwkQZZEIAgS6SXbDBBNGtT6wJ-o1dWVTVwEYFNLRp4F62V8OcyZxbh9CH3On-rVVu-4mV4h61yPd7NAoZvT3rVnXRRKMvCahTkw2Db3g4Oe2lZnBH3BrXWzTgsaJ8Ar2hvHcd5YvRS5m17Xx2V_OYzLhJumHe5OS1_g-dt6tmvNOYG-k11QMuYWFc-z0aoKkRgZZxMKocFWWRpF81Vl-qfL2s3f3h4La1q_12oXoEivkaPXHdwmbqT5gRvvWndhQaYNWmAnAxZltRPfBe4GHbv8EJauHcZmj7tRNfCzgZ-bA1DyYuAfavXJQPHVwGdJGiggYLbMU0AxBoM-iggxYx5g_tURvrpKxVfnUPz-Kv00UXlZJhLEkiBBCUEo9ZJhVsjajtaGPl6F2ZJcyyVix62eVXRzoYBN4nJhmdwti87lSpkgz-ycW07VzbZfcGjYikEXzAJM6K3MjaE6XS5n_WmrHW3zZnt93DqTMY2Si4tnkkayUhGLaHE8-9N0WjoypzbqTVeVEkz44KupKJHfC5yEjrNVrPttooE7hBwtjd3IsJjsQcdO7mcQ6FgMHXcbWmybIeey-iHOPJ9W2Rd3FJN_NvDXqSi-GoifBTQ9J1A_JI2UD0n5fp-KNu_p8NXA78_hp47CAsRYhkgWEUEEko-OaolWDWrt_mgahkiCR5EMpuE1cFZqvhueA5aWh8WaobNU5te95zadt_S5DAf64OTOpjNxEtjtjpLY3NDriCUnLSnIfOvIKjuUOlj5zc7FrWKfV81yhfmDhZrQxEgvjfR8PRX16XStbC297BS8kEHa3GdGTO_ddSzim2XZYtivofTv4ovbH5b0s0n99heUoIvF/dl4/d5/L2dBISEvZ0FBIS9nQSEh/): PDF
- [x] [Bangladesh](http://103.247.238.92/webportal/pages/covid19.php)
- [ ] [Bhutan](https://www.facebook.com/MoHBhutan/)
- [x] [China](http://en.nhc.gov.cn/news.html)
- [ ] [Dominican Republic](https://www.msp.gob.do/web/?page_id=6948#1586785071804-577a2da4-6f72)
-   [x]   [DRC](https://us3.campaign-archive.com/home/?u=b34a30571d429859fb249533d&id=1d019331c1)
-   [x]   [Ecuador](https://www.gestionderiesgos.gob.ec/informes-de-situacion-covid-19-desde-el-13-de-marzo-del-2020/)
-   [ ] [Guyana](https://www.youtube.com/channel/UCGA8-rFam5zwrBs7GZ1tRpw)
- [x] [Iraq](https://moh.gov.iq/)
- [ ] [Jamaica](https://www.moh.gov.jm/ )
- [x]   [Kuwait](https://twitter.com/KUWAIT_MOH)
- [x]   [Maldives](https://twitter.com/HPA_MV)
- [x]  [Morocco](https://twitter.com/Ministere_Sante/)
- [x]   [Oman](https://twitter.com/OmanVSCovid19)
- [ ]  [Palestine](https://www.facebook.com/mohps/)
- [ ] [Panama](https://twitter.com/MINSAPma/)
- [x]   [Paraguay](https://twitter.com/msaludpy)
- [x]   [Poland](https://twitter.com/MZ_GOV_PL)
- [x] [Saint Vincent and the Grenadines](https://www.facebook.com/SVGHEALTH/)
- [x] [Togo](https://covid19.gouv.tg/)
- [x] [Trinidad and   Tobago](https://www.covid19.gov.tt/category/covid-19-updates/)
- [x] [Vanuatu](https://covid19.gov.vu/index.php/surveillance): PDF

**Comment by camappel** [comment]
Thanks! The ones labelled PDF should be the easiest place to start.

**Comment by Rouein** [comment]
should I write a script for WHO EMRO to collect all the countries in the biweekly situation reports? because Afghanistan, Kuwait , Iraq , Oman , Yemen and Palestine can only be automated via WHO reports.

**Comment by lucasrodes** [comment]
@Rouein That is a great idea. I can see how we could extract the data from _Table 1_ from reports (such as http://www.emro.who.int/images/stories/coronavirus/29.pdf). Let me know if you take this, otherwise, I am happy to work on this one.

**Comment by Rouein** [comment]
> @Rouein That is a great idea. I can see how we could extract the data from _Table 1_ from reports (such as http://www.emro.who.int/images/stories/coronavirus/29.pdf). Let me know if you take this, otherwise, I am happy to work on this one.

I am on it.

**Comment by 3dgiordano** [comment]
Hello, if it helps you, EcuaCovid test data for Ecuador (the same data source used in vax data)

https://github.com/andrab/ecuacovid/blob/master/datos_crudos/ecuacovid-positivas_por_dia.csv

**Comment by Rouein** [comment]
@camappel , @lucasrodes 
weekly Testing data for poland is available in ecdc. should I write script for ecdc or just for poland?

**Comment by Rouein** [comment]
Hi @camappel ,
I think this issue can be closed based on the list in my first comment. Otherwise, let me know what I might have missed.
