### ISSUE TITLE
check(vax): countries where a metric is >5% higher in WHO than OWID

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2554]
For the countries listed below, the WHO shows either `people_vaccinated` or `people_fully_vaccinated` with a value that's at least 5% higher than our latest count. We should check them to make sure that there is nothing wrong with our current calculations. (It's possible that our data is fine, and that the differences are due to reporting errors, or definitions that are different from ours – but we should check nevertheless.)

- [x] Bulgaria: Differences in `total_vaccinations` and `people_fully_vaccinated` are negligible (1%). The difference in `people_vaccinated` is high because it hasn't been reported for a long time (the source does not allow for it to be estimated, due to single-doses). I have added a call to `add_latest_who_values` to obtain `people_vaccinated` from the WHO.
- [x] Guinea: Differences due to latest reporting dates miss-match. 2022-03-13 for the WHO, 2022-02-27 for us. So far we had been collecting data for Guinea manually, now switching to automated using the WHO.
- [x] Guyana: WHO reported values are ~5% higher for all metrics, even if their reporting date is earlier. There might have been some counting discrepancies between the National Government and the WHO (cc. @camappel). So far  we have been collecting the data manually, moving to automated using PAHO (which also includes booster doses) 
- [x] Israel: We report 30% (~5 million) more doses compared to the WHO. This appears to be due to the WHO not counting booster doses, which currently are precisely [~5 million](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Vaccine+booster+doses&Interval=7-day+rolling+average&Relative+to+Population=false&Color+by+test+positivity=false&country=~ISR). Also, the last update from the WHO dates back to 2022-02-13. No action is required.
- [x] Kazakhstan: Most noticeable differences come from `total_vaccinations`, as we haven't reported new values for ~10 days. This is because they stopped reporting booster data, hence we are not able to estimate the total number of doses. Regarding `people_vaccinated` and `people_fully_vaccinated`, although slightly different, I am confident that [our current source](https://www.coronavirus2020.kz/) should be more accurate. They should release data on boosters soon again, so we should have good estimates for all metrics soon. I sent them a message, I hope to hear back from them soon.
- [x] Lebanon: Our numbers are slightly lower than WHO's (~5%). The [source we use](https://impact.cib.gov.lb/home?dashboardName=vaccine) seems legit and up to date. I dropped them a message to see if they know the reasons behind these discrepancies.
- [x] Philippines: Differences seem reasonable due to date mismatch (2022-02-24 for WHO, 2022-03-13 for [our source](https://news.abs-cbn.com/spotlight/multimedia/infographic/03/23/21/philippines-covid-19-vaccine-tracker)). Metric `people_vaccinated` can't be extracted or estimated from the source. I have added a call to `add_latest_who_values` to import ` people_vaccinated` from WHO, as we can't currently estimate it from the source.
- [x] Qatar: Main discrepancies stem from metrics `people_vaccinated` and `people_fully_vaccinated`, which are not reported by [our source](https://covid19.moph.gov.qa/EN/Pages/Vaccination-Program-Data.aspx) but by the WHO. I have added a call to `add_latest_who_values` to get WHO's values for these metrics.
- [x] Moldova: Discrepancy appearing for `people_vaccinated` (~7%). We haven't reported this metric since 2021-10-03, as [our source](https://vaccinare.gov.md) does not allow for its estimation/extraction. Metric `people_vaccinated` can't be extracted or estimated from the source. I have added a call to `add_latest_who_values` to get WHO's values for this metric.
- [x] Tunisia: Our reports are quite lower than WHO's for metrics `total_vaccinations` and `people_vaccinated` (~10%), even if ours are more recent (2022-03-14 vs 2022-02-27). [Our current](https://www.facebook.com/photo?fbid=335215358648933&set=pcb.335215421982260) source seems perfectly fine. It provides complete data: total doses, people with one dose, people with two doses, people with single-dose (J&J) and boosters. I presume there is some miscalculation being done by the WHO. No action required.

**Comment by lucasrodes** [comment]
For reproducibility purposes, find the code to recreate this analysis below. When executing, it should display a dataframe with the ratios between WHO and OWID metrics.

```python
import pandas as pd
from cowidev.vax.incremental.who import WHO

# Countries of interest
countries = {
    "Bulgaria": "Bulgaria",
    "Guinea": "Guinea",
    "Guyana": "Guyana",
    "Israel": "Israel",
    "Kazakhstan": "Kazakhstan",
    "Lebanon": "Lebanon",
    "Philippines": "Philippines",
    "Qatar": "Qatar",
    "Republic of Moldova": "Moldova",
    "Tunisia": "Tunisia",
}
countries_who = list(countries.keys())
countries_owid = list(countries.values())

# Read data from WHO
who = WHO()
df = who.read()
df_who = df.loc[
    df.COUNTRY.isin(countries_who),
    ['COUNTRY', 'TOTAL_VACCINATIONS', 'PERSONS_VACCINATED_1PLUS_DOSE', 'PERSONS_FULLY_VACCINATED']
]
df_who = df_who.assign(COUNTRY=df.COUNTRY.replace(countries))

# Read our data
url = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv"
df = pd.read_csv(url)
df = df.loc[
    df.location.isin(countries_owid),
    ["location", "date", "total_vaccinations", "people_vaccinated", "people_fully_vaccinated"]
].sort_values("date").fillna(method="ffill").drop_duplicates(subset=["location"], keep="last")

# Merge & estimate ratio owid/who
df = df.merge(df_who, left_on="location", right_on="COUNTRY")
df = df.assign(
    ratio_total=(1-df.total_vaccinations/df.TOTAL_VACCINATIONS) * 100,
    ratio_ppl=(1-df.people_vaccinated/df.PERSONS_VACCINATED_1PLUS_DOSE) * 100,
    ratio_full=(1-df.people_fully_vaccinated/df.PERSONS_FULLY_VACCINATED) * 100,
)

# Display
cols = df.columns
cols_imp = ["location", "ratio_total", "ratio_ppl", "ratio_full"]
cols = [c for c in cols if c not in cols_imp]
df[cols_imp + cols]
```

**Comment by lucasrodes** [comment]
Checked all countries and fixed when applicable, mainly by importing data from the WHO and automating previously manual processes.

I also contacted people behind our sources for Kazakhstan and Lebanon, to clarify some issues.

In some other cases, WHO data doesn't seem to be aligned with national reports (likely due to a miscalculation on their side, not considering boosters, etc.)
