### ISSUE TITLE
feat(vax,hk): add vaccinations by age

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2556]
Our current source already includes doses administered by age, but we don't have HK in our current dataset by age.

I think the source only provides the numerator though. For the denominators we can use the following age-group estimates from the [United Nations](https://population.un.org/wpp/):

```python
{
    "0 - 19": 1248580,
    "20 - 29": 835068,
    "30 - 39": 1113725,
    "40 - 49": 1134217,
    "50 - 59": 1188969,
    "60 - 69": 1085732,
    "70 - 79": 563693,
    "80 and above": 382816,
}
```

**Comment by lucasrodes** [comment]
Live

- [people vaccinated](https://ourworldindata.org/grapher/covid-vaccine-by-age?country=~HKG)
- [people with completed primary protocol](https://ourworldindata.org/grapher/covid-fully-vaccinated-by-age?country=~HKG)
- [people with booster dose](https://ourworldindata.org/grapher/covid-booster-vaccinated-by-age?country=~HKG)
