### ISSUE TITLE
bug: Duplicate countries in iso code list

### ISSUE THREAD

**Issue by 3dgiordano** [owid/covid-19-data#2558]
### Description

Hi @lucasrodes 

In this last commit you correctly incorporated the numeric column, however there are duplicate rows.

https://github.com/owid/covid-19-data/commit/aa2421cf6a91b97c0b39d946eea6a4e3cc181ab9

The countries I noticed duplicates

- BOL
- CIV
- LBY
- MMR
- RUS
- KOR
- TWN
- VEN
- VNM

**Comment by lucasrodes** [comment]
Thanks for spotting, @3dgiordano!
Just fixed it.
