### ISSUE TITLE
Daily_vaccinations calculation

### ISSUE THREAD

**Issue by wellsangels** [owid/covid-19-data#256]
I'm trying to figure out how you're calculating the <b>daily_vaccination</b> column in the [vaccinations.csv ](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv)file for countries that don't report daily. It looks like you're averaging the difference between two points to fill in the gaps, and then taking the seven-day average of that, but only after 12/28. Can you tell us what the calculation is before that?

<table>
<thead><tr><th>date</th><th>total_vaccinations</th><th>daily_vaccinations</th><th>diff_avg</th><th>seven_day_avg</th></tr></thead><tbody>
 <tr><td>12/20/20</td><td> 556,208 </td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td>12/21/20</td><td> 614,117 </td><td> 57,909 </td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td>12/22/20</td><td>&nbsp;</td><td> 127,432 </td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td>12/23/20</td><td> 1,008,025 </td><td> 150,606 </td><td> 196,954.00 </td><td> 196,954 </td></tr>
 <tr><td>12/24/20</td><td>&nbsp;</td><td> 191,001 </td><td> 312,187 </td><td> 254,570 </td></tr>
 <tr><td>12/25/20</td><td>&nbsp;</td><td> 215,238 </td><td> 312,187 </td><td> 273,776 </td></tr>
 <tr><td>12/26/20</td><td> 1,944,585 </td><td> 231,396 </td><td> 312,186.67 </td><td> 283,379 </td></tr>
 <tr><td>12/27/20</td><td>&nbsp;</td><td> 211,379 </td><td> 91,279.00 </td><td> 244,959 </td></tr>
 <tr><td>12/28/20</td><td> 2,127,143 </td><td> 216,147 </td><td> 91,279.00 </td><td> 219,345 </td></tr>
 <tr><td>12/29/20</td><td>&nbsp;</td><td> 235,685 </td><td> 333,722.50 </td><td> 235,685 </td></tr>
 <tr><td>12/30/20</td><td> 2,794,588 </td><td> 255,223 </td><td> 333,722.50 </td><td> 255,223 </td></tr>
 <tr><td>12/31/20</td><td>&nbsp;</td><td> 278,776 </td><td> 477,056.00 </td><td> 278,776 </td></tr>
 <tr><td>1/1/21</td><td>&nbsp;</td><td> 302,329 </td><td> 477,056.00 </td><td> 302,329 </td></tr>
 <tr><td>1/2/21</td><td> 4,225,756 </td><td> 325,882 </td><td> 477,056.00 </td><td> 325,882 </td></tr>
 <tr><td>1/3/21</td><td>&nbsp;</td><td> 336,949 </td><td> 168,752.00 </td><td> 336,949 </td></tr>
 <tr><td>1/4/21</td><td> 4,563,260 </td><td> 348,017 </td><td> 168,752.00 </td><td> 348,017</td></tr>
</tbody></table>

**Comment by edomt** [comment]
Hi @wellsangels 

That's indeed exactly how we do this.

- For days when we don't have data, we interpolate the totals linearly (by assuming the same amount of vaccinations each day) between the previous and the next data point;
- We calculate the daily differences between those totals;
- We smooth the result with a 7-day rolling average. The rolling window allows partial data, so for the earliest days in each country it can be calculated with less than 7 values.

**Comment by wellsangels** [comment]
Great. Thanks for the prompt response
