### ISSUE TITLE
Vaccination: how will you deal with second shots?

### ISSUE THREAD

**Issue by sapomnia** [owid/covid-19-data#257]
Both Moderna and Pfizer-BioNTech vaccine need a second shot to give a complete immunization from the virus. What will happen to the dataset once they start with second shots? Of course they will not be counted twice to calculate the percentage of people vaccinated. Are you planning on adding a new column to the dataset? Thanks in advance

**Comment by edomt** [comment]
Hi @sapomnia. See #234
