### ISSUE TITLE
data: Trinidad and Tobago Vaccines

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2571]
### Country

Trinidad and Tobago

### Domain

Vaccinations

### Which data is inaccurate or missing?

It seems that J&J doses have been administered in Trinidad and Tobago.

### Why do you think the data is inaccurate or missing?

The latest data: 
{"objectid":969,"globalid":"7e096d09-9d70-408d-ae2c-2a90adaacd3f","report_dt":1647553500000,"reportlocation":"+010.79615_-061.05270","total_samples":null,"unique_tests":360559,"repeated_tests":null,"positive_tests":134272,"active_cases":10773,"deaths":3700,"discharged":119799,"cmmf_total":54,"cmmf_icu":8,"cmmf_hdu":4,"caura":22,"brooklyn":null,"balandra":null,"tacarigua":0,"uwi_debe":0,"uwi_canada":null,"uwi_freedom":null,"napa":null,"CreationDate":1647553733487,"Creator":"MOH_GIS1","EditDate":1647553733487,"Editor":"MOH_GIS1","HomeQuarantine":10543,"Processing":0,"arima":30,"arima_icu":null,"arima_hdu":null,"augustus_long":35,"st_anns":1,"scarborough_regional":10,"signal_hill":3,"tobago_stepdown":0,"claxton_bay_correctional":0,"Update_Num":"1031","sum_hospitalised":177,"sum_stepdown_facs":21,"state_quarantine":32,"new_cases_reported":484,"report_day":"Thu, 17 Mar 2022","unique_public_private_test":657641,"unique_private_tests":297082,"report_date_str":"17/03/2022","positive_to_tests_prop":0.20417218512836,"total_vaccinated":688452,"total_pop_first_vaccine":0.493513978494624,"total_second_dose":706781,"proportion_with_second_vaccine":0.506653046594982,"utt_valsayn":0,"point_fortin_hospital":21,"field_hospital_jean_pierre":0,"new_point_fortin_hospital":0,"field_hospital_couva":0,"total_scarborough_occup":13,"total_parallel_occupancy":198,"cfu_port_of_spain":0,"fd_astrazeneca":null,"fd_sinopharm":null,"sd_astrazeneca":null,"sd_sinopharm":null,"st_james_med":22,"sd_total_second_dose":650830,"fd_pfizer":null,**"fd_j_and_j":55951**,"total_icu":11,"rolling_sevenday_deaths":null,"additional_primary_dose":141910,"additional_primary_proportion":0.101727598566308,"deaths_additional":5,"epi_week":"Week 11","epi_year":"2022","ray_of_hope":0,"epi_week_number":11}

Historical data available in the [JSON](https://services3.arcgis.com/x3I4DqUw3b3MfTwQ/arcgis/rest/services/service_7a519502598f492a9094fd0ad503cf80/FeatureServer/0/query?f=json&resultOffset=0&resultRecordCount=32000&where=report_dt%20IS%20NOT%20NULL%20AND%20report_dt%20BETWEEN%20timestamp%20%272020-12-20%2021%3A00%3A00%27%20AND%20CURRENT_TIMESTAMP&orderByFields=report_dt%20asc&outFields=*&resultType=standard&returnGeometry=false&spatialRel=esriSpatialRelIntersects).

P.S. Batch Hospitalization data is available in the JSON.

**Comment by lucasrodes** [comment]
Hi @Rouein,
Thanks for your report. 

We have been reporting J&J doses for Trinidad and Tobago since 2021-08-13. Could you please elaborate on what is that is inaccurate in Trinidad and Tobago's data?


Thanks!

**Comment by Rouein** [comment]
> Hi @Rouein, Thanks for your report.
> 
> We have been reporting J&J doses for Trinidad and Tobago since 2021-08-13. Could you please elaborate on what is that is inaccurate in Trinidad and Tobago's data?
> 
> Thanks!

You are right I must have mixed the csvs.
