### ISSUE TITLE
data: Romania Testing

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2577]
### Country

Romania

### Domain

Testing

### Which data is inaccurate or missing?

Daily change in cumulative total
Daily change in cumulative total per thousand

### Why do you think the data is inaccurate or missing?

May I confirm the above data are been fully deleted from the source?

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
We recently switched to ECDC as our main source for Romania. As a consequence, the time series has slightly changed (new dates added, some removed, etc.).

cc @camappel

**Comment by Leonaides96** [comment]
> 

Hi @lucasrodes ,
Okay noted and when can know the data will be updated?

**Comment by lucasrodes** [comment]
We update the data daily, before 12h CET.

Note that ECDC does not report data on a daily base. In particular, [their last report](https://www.ecdc.europa.eu/en/publications-data/covid-19-testing) is from the 17th of March, when only data up to the 10th of March was available for Romania.

**Comment by Leonaides96** [comment]
@lucasrodes 

Alright understand, thanks for the reply.
