### ISSUE TITLE
Inconsistent number of confirmed cases in France

### ISSUE THREAD

**Issue by Lofhi** [owid/covid-19-data#258]
It will never be fixed, because it's a choice made by the Johns Hopkins University, so I'm writing this note. You can read on the government [dashboard](https://dashboard.covid19.data.gouv.fr/vue-d-ensemble?location=FRA) that the numbers are less important than the reported by the university.

The university has added **confirmed or possible cases** to the total number of **confirmed cases**. Moreover, the addition made by Johns-Hopkins were distorted by the fact that the Ehpad (or EMS) patients who were tested (and who therefore represent a share of the precedent confirmed or possible cases) were already counted among the total of confirmed cases.

You can read [here](https://github.com/CSSEGISandData/COVID-19/issues/2226#issuecomment-614931386) their message where they confirm adding probable cases to the total number of confirmed cases. [Here](https://github.com/CSSEGISandData/COVID-19/issues/2459) the official announcement.

Admittedly, today it doesn't really matter anymore (confirmed cases are underestimated compared to reality), but it remains a strange decision of the university that has been forgotten over the months.

**Comment by edomt** [comment]
Thanks for documenting this @Lofhi. I'll leave it here for others to see if needed.
