### ISSUE TITLE
data: Total Tests in Nicaragua

### ISSUE THREAD

**Issue by Javierpedatos** [owid/covid-19-data#2580]
### Country

Nicaragua

### Domain

Testing

### Source

http://www.minsa.gob.ni/index.php/repository/Descargas-MINSA/COVID-19/Boletines-Epidemiol%C3%B3gico/Boletines-2022/Bolet%C3%ADn-Epidemiol%C3%B3gico-de-la-Semana-No.-9/

### Comments

Information from March 8

**Comment by Javierpedatos** [comment]
New epidemiological reports from Nicaragua

https://www.minsa.gob.ni/index.php/repository/Descargas-MINSA/COVID-19/Boletines-Epidemiol%C3%B3gico/Boletines-2022/

Week 17: https://www.minsa.gob.ni/index.php/repository/Descargas-MINSA/COVID-19/Boletines-Epidemiol%C3%B3gico/Boletines-2022/Bolet%C3%ADn-Epidemiol%C3%B3gico-de-la-Semana-No.-17/

Week from 10 to 17

Week 10: 2,443 tests performed ,183,540 total tests
Week 11: 1,835 tests perfomed ,185,372 total tests
Week 12: 1,611 test perfomed ,186,983 total tests
Week 13: 1,512 test perfomed , 188,495 total tests
Week 14: 1,392 tests perfomed, 189,887 total tests
Week 15: 956 tests perfomed, 190,843 total tests
Week 16: 1,283 tests perfomed, 192,126 total tests
Week 17: 1,382 tests perfomed, 193,508 total tests

**Comment by camappel** [comment]
Thank you, this data will be included in today's update.
