### ISSUE TITLE
data: Data for UK is not matching with many sources including JHU.

### ISSUE THREAD

**Issue by gauravjoshijo** [owid/covid-19-data#2582]
### Country

UK 

### Domain

Cases

### Which data is inaccurate or missing?

Hello, 

Since OWID takes data[ from the JHU](https://github.com/owid/covid-19-data/blob/master/public/data/README.md), then shouldn't they match? Below is given the data of OWID feed for the following dates:

29th March- 81280
30th March- 88648
31st March- 74664
1st April -69689.

& Data as per JHU: 

29th March: 80656
30th March: 86838
31st March: 74416
1st April: 69449

The difference is minute, but is it expected? 

Also there seem to be some data discrepancy in the data also : 

[WHO](https://covid19.who.int/region/euro/country/gb) : 
29th March : 67,870 
30th March: 91,075 
31st March:   69,485 
1st April: 35,968 
 
[Worldometer: ](https://www.worldometers.info/coronavirus/country/uk/ )
29th March:  92279
30th March: 77,915
31st March:  63, 462
1st April: 29,825
[
UK Govt. Official Website:](https://coronavirus.data.gov.uk/details/cases)
29th March: 77,915
30th March:  63,462
31st March: 29,825
1st April:  Not available

I would have reported this in JHU CSSE, but mismatching of JHU and OWID would not have been addressed there. 

Thanks :)

 

### Why do you think the data is inaccurate or missing?

NA

**Comment by edomt** [comment]
Hi @gauravjoshijo - thanks for reporting!

For the data labeled `United Kingdom` in our dataset, we group together some of the entities that are separated in JHU dataset. 

Precisely, our values are the sum of:

- "Mainland" UK (the row with an empty `Province/State` in the JHU dataset)
- Channel Islands
- Guernsey
- Jersey

That's what explains the discrepancy you're seeing between the original JHU dataset and our files.

**Comment by gauravjoshijo** [comment]
Thanks for the swift reply. I have checked a few of these dates in JHU feed to compare it with OWID, Except 1st of the April no other data is matching with OWID feed. Do I need to 

![Screenshot 2022-04-04 9 05 27 PM](https://user-images.githubusercontent.com/91567479/161579947-220665f6-1cc5-443c-9e11-45267ce8908e.png)

**Comment by gauravjoshijo** [comment]
Oh! Thanks for highlighting... I had applied the sum formula in haste without realizing I applied a filter. As they say, "Haste makes waste" 

Now the stats match perfectly. Once again Thanks!!
