### ISSUE TITLE
docs(vax): update documentation to mention vaccination updates on weekdays only

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2586]
- [x] Update the main public README (table + changelog + other possible mentions?)
- [x] Update https://covid-docs.ourworldindata.org/en/latest/ if necessary
- [x] Pin an announcement at the top of https://github.com/owid/covid-19-data/discussions

**Comment by lucasrodes** [comment]
I just created https://github.com/owid/covid-19-data/pull/2587 in this regard. Once merged, we can trigger an update on the live documentation (point 2) and then release an announcement in the discussions section (point 3).

**Comment by lucasrodes** [comment]
Announcement published: https://github.com/owid/covid-19-data/discussions/2588

**Comment by lucasrodes** [comment]
Documentation updated. In particular, the table under "Overview" and text under "Vaccinations pipeline" at https://covid-docs.ourworldindata.org/en/latest/data-pipeline.html .
