### ISSUE TITLE
data: In-use China-developed COVID-19 Vaccines

### ISSUE THREAD

**Issue by aywi** [owid/covid-19-data#2598]
### Country

China

### Domain

Vaccinations

### Which data is inaccurate or missing?

Seven in-use China-developed COVID-19 vaccines that obtained [NMPA](https://www.nmpa.gov.cn/) approval/EUA are listed as follows:

|  Vaccine   |          WHO Name           |      OWID Name      |                                                        NMPA EUA                                                        |                                 NMPA Approval                                  |                                                              WHO EUL                                                              |
| :--------: | :-------------------------: | :-----------------: | :--------------------------------------------------------------------------------------------------------------------: | :----------------------------------------------------------------------------: | :-------------------------------------------------------------------------------------------------------------------------------: |
| BBIBP-CorV | `Beijing CNBG - BBIBP-CorV` | `Sinopharm/Beijing` |            **[2020-07-22](http://www.nhc.gov.cn/xcs/s3574/202012/dd603e667f6d47238a8998860f8b9c0a.shtml)**             |   [2020-12-30](https://www.nmpa.gov.cn/yaowen/ypjgyw/20201231193329157.html)   |                  [2021-05-07](https://extranet.who.int/pqweb/vaccines/who-recommendation-covid-19-vaccine-bibp)                   |
| CoronaVac  |    `Sinovac - CoronaVac`    |      `Sinovac`      |            **[2020-07-22](http://www.nhc.gov.cn/xcs/s3574/202012/dd603e667f6d47238a8998860f8b9c0a.shtml)**             |   [2021-02-05](https://www.nmpa.gov.cn/yaowen/ypjgyw/20210206154636109.html)   | [2021-06-01](https://extranet.who.int/pqweb/vaccines/who-recommendation-sinovac-covid-19-vaccine-vero-cell-inactivated-coronavac) |
| WIBP-CorV  | `Wuhan CNBG - Inactivated`  |  `Sinopharm/Wuhan`  |            **[2020-07-22](http://www.nhc.gov.cn/xcs/s3574/202012/dd603e667f6d47238a8998860f8b9c0a.shtml)**             |   [2021-02-25](https://www.nmpa.gov.cn/yaowen/ypjgyw/20210225184306142.html)   |                                                                 /                                                                 |
| Convidecia |   `CanSino - Convidecia`    |      `CanSino`      |                                                          /[1]                                                          | **[2021-02-25](https://www.nmpa.gov.cn/yaowen/ypjgyw/20210225184523188.html)** |                                                                 /                                                                 |
|  Zifivax   |    `Anhui ZL - Zifivax`     |      `ZF2001`       |                  **[2021-03-10](https://www.im.cas.cn/xwzx2018/jqyw/202103/t20210316_5975187.html)**                   |   [2022-03-01](https://www.nmpa.gov.cn/yaowen/ypjgyw/20220302143909157.html)   |                                                                 /                                                                 |
|  Covidful  |     `IMB - Covidful`[2]     |  **`IMBCAMS`**[3]   |                 **[2021-05-01](https://www.imbcams.ac.cn/en/responsibility/protectingagainstcovid19)**                 |                                       /                                        |                                                                 /                                                                 |
|  KCONVAC   | `Shenzhen - LV-SMENP-DC`[4] |  **`KCONVAC`**[5]   | **[2021-05-14](https://www.szse.cn/disclosure/listed/bulletinDetail/index.html?d3c250ff-42f9-4a8b-87ce-41ad63495776)** |                                       /                                        |                                                                 /                                                                 |

- [1] Convidecia didn't obtain EUA from NMPA before the approval but only [obtained military specially-needed drug approval from PLA on 2020-06-25](https://www.cansinotech.com/html/1//156/218/index.html) which cannot be considered an EUA.
- [2] The older name is `IMB - Inactivated`.
- [3] Currently are `Covidful` and `IMBCAMS/Inactivated`. Suggesting `IMBCAMS` ([Institute of Medical Biology, Chinese Academy of Medical Sciences](https://www.imbcams.ac.cn/en)) since OWID favored developer-related names (and `Inactivated` is unnecessary).
- [4] The name is misleading because [LV-SMENP](https://covid19.trackvaccines.org/vaccines/62/) is another Shenzhen-developed vaccine that has no update since 2021. [KCONVAC](https://covid19.trackvaccines.org/vaccines/47/) is the only Shenzhen-developed vaccine that obtained EUA.
- [5] Currently is `LV-SMENP`. Suggesting ~~`BioKangtai` ([Shenzhen Kangtai Biological Products Co., Ltd.](https://en.biokangtai.com/)) since OWID favored developer-related names~~`KCONVAC`.

### Why do you think the data is inaccurate or missing?

1. `CanSino` should be added to [`China.csv`](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/China.csv) starting from 2021-02-25.
2. `ZF2001` should be added to [`China.csv`](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/China.csv) starting from 2021-03-10.
3. `Covidful` and `IMBCAMS/Inactivated` should be combined as `IMBCAMS`, and mapped to `IMB - Covidful` and `IMB - Inactivated` in [`checks.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/vax/utils/checks.py) and [`who_config.yaml`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/vax/utils/orgs/who_config.yaml).
4. `IMBCAMS` should be added to [`China.csv`](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/China.csv) starting from 2021-05-01.
5. `LV-SMENP` should be renamed as `KCONVAC` in [`checks.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/vax/utils/checks.py) and [`who_config.yaml`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/vax/utils/orgs/who_config.yaml).
6. `KCONVAC` should be added to [`China.csv`](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/China.csv) starting from 2021-05-14.
7. `IMBCAMS` and `KCONVAC` should be added to [`china.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/vax/incremental/china.py).

**Comment by lucasrodes** [comment]
Thanks very much for your contribution, @aywi! This helps us a lot.

I've added some minor changes in #2599

**Comment by aywi** [comment]
It looks good now.
