### ISSUE TITLE
Portugal Cases Tested Source

### ISSUE THREAD

**Issue by f13arnabe** [owid/covid-19-data#26]
Hi @edomt ,
I am from Portugal and I am building a Dashboard in PowerBI about this Pandemic and I am interesting in show a chart with Total Cases vs Total Tests in Portugal but I couldn't find that information in the Github source that I am using DSSG-PT but I found that your csv data "covid-testing-latest-data-source-details.csv" contains tests for Portugal and you refer as source the same source where I am retrieving the data for Portugal "Portugal - cases tested	2020-04-21	**https://github.com/dssg-pt/covid19pt-data/blob/master/data.csv**" but I couldn't find that info in that csv. Could you please help me?

Best regards,
Fábio Barnabé

**Comment by edomt** [comment]
Hi @f13arnabe 

The Portugal Ministry of Health provides daily updates of the number of confirmed cases, unconfirmed cases, and those awaiting laboratory results. You can see them here for example: https://covid19.min-saude.pt/wp-content/uploads/2020/04/50_DGS_boletim_20200421.pdf

Given that _"aguardam resultado laboratorial"_ are reported separately from _"total de casos não confirmados"_, this suggests _"total de casos não confirmados"_ refers to those with a negative test result and _"total de casos confirmados"_ to those with a positive test result. Hence, we sum _confirmados_ + _não confirmados_ cases to get an estimate of the total number of cases tested. 

You can find the equivalent data in the dssg-pt data, in columns `confirmados` and `n_confirmados`: https://github.com/dssg-pt/covid19pt-data/blob/master/data.csv

Edouard

**Comment by f13arnabe** [comment]
Thanks @edomt 👍

**Comment by f13arnabe** [comment]
Hi @edomt , shouldn't we consider that "Aguardam resultado laboratorial", column lab in the DSSG PT dataset from Github, meaning waiting for results, counts as Tests that were done also? After those waiting results get conclusive, we will get either "new confirmed cases" or "not confirmed cases", but we will always have "waiting for result" ones. I guess the total tests should be sum confirmados + não confirmados + lab . Am I right?

**Comment by edomt** [comment]
Hi @f13arnabe 

I guess it depends what exactly it is that you want to describe. If your target is the exact number of samples taken so far, then yes you should include "Aguardam resultado laboratorial".

However, in our testing data, we try to give numbers that are as close as possible to the _actual_ number of fully processed tests, because we think that it has a great impact on the number of cases that are reported. So for all countries we try to exclude pending tests (when we have the information).

Edouard
