### ISSUE TITLE
data: Testing and Distribution of cases by severity Syria

### ISSUE THREAD

**Issue by Javierpedatos** [owid/covid-19-data#2602]
### Country

Syria

### Domain

Testing

### Source

https://reliefweb.int/sites/reliefweb.int/files/resources/covid-19_weekly_epidemiological_bulletin-_22w15-2.pdf

### Comments

Epidemiological Report of Syria that belongs to the week of April 10 to 16. Data of Tests Performed, Positivity and more information about vaccination

**Comment by camappel** [comment]
Thank you for finding this source.

WHO EMRO, our previous source for Syria (along with other countries in the region), stopped reporting the number of tests in their situation reports on 12-03-2021. We will use the new source for Syria until WHO EMRO report test figures again.
