### ISSUE TITLE
Last update was incomplete?

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2609]
Reported by @marcopiani

<div type='discussions-op-text'>

<sup>Originally posted by **marcopiani** April 22, 2022</sup>
Hi,

Is there any issue with the most recent update?

The data appears not to have been updated up to yesterday (last date on graphs is Apr 20, rather than the expected Apt 21).

Thanks!

Marco</div>

**Comment by edomt** [comment]
Thank you for reporting @marcopiani - this has now been fixed. I'll leave it to @lucasrodes to investigate (if needed).

**Comment by marcopiani** [comment]
Thanks to you for the prompt fix, @edomt !

**Comment by aywi** [comment]
Another issue is the [data on China](https://github.com/owid/covid-19-data/commits/master/scripts/output/vaccinations/main_data/China.csv) seems never be updated through "data(vax): automated update (get,process)". Is there any additional setting on the server-side? For recent versions, there is no problem in local runs.

**Comment by lucasrodes** [comment]
@aywi, We are getting several timeouts when running our script for China. I'll try to increase the timeout limit and see how it works.

This was not the case a month ago. I wonder if something was added on the server that prevents automation scripts from running less seamlessly.

**Comment by aywi** [comment]
@lucasrodes If the timeout is the 30s limit per page I saw in the script, I guess this is less likely the problem of the potential anti-crawler of the www.nhc.gov.cn website. I have tried fetching 300+ days of data from that website without problems (by adding 2s sleep intervals). But it did have some problems when I tried to fetch the www.gov.cn website. So if the timeout keeps happening in the future (after solving the server issues), you may also try to add a 2~5s sleep interval after each single page visit.

**Comment by aywi** [comment]
https://github.com/owid/covid-19-data/blob/1c8afc4e8aad57c22582d3fd8b4dc38f720ced6d/scripts/src/cowidev/vax/incremental/china.py#L80

@lucasrodes This line also needs to be considered if you want to add sleep as in https://github.com/owid/covid-19-data/commit/f62a63c7acf28c02ec124a7944cf85b3dba55596.

**Comment by johncdavis200** [comment]
I just downloaded https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/us_state_vaccinations.csv
and it still does not have any data after April 20, 2022.  Can someone check on that data as well?
Thanks,
JD

**Comment by lucasrodes** [comment]
> I just downloaded https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/us_state_vaccinations.csv
> and it still does not have any data after April 20, 2022. Can someone check on that data as well?
> Thanks,
> JD

@johncdavis200 The data for US vaccinations is updated daily at 19:00h UTC, with data until the previous day.

**Comment by lucasrodes** [comment]
> @lucasrodes These lines also need to be considered if you want to add sleep as in https://github.com/owid/covid-19-data/commit/f62a63c7acf28c02ec124a7944cf85b3dba55596.
> 
> Also, I find out the most possible problem may be not the timeout, but the index page not being fully loaded (that is, return null list). http://www.nhc.gov.cn/xcs/yqjzqk/list_gzbd.shtml and http://www.nhc.gov.cn/xcs/s2906/new_list.shtml can auto refresh a little time after driver.get(url) finished. So for the driver.get(url) in read() and read_complete(), the sleep interval should be longer and [5, 10] is acceptable. For the driver.get(url) in _parse_data() and _parse_data_complete(), the sleep interval could be shorter like [2, 5].

@aywi Thanks for your suggestions. Added these, will evaluate these days.

**Comment by aywi** [comment]
@lucasrodes I can finally replicate the potential timeout that could also happen on the server. During some time of the day, the page loading of sub-pages of http://www.nhc.gov.cn/xcs/yqjzqk/list_gzbd.shtml and http://www.nhc.gov.cn/xcs/s2906/new_list.shtml could be slow down by some unnecessary web elements (pointing to other websites). I have already made a fix for that.
