### ISSUE TITLE
data: India Testing Data on April 14

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#2610]
### Country

India

### Domain

Testing

### Which data is inaccurate or missing?

the value of new_tests on April 14 does not seem correct.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File href="file:///C:/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List href="file:///C:/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

iso_code | continent | location | date | new_tests
-- | -- | -- | -- | --
IND | Asia | India | 4/12/2022 | 406251
IND | Asia | India | 4/13/2022 | 429323
IND | Asia | India | 4/14/2022 | 35855632
IND | Asia | India | 4/15/2022 | 367213
IND | Asia | India | 4/16/2022 | 300918

</body>

</html>

### Why do you think the data is inaccurate or missing?

35855632 is about 100 times than normal data.

**Comment by camappel** [comment]
Our source for testing data in India is https://github.com/datameet/covid19. This sudden increase is probably due to a backlog of tests being reported all at once. We will remove the positive rate for the week following 2022-04-14 to account for the sudden increase
