### ISSUE TITLE
data(vax,chn): Correcting Early Entries of China COVID-19 Vaccination Data

### ISSUE THREAD

**Issue by aywi** [owid/covid-19-data#2615]
## Correcting Automated Entries

|    date    |                                                                                source_url                                                                                 |         total_vaccinations |     Reason     |
| :--------: | :-----------------------------------------------------------------------------------------------------------------------------------------------------------------------: | -------------------------: | :------------: |
| 2021-04-06 |                                     [www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/yqjzqk/202104/f46fb541aabb4b4c8a79317dd542baa6.shtml)                                      | ~~145920000~~**145392000** |  Correct data  |
| 2021-04-16 |                                     [www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/yqjzqk/202104/d2755da833374735ab125abcc2699849.shtml)                                      | ~~187360000~~**187368000** |  Correct data  |
| 2021-04-20 |                                     [www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/yqjzqk/202104/4f3b401243cb4c57a940b6b9902f2bd9.shtml)                                      | ~~198950000~~**198965000** |  Correct data  |
| 2021-08-24 | ~~[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/yqjzqk/list_gzbd.shtml)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/jkj/s7915/202108/be52c13a94d94568bd87db40f9c4222e.shtml)** |                 1975738000 | Correct source |
| 2021-08-25 | ~~[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/yqjzqk/list_gzbd.shtml)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/jkj/s7915/202108/dd50de9b920b43268d5f61d8d90e79d9.shtml)** |                 1988433000 | Correct source |
| 2021-08-27 | ~~[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/yqjzqk/list_gzbd.shtml)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/jkj/s7915/202108/fc4d2595279f4158960e5e988c85a4c2.shtml)** |                 2019549000 | Correct source |
| 2021-08-28 | ~~[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/yqjzqk/list_gzbd.shtml)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/jkj/s7915/202108/2d51303d095e49118cdbd958594ce2b2.shtml)** |                 2032934000 | Correct source |
| 2021-08-29 | ~~[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/yqjzqk/list_gzbd.shtml)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/jkj/s7915/202108/431cbd3a4fc34fe3af25801abd674870.shtml)** |                 2044625000 | Correct source |
| 2021-08-30 | ~~[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/yqjzqk/list_gzbd.shtml)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/jkj/s7915/202108/184ada26390546bc90cdabebe25fe5de.shtml)** |                 2055966000 | Correct source |
| 2021-08-31 | ~~[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/yqjzqk/list_gzbd.shtml)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/jkj/s7915/202109/532ea949181e44988d3765a775bb170b.shtml)** |                 2067589000 | Correct source |

## Correcting Manual Entries Before 2021-03-23

|             date             |                                                                                                                                         source_url                                                                                                                                          |       total_vaccinations |      Reason      |
| :--------------------------: | :-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: | -----------------------: | :--------------: |
|          2020-12-15          |                                                                       ~~[www.globaltimes.cn](https://www.globaltimes.cn/page/202012/1211515.shtml)~~**[www.gov.cn](http://www.gov.cn/xinwen/gwylflkjz143/index.htm)**                                                                       |                  1500000 | Official source  |
|          2020-12-31          |                                                                       ~~[www.globaltimes.cn](https://www.globaltimes.cn/page/202012/1211515.shtml)~~**[www.gov.cn](http://www.gov.cn/xinwen/gwylflkjz143/index.htm)**                                                                       |                  4500000 | Official source  |
|          2021-01-09          |                                                     ~~[www.scio.gov.cn](http://www.scio.gov.cn/xwfbh/xwbfbh/wqfbh/44687/44700/zy44704/Document/1696668/1696668.htm)~~**[www.gov.cn](http://www.gov.cn/xinwen/gwylflkjz144/index.htm)**                                                      |                  9000000 | Official source  |
|          2021-01-13          |                                          ~~[www.chinadaily.com.cn](https://www.chinadaily.com.cn/a/202101/13/WS5ffeb9f2a31024ad0baa2659.html)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/s3574/202101/f7958ce31df146d2a2113233d1d08027.shtml)**                                          |                 10000000 | Official source  |
|          2021-01-20          |                                                      ~~[www.globaltimes.cn](https://www.globaltimes.cn/page/202101/1213364.shtml)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/s3574/202101/ed502e669b6a4b1ab70fb194fc87a1d8.shtml)**                                                      |                 15000000 | Official source  |
| ~~2021-01-27~~**2021-01-26** |                                                                                                                [www.gov.cn](http://www.gov.cn/xinwen/gwylflkjz147/index.htm)                                                                                                                |                 22767000 |   Correct date   |
|          2021-01-31          |                                    ~~[english.www.gov.cn](http://english.www.gov.cn/news/topnews/202101/31/content_WS6016a596c6d0f72576944df7.html)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/s3574/202101/fde67feab1054b1893fdd5a841541edb.shtml)**                                    |                 24000000 | Official source  |
|          2021-02-03          |                                               ~~[news.yahoo.com](https://news.yahoo.com/china-administered-31-2-million-071552622.html)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/s3574/202102/e2d48b7fcb4f4313985c63162ed6fce7.shtml)**                                                | ~~31200000~~**31236000** | Official source  |
|          2021-02-09          |                                          ~~[www.reuters.com](https://www.reuters.com/article/health-coronavirus-china-vaccine-idUSB9N2J803T)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/s3574/202102/760645bfaff0402bb7bc6edf8eced4b6.shtml)**                                           |                 40520000 | Official source  |
|          2021-02-28          |                                     ~~[global.chinadaily.com.cn](https://global.chinadaily.com.cn/a/202103/03/WS603ec65ba31024ad0baac40f.html)~~**[www.chinadaily.com.cn](https://www.chinadaily.com.cn/a/202103/02/WS603dbe06a31024ad0baac25b.html)**                                      |                 52520000 | Earliest source* |
|          2021-03-14          |                                                           ~~[www.chinadaily.com.cn](https://www.chinadaily.com.cn/a/202103/15/WS604efbd6a31024ad0baaf3de.html)~~**[www.gov.cn](http://www.gov.cn/xinwen/gwylflkjz151/index.htm)**                                                           |                 64980000 | Official source  |
|          2021-03-20          | ~~[www.reuters.com](https://www.reuters.com/article/us-health-coronavirus-china-vaccine/china-steps-up-covid-19-vaccination-considers-differentiated-visa-policies-idUSKBN2BD0A8?il=0)~~**[www.nhc.gov.cn](http://www.nhc.gov.cn/xcs/s3574/202103/b3b8103da9104fc58d7ce8f5189e9be2.shtml)** |                 74956000 | Official source  |
|          2021-03-22          |                ~~[www.reuters.com](https://www.reuters.com/article/us-health-coronavirus-china-vaccines/china-administered-80-46-million-covid-19-vaccine-doses-as-of-end-march-22-idUSKBN2BG04O)~~**[www.gov.cn](http://www.gov.cn/xinwen/2021-03/24/content_5595306.htm)**                | ~~80460000~~**80463000** | Official source  |

\* The total_vaccinations from the [official source](http://www.gov.cn/xinwen/2021-03/04/content_5590065.htm) is 52000000, which is less accurate.

## Correcting Manual Entries Since 2021-03-23

8 manual entries since 2021-03-23 are not covered by the current version of [`china.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/vax/incremental/china.py). Some of them are actually from both the automated source and the manual source. In that case, only the manual source will be stored in source_url.

|    date    |                                                                                   source_url                                                                                    | total_vaccinations | people_vaccinated | people_fully_vaccinated | total_boosters |
| :--------: | :-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------: | -----------------: | ----------------: | ----------------------: | -------------: |
| 2021-06-10 | ~~[[M]](http://www.nhc.gov.cn/xcs/fkdt/202106/e28487f08ad745c5952356e448a87f13.shtml)~~**[[M]](http://www.nhc.gov.cn/xcs/s3574/202106/e28487f08ad745c5952356e448a87f13.shtml)** |       845299000[M] |      622000000[M] |                         |                |
| 2021-08-26 |  [[A]](http://www.nhc.gov.cn/jkj/s7915/202108/d4b293af07a54c80b4656eb672e7df88.shtml) **[[M]](http://www.nhc.gov.cn/xcs/s3574/202108/f211dd79672642b7908ffb7575d020a1.shtml)**  |      2003914000[A] |     1072500000[M] |            889439000[M] |                |
| 2021-09-18 |           ~~[[M]](http://www.nhc.gov.cn/xcs/yqfkdt/202109/bf2cf785ce0544ae818a76ffbb18ca79.shtml)~~**[[M]](http://www.gov.cn/xinwen/2021-09/19/content_5638418.htm)**           |      2174043000[M] |     1100842000[M] |           1022207000[M] |                |
| 2021-11-19 |                                              [[M]](http://www.nhc.gov.cn/xcs/s3574/202111/019a8b08d32740258899260f15592f40.shtml)                                               |      2422908000[M] |     1225000000[M] |           1076308000[M] |    65730000[M] |
| 2021-12-03 |            [[A]](http://www.nhc.gov.cn/jkj/s7915/202112/a6e6ef6421c14cc1a3f830c0348fa765.shtml) **[[M]](http://www.jksb.com.cn/html/xinwen/2021/1204/174283.html)**             |      2532799000[A] |                   |           1125000000[M] |    96312000[M] |
| 2021-12-25 |                           ~~[[M]](http://www.news.cn/politics/2021-12/26/c_1128202069.htm)~~**[[M]](http://www.news.cn/2021-12/26/c_1128202069.htm)**                           |      2758094000[M] |                   |           1203362000[M] |                |
| 2022-01-06 |            [[A]](http://www.nhc.gov.cn/jkj/s7915/202201/f907621192b4441f89d684f66c9d3e86.shtml) **[[M]](https://www.chinanews.com.cn/gn/2022/01-06/9645782.shtml)**             |      2879993000[A] |                   |           1213000000[M] |   331000000[M] |
| 2022-03-17 |  [[A]](http://www.nhc.gov.cn/jkj/s7915/202203/4860193a87064179866f275c836b98f9.shtml) **[[M]](http://www.nhc.gov.cn/xcs/s3574/202203/82d1b154447644839760bcf25696687f.shtml)**  |      3213773000[A] |     1273470000[M] |           1239570000[M] |   644680000[M] |

A = Automated source, M = Manual source.

**Comment by lucasrodes** [comment]
Thanks, for your careful analysis. Appreciate it very much!
