### ISSUE TITLE
bug: JHU data updated too late

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2625]
### Description

Recently the JHU data has been updated very irregularly on our end, and sometimes very late in the day (e.g. 9 PM today).

We need to fix the pipeline to make sure that confirmed cases & deaths are always in sync with the JHU data, **within a maximum of 2 hours after they update**.

**Comment by lucasrodes** [comment]
This was happening due to a small bug in our automation script.

This should have been fixed by https://github.com/owid/covid-19-data/commit/eb1dee92473c76f649aeadbf3088b448af897e9e

**Comment by lucasrodes** [comment]
Seems to be working.

We had the GMT morning's update https://github.com/owid/covid-19-data/commit/6c3a715c67dc9f7cb75ee8cd73d5c3ab26d92a16.

Will monitor the next days

**Comment by lucasrodes** [comment]
Seems to be working as expected.
