### ISSUE TITLE
enhance(vax): Automate the last few countries using WHO data

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2626]
We have a few countries where data is still collected manually in our spreadsheet:

- [x] Cambodia
- [x] Gibraltar
- [x] Haiti
- [x] Maldives
- [x] North Macedonia
- [x] Saint Vincent and the Grenadines
- [x] Tunisia
- [x] Falkland Islands
- [x] Saint Helena

At this point we should be able to stop manually collecting data for all these countries:

- For countries where data is available from the WHO, we should get rid of the spreadsheet tab and collect automatically from the WHO
- For countries where no data is available from the WHO (I think: Gibraltar, Falkland Islands, and Saint Helena), we can freeze the data (either in the spreadsheet or in a CSV file in `output/vaccinations/main_data`)

**Comment by lucasrodes** [comment]
> For countries where no data is available from the WHO (I think: Gibraltar, Falkland Islands, and Saint Helena), we can freeze the data (either in the spreadsheet or in a CSV file in output/vaccinations/main_data)

Do you mean stop updating their data for now?

**Comment by edomt** [comment]
> Do you mean stop updating their data for now?

Yes, for Falkland and Saint Helena we only have a few rows dating back to Spring 2021, and for Gibraltar it should be safe to stop the updates given they've now reached close to 130%.

**Comment by edomt** [comment]
All done!
