### ISSUE TITLE
data(vax,portugal): New source + problem with ECDC script?

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2633]
Our source for Portugal's vaccination data (https://github.com/dssg-pt/covid19pt-data/blob/master/vacinas.csv) has stopped updating because the Portugal DGS has stopped publishing daily data since the end of March.

I initially tried to replace `portugal.py` with the data from `ecdc.py`, but the totals generated were much lower than expected (85% with at least one dose, when the ECDC dashboard says 94%).

So instead I've kept the original time series from dssg-pt, and added the latest data point from the WHO – but I think it would be better to have the full time series coming from the ECDC if possible, so we should investigate whether `ecdc.py` might do something wrong during the calculations.

**Comment by lucasrodes** [comment]
I've been briefly exploring the data by ECDC, and they indeed report a much lower value of people with at least one dose (87,32,428 vs 9,696,928). I just raised the issue https://github.com/dssg-pt/covid19pt-data/issues/1214, to see if we can reconcile these numbers.

Once the [health minister's website](https://covid19.min-saude.pt/vacinacao/) is operative I'll review their numbers too.

**Comment by lucasrodes** [comment]
switched to ECDC
