### ISSUE TITLE
data(vax, peru) - COVID-19 from Moderna (and possibly from Janssen) are not considered

### ISSUE THREAD

**Issue by jmcastagnetto** [owid/covid-19-data#2639]
### Country

Peru

### Domain

Vaccinations

### Which data is inaccurate or missing?

The data from the Ministry of Health of Peru (MINSA) is starting to include two more approved COVID-19 vaccines, the one from Janssen and the one from Moderna).

### Why do you think the data is inaccurate or missing?

The processing logic, in particular in https://github.com/owid/covid-19-data/blob/86861e52c9ab7463135f0c4953461e15a35d64ff/scripts/src/cowidev/vax/batch/peru.py#L19, assumes only Sinopharm, Astra/Zeneca and Pfizer vaccines. So that will need to change, and will affect summaries such as accumulation by manufacturer.

I am going to look more in depth at the data, because, as far as has been publicized, only Moderna has started to arrive on 2022-03-27. Janssen's vaccine was approved on July 2021, but AFAIK there has not been shipments arriving to Peru.

**Comment by edomt** [comment]
FYI I've added Moderna in 9d0aa8a087675e58794eb9d6b6db46818fb075d4

**Comment by lucasrodes** [comment]
Looks to me that Janssen has not been used in the general vaccination campaign.

Therefore I'd lean towards just adding Moderna as @edomt did in https://github.com/owid/covid-19-data/commit/9d0aa8a087675e58794eb9d6b6db46818fb075d4 and wait for the source data by @jmcastagnetto to report Janssen doses in the general campaign to add this vaccine.

**Comment by jmcastagnetto** [comment]
When I detect Janssen being used in the general campaign, I'll reopen this issue. For now I agree with @lucasrodes that having Moderna should suffice right now.

This issue can be closed for now.
