### ISSUE TITLE
data: missmatch in vaccination data smoothed/raw for regions

### ISSUE THREAD

**Issue by lpicci96** [owid/covid-19-data#2644]
### Country

Africa (OWID_AFR)

### Domain

Vaccinations

### Which data is inaccurate or missing?

`new_vaccinations_smoothed` seems inaccurate for Africa from September 2021 to present. Smoothed values seem to be undervalued and variance does not correlate with `new_vaccinations`. 

### Why do you think the data is inaccurate or missing?

Smoothing calculation

**Comment by lucasrodes** [comment]
Thanks for your report, @lpicci96.

For the record, there seems to be some miss-calculation when smoothing the variable the number of vaccines administered in Africa.

This is visible in the following charts

[7 day average, daily administered vaccine doses in Africa](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&facet=none&pickerSort=desc&pickerMetric=new_cases_per_million&Metric=Vaccine+doses&Interval=7-day+rolling+average&Relative+to+Population=false&Color+by+test+positivity=false&country=~Africa)
![coronavirus-data-explorer(64)](https://user-images.githubusercontent.com/18101289/168121545-c5896ba0-ee2a-4390-bb7f-6bc11f0a6fbb.png)


[daily administered vaccine doses in Africa](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=desc&pickerMetric=new_cases_per_million&Metric=Vaccine+doses&Interval=New+per+day&Relative+to+Population=false&Color+by+test+positivity=false&country=~Africa)
![coronavirus-data-explorer(63)](https://user-images.githubusercontent.com/18101289/168121557-de8987fc-7d95-4783-89b1-c16958bede80.png)

**Comment by lucasrodes** [comment]
The first point of exploration is in the [generate.py](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/cmd/vax/generate/utils.py) step.

Especially in these lines:

https://github.com/owid/covid-19-data/blob/d0ccd1e1de71d81ffb59ba28bac05e55e846f5a3/scripts/src/cowidev/cmd/vax/generate/utils.py#L340-L342

Possible solution: call `pipe_aggregates` before `pipe_smoothed`.

**Comment by lucasrodes** [comment]
Seems it started happening here: https://github.com/owid/covid-19-data/commit/75c5d9d40c30016b08dfa96562f1b6a9dfcc7113, @edomt 

I am running tests with the following code:

```python
import pandas as pd


def check(commit):
  url = f'https://raw.githubusercontent.com/owid/covid-19-data/{commit}/public/data/vaccinations/vaccinations.csv'
  # read
  x = pd.read_csv(url)
  # filter
  x=x[x.location=='Africa']
  x = x[['location','date','daily_vaccinations_raw','daily_vaccinations']]
  # check
  x['debug'] = x.daily_vaccinations_raw.rolling(7).mean()
  assert (x.daily_vaccinations-x.debug > .5).sum() == 0
```

If `daily_vaccinations_raw` and `daily_vaccinations` seem uncorrelated, this code raises an `AssertionError`.

Using `commit = 'b1e6a460b7cd32ca5b573a72dc210f4e451081e1'` (b1e6a460b7cd32ca5b573a72dc210f4e451081e1) seems OK.

But for `commit = 'e7effec6086c1233eb9e7c82d1a3b8c0e82dc294'` (e7effec6086c1233eb9e7c82d1a3b8c0e82dc294) it no longer works.

**Comment by edomt** [comment]
Hi @lucasrodes @lpicci96 

This is quite a complex problem actually, and we should take the time to carefully review how to do it best (and it's possible that we'll keep the current implementation). My change in 75c5d9d40c30016b08dfa96562f1b6a9dfcc7113 was the result of the previous implementation showing a very spiky time series.

> Better solution for https://github.com/owid/covid-19-data/commit/3527c25879b297bbbd7e876d8c44c4aa086d94fc. Previously we calculated each continent's daily vaccinations using the same method as for countries (7-day average of daily changes). But this created spikes in the time series when countries in that aggregate reported irregularly. Now we calculate each continent's daily time series as the sum of the *daily* time series of its countries.

We'll likely work on this next week.

**Comment by jm-rivera** [comment]
Thank you @edomt and @lucasrodes for looking into this. If it helps, as additional context, the shape of the 7-day rolling average changes quite significantly every few days. Here are some images (dates as names) to give you an idea.
![8 may](https://user-images.githubusercontent.com/7374450/168238890-0e93d3c4-d76d-4d6a-8b68-c4e5dd93fabb.png)
![9 may](https://user-images.githubusercontent.com/7374450/168238895-b179f47d-b362-4f2e-a1f9-67b950d6747c.png)
![11 may](https://user-images.githubusercontent.com/7374450/168238897-eaba7218-5d0e-47d7-ab86-320914846f4e.png)

Going back a bit further (with a chart we generate daily straight from the Africa 7-day rolling average) for **May 3**
![image](https://user-images.githubusercontent.com/7374450/168239398-6849c8aa-05a5-4a64-bd8b-a37b5d51194c.png)

And for **April 29**
![image](https://user-images.githubusercontent.com/7374450/168239716-92f5c006-3a96-406a-9c84-241bf9fb2fa6.png)


We're really grateful for all the work you do to maintain this dataset. Let @lpicci96 or I know if we can help work on a solution.

**Comment by lucasrodes** [comment]
The discrepancy seems to appear due to how we do the regional aggregates here:

https://github.com/owid/covid-19-data/blob/d0ccd1e1de71d81ffb59ba28bac05e55e846f5a3/scripts/src/cowidev/cmd/vax/generate/utils.py#L157-L169

In particular, we forward fill cumulative and daily metrics, which might not consistent. If we assumed no growth in cumulative metrics, daily metrics should be zero-filled and not forward-filled. The discrepancy is most notorious for the latest days available, as highlighted in this thread.

We are looking into possible solutions. The most direct one is to assume missing data for the latest days, knowing that it will be an underestimate of the raw and smoothed daily values.

**Comment by lucasrodes** [comment]
I am running some experiments, but I think we can have a solution by next week.

My proposed solution reconciles both raw and smoothed daily metrics, at the cost of both having underestimated for latest dates. 

https://github.com/owid/covid-19-data/blob/e661d967d11c2234314a20b90b72e0c4a5397d6f/scripts/src/cowidev/cmd/vax/generate/utils.py#L198-L243

**Comment by lucasrodes** [comment]
This has now been solved. There was a minor bug in how aggregates were estimated when no daily metrics were available.

Now, daily metrics are reported up to 7 days ago to reduce uncertainty.
