### ISSUE TITLE
data: switch to ECDC for Poland testing data

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2647]
### Country

Poland

### Domain

Testing

### Which data is inaccurate or missing?

Daily change in cumulative total

### Why do you think the data is inaccurate or missing?

Hi, may I confirm there is no data for Daily Change in Cumulative Total in Poland Country, but I refer to this source ECDC (https://www.ecdc.europa.eu/en/publications-data/covid-19-testing), it obtain testing data for Poland, may I have your comfirm?

**Comment by camappel** [comment]
Correct, previously we obtained data from the Polish Ministry of Health's [Twitter](https://twitter.com/MZ_GOV_PL), but we switched to the ECDC on 25 March 2020.

The ECDC publish the cumulative number of tests performed once a week, from which we derive a 7-day average of the daily change in the cumulative total.

This information is available on our website [here](https://ourworldindata.org/coronavirus-testing#poland), along with information on all of our sources for testing data.
