### ISSUE TITLE
data: Vaccination data in Vietnam has not been updated since 2022-03-22

### ISSUE THREAD

**Issue by VozVuiVe** [owid/covid-19-data#2649]
### Country

Vietnam

### Domain

Vaccinations

### Which data is inaccurate or missing?

Vaccination data since 2022-03-22 is missing.

### Why do you think the data is inaccurate or missing?

No data is logged after 2022-03-22 in https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Vietnam.csv.

**Comment by lucasrodes** [comment]
Thanks for reporting, I just manually added a data point for the 15th of May.

**Comment by Leonaides96** [comment]
Hi @lucasrodes ,

Is it possible to capture back the historical data from 22-03-2022 till 15-05-2022 for this country?

**Comment by lucasrodes** [comment]
hi @Leonaides96,
I've added data for the last couple of months!
