### ISSUE TITLE
data(vax,ury): Abnormal rows in locations-age.csv

### ISSUE THREAD

**Issue by aywi** [owid/covid-19-data#2651]
### Country

Uruguay

### Domain

Vaccinations

### Which data is inaccurate or missing?

https://github.com/owid/covid-19-data/blob/8045699b185c971b3dd41d5a703fc1feee752252/scripts/output/vaccinations/metadata/locations-age.csv#L1-L5

Looks like these two rows were generated by [`uruguay.py`](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/vax/batch/uruguay.py) but I found no problem with the current version.

### Why do you think the data is inaccurate or missing?

These two rows can be deleted if there are no problems elsewhere.

**Comment by lucasrodes** [comment]
Thanks for reporting
