### ISSUE TITLE
data: World total vaccinations and full vaccinations have not been updated after 07 May 2022

### ISSUE THREAD

**Issue by tllkrmn** [owid/covid-19-data#2652]
### Country

World

### Domain

Vaccinations

### Which data is inaccurate or missing?

The world total vaccinations and full vaccinations have not been updated after 07 May 2022.

### Why do you think the data is inaccurate or missing?

Considering the world total is the sum of all countries, there should be the world total if the individual countries data are being updated.

**Comment by edomt** [comment]
@lucasrodes Would it be doable to only filter the region & world aggregates for _daily_ metrics, but calculate the cumulative metrics up to the last day?

**Comment by lucasrodes** [comment]
@edomt, totally doable! That was my idea. Will ping once corrected.

**Comment by lucasrodes** [comment]
Daily metrics are now reported up to 7 days ago, as these metrics take longer to stabilize.

Cumulative metrics are live until yesterday, f-filling the last available values.
