### ISSUE TITLE
data: Large spike in tests for Singapore

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2653]
### Country

Singapore

### Domain

Testing

### Which data is inaccurate or missing?

[Daily new COVID-19 tests](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Tests&Interval=7-day+rolling+average&Relative+to+Population=false&Color+by+test+positivity=false&country=~SGP)

### Why do you think the data is inaccurate or missing?

The time series report 60 million daily tests - something must be wrong in our input data.

**Comment by camappel** [comment]
The index number of cumulative and daily tests were swapped
