### ISSUE TITLE
data: Ambiguity in transliteration from Cyrillic for КовиВак (Chumakov Center vaccine)

### ISSUE THREAD

**Issue by rando2** [owid/covid-19-data#2656]
### Country

Belarus

### Domain

Vaccinations

### Which data is inaccurate or missing?

The `vaccines` listed for Belarus in `locations.csv` are: 
> CoviVac, Sinopharm/Beijing, Sputnik Light, Sputnik V 

I think the term "CoviVac" is confusing because there is [another vaccine candidate](https://covid19.trackvaccines.org/vaccines/107/) with that name.

### Why do you think the data is inaccurate or missing?

I was trying to unify this data with VIPER and was confused because the vaccine they list as [COVIVAC](https://covid19.trackvaccines.org/vaccines/107/) has not been approved anywhere, yet in OWID it looked like it had been approved in Belarus. It turns out, the one VIPER lists as [Kovivac](https://covid19.trackvaccines.org/vaccines/100/) has been approved in Belarus.

Digging into the [WHO vaccination-metadata.csv data](https://covid19.who.int/data), the data they reported is:
> BLR | Chumakov - Covi-Vac | Covi-Vac | Chumakov 

The Cyrillic spelling seems to be КовиВак. In order to make it easier to process downstream, I wanted to suggest possibly re-identifying this vaccine as `CoviVac (Chumakov)`.

Thank you! 

For reference, here is the use-case of fuzzy matching integration of the OWID and VIPER datasets: https://github.com/greenelab/covid19-review/pull/1149

**Comment by lucasrodes** [comment]
Hi @rando2,
Thanks for reporting.

We will be renaming this vaccine to `KoviVac (Chumakov)`. When the vaccine by Institute of Vaccines and Medical Biologicals is approved we will probably add it with the name `CoviVac`.
