### ISSUE TITLE
data: Vac: Myanmar 

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2661]
### Country

Myanmar

### Domain

Vaccinations

### Which data is inaccurate or missing?

total_booster

### Why do you think the data is inaccurate or missing?

Hi, I found out the Myanmar source website (Ministry of Health) published the booster since 19th March 2022, may I know the historical data for Myanmar total booster will update it soon? 

Link : https://mohs.gov.mm/page/18015

**Comment by lucasrodes** [comment]
Thanks for reporting. I have added historical booster data.
