### ISSUE TITLE
Heads up: Problems with the COVID-19 vaccination data from Peru

### ISSUE THREAD

**Issue by jmcastagnetto** [owid/covid-19-data#2672]
The official entry for the COVID-19 vaccination data in Peru is: https://www.datosabiertos.gob.pe/dataset/vacunaci%C3%B3n-contra-covid-19-ministerio-de-salud-minsa, which contains a link to download the dataset from a new URL: https://drive.minsa.gob.pe/s/qioYn4FDbsJ62Mw/download

Unfortunately, the new URL seems to be not setup correctly, so it is blocking downloading attempts (see screenshot below), therefore I am not sure when I will be able to update my repository. 

The previous dataset download URL was:  https://cloud.minsa.gob.pe/s/oHF5JSLEk8KzpPW/download, but that data has information only until 2022-06-01.

![Error generated when trying to download the most recent data on COVID-19 vaccionations in Peru](https://user-images.githubusercontent.com/364668/172062507-e924d48c-87ec-4890-9899-bbec1cd62bc7.png)

**Comment by jmcastagnetto** [comment]
*Update*: Apparently **someone at MINSA has geolocked the dataset**, thus defeating the purpose of it being open data. 

Currently I am abroad, so I am trying a VPN to get the data. Unfortunately it only seems to work in my Android phone, and it is a bit problematic to be downloading 780+MB via a cellphone.

This will mean that I might be updating my repo (https://github.com/jmcastagnetto/covid-19-peru-vacunas) less often until this issue is resolved at the source.

**Comment by jmcastagnetto** [comment]
Was able to update the data up to 2022-06-11, and had to change the workflow because of two issues:

- The official dataset has now a URL that is blocking attempts to download it from IP addresses that are not in Peru (had to use a VPN to work around this)
- The data structure has (again) changed, with some columns missing (in particular those related to UBIGEO, the geographical location code), and others been now replaced.

@lucasrodes

**Comment by lucasrodes** [comment]
Hi @jmcastagnetto!
Thank you very much for sorting this out.

I am sorry to hear that the data is no longer accessible from countries other than Peru. I just reached out to them to ask whether they plan on changing this.
