### ISSUE TITLE
China's June 5 daily new confirmed death count is wrong

### ISSUE THREAD

**Issue by sevenwong** [owid/covid-19-data#2675]
### Country

china

### Domain

Deaths

### Which data is inaccurate or missing?

the value of confirmed death for this country on 2022-06-05 does not seem right

### Why do you think the data is inaccurate or missing?

Data from the following sources show that China has zero new confirmed deaths in 2022-06-05:
https://weekly.chinacdc.cn/news/TrackingtheEpidemic.htm
http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml

**Comment by lucasrodes** [comment]
Dear @sevenwong,

We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues


---

Closing this issue as it is duplicated (https://github.com/CSSEGISandData/COVID-19/issues/5789)
