### ISSUE TITLE
data: Costa rica: Data deletion 

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2677]
### Country

Costa Rica

### Domain

Testing

### Which data is inaccurate or missing?

All Testing indicators

### Why do you think the data is inaccurate or missing?

Hi,

May I confirm data deletion in Costa Rica country, the Testing dataset from 26th March 2022 until May?

May I know more detail about the deletion? 

Thanks and regards,
Leonaides

**Comment by camappel** [comment]
Hi @Leonaides96 ,

Thank you for pointing this out. The testing data was dropped last update due to a change in the source's structure; it will be included in todays update (data available up to [May 30 2022](https://geovision.uned.ac.cr/oges/))

**Comment by Leonaides96** [comment]
Ok thanks
