### ISSUE TITLE
data: discrepancy in China data wrt OW i.e CNHC

### ISSUE THREAD

**Issue by mkhanka** [owid/covid-19-data#2678]
### Country

China

### Domain

Cases

### Which data is inaccurate or missing?

As on 07th June 2022, Data in OWID is: 

28/05/2022 : 326
29/05/2022 : 218
30/05/2022 : 195

Data on the OW i.e [CNHC](http://en.nhc.gov.cn/2022-05/29/c_85981.htm)(official source):

28/05/2022 : 82
29/05/2022 : 34
30/05/2022 : 50
 

### Why do you think the data is inaccurate or missing?

When we closely checked the data we found that CNHC bifurcates the data on the basis of Symptomatic & Asymptomatic. 
Query: The data you pulled from CNHC, you included asymptomatic data in it or not?

**Comment by lucasrodes** [comment]
Hi @mkhanka,
Thanks for reporting!

We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues
