### ISSUE TITLE
data: Bug in vaccination data for Philippines 2022-06-06

### ISSUE THREAD

**Issue by imoskvin** [owid/covid-19-data#2679]
### Country

Philippines

### Domain

Vaccinations

### Which data is inaccurate or missing?

https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Philippines.csv#L236
people_fully_vaccinated at 2022-06-06 is wrong. 
You've put total_vaccinations data into people_fully_vaccinated column at this point

### Why do you think the data is inaccurate or missing?

people_fully_vaccinated is greater than country population =)

**Comment by lucasrodes** [comment]
Thanks for reporting. 

The source changed its layout which lead to some inconsistencies in the data. We have now switched to the WHO as our main source for vaccination data for the Philippines
