### ISSUE TITLE
data: OWID feed for test stopped adding data after 31 May. 

### ISSUE THREAD

**Issue by gauravjoshijo** [owid/covid-19-data#2680]
### Country

USA

### Domain

Testing

### Which data is inaccurate or missing?

Data is not being updated after 31 May.

### Why do you think the data is inaccurate or missing?

As per the announcement, OWID will stop updating the data after 23rd June. I think OWID has already stopped before the given date.

**Comment by lucasrodes** [comment]
Hi @gauravjoshijo,
Thanks for your message.

We are still going as planned, and the testing data will be updated every week until the 23rd of June, as explained in [our announcement](https://github.com/owid/covid-19-data/discussions/2667).

I see that we collected data points for the US until the 3rd of June, but for some reason, these values are not being shown in our dataset and charts.

@camappel, could you perhaps re-run the R scripts and the `megafile` so we can get these values into the final dataset? Thanks!

**Comment by camappel** [comment]
The testing data for the USA is now updated with the latest available data (June 3 2022) and included in the [grapher](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Tests&Interval=Cumulative&Relative+to+Population=true&Color+by+test+positivity=false&country=~USA) and the public Github [dataset](https://github.com/owid/covid-19-data/blob/master/public/data/testing/covid-testing-all-observations.csv)
