### ISSUE TITLE
data: Vac : Qatar

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2681]
### Country

Qatar

### Domain

Vaccinations

### Which data is inaccurate or missing?

people_vaccinated and people_fully_vaccinated

### Why do you think the data is inaccurate or missing?

Hi team, 

I found out there are not data update on those metrics, and I have check the source website, may I confirm value are take from WHO website or Qatar local source website?

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
Thanks for reporting this!

We currently use https://covid19.moph.gov.qa/EN/Pages/Vaccination-Program-Data.aspx to collect data for Qatar. Unfortunately, they do not provide absolute numbers on first and second doses.

I just switched to the WHO so we can collect numbers on these metrics. However, the data update frequency will be lower, as the WHO only reports on a weekly basis.
