### ISSUE TITLE
data: Vac Mfg: US

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2684]
### Country

United Stated

### Domain

Vaccinations

### Which data is inaccurate or missing?

Total Vaccination by Johnson & Johnson Manufacture 

### Why do you think the data is inaccurate or missing?

Hi Team, 

I have found out that there are some missing values for Total Vaccination by Johnson & Johnson Manufacture in the US. On 2022-06-11 commit, the total vaccination for Johnson & Johnson vaccine on 8/6/2022 - 6/62022 timepoint have been deleted. 

May I confirm is removed by the local source? And any reason for this deletion? 

Thanks and regards,
Leonaides

**Comment by Leonaides96** [comment]
Hi Team

Based on today's update, there are many time points on Vaccination Manufacture been deleted from 2022-01-21 till 2022-05-27 in Lithuania country, Can I confirm this too? 

Thank you very much 

Best regards,
Leonaides

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
Thanks for reporting, really helpful!

For the future, please open separate issues when reporting different problems (i.e. different countries, different dates)

---
Responding to your first comment:

We force all the cumulative variables in our data to be monotonically increasing. Reported values for administered J&J doses on the 6th, 7th and 8th of June were higher than the value reported on the 9th, so we remove these for consistency. We do this for all countries and cumulative metrics.

In particular we had:

- 6th June: 18,791,078
- 7th June: 18,793,750
- 8th June: 18,792,505
- 9th June: 18,791,038

---
As per your second comment, there seemed to be some problem with the source. I just fixed it, will be live soon!

**Comment by Leonaides96** [comment]
Hi @lucasrodes, 

Ok, and thanks for the helpful information

Thanks and regards,
Leonaides
