### ISSUE TITLE
data:  Testing: North Korea

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2685]
### Country

North Korea

### Domain

Testing

### Which data is inaccurate or missing?

Testing dataset

### Why do you think the data is inaccurate or missing?

Hi Team,

Based on yesterday's commit, may I confirm Local source has changed the unit measurement of the Testing dataset for North Korea country from People tested to Sample tested?

Thanks and regards,
Leonaides

**Comment by camappel** [comment]
Hi Leonaides,

Yes, we changed because more data is available for samples tested. Note that 2 samples are used for every person tested.
