### ISSUE TITLE
data ( Vac, Mfg ) : Austria

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2687]
### Country

Austria

### Domain

Vaccinations

### Which data is inaccurate or missing?

total_vaccinations: Austria: Johnson&Johnson
total_vaccinations: Austria: Moderna
total_vaccinations: Austria: Oxford/AstraZeneca
total_vaccinations: Austria: Pfizer/BioNTech

### Why do you think the data is inaccurate or missing?

Hi team, 

May I question that, on 17th Jun 2022 commit, the data are available on 14th Jun 2022 for the above manufacture indicator in Austria, but on the next day commit, the data are been deleted on 14th Jun 2022 and the data added on 17th Jun 2022 which the data exactly same as the 14th Jun 2022, is there any issues on the automation or from the source website?

Thanks and regards
Leonaides

**Comment by lucasrodes** [comment]
Thanks for reporting. This occurred because of a subtle thing in our automation process. I just corrected this.

Thanks once again!
