### ISSUE TITLE
data: Netherland vaccinations data are doubled

### ISSUE THREAD

**Issue by imoskvin** [owid/covid-19-data#2694]
### Country

Netherland

### Domain

Vaccinations

### Which data is inaccurate or missing?

Todays commit corrupts vaccinations data for Netherland. 
https://github.com/owid/covid-19-data/commit/83c50d46851e1470319789ba9a8cde789083469a#diff-0509bc13a573103cc554cce40b3a564e777eddde54ddde5c75463d019e242733

### Why do you think the data is inaccurate or missing?

Fully vaccinated people is more that country population

**Comment by lucasrodes** [comment]
Hi @imoskvin,
I am not sure I understand the issue.

People fully vaccinated is 4,114,696, which according to UN WPP 2019 population estimates _is less_ than New Zealand's population (5,126,300).

**Comment by fibke** [comment]
People vaccinated is currently 24 million, whereas the population is 17 million. OWID mentions the difference is due to vaccination of non-residents, but the discrepancy seems way too large for this to be possible. 

So indeed likely an error.

@edomt

**Comment by lucasrodes** [comment]
@fibke It is indeed an error, please read my comment above.

I'll disable updates until the source has fixed the figures. Thanks for reporting!

**Comment by lucasrodes** [comment]
As the source data still contains irregularities, we have switched to ECDC data for now for the Netherlands.
