### ISSUE TITLE
data: Vac: Mozambique 

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2699]
### Country

Mozambique

### Domain

Vaccinations

### Which data is inaccurate or missing?

The Total Boosters values for the Mozambique on 10/07/2022 been removed

### Why do you think the data is inaccurate or missing?

Hi Teams,

May I have your help in checking the Total Boosters Values for Mozambique? I found out the value has been removed after the latest commit update.

And what are the issues regarding the deletion above?

Thanks and regards,
Leonaides

**Comment by lucasrodes** [comment]
The datapoint has been added again: https://github.com/owid/covid-19-data/commit/ffb36a3bf8b47a4bd56b4e5b2d8823281ed5d441#diff-34f6e3070c206c6b96073c936c3ad51d6f563118ae8404e51674b27021980cb3


It will be live in the next 24h, thanks for reporting @Leonaides96
