### ISSUE TITLE
ECDC not entirelery reliable

### ISSUE THREAD

**Issue by mick-d** [owid/covid-19-data#27]
Excellent website, however one limitation is that ECDC data is not all reliable. For example number of deaths on April 23 in Switzerland is off by 25% (ECDC reports 1216 deaths when it is actually 25% more with 1526 deaths: https://interactif.tdg.ch/2020/covid-19-carte-suisse/ )

**Comment by edomt** [comment]
Hi @mick-d,

There is unfortunately not much we can do to fix this. We source our data directly from the European Centre for Disease Prevention and Control, and report it without making alterations to its original cases and death figures—and the ECDC itself reports them exactly as they are given by national sources.

Edouard
