### ISSUE TITLE
data: data deletion on Country New Zealand

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2711]
### Country

New Zealand

### Domain

Vaccinations

### Which data is inaccurate or missing?

The vaccination value from 03-08-2022 till 08-08-2022 have been removed on New Zealand country

### Why do you think the data is inaccurate or missing?

Hi Team,

I have noticed that the vaccination value on 03-08-2022 till 08-08-2022 have been removed for New Zealand country. 

Can have any reason on this timepoint deletion?

Thanks and regards,
Leonaides

**Comment by lucasrodes** [comment]
Has been fixed -- thanks for reporting
