### ISSUE TITLE
data: owid-covid-data.csv

### ISSUE THREAD

**Issue by fxdci2005** [owid/covid-19-data#2713]
### Country

ALL

### Domain

Cases

### Which data is inaccurate or missing?

Dataset hasn't been updated in two days.  Still showing up to 8/14/22

### Why do you think the data is inaccurate or missing?

The max date value in the date column is 8/14/22

**Comment by dkasprzak99** [comment]
Agreed - just reported the same thing!

**Comment by lucasrodes** [comment]
Thanks for reporting!

We will be tracking this issue in #2712.
