### ISSUE TITLE
data: Covid-19 data hasn't updated in 3 days?

### ISSUE THREAD

**Issue by davidjayjackson** [owid/covid-19-data#2714]
### Country

World

### Domain

Other

### Which data is inaccurate or missing?

What is the link in GitHub to get the latest worldwide covid-19 data? The data listed with the link below hasn't been updated in 3 days.

https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv

David Jackson

### Why do you think the data is inaccurate or missing?

Because according to the date stamp it hasn't been updated in 3 days?

**Comment by lucasrodes** [comment]
Thanks for reporting!

We will be tracking this issue in #2712.
