### ISSUE TITLE
Changes planned for vaccination data from Peru

### ISSUE THREAD

**Issue by jmcastagnetto** [owid/covid-19-data#2716]
Now that there is more data on the second booster shots in Peru, I am going to be adding a column named `people_receiving_second_booster_per_hundred` to the usual data file.

This change will appear with the update I will be running next Sunday (August 28).

You can see the planned changes in:

https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/use-duckdb/datos/vacunas_covid_rangoedad_owid.csv

And the schema in: 

https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/use-duckdb/schemas/vacunas_covid_rangoedad_owid-schema.yaml

Do let me know if this is OK, or if you rather I use a different column name, etc.

@lucasrodes

**Comment by lucasrodes** [comment]
This looks perfect! Thanks for your work once again, @jmcastagnetto!

**Comment by jmcastagnetto** [comment]
The changes have been merge on the main branch of my repo, and the data has been updated.

Let me know if you find any issue. 

For now I will close this ticket.

**Comment by jmcastagnetto** [comment]
@lucasrodes 

I am reopening this issue, to let you know that now that in Peru there are applying a bivalent COVID-19 vaccines since January, the data for OWID in my repo will have an extra column: `people_receiving_third_booster_per_hundred`.

In a the next 30 min or so, I will be uploading the data with this extra field.

**Comment by lucasrodes** [comment]
Thanks for letting us know, @jmcastagnetto! I just added this to our sanity checks of the column names.
