### ISSUE TITLE
Covid cases and deaths are not updating in every country except the Us

### ISSUE THREAD

**Issue by 807lachlb** [owid/covid-19-data#2717]
I have noticed that Covid-19 cases and deaths are not updating in every country except the US and please fix it.

**Comment by lucasrodes** [comment]
As of now, case data is updated for all countries.

Where were you checking this? From GitHub files, our charts at our website?

Thanks

**Comment by 807lachlb** [comment]
I was checking on the internet.

**Comment by lucasrodes** [comment]
Could you provide a link to the data you are referring to, please?

**Comment by 807lachlb** [comment]
https://news.google.com/covid19/map?hl=en-AU&mid=%2Fm%2F02j71&gl=AU&ceid=AU%3Aen

**Comment by 807lachlb** [comment]
This is the link to the data I’m referring to.
