### ISSUE TITLE
data: Missing data in OWID_WRL location in vaccinations.csv

### ISSUE THREAD

**Issue by CapMar00** [owid/covid-19-data#2720]
### Country

OWID_WRL

### Domain

Vaccinations

### Which data is inaccurate or missing?

Starting from 2022-08-19 the 'daily_vaccinations' values are missing for the OWID_WRL location

### Why do you think the data is inaccurate or missing?

Because before the 2022-08-19 this value has always been present

**Comment by lucasrodes** [comment]
Data for aggregates, such as continents, income groups or 'World' are estimated with a 7-day delay, so we leave some buffer time for all countries to report vaccination figures.

I have added this note to the vaccination docs.

**Comment by DidierCOQUARD** [comment]
Toute matérialité subit la législation de l'esprit qui l'impose.
La mathématique est le langage du volume qui la contient.
Nous sommes matière et volume dans le volume. Par conséquent, nous sommes assujettis à la législation de l'esprit qui l'impose
La législation dimensionnelle.
