### ISSUE TITLE
data: owid-covid-data.csv

### ISSUE THREAD

**Issue by dkasprzak99** [owid/covid-19-data#2724]
### Country

All

### Domain

Cases

### Which data is inaccurate or missing?

The data from the past two days is blank in Column M and many other columns.

### Why do you think the data is inaccurate or missing?

 The data stopped updating on 9/12

**Comment by lucasrodes** [comment]
Thanks for reporting @dkasprzak99. JHU added data for two new countries (Nauru and Tuvalu), which we did not notice and prevented our scripts from running successfully. 

We have fixed this now and should be live shortly.

**Comment by dkasprzak99** [comment]
Thank you,

Derek Kasprzak
GLOBAL Safety, Health and Environment
SH&E mANAGER management Systems

ECOLAB 1601 W. DIEHL RD, NAPERVILLE, IL 60563-1198
M 630 605 7932   T 630 305 1523    F 630 305 2986
