### ISSUE TITLE
data: 

### ISSUE THREAD

**Issue by fibke** [owid/covid-19-data#2725]
### Country

World

### Domain

Vaccinations

### Which data is inaccurate or missing?

Global vaccinations show a decline between 9/17 and 9/18.

<img width="663" alt="image" src="https://user-images.githubusercontent.com/69641575/190974084-2efb51c8-4a7c-4107-98ed-094f4981d1b1.png">

### Why do you think the data is inaccurate or missing?

An error somewhere? Or did a major country revise the data?

**Comment by lucasrodes** [comment]
Hi @fibke,
From your screenshot, I can see that the value for `total_vaccinations` has increased between the mentioned dates: From 12,676,247,728 to 12,678,074,076. So it seems fine.

Perhaps you were referring to another variable?
