### ISSUE TITLE
data: Vaccination: Slovakia

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2730]
### Country

Slovakia

### Domain

Vaccinations

### Which data is inaccurate or missing?

total_vaccination, booster and etc have been deleted from 18-July-2022 till 31-July-2022

### Why do you think the data is inaccurate or missing?

Hi Team, 

I found the vaccination and booster values have been remove on the latest commit ([c4aecbe](https://github.com/owid/covid-19-data/commit/c4aecbe6c662a6108f7336f56ef900cb0e717af8)). 

The timepoint from 18-Jul-2022 till 31-Jul-2022 have been removed in Slovakia, can I know what are the issue on this deletion?

Thanks 
Best regards,
Leonaides

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
Thanks for reporting.

We have fixed this in https://github.com/owid/covid-19-data/commit/4cb9266059d5450a6060982148927a2952ccaedc and https://github.com/owid/covid-19-data/commit/cc2d97ff0727a64615ff83b185b8abff7a4f30a0.

It should be live on our site in the next 24 hours.
