### ISSUE TITLE
data: Vaccination: United Kingdom 

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2733]
### Country

United Kingdom
### Domain

Vaccinations

### Which data is inaccurate or missing?

the data for the 2021-01-10 - 2021-09-29 periods was removed

### Why do you think the data is inaccurate or missing?

Hi OWID,

I figure out that the country source website (https://coronavirus.data.gov.uk/details/vaccinations) has the data for the respective period.

May I question what is the reason for the timepoint deletion in the United Kingdom country?

Thanks
Best regards,
Leonaides

**Comment by lucasrodes** [comment]
Once again, thanks for raising this, @Leonaides96! Appreciate it.

This has been solved in https://github.com/owid/covid-19-data/commit/f978b6ab68a9d3def5527ccbfdce1083285f379c and https://github.com/owid/covid-19-data/commit/12450330e7ab6856bb656974f751be5dce3558c7. It should be live shortly.
