### ISSUE TITLE
Missing Vac data: United Kingdom country

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2734]
### Country

United Kingdom

### Domain

Vaccinations

### Which data is inaccurate or missing?

from 2021-01-10 till  2021-09-29 

### Why do you think the data is inaccurate or missing?

Hi Team,

May I question, I found out that from 2021-01-10 till  2021-09-29  the vaccination data  has been removed in United Kingdom country. But I check on the local source website (https://coronavirus.data.gov.uk/details/vaccinations) there are available for the respective period. 

May I question this issues? 

Thanks 
Best regards,
Leonaides

**Comment by lucasrodes** [comment]
duplicate of #2733
