### ISSUE TITLE
bug: vaccination graphs

### ISSUE THREAD

**Issue by MarcoVax** [owid/covid-19-data#2737]
### Description

Since 10 days, OWID covid vaccination graphs seem be no longer available in the covid google dashboard, for each country. Why?

**Comment by lucasrodes** [comment]
Hi @MarcoVax,
Thanks for your message.

Could you perhaps specify for which country you are checking this? It might be that data for that country is not being reported by official authorities.

For instance, data for France is currently available [here](https://news.google.com/covid19/map?hl=en-US&mid=%2Fm%2F0f8l9c&gl=US&ceid=US%3Aen).

**Comment by MarcoVax** [comment]
For example, as shown in the following pictures, vaccination graphs were shown (for each Countries) until 10 days ago. Now only cases and deaths data are shown (for each Countries).
![20221026_201322](https://user-images.githubusercontent.com/116708805/198105139-906b2022-bfdb-4f59-9956-ce17292eca92.jpg)
![20221026_201244](https://user-images.githubusercontent.com/116708805/198105144-a36ffa18-a3ac-477d-8dcb-1a12ff57d388.jpg)
