### ISSUE TITLE
data: 

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#2738]
### Country

Spain

### Domain

Hospital & ICU

### Which data is inaccurate or missing?

Spain data in [owid-covid-data.csv](https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv), do not report any data between 1/8/2020 and 1/31/2020, which may not look good.

### Why do you think the data is inaccurate or missing?

![image](https://user-images.githubusercontent.com/68354122/198347706-4fe29a12-a3c6-4466-9dc1-07c9e86ee090.png)
![image](https://user-images.githubusercontent.com/68354122/198347861-1ae84d90-e812-4ac4-985b-df54776bef13.png)

**Comment by lucasrodes** [comment]
Hi @RuijingZ,
The metrics related to cases and deaths come from https://github.com/CSSEGISandData/COVID-19. The first reporting values appear to be from January 22 2020 approx (https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv).

Therefore, there are no available values for these dates.
