### ISSUE TITLE
data: Issue with hospital & ICU data in Spain

### ISSUE THREAD

**Issue by Rayson9** [owid/covid-19-data#2739]
### Country

Spain

### Domain

Hospital & ICU

### Which data is inaccurate or missing?

 - "Daily hospital occupancy" & "Daily ICU occupancy" in the URL below
 - (https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv)

I have a Python script which plots 1) ICU occupancy % of Spain population and 2) "Daily hospital occupancy % of Spain population" and as you can see the attached plot (See SPAIN_INCORRECT.png), there seems to be some issue with the data. It used to not be so "cyclical" (See SPAIN_CORRECT.png)
![SPAIN_INCORRECT](https://user-images.githubusercontent.com/77030110/199420974-122b6fd0-f8a8-4c13-83d6-ae743f70accb.png)
![SPAIN_CORRECT](https://user-images.githubusercontent.com/77030110/199420975-2db2b0b2-2ae1-4ce8-847d-a5cef797ac16.png)

### Why do you think the data is inaccurate or missing?

Can I check if a different set of "Daily hospital occupancy" and "Daily ICU occupancy" for Spain is uploaded?

**Comment by lucasrodes** [comment]
Thanks for your report, @Rayson9.

I will be looking into this in the next 24 hours.

**Comment by lucasrodes** [comment]
@Rayson9,
Based on your analysis, I have been reviewing the hospitalisation data for Spain, and it seems to be correct.

Feel free to comment if you think that there is still an issue.
