### ISSUE TITLE
data: Improve vaccination data for Sweden

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#2744]
It seems the main weekly file now provides complete time series for boosters:

![image](https://user-images.githubusercontent.com/7103774/200535058-ef6486e4-c3ce-4496-880e-3e10d537649c.png)

We should try to clean up `sweden.py` to get rid of the daily data (it's no longer useful now) and build clean time series for all metrics.

**Comment by lucasrodes** [comment]
This has now been fixed. Thanks for reporting!
