### ISSUE TITLE
data: 

### ISSUE THREAD

**Issue by Smile-L** [owid/covid-19-data#2746]
### Country

Australia

### Domain

Vaccinations

### Which data is inaccurate or missing?

The "daily_vaccinations" data of Australia at Sep. 28, 2022. 

### Why do you think the data is inaccurate or missing?

Hi OWID.
The "daily_vaccinations" data of Australia may be incorrect as of Sep. 22, 2022.
Australia had around 3000 daily doses before, and the number dramatically increased to 713440 at Sep. 28, 2022. Could anyone please take a look at it? 

Thanks
Best regards,
simin

**Comment by lucasrodes** [comment]
Duplicated thread. See: https://github.com/owid/covid-19-data/discussions/2741

**Comment by Smile-L** [comment]
> Duplicated thread. See: #2741

Thanks for your reply!
I see that Australia’s official website is still updating data every week. The latest data has been updated to November 16 (WHO was only updated to September 28), and the historical data uses Australian official website data. Switching to WHO data on September 28 led to The daily new count is weird. Will you consider switching the data source to the Australian official website in the future?

**Comment by lucasrodes** [comment]
Hi @Smile-L,
Thanks for your heads up. We will look into our vaccination for Australia in short. We were reporting their values, but since late September, they started reporting lower values, which is incompatible with the cumulative nature of the time-series metrics.
