### ISSUE TITLE
Myanmar social connectivity

### ISSUE THREAD

**Issue by BreakerZoeBurma** [owid/covid-19-data#2748]
### Country

Myanmar

### Domain

Hospital & ICU

### Source

name: Bug Report description: File a bug report title: "[Bug]: " labels: ["bug", "triage"] assignees:   - octocat body:   - type: markdown     attributes:       value: |         Thanks for taking the time to fill out this bug report!   - type: input     id: contact     attributes:       label: Contact Details       description: How can we get in touch with you if we need more info?       placeholder: ex. email@example.com     validations:       required: false   - type: textarea     id: what-happened     attributes:       label: What happened?       description: Also tell us, what did you expect to happen?       placeholder: Tell us what you see!       value: "A bug happened!"     validations:       required: true   - type: dropdown     id: version     attributes:       label: Version       description: What version of our software are you running?       options:         - 1.0.2 (Default)         - 1.0.3 (Edge)     validations:       required: true   - type: dropdown     id: browsers     attributes:       label: What browsers are you seeing the problem on?       multiple: true       options:         - Firefox         - Chrome         - Safari         - Microsoft Edge   - type: textarea     id: logs     attributes:       label: Relevant log output       description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.       render: shell   - type: checkboxes     id: terms     attributes:       label: Code of Conduct       description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)       options:         - label: I agree to follow this project's Code of Conduct           required: true

### Comments

body:
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      ...
    render: bash
  validations:
    required: true- type: textarea
  attributes:
    label: Operating System
    description: What operating system are you using?
    placeholder: Example: macOS Big Sur
    value: operating system
  validations:
    required: true
- type: dropdown
  attributes:
    label: Version
    description: What version of our software are you running?
    multiple: false
    options:
      - label: 1.0.2 (Default)
      - label: 1.0.3 (Edge)
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Code of Conduct
    description: The Code of Conduct helps create a safe space for everyone. We require
      that everyone agrees to it.
    options:
      - label: I agree to follow this project's [Code of Conduct](link/to/coc)
        required: true
- type: markdown
  attributes:
    value: "Thanks for completing our form!"body:
- type: markdown
  attributes:
    value: "## Thank you for contributing to our project!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report.body:
- type: input
  id: prevalence
  attributes:
    label: Bug prevalence
    description: "How often do you or others encounter this bug?"
    placeholder: "Example: Whenever I visit the personal account page (1-2 times a week)"
  validations:
    required: truebody:
- type: checkboxes
  id: operating-systems
  attributes:
    label: Which operating systems have you used?
    description: You may select more than one.
    options:
      - label: macOS
      - label: Windows
      - label: Linux

**Comment by lucasrodes** [comment]
Can't understand the issue @BreakerZoeBurma ー  Feel free to edit and re-open to clarify it.
