### ISSUE TITLE
bug: Excess mortality data file on GitHub is not being updated automatically

### ISSUE THREAD

**Issue by CGiattino** [owid/covid-19-data#2755]
### Description

The excess_mortality.csv file [here](https://github.com/owid/covid-19-data/tree/master/public/data/excess_mortality) is no longer being updated automatically.

The current workflow is that I (Charlie) upload the data to the grapher, and then Lucas's script converts it and uploads to that GitHub page.

I last uploaded to the grapher 10 days ago, but the GitHub file is 27 days old.

![image](https://user-images.githubusercontent.com/7489781/203362500-af181909-ae75-4467-bf10-da6792f5680c.png)

**Comment by lucasrodes** [comment]
The excess mortality file seems to be up to date now. 

The excess Mortality file is updated in this repo every day by 9 PM UTC. Note that this file will _only_ be updated if the file in `owid-datasets` repository has changed ([this file](https://github.com/owid/owid-datasets/blob/master/datasets/Excess%20Mortality%20Data%20%E2%80%93%20OWID%20(2022)/Excess%20Mortality%20Data%20%E2%80%93%20OWID%20(2022).csv)) from the previous day.

At the moment, both files were last updated two days ago. Before that, and looking at the [history](https://github.com/owid/owid-datasets/commits/master/datasets/Excess%20Mortality%20Data%20%E2%80%93%20OWID%20(2022)/Excess%20Mortality%20Data%20%E2%80%93%20OWID%20(2022).csv) of the file from `owid-datasets`, it had last been updated on the 26th of October. Therefore, no updates were done on the file in this repo.

Hope this helps.
