### ISSUE TITLE
Vac: SG: Singapore Total Vaccination Values are not recorded

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2759]
Hi Team. 

I have some doubt on the below line:

https://github.com/owid/covid-19-data/blob/f197c123370b563c379ac43577dfc39e04b04aed/scripts/src/cowidev/vax/batch/singapore.py#L100

Is there any reason the Total vaccination is not calculated and recorded as NA instead? 

Hope can have your quick reply on this issue.

Thanks and regards,
Leonaides

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
Thanks for your message and checking!

Singapore has stopped reporting data on the number of booster doses administered. Previously, they shared a file named "progress-of-vaccine-booster-programme.csv" at https://storage.data.gov.sg/covid-19-vaccination/covid-19-vaccination.zip, which had this data.

Now, without this data, we cannot estimate the number of total doses.

I reached out to them to see if they plan to report data on boosters back again, but I still haven't heard from them.
