### ISSUE TITLE
Vac data: 

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2760]
### Country

Mexico, Netherlands, Ecuador

### Domain

Vaccinations

### Which data is inaccurate or missing?

Total vaccination has been stopped updated from Aug - Oct 2022

### Why do you think the data is inaccurate or missing?

Hi Team,

I have found out there is some country where the total vaccination has been stopped updating, most of the country latest timepoint for total vaccination are updated from Aug 2022 till Oct 2022. May I have your help on this issue, is it because the local source has started to stop updating the total vaccination record already? 

Thank you so much for the help.

Best regards,
Leonaides

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
Thanks for reporting!

Answering your question per country:

- Mexico: We source this data from the WHO. The last data point in their dataset for Mexico dates from 7th October. For the time being, we will switch to PAHO data.
- Netherlands: We have been collecting data from [ECDC](https://www.ecdc.europa.eu/en/publications-data/data-covid-19-vaccination-eu-eea), which hasn't provided updated figures since September 2022. Hopefully, they will start reporting data again soon.
- Ecuador: Our current source (third party) has not updated the data since August 2022. I reported an issue to this project in https://github.com/andrab/ecuacovid/issues/516. For the time being, we will switch to PAHO data.

**Comment by Leonaides96** [comment]
Hi @lucasrodes, 

Thanks for your prompt replied, but I have some doubt question on above countries

Mexico - I have review the PAHO source have release the data till week 45, 2022, which are on November 07 till November 13, but from your countries file there, the data are yet up to date. 

May I have you help on this matter?

Thanks 
Best regards,
Leonaides

**Comment by lucasrodes** [comment]
@Leonaides96, thanks for reporting! I corrected a minor fix on our end. Data should be live in short. Thanks again for your time!

**Comment by Leonaides96** [comment]
> @Leonaides96, thanks for reporting! I corrected a minor fix on our end. Data should be live in short. Thanks again for your time!

@lucasrodes ,
Thanks so much for the prompt response, anyways data gap will be reflected in the latest changes as well? Because there are data gap due to the previous source website are not updated

**Comment by lucasrodes** [comment]
@Leonaides96, do you mean if we will fill the gap of data? Unfortunately, the data is no longer available live, as the sources report these numbers incrementally. Sorry for the inconvenience.

**Comment by Leonaides96** [comment]
Hi @lucasrodes, 

Again thanks and understand, but on the latest commit ([17f2f94](https://github.com/owid/covid-19-data/commit/17f2f949a29e0767610c990b211c9bad31519dc8)) I have checked available data for the total_vaccination from the PAHO source website for Mexico country, and it seems the code doesn't capture it either. 

Thanks for the help on this issue.

Thanks and regards,
Leonaides

**Comment by lucasrodes** [comment]
You are not looking at the latest commit for Mexico, please see https://github.com/owid/covid-19-data/commit/136ec981ea7eea34e4bf5950464b421485e1cec3

**Comment by Leonaides96** [comment]
> You are not looking at the latest commit for Mexico, please see [136ec98](https://github.com/owid/covid-19-data/commit/136ec981ea7eea34e4bf5950464b421485e1cec3)

Hi @lucasrodes , referring to the latest commit [136ec98](https://github.com/owid/covid-19-data/commit/136ec981ea7eea34e4bf5950464b421485e1cec3), the number for 1st dose and booster dose are recorded, but the total vaccination dose and number for 2nd dose are not been capture, which there has data from the PAHO source

![image](https://user-images.githubusercontent.com/86961920/205180543-53a24f0c-57c6-4539-8194-14238fdcd1b7.png)

**Comment by Leonaides96** [comment]
Hi @lucasrodes ,

Hope you are well. I hope can have your reply regarding the question above 

Thanks and regards
Leonaides

**Comment by Leonaides96** [comment]
Hi @lucasrodes ,

Hope you are well. I hope can have your reply regarding the question above. Regarding the the Mexico total_vaccination data, and fully_vaccinated data are not recorded from PAHO source website 

Thanks and regards
Leonaides

**Comment by edomt** [comment]
Hi @Leonaides96 

Just a quick note on the speed of responses: the OWID staff does not work on weekends, and we're often busy with lots of parallel projects, so please allow several days between comments so we can give you an answer.
