### ISSUE TITLE
data: Vaccination dose by manufacturer in India

### ISSUE THREAD

**Issue by CKingX** [owid/covid-19-data#2764]
### Country

India

### Domain

Vaccinations

### Source

https://dashboard.cowin.gov.in/

### Comments

This is the official dashboard by Ministry of Health and Family Welfare in India and breaks down administered vaccine doses by vaccine type. 
![image](https://user-images.githubusercontent.com/13824156/208570917-563cf138-d222-4b8d-b711-ab02b440fad3.png)
You can even cross out certain vaccine types to hover over vaccines that were barely distributed 
![image](https://user-images.githubusercontent.com/13824156/208570995-ad9490d9-e27b-41bd-9c75-bb3c2b167cb1.png)

**Comment by lucasrodes** [comment]
Hi @CKingX,
Thanks for your report.

Unfortunately, our pipeline only accepts reports that contain complete time series (and not just _live_ values). You can read more details in our [documentation](https://docs.owid.io/projects/covid/en/latest/contribute-vax.html#contribute-to-manufacturer-or-age-group-dataset).
