### ISSUE TITLE
data: Vaccine doses administered by manufacturer for Bangladesh

### ISSUE THREAD

**Issue by CKingX** [owid/covid-19-data#2765]
### Country

Bangladesh

### Domain

Vaccinations

### Source

http://dashboard.dghs.gov.bd/webportal/pages/covid19-vaccination-update.php

### Comments

It contains data on doses administered by manufacturer

**Comment by lucasrodes** [comment]
Hi @CKingX,
Thanks for your report.

Unfortunately, our pipeline only accepts reports that contain complete time series (and not just _live_ values). You can read more details in our [documentation](https://docs.owid.io/projects/covid/en/latest/contribute-vax.html#contribute-to-manufacturer-or-age-group-dataset).
