### ISSUE TITLE
data: vaccine doses by manufacturer in Thailand

### ISSUE THREAD

**Issue by CKingX** [owid/covid-19-data#2766]
### Country

Thailand

### Domain

Vaccinations

### Source

https://dashboard-vaccine.moph.go.th/

**Comment by lucasrodes** [comment]
Hi @CKingX,
Thanks for your report.

Unfortunately, our pipeline only accepts reports that contain complete time series (and not just _live_ values). Also, we can't currently add manual reports.

You can read more details in our [documentation](https://docs.owid.io/projects/covid/en/latest/contribute-vax.html#contribute-to-manufacturer-or-age-group-dataset).
