### ISSUE TITLE
Vac data: Pakistan 

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2768]
### Country

Pakistan

### Domain

Vaccinations

### Which data is inaccurate or missing?

There are no latest updates for Vaccination data for Country Pakistan 

### Why do you think the data is inaccurate or missing?

Hi OWID team,

May I have your time to check the Vaccination data for Pakistan Country, it seem that the latest update is till 03 December 2022, is there any reason for this lack of timepoint? 

Thanks and Regards,
Leonaides

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
Thanks for your report.

We currently use the WHO for Pakistan, which reports data every week approximately. The last datapoint is from the 18th of December, which we added ~11 hours ago.

We used to source data for Pakistan from https://covid.gov.pk/vaccine-details, but the data there seems not to update anymore.

**Comment by Leonaides96** [comment]
Hi @lucasrodes ,

understand, and thanks for the information regarding to the above mentioned issues

Thanks and regards,
Leonaides
