### ISSUE TITLE
data: China vaccinations data

### ISSUE THREAD

**Issue by Smile-L** [owid/covid-19-data#2775]
### Country

China

### Domain

Vaccinations

### Which data is inaccurate or missing?

the China vaccination data,
"people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred" columns in csv: https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv

### Why do you think the data is inaccurate or missing?

Hello. Could you please update China vaccinations data since China had published new data about vaccinations.

> 92.1 percent of the population from the 31 provincial-level regions and the Xinjiang Production and Construction Corps have received the first dose of COVID-19 vaccines, 89.7 percent are fully vaccinated, and 71.7 percent have received the booster,
from https://english.www.gov.cn/news/topnews/202207/24/content_WS62dc8e27c6d02e533532e666.html

**Comment by Smile-L** [comment]
http://www.chinadaily.com.cn/a/202212/18/WS639f1344a31057c47eba4f0a.html

**Comment by Smile-L** [comment]
http://www.chinadaily.com.cn/a/202212/18/WS639f1344a31057c47eba4f0a.html
“In China, over 90 percent of the population have been fully vaccinated”

**Comment by Smile-L** [comment]
https://www.reuters.com/world/china/china-opens-14000-fever-clinics-big-hospitals-33000-community-hospitals-nhc-2022-12-14/

**Comment by Smile-L** [comment]
https://www.reuters.com/world/china/china-opens-14000-fever-clinics-big-hospitals-33000-community-hospitals-nhc-2022-12-14/
“As of Dec. 13, 92.73% of people have received COVID-19 vaccine shots, and 90.37% of people have received a full course of vaccination in China”

**Comment by lucasrodes** [comment]
Hi @Smile-L,
Thanks for your report.

For the sake of accuracy, we only accept reports with absolute counts. Therefore, I am afraid these data points are inadequate for our dataset.

> https://www.reuters.com/world/china/china-opens-14000-fever-clinics-big-hospitals-33000-community-hospitals-nhc-2022-12-14/
“As of Dec. 13, 92.73% of people have received COVID-19 vaccine shots, and 90.37% of people have received a full course of vaccination in China”

Note that our last data point dates from the 13th of December: 1.31 billion people vaccinated (91.68%) and 1.27 billion people fully vaccinated (89.35%). These figures come from NHC agency: http://www.nhc.gov.cn/xcs/s3574/202212/b927d43bd0354ffeb5a8e1b91377302f.shtml.

**Comment by Smile-L** [comment]
> Hi @Smile-L, Thanks for your report.
> 
> For the sake of accuracy, we only accept reports with absolute counts. Therefore, I am afraid these data points are inadequate for our dataset.
> 
> > https://www.reuters.com/world/china/china-opens-14000-fever-clinics-big-hospitals-33000-community-hospitals-nhc-2022-12-14/
> > “As of Dec. 13, 92.73% of people have received COVID-19 vaccine shots, and 90.37% of people have received a full course of vaccination in China”
> 
> Note that our last data point dates from the 13th of December: [1.31 billion people vaccinated](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=desc&pickerMetric=new_cases_per_million&Metric=People+vaccinated&Interval=Cumulative&Relative+to+Population=true&Color+by+test+positivity=false&country=~CHN) (91.68%) and [1.27 billion people fully vaccinated ](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=desc&pickerMetric=new_cases_per_million&Metric=People+fully+vaccinated&Interval=Cumulative&Relative+to+Population=true&Color+by+test+positivity=false&country=~CHN)(89.35%). These figures come from [NHC agency](http://www.nhc.gov.cn/xcs/s3574/202212/b927d43bd0354ffeb5a8e1b91377302f.shtml.).


ChinaCDC had published absolute counts of booster/vaccinated/fully vaccinated people at this website:
https://www.chinacdc.cn/jkzt/crb/zl/szkb_11803/jszl_13141/202301/t20230115_263381.html
Could you please check if this data is suitable?

**Comment by lucasrodes** [comment]
Hi @Smile-L,
Thanks for your report! That source is precious! It seems that all related entries will be posted here: https://www.chinacdc.cn/jkzt/crb/zl/szkb_11803/jszl_13141/. I have added this to our automation script; let's see the behaviour in the upcoming days!
