### ISSUE TITLE
Vac data: Venezuela 

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2781]
### Country

Venezuela

### Domain

Vaccinations

### Which data is inaccurate or missing?

Fully vaccinated people timepoint on 2023-02-03 

### Why do you think the data is inaccurate or missing?

Hi OWID team,

Recently I notice the Fully Vaccinated People for Venezuela country are abnormal, there are timepoint on 2023-02-03, but after the next commit update the timepoint is been remove. 

May I have your help on this issue, since the issue have have occurred since a few weeks ago.

Thanks 
Best regards,
Leonaides

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
Thanks for your message.

The data point for Venezuela was removed because it reported the exact same values reported weeks before.

However, this should not be visible on our end files. Therefore, I have added a step in our code to filter these data points directly.
