### ISSUE TITLE
owid-covid-data.csv has not been updated for 2 days

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#2793]
Hi there,

I noticed that confirmed cases and death data will be replaced by WHO data on March 10th. However, I assume that this will not affect the other concepts, like ICU and vaccination data. May I ask if you will resume updating this dataset?

**Comment by lucasrodes** [comment]
Thanks for raising this up.

We are reviewing this and should be solved shortly.

**Comment by lucasrodes** [comment]
This has now been solved!

Regarding the switch to WHO, please refer to the discussion at https://github.com/owid/covid-19-data/issues/2784
