### ISSUE TITLE
Vac data: Anguilla

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2796]
### Country

Anguilla

### Domain

Vaccinations

### Which data is inaccurate or missing?

There are not timepoint for fully vaccinated and vaccinated values on 2023-03-10 

### Why do you think the data is inaccurate or missing?

Hi OWID,

Upon checking from the https://ais.paho.org/imm/IM_DosisAdmin-Vacunacion.asp for Anguilla country, we found out that there are timepoint record for 2023 week 11 ( which is to date to 2023-03-12 ). But it seen the automation are not recorded the timepoint as well. 

May I have you help on this issues? 

Thanks 
Best regards,
Leonaides

**Comment by Leonaides96** [comment]
Hi OWID,

Wish all are well, and for your reminder on the above issues. 

I wish to receive you reply soon

Thanks 
Best regards,
Leonaides

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
Thanks for your message.

We have updated the data for Anguilla.
