### ISSUE TITLE
data: Question on US vax per 100 calculation

### ISSUE THREAD

**Issue by beansrowning** [owid/covid-19-data#2801]
### Country

United States

### Domain

Vaccinations

### Which data is inaccurate or missing?

doses per 100, completed initial series per 100, boosted per 100

### Why do you think the data is inaccurate or missing?

The most recent stated vaccination counts appear [accurate](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/United%20States.csv#L844):

total_vaccinations | people_vaccinated | people_fully_vaccinated
| --- | ---- | ---- |
674375206 | 270045602 | 230418632

These appear fine on the dashboard. The computed population metrics seem off though.

I'm using the UNWPP 2022 medium variant estimate for US pop (338,289,856), mentioned here: https://github.com/owid/covid-19-data/blob/master/scripts/input/un/population_latest.csv#L237

By that metric, the per-100 population values would be:

total_vaccinations_per_100 | people_vaccinated_per_100 | people_fully_vaccinated_per_100
| --- | ---- | ---- |
199.348 | 79.827 | 68.113

These are substantially lower than those reported in vaccines.csv/json and the dashboard:

total_vaccinations_per_100 | people_vaccinated_per_100 | people_fully_vaccinated_per_100
-- | -- | --
203.12 | 81.34 | 69.4

Are these values calculated, or captured separately?
If the latter, it seems like something might be wrong with the calculation.
If the former, do you know the source? I tried searching a bit to no avail.

**Comment by lucasrodes** [comment]
Thanks for raising this, @beansrowning.

The UNWPP definition of US is different from the one used by the CDC (in terms of which small territories are included/excluded). So to match up perfectly, we started using the CDC estimate for the US population instead (332,008,832).

In the past, the CDC used to make this number (332,008,832) very prominent in one of their files. Now they don't, but you can calculate it backwards with a file like [this one](https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-Jurisdi/unsk-b7fc), by using `Administered` and `Admin_Per_100K` for example. We get a value of 332,008,968, slightly different to what we have so I will update our processes to reflect this change.

**Comment by beansrowning** [comment]
Thanks--still not 100% sure how that's being done, but I can inquire internally if there's a national estimate floating around. 

Should that denom also be documented in population_latest.csv rather than just embedded as a magic number in code?

**Comment by lucasrodes** [comment]
Hi @beansrowning,
Agree that having that number embedded in code is not ideal at all. The thing is, there is a value in `population_latest.csv` already, which is used in other parts of the pipeline.
