### ISSUE TITLE
data: Vac: Switzerland and Liechtenstein

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2802]
### Country

Switzerland and Liechtenstein

### Domain

Vaccinations

### Which data is inaccurate or missing?

The value for people_fully_vaccinated and people_fully_vaccinated_per_hundred from available timepoint to Blank

### Why do you think the data is inaccurate or missing?

Hi OWID team,

I have found some abnormal vaccination data for countries Switzerland and Liechtenstein. 

The people_fully_vaccinated has been revised from available value to blank in the CSV file. Could you have a look at this issue? 

If the timepoints are legit, could you share the reason for this matter?

Hope to receive your reply soon.

Thanks 
Best regards
Leonaidas

**Comment by Leonaides96** [comment]
Hi team, 

I hope you have noticed the above issues, I wish I can receive your reply on this issue soon. 

Apologies for the disturbance.

Thanks 
Best regards,
Leonaides

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
Sorry for my belated response.

The swiss government stopped reporting this metric couple of weeks ago. They no longer display it on their maps [on their dashboard](https://www.covid19.admin.ch/en/vaccination/persons).

Consequently, as full time series for both Switzerland and Liechtenstein is updated everytime there is an update on the source, all the values were removed.

For context, the link we use to update some of the vaccinations metrics is this one: https://www.covid19.admin.ch/api/data/20230530-2fbekw2t/sources/COVID19VaccPersons_v2.json.

If you need historical values, I suggest accessing the old files for both countries:

- [Switzerland](https://github.com/owid/covid-19-data/blob/cb0e6ce629eb097dd46063ab021466e293bd2df4/public/data/vaccinations/country_data/Switzerland.csv)
- [Liechtenstein](https://github.com/owid/covid-19-data/blob/cb0e6ce629eb097dd46063ab021466e293bd2df4/public/data/vaccinations/country_data/Liechtenstein.csv)
