### ISSUE TITLE
data: Covid recovered cases

### ISSUE THREAD

**Issue by WorldometersActiveCases** [owid/covid-19-data#2803]
### Country

Poland

### Domain

Other

### Source

https://www.worldometers.info/coronavirus/country/poland/

### Comments

Poland has 6,396,899 recoveries since the start of the pandemic
https://coronalevel.com/Poland/

**Comment by lucasrodes** [comment]
Hi @WorldometersActiveCases,
We are currently not reporting data on recovered cases.

You can see all the metrics we report at https://ourworldindata.org/explorers/coronavirus-data-explorer
