### ISSUE TITLE
data: Vac: Honduras

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2810]
### Country

Honduras

### Domain

Vaccinations

### Which data is inaccurate or missing?

the values of vaccination on 2023-06-02 has been removed on the [69ebf9d](https://github.com/owid/covid-19-data/commit/69ebf9dd11c516d0056fa1469f4f87e607a214cb) commit. 

### Why do you think the data is inaccurate or missing?

Hi OWID,

I notice there are some Vaccination timepoint for Honduras Country have been removed on this [69ebf9d](https://github.com/owid/covid-19-data/commit/69ebf9dd11c516d0056fa1469f4f87e607a214cb) 

May I confirm the removed data are legit? or any reason on the removed timepoint? 

Thanks 
Best regards,
Leonaides

**Comment by Leonaides96** [comment]
Hi OWID Team,

Apologies for the disturbing, may I have a update on the above matter?

Thanks 
Best regards,
Leonaides

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
Thanks for your message, and apologies for the belated response.

This should be now fixed.

**Comment by Leonaides96** [comment]
Hi @lucasrodes, 

Thanks for the update and response, but I notice there are many timepoint gap, are the gap going the fill backed?

Thanks 
Best regards
Leonaides

**Comment by lucasrodes** [comment]
Data gaps are due to inconsistencies in the origin data, where the values were not monotonically increasing. Therefore, we had to remove some datapoints to ensure the time series was monotonically increasing.
