### ISSUE TITLE
data: Data Update ceases

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#2811]
### Country

All

### Domain

Vaccinations

### Which data is inaccurate or missing?

Datasets under covid-19-data/public /data has not been updated for 2 days. Will the update frequency change?

### Why do you think the data is inaccurate or missing?

These datasets usually update daily, but now the last commit date are all 2 days ago

**Comment by lucasrodes** [comment]
Thanks for reporting, @RuijingZ.
The data should be updated regularly; we are looking into this issue.

**Comment by lucasrodes** [comment]
I've now manually triggered an update. I'll monitor these days if automated updates work as expected.
