### ISSUE TITLE
bug: wrong numbers from CoVariants

### ISSUE THREAD

**Issue by yuval-harpaz** [owid/covid-19-data#2813]
### Description

For Israel, XBB.1.5 is at 20.37%, yet in the source (CoVariants, 23A) it is at 70%. In contrast, others get 76.85% for OWID vs 0% for CoVariants
links:
[CoVariants](https://covariants.org/per-country?country=Israel) 
[OWID](https://ourworldindata.org/grapher/covid-variants-area?country=~ISR)

**Comment by lucasrodes** [comment]
This should be solved by now.
