### ISSUE TITLE
Add the field "date" to latest data

### ISSUE THREAD

**Issue by bennokress** [owid/covid-19-data#282]
In the folder `latest`, we always get the latest data points. Would it be possible to add a field `covid_data_date` indicating when that data was last updated per country? The date should already be available since we have it in the arrays in the COVID data files.

**Comment by edomt** [comment]
Hey @bennokress 

We get daily updates from Johns Hopkins for cases & deaths data (with a date of D–1 for the update published on date D). The only data that can go up to date D on date D is testing or vaccination data.
So basically you'll always get a date of either D-1 (for countries without up-to-date testing or vaccination data) or D.

Can you confirm that you need the date given this?

**Comment by bennokress** [comment]
My usage is in a [Scriptable widget](https://github.com/bennokress/Scriptable-Scripts#covid-19-vaccinations) showing vaccination progress on iOS, where the data gets cached in order to save data on mobile plans. Having the date in the retrieved data and therefore in the cache would enable me to easily display it in the widget without having to extend the cached data with the current date - 1 day manually.

Since there are data points from different time zones around the world it could in my opinion also be useful for comparisons of vaccination data.

But if it is no trivial change to include the date or my use case is too small for a change in the process, I completely understand and I'll find a solution.

**Comment by edomt** [comment]
It's entirely trivial! I've adjusted the code now, it'll appear in the next hour when I run the update.
