### ISSUE TITLE
data: Who does not report data from Paraguay 

### ISSUE THREAD

**Issue by DailyCovidCases** [owid/covid-19-data#2825]
### Country

Paraguay

### Domain

Cases

### Which data is inaccurate or missing?

Why do those datasets prodive different numbers so much?
https://dgvs.mspbs.gov.py/reporte-covid-19/ (824940 cases, 20094 deaths)
https://data.who.int/dashboards/covid19/cases?m49=600&n=c (736235 cases, 19952 deaths)

### Why do you think the data is inaccurate or missing?

Counting reinfections

**Comment by lucasrodes** [comment]
Hi @DailyCovidCases,
Thanks for your interest in our project. We currently use the data from the WHO to ensure that the definitions of indicators are aligned across all countries.

I would suggest emailing the websites that you cite to clarify these differences.
