### ISSUE TITLE
Vaccinations: World 'total_vaccinations' don't match with the sum of all countries

### ISSUE THREAD

**Issue by sapienzafra** [owid/covid-19-data#283]
File: vaccinations.csv

On day '2021-01-10' World 'total_vaccinations' value is 23.749.851, but when I sum all countries max available number of 'total_vaccinations' I get 25.067.596.

**Comment by nrazon** [comment]
You need to exclude Wales, Scotland, North Ireland and England from totals because they are part of united kingdom.

**Comment by sapienzafra** [comment]
Thank you sir!

**Comment by metrocoding** [comment]
for today i see 475 milion total vaccination in your site but when i get sum  i faced very huge number 1,517 milion, excluding Wales, Scotland, North Ireland and England cant help much i think is there anything more?
i exclude United Kingdom and count Wales, Scotland, North Ireland and England now number is 1,486

**Comment by metrocoding** [comment]
> You need to exclude Wales, Scotland, North Ireland and England from totals because they are part of united kingdom.

for today i see 475 milion total vaccination in your site but when i get sum i faced very huge number 1,517 milion, excluding Wales, Scotland, North Ireland and England cant help much i think is there anything more?
i exclude United Kingdom and count Wales, Scotland, North Ireland and England now number is 1,486

**Comment by edomt** [comment]
@metrocoding Did you also remove aggregates, such as World, Europe, North America, etc.?

**Comment by nrazon** [comment]
Just get sum of countries with 3 letter iso_code. 
don't get sum of countries which has more than 3 characters in their iso_code field (like OWID_ENG)

**Comment by metrocoding** [comment]
sorry guys i forgot to remove world and continent data. thanks a lot
