### ISSUE TITLE
data: new zealand data looks odd

### ISSUE THREAD

**Issue by USMortality** [owid/covid-19-data#2833]
### Country

new zealand

### Domain

Deaths

### Which data is inaccurate or missing?

<img width="950" alt="Screenshot 2024-03-06 at 9 53 52 AM" src="https://github.com/owid/covid-19-data/assets/94856880/47b91bea-2523-4a6c-867f-325953b094a3">

### Why do you think the data is inaccurate or missing?

Many jumps in the data, that haven' been there a few days ago. Something must have changed, that introduced this regression.

**Comment by lucasrodes** [comment]
Thanks for reporting, @USMortality.

The WHO changed the date format, and that caused some errors in our date-parsing. We are looking into shipping a fix asap.
