### ISSUE TITLE
data: Singapore hospitalizations run for a limited period only

### ISSUE THREAD

**Issue by josesho** [owid/covid-19-data#2835]
### Country

Singapore

### Domain

Hospital & ICU

### Which data is inaccurate or missing?

The weekly hospitalization data for Singapore only runs from 13 Dec 2022 to 05 Feb 2023, which is an unusually small window.

### Why do you think the data is inaccurate or missing?

As of the time of writing, the publicly available numbers from [data.gov.sg](https://beta.data.gov.sg/datasets/d_98e8d8ba612a748413c439550c3c6942/view) runs instead from Feb 2023 to Feb 2024.

**Comment by lucasrodes** [comment]
Thanks for reporting, @josesho!

I've updated the pipeline for Singapore. Data is now updated here: https://github.com/owid/covid-19-data/blob/master/scripts/output/hospitalizations/main_data/Singapore.csv. This should be live on our site in the next 24 hours.
