### ISSUE TITLE
Inaccurate no. of cases in MENA region

### ISSUE THREAD

**Issue by Rohit-Satyam** [owid/covid-19-data#2840]
### Country

MENA Countries

### Domain

Cases

### Which data is inaccurate or missing?

I see that the biweekly cases were up to 80K (such as Qatar in Nov 2023) in some of the mean countries from Jan1 2024 to 13th August 2024. This is opposed to the plots I have for uptil May 2023 from your webserver:

![image](https://github.com/user-attachments/assets/4eedacfc-e28c-48ff-8211-1cc98144bd55)

Right now it's 80K. This error occurred second time. Could you please correct it.

![coronavirus-data-explorer (16)](https://github.com/user-attachments/assets/41ea3b44-e52d-40d3-9e6b-3e8ccd35a2d8)

**Comment by lucasrodes** [comment]
Hi @Rohit-Satyam, thanks for your interest in our data and for reporting this.

This is indeed a bug in our pipeline, that was introduced in the last days, while we are migrating our COVID-19 data pipeline. This should be fixed shortly.

In the meantime, I'd suggest looking at this chart instead: https://ourworldindata.org/grapher/biweekly-confirmed-covid-19-cases?tab=chart&time=earliest..latest&country=OMN~EGY~KWT~MAR~GNQ~QAT

**Comment by lucasrodes** [comment]
Hi @Rohit-Satyam!
This should now be fixed!

Sorry for the inconvenience that this may have caused, and thanks for reporting!
