### ISSUE TITLE
VACCINATIONS: what does 'new vaccinations' mean?

### ISSUE THREAD

**Issue by sapomnia** [owid/covid-19-data#289]
I've noticed you added two columns in the 'latest' file (new vaccinations and new vaccinations per million). What do they stand for?
Thanks in advance

**Comment by edomt** [comment]
Hi @sapomnia 
You can find their full description in the codebook: https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-codebook.csv

**Comment by sapomnia** [comment]
Thanks. Apologies, I didn't see that
Riccardo Saporitimobile 3495207868email sapomnia@yahoo.itskype riccardo.saporiti 

    Il lunedì 11 gennaio 2021, 18:06:35 CET, Edouard Mathieu <notifications@github.com> ha scritto:  
 
 


Hi @sapomnia
You can find their full description in the codebook: https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-codebook.csv
