### ISSUE TITLE
Incorrect UK daily testing numbers

### ISSUE THREAD

**Issue by tomwhite** [owid/covid-19-data#29]
The UK daily testing numbers cannot simply be derived from the cumulative totals (by finding the difference from the previous day's total), since the total incorporates revisions that may not just apply to the previous day.

For example, on 25 April the [notes](https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public#number-of-cases-and-deaths) say:

> The difference between the cumulative numbers from today and yesterday for people tested is 50,499 higher than the daily increase figure. Cumulative testing figures include 50,499 retrospective reports of people who tested negative between 31 January and 24 April.

The page from which the testing numbers are collected (https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public#number-of-cases-and-deaths), includes daily totals, so they can be directly added to the data in this repository.

I have been maintaining a repository of the raw HTML for the source page, collected every day (see coronavirus-covid-19-number-of-cases-in-uk-*.html in https://github.com/tomwhite/covid-19-uk-data/tree/master/data/raw), which can be used to get the corrected numbers for daily people tested.

I pulled out the correct figures for the dates that need fixing here:

```
Date                  DailyPeopleTested
2020-04-08            12959
2020-04-10            13543
2020-04-13            10745
2020-04-20            14106
2020-04-25            23115
```

**Comment by edomt** [comment]
Hi @tomwhite 

Many thanks for alerting us to the issue. We've now reconstructed the time series of daily changes based on your archives (a fix was just pushed to the repo), and from now we'll be collecting both the cumulative total and the daily change from the official table.

Best,
Edouard

**Comment by tomwhite** [comment]
Thanks @edomt!
