### ISSUE TITLE
IRL new data as of 2020-01-11

### ISSUE THREAD

**Issue by akashdeep-singh** [owid/covid-19-data#290]
Some new information about Ireland's vaccinations is available today. 
According to [Richard Chambers's tweet](https://twitter.com/newschambers/status/1348701763776503808), 

> "Exceeded the target of 35,000" is Karina Butler and Stephen Donnelly’s assessment of vaccination to date.

Source: https://twitter.com/newschambers/status/1348701763776503808

**Comment by edomt** [comment]
Thank you!
