### ISSUE TITLE
VACCINATION: adding data for Saudi Arabia

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#291]
@ashahat I'm opening a dedicated issue to avoid sending too many messages in issue #230.

Thank you very much for letting us know about the map. Is there any place where either the full time series, or even just the latest number (178,337) is accessible in a machine-readable format?

**Comment by ashahat** [comment]
yes we can supply you with a web service for you to read if you can tell us what is the data needed

**Comment by edomt** [comment]
@ashahat The best format would be a time series of:

- Date field
- Total number of first doses administered
- Total number of second doses administered

We're happy to fetch this via an API URL, or from a simple file that you could put online on GitHub.

**Comment by ashahat** [comment]
We have built a webservice for the data how do you want us to send it to you 
Also it has the other countries data in your sheets

**Comment by edomt** [comment]
That's completely fine we can filter out the other countries.

You can send me the necessary information at:  edouard [at] ourworldindata [dot] org
