### ISSUE TITLE
Chilean Data

### ISSUE THREAD

**Issue by dna33** [owid/covid-19-data#292]
Hi, can you please expand as to how do you obtain daily report data from Chile please?

Thanks in advance

**Comment by edomt** [comment]
Hi @dna33 

For Chile, we follow the dashboard published here by the Department of Statistics and Health Information: https://informesdeis.minsal.cl/SASVisualAnalytics/?reportUri=%2Freports%2Freports%2F1a8cc7ff-7df0-474f-a147-929ee45d1900&sectionIndex=0&sso_guest=true&reportViewOnly=true&reportContextBar=false&sas-welcome=false

**Comment by dna33** [comment]
Great, thanks. What about for daily new cases, total cases and those daily statistics you publish?

**Comment by edomt** [comment]
We import all of this data from Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19/

**Comment by dna33** [comment]
oh, excelent. Can you please update your source then? JHU data comes from this repo: https://github.com/MinCiencia/Datos-COVID19.

It is an official government repo, maintained jointly by Ministry of Science and Ministry of Health in Chile, we are pursuing permanent funding for this kind of data initiatives in Chilean state, so would benefit from getting proper attribution when used.

Thanks in advance!

**Comment by edomt** [comment]
Sorry, I meant that we import all our data on cases & deaths from Johns Hopkins, for all countries in the world (and we use it without alteration). So we don't have country-by-country sources for this data.

**Comment by dna33** [comment]
@edomt thanks for your kind replies and dedication. What about this one? https://github.com/owid/covid-19-data/blob/master/public/data/testing/covid-testing-latest-data-source-details.csv

**Comment by lucasrodes** [comment]
Hi @dna33, 
From what I can see in [the script that automates the testing data imports](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automations/batch/chile.py), this [graph](https://e.infogram.com/79acdebc-18ad-4399-8936-bce3b3a49068) extracted from [gov's dashboard](https://www.gob.cl/coronavirus/cifrasoficiales/) is being used.

Hope this helps

**Comment by edomt** [comment]
Indeed, for tests we had been extracting data from one of the official graphs. We'll now use data products 17 (for the number of tests) and 55 (for the positive rate). Many thanks for making these available.
