### ISSUE TITLE
2nd Doses for the UK

### ISSUE THREAD

**Issue by adamredfern92** [owid/covid-19-data#293]
The UK is now reporting 2nd doses - is there any plan to add this to the vaccination data?

Thanks for all the hard work!

**Comment by edomt** [comment]
Hi @adamredfern92, yes there is! I'm working on it today :)

**Comment by edomt** [comment]
@adamredfern92 This is now part of our data - see https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/ (it's also in our entry: https://ourworldindata.org/covid-vaccinations)
