### ISSUE TITLE
Vaccination data for Belgium

### ISSUE THREAD

**Issue by Romain1798** [owid/covid-19-data#295]
Hello, I recommend you use this website that compiles data for Belgium: 

https://covid-vaccinatie.be/en

Thank you for your work.

**Comment by edomt** [comment]
Hi @Romain1798. We'd like to use numbers for the whole of Belgium rather than the sum of regions. But if Sciensano still hasn't published anything by the end of the week we'll probably consider doing that.

**Comment by Fred-3000** [comment]
I am anxiously awaiting information from Sciensano as well, but this dashboard compiles data from the 3 regions. Belgium is the sum of the 3 regions after all. :)
