### ISSUE TITLE
Vaccination.csv

### ISSUE THREAD

**Issue by dprata00** [owid/covid-19-data#296]
While I was compiling the data from "Vaccination.csv" file, I noted that there is a minimum difference between the "total_vaccinations" and the sum of" daily_vaccinations". I went to the "README.md" file and they explained the math behind "daily_vaccinations" as:  "For countries that don't report data on a daily basis, we assume that vaccinations changed equally on a daily basis over any periods in which no data was reported." I would like to know if over time, you guys fix this small sum differences or not. 

Thanks for your attention!

**Comment by edomt** [comment]
Hi @dprata00 - we've now clarified the calculations for `total_vaccinations` and `daily_vaccinations` and added a `daily_vaccinations_raw` variable that includes the raw change between days. See here: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/

**Comment by dprata00** [comment]
Thanks for the clarification!
