### ISSUE TITLE
Lebanon Data Offset by One

### ISSUE THREAD

**Issue by pkhoueiry** [owid/covid-19-data#3]
Lebanon data is offset by one day in Owid. The first case was reported on Feb 21, and not Feb 22. This is shifting the plots and is specifically impacting the current day, which shows the data from the previous day...

**Comment by HannahRitchie** [comment]
This is not an issue specific to Lebanon. It is instead the fact that the dates shown are representative of the reporting date, not the day itself. This is how the original dataset (from the [European CDC](https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide)) reports it. We note this in our documentation on our website here:

https://ourworldindata.org/coronavirus-source-datahttps://ourworldindata.org/coronavirus-source-data

_Each day the ECDC collects data from 6am to 10am CET and publishes this data via its COVID-19 dashboard. This dataset is then also made publicly available through downloadable CSV files at 1pm CET. Its daily Situation Reports are then update to reflect this new data from 2pm to 4pm CET._

_The date here reflects to the date of reporting, not necessarily the confirmed case and death figures on that given day. For example, data shown for 25th March presents the latest figures as of 10am CET on 25th March._

**Comment by pkhoueiry** [comment]
Thanks for taking the time to reply. Makes sense now. If I may suggest,  it would be better to show them the "right" number for the right date as other sites are doing. 

Many thanks again for the great work and tools you have. Best
