### ISSUE TITLE
VACCINATIONS: Chile source data

### ISSUE THREAD

**Issue by lucasrodes** [owid/covid-19-data#306]
In the near future, data will be available in https://github.com/MinCiencia/Datos-COVID19, as reported in https://github.com/MinCiencia/Datos-COVID19/issues/804.

However, for now, there appears to be a repo (https://github.com/juancri/covid19-vaccination) which releases the vaccination data from https://deis.minsal.cl as CSV files (see [releases](https://github.com/juancri/covid19-vaccination/releases)).

If deemed suitable/reliable I can work on a PR for this. I guess it should be fine, but is not a direct source.

**Comment by edomt** [comment]
Unless I'm misunderstanding the "Setup" part of the README it still looks pretty manual? Unless you can automate the JSON fetching as well of course. But in terms of "officialness" that would be completely fine as long as the data can be traced back to https://deis.minsal.cl. So feel free to give it a try!

**Comment by edomt** [comment]
I just had a look at the releases link—sorry I missed that. So yes, that's fine!
