### ISSUE TITLE
make US states data available

### ISSUE THREAD

**Issue by smcclatchie** [owid/covid-19-data#31]
The full covid-19 dataset is aggregated at the country level. I would like to access the data at the state level in the U.S. as well. Can these data please be made available for download either as additional cases in the full dataset, or as a separate file?

**Comment by edomt** [comment]
Hi @smcclatchie 

For now our plan is to stick to country-level data, as we don't currently have the time or resources to delve into local or regional data. However, I can point you to the COVID Tracking Project and [its great API](https://covidtracking.com/api), which should have everything you need.

Edouard
