### ISSUE TITLE
Germany vaccination data *per state*

### ISSUE THREAD

**Issue by mathiasbynens** [owid/covid-19-data#311]
Thank you for this important project!

covid-19-data contains vaccination data for Germany at a national level: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Germany.csv

If anyone's looking for more fine-grained historical data per German state based on the same source, here's the repository for you: https://github.com/mathiasbynens/covid-19-vaccinations-germany/blob/main/data/data.csv

If the covid-19-data project changes its mind and decides to increase the granularity of its vaccination data to include data per German state, let me know! I'd love to make my project obsolete in favor of yours.

Feel free to close this issue, it's just an FYI.

**Comment by edomt** [comment]
Thanks @mathiasbynens. We'll keep this in mind if we decide to get into subnational vaccination data.
