### ISSUE TITLE
Turkey started vaccination offically and opened a web site for it

### ISSUE THREAD

**Issue by nrazon** [owid/covid-19-data#313]
@edomt 
https://covid19asi.saglik.gov.tr/

I just shows total vaccinated people not much detail.

FYI

**Comment by edomt** [comment]
Thank you! Working on the automation now :)

**Comment by nrazon** [comment]
api url that site uses:
https://covid19asi.saglik.gov.tr/covid19asisayisi?getir=asiYapilanKisiSayisi

returns json:
{
"asisayisi": 132151
}

**Comment by edomt** [comment]
I love you!

**Comment by edomt** [comment]
But yes, that counter is going incredibly fast. When I found the website it was at 125k. Do you know anything about that? Is it connected in real time to the DB or something?

**Comment by nrazon** [comment]
Yes it is realtime. 
Fahrettin Koca (Minister of Health) was told before when turkey will start vaccinations we will push numbers realtime to a website.
And seems they did this :) 
More than 100K health workers got vaccinations today and going on.

this is the priority order or who will got vaccines first.
https://covid19asi.saglik.gov.tr/TR-77707/covid-19-asisi-uygulanacak-kisiler.html

**Comment by edomt** [comment]
Well if that's really the case it's absolutely amazing. Thanks again! It's on https://ourworldindata.org/covid-vaccinations now.

**Comment by nrazon** [comment]
@edomt BTW, Turkey is using Sinovac vaccine not Sinopharm.
Both are China's vaccines but Turkey tested and bought Sinovac.

**Comment by edomt** [comment]
Yes someone just told me this on Twitter, I'm fixing it now (this press release by AA mentions "CoronaVac" which is the Sinopharm vaccine but it's probably a mistake: https://www.aa.com.tr/en/turkey/turkey-set-to-start-covid-vaccination-on-thursday/2109003)

**Comment by nrazon** [comment]
@edomt  Seems that one more promise of health of minister has failed.
Real Time Vaccination crashed because of load. And site turned to static html. :((
If API doesn't returns back you might need to parse html and get he number from "var asiyapilankisisayisi  = xxx"

view-source:https://covid19asi.saglik.gov.tr/

--
  | <script type="text/javascript">
  | //<![CDATA[
  | var asiyapilankisisayisi = 214028;//]]>
  | </script>
  | </form>
  |  
  | <script>
  |  
  | //alert (" "+asiyapilankisisayisi+"");
  |  
  | $(".count-nums1").html(""+numberWithPoints(asiyapilankisisayisi)+"");
  | function numberWithPoints(x) {
  | return x.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ".");
  | }
  |  
  | </script>
  |  
  | </body>
  | </html>
