### ISSUE TITLE
Wrong source URL for Austria

### ISSUE THREAD

**Issue by botic** [owid/covid-19-data#318]
I know, the Dashboard is a mess for journalists and scientists … but at least it should be referenced as source URL in the automation. `https://info.gesundheitsministerium.at/`

https://github.com/owid/covid-19-data/blob/401059d7b85a071eae1a8d3dbbe830d4e8bd9c69/scripts/scripts/vaccinations/automations/batch/austria.py#L20

**Comment by edomt** [comment]
Oops! Too much copy-pasting :) thank you for spotting this! Will be fixed in ~1 minute.

**Comment by botic** [comment]
Thanks! Just to blame the right source if they change again the definitions etc. ;)
