### ISSUE TITLE
Add US county level Vaccine data

### ISSUE THREAD

**Issue by lilyclemson** [owid/covid-19-data#321]
Since CDC has already published US state-level vaccine data, it would be much more appreciated if OWID can acquire vaccine data for US county as well. E.g. add columns sub_location_1 (state), sub_location_2 (county) in the future.  Thank you.

**Comment by edomt** [comment]
Hi @lilyclemson 
Given how complex and extensive this effort would be, I don't see us being able to do this unfortunately.
