### ISSUE TITLE
Argentina's number are extremely off

### ISSUE THREAD

**Issue by Gabriel-p** [owid/covid-19-data#33]
I'm not sure how this site gathers its data, but the numbers for Argentina's daily new cases are completely off. You can see in this [local newspaper](https://www.infobae.com/coronavirus/argentina/)  the actual data:

![Captura de pantalla de 2020-04-28 09-29-20](https://user-images.githubusercontent.com/6054951/80487188-c84bc380-8932-11ea-8f94-e157320fa6e0.png)

To compare, here are the values from this repo (taken from https://ddi.sutd.edu.sg/)

![Captura de pantalla de 2020-04-28 09-31-04](https://user-images.githubusercontent.com/6054951/80487374-15c83080-8933-11ea-9792-682df1949498.png)

In particular, that ~350 point is ridiculously large.

**Comment by HannahRitchie** [comment]
Hi Gabriel,

We source our data directly from the European CDC (you find their daily updates [here](https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide)) and we do not make alterations to its original cases and death figures. The ECDC collates this data every morning (until 10am CET).

Looking at the Argentinian [trend](https://ourworldindata.org/grapher/daily-cases-covid-19?time=2020-03-04..&country=ARG) it looks like the government reports to the ECDC every few days, which results in a somewhat noisy series ranging from zero to essentially two days of cases in a single day. 

There is unfortunately not much we can do to fix this: we report it exactly as it given to us (and the ECDC exactly as it is given to them by national sources).

For assessing trends it's perhaps better to look at the [three-day rolling average](https://ourworldindata.org/grapher/daily-covid-cases-3-day-average?time=2020-03-04..&country=ARG)?

Thanks.

**Comment by Gabriel-p** [comment]
Hi, even if the government reports to the ECDC every few days (why should they report to the ECDC at all?) that spike of ~340 cases is not real. I'll try to report the issue over there.

Cheers
