### ISSUE TITLE
German vaccination data source spreadsheet changed its structure

### ISSUE THREAD

**Issue by mathiasbynens** [owid/covid-19-data#335]
https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/automations/batch/germany.py will need to be updated according to the upstream updates in the spreadsheet. The structure changed (in quite painful ways), and additional data points are now available: first vs. second dose, distinct stats for each vaccine (so far: either BioNTech/Moderna), etc.

In case you don't get to it before today's spreadsheet update, feel free to retroactively get the `2021-01-18` data from this file: https://github.com/mathiasbynens/covid-19-vaccinations-germany/blob/main/data/data.csv

**Comment by edomt** [comment]
Thanks @mathiasbynens! Thankfully we take our data for Germany from the `Impfungen_proTag` tab of the spreadsheet, which hasn't changed in any major way. :)

**Comment by mathiasbynens** [comment]
> Thanks @mathiasbynens! Thankfully we take our data for Germany from the `Impfungen_proTag` tab of the spreadsheet, which hasn't changed in any major way. :)

I wasn't sure about the goal, since [your data](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Germany.csv) contains a `vaccine` column that currently says "Pfizer/BioNTech" for all entries. With the recent changes to the upstream spreadsheets, you _could_ get more detailed numbers for each vaccine if you wanted to -- but it would require reading the other spreadsheet tabs.

**Comment by edomt** [comment]
You're right, that's something that I had initially built into the system. But sadly very few countries (almost none) have published disaggregated numbers, and typically in this case the German spreadsheet gives a choice between the `Gesamt_bis_einschl_18.01.21` tab that only includes the latest total, or the `Impfungen_proTag` that includes the whole time series. And given that they're including retroactive corrections in the time series (by changing previous days including very distant ones in December), I prefer sticking to this one for now to make sure we have the most accurate historical data.
