### ISSUE TITLE
INDIA Vaccination  data

### ISSUE THREAD

**Issue by ravigkp** [owid/covid-19-data#337]
You can take data of Vaccination. from https://www.mohfw.gov.in/ site as it mentions
<img width="998" alt="Screen Shot 2021-01-19 at 5 42 13 PM" src="https://user-images.githubusercontent.com/2543608/105033131-b6402100-5a7d-11eb-986b-77a283ef87dd.png">

**Comment by edomt** [comment]
Thank you @ravigkp - we'll collect the data automatically from there now.

**Comment by ravigkp** [comment]
Thanks @edomt, let me clear few things
daily data updated on this website around 9-10 AM IST, and the data is for yesterday date like if it says 20 Jan then vaccination data is up to 10 jan IST.
I am saying this bcz there should not be any discrepancy in data. 

current data from your site shows: 454049 till 19th Jan
current data from MoHfw site shows:  674835 till 19th Jan

Hope I am clear, I am also coder if you allow I would like to be part of india data update (auto)

**Comment by edomt** [comment]
Thanks, good to know, I've made the necessary change.
