### ISSUE TITLE
Incorrect data for The Netherlands

### ISSUE THREAD

**Issue by VictorHartman** [owid/covid-19-data#339]
I noticed a small mistake based on [the new data of RIVM](https://www.rivm.nl/covid-19-vaccinatie/cijfers-vaccinatieprogramma)

When compared with what is currently present in https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/automations/output/Netherlands.csv

At the end of week 1, on January 10, the cumulative should be 33.000 (31.000 plus 3.000). See the full report of the RIVM.

Also I think for the January 9 data, the LNAZ is better to cite, https://www.lnaz.nl/nieuws/30000-medewerkers-in-de-acute-zorg-gevaccineerd

On another note, will this file also be updated? https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Netherlands.csv Was a little confusing seeing old data in this file.

**Comment by edomt** [comment]
Thanks @VictorHartman, we'll make some adjustments. 

Yes, the file in `country_data` will be updated when we make today's update live (~8PM Central European Time).

**Comment by VictorHartman** [comment]
Thanks for the response. However the data is still incorrect. [Looking at the data of the RIVM](https://www.rivm.nl/sites/default/files/2021-01/Deelname%252525252520COVID-19-vaccinatie%252525252520in%252525252520Nederland%25252525252020210119_0.pdf), they counted the amount of vaccinations separately per healthcare division. So to get the total per week, you need take the values of figure 1.2 and 1.3 together. This makes on January 10 the amount of vaccinations 34.000 as in 31.000 plus 3.000 and NOT 31.000 as it is right now. The old data only counts the vaccinations of one division of Dutch healthcare.

It's a small error... In table 1.1 you can see that when you take the sum of figure 1.2 and 1.3, you get the total vaccinations.
