### ISSUE TITLE
/covid-19-data/blob/master/public/data/testing/covid-testing.xlsx

### ISSUE THREAD

**Issue by GuillermousK** [owid/covid-19-data#34]
Hi,

I'm trying to import this excel with the URL "raw format" (https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/testing/covid-testing.xlsx) on my PowerBI Desktop and it throws an error of data file format.

If I try to import the file locally it says the same, but if I try to "Save as" the file in a new file with the same data, it works.

It seems that the file haves some invalid format, can you try to save the file again and upload again please?

**Comment by edomt** [comment]
Hi @GuillermousK 

Can you try again now please? I've changed a couple of things to the xlsx export and I'm curious to see if that'll solve your problem.

Edouard

**Comment by GuillermousK** [comment]
Hi @edomt ,

Thank you for answwer, It's still saying the same.
What options you have to export?, maybe we can find together the problem.

Thanks in advance

**Comment by edomt** [comment]
I've replaced the existing xlsx file with two different files:
`public/data/testing/covid-testing-all-observations.xlsx`
`public/data/testing/covid-testing-latest-data-source-details.xlsx`

Could you please check whether the import is now working correctly?

**Comment by GuillermousK** [comment]
Hi @edomt ,
There still saying the same, I can load xlsx with more than one sheet.
But csv files works perfect, if you will update the csv files I can update correctly.

If you look this link [https://docs.microsoft.com/en-us/power-bi/service-excel-workbook-files](https://docs.microsoft.com/en-us/power-bi/service-excel-workbook-files)
"Power BI supports importing or connecting to workbooks created in Excel 2007 and later"

Maybe the problem is there with xlsx files if you want to test it for new projects, I'll confirm you if it works.

Thank you!

**Comment by edomt** [comment]
Thanks @GuillermousK — if CSV files are working with PowerBI then yes I think you should use those CSV versions! They're also updated every day 👌 

Edouard
