### ISSUE TITLE
Belguim.csv has "False" in "people_fully_vaccinated" column

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#344]
Sorry back again. The Belgium file has False under the "people_fully_vaccinated" column. Link below. Is that correct as I would think it should be a number.

https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Belgium.csv

**Comment by edomt** [comment]
Thanks! Looking into it now.

**Comment by edomt** [comment]
✅ Fixed
