### ISSUE TITLE
UK Vaccs

### ISSUE THREAD

**Issue by markyb705242** [owid/covid-19-data#345]
Why have the UK vaccinations dropped off and can we have 1st and 2nd dose.

**Comment by edomt** [comment]
Hi @markyb705242 

Why do you mean by "dropped off"?

1st and 2nd dose data is available here: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv

**Comment by markyb705242** [comment]
There is no data for December or week 1 of January.

**Comment by edomt** [comment]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/7103774/105327542-48a40a00-5bcf-11eb-902b-8e7b5376f96c.png">
