### ISSUE TITLE
Is this related to bizpoint?

### ISSUE THREAD

**Issue by Falnesio** [owid/covid-19-data#35]
Is this related to https://www.bizpoint.com/l/en-covid ?

I see no direct link to their site in the visualization so I thought that it was suspicious.

**Comment by edomt** [comment]
Hi @Falnesio 

We are not affiliated with this website, no. However all of _Our World in Data_ is completely open access and all work is licensed under the Creative Commons BY license. People have the permission to use, distribute, and reproduce in any medium, provided the source and authors are credited.

Edouard
