### ISSUE TITLE
Testing data for Israel

### ISSUE THREAD

**Issue by Aric5301** [owid/covid-19-data#356]
Testing data for Israel seems to be  lagging behind by about a week.
Updated testing data can be fetched [from here.](https://datadashboardapi.health.gov.il/api/queries/testResultsPerDate)

Here is what I understand about the meaning of each variable:

- `amount` = the **total** amout of tests performed on a single day, including tests to determine whether someone has recovered from COVID-19. I'm not sure if this is useful for OWID.
- `amountVirusDiagnosis` = the number of tests performed on a single day, to discover whether one is newly infected with COVID-19.
- `amountMagen` = out of the total tests, this is the amount of tests that were performed by Magen David Adom, Israel's National Emergency Pre-Hospital Medical and Blood Services Organization. This is not useful for OWID.
- `positiveAmount` = the amount of virus diagnosis tests that came back positive on a given day.
- The positivity rate is calculated like this: `(positiveAmount/amountVirusDiagnosis)*100`

It seems to me that the current source of data ([this site](https://govextra.gov.il/media/31052/covid19-data-israel-15012021.csv)) is displaying tests using the `amount` variable and not `amountVirusDiagnosis`. (I compared data for 14/01/21).

Anyway, I provided as much information as I could.
I hope this is helpful 😄

**Comment by edomt** [comment]
Thank you @Aric5301, very useful! I've adapted our testing script to use this instead.
