### ISSUE TITLE
Israel uses also Moderna vaccines 

### ISSUE THREAD

**Issue by AssafKatz3** [owid/covid-19-data#357]
Hi,
The [sources list](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/locations.csv) should be fixed.
There are multi sources for it, for example [here](https://www.timesofisrael.com/first-batch-of-moderna-vaccines-arrives-in-israel/).
Thanks

**Comment by edomt** [comment]
Thanks @AssafKatz3. Are you able to find exactly on which day the use of Moderna started?

**Comment by Aric5301** [comment]
On 11.01.2021 it was still not clear who will be vaccinated using Moderna vaccines ([source](https://news.walla.co.il/item/3410922)).
I was not able to find any more official publicly available information about those vaccines. Their use in Israel is very minor and after the agreement that was signed between the State of Israel and Pfizer, authorities went pretty silent about other vaccine firms (Israel has also ordered AstraZeneca vaccines but no one is talking about it anymore ([source](https://en.globes.co.il/en/article-israel-changed-plans-in-buying-astrazeneca-vaccine-1001350876)))

**Comment by AssafKatz3** [comment]
@Aric5301 is right, the vaccination with Moderna started on 7 January, but this was minor (some workers in hospital, especially Hadassah). The missing of more information is probably due the reason that it is written in his source - the army uses it and obviously releases less information about it than civil authorization.
