### ISSUE TITLE
Incorrect info: change "country" to "state" in README for United States vaccination data

### ISSUE THREAD

**Issue by chloelubin** [owid/covid-19-data#358]
In reference to the [README](https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations), the description of a number of columns is incorrect. For all fields ending in 'per_hundred', you define the variables by saying that they represent "per 100 people in the total population of the country." However, it should read "per 100 people in the total population of the state." 

Doing a quick cross-reference on Google, I was able to confirm that the population of the state of Alabama was 4.9M people in 2019 (US Census Bureau data). The number of people vaccinated in that state as of 2021-01-13 was 84040.

84040/(4903000/100) = 1.71, which is the number in the total_vaccinations_per_hundred column.

Please correct the variable definitions at your earliest convenience.

On another note, awesome job putting this dataset together, it's no easy feat!

**Comment by edomt** [comment]
Hi @chloelubin! Well spotted—that's a typo due to the fact that the README was written for our global dataset ([vaccinations.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv)) and I forgot to change the word "country". It's fixed now!

**Comment by chloelubin** [comment]
No problem! Figured as much. Thanks a lot!
