### ISSUE TITLE
Reproduction rate issue in latest data

### ISSUE THREAD

**Issue by elreviae** [owid/covid-19-data#365]
Hi,
first of all thank you very much for all the good work about the data.

Well, actually into the latest data file, I'm using JSON one, I don't have the ' reproduction_rate ' values anymore.
Is it finally a real issue  or maybe some data are coming for this specific field ?
thanks

**Comment by edomt** [comment]
Bonjour Maxime,
We have a limit of 14 days for the data that's in the "latest" set of files, and the reproduction rates (that we source from an external research team) had passed that threshold. I've just updated the underlying data and the rates are back in "latest" now.
