### ISSUE TITLE
Negative new cases

### ISSUE THREAD

**Issue by lautaroblatto** [owid/covid-19-data#37]
I would like to know what the meaning is for negative figures in the new cases column. May it be a mistake or does it mean something else?
As an example, the new cases figure for Spain on April 19th is -1430.

**Comment by HannahRitchie** [comment]
Hi,

On April 19th Spain changed its methodology on what is counted in confirmed cases. Previously both PCR and antibody testing results were used for this count; as of April 19th it only reports PCR test results. This results in a drop in confirmed cases in the confirmed cases series published by the Spanish authorities [here](https://covid19.isciii.es/resources/CURVAACUMULADA.png). This then shows as negative daily case numbers in the ECDC dataset on April 19th.
