### ISSUE TITLE
Update Sweden 

### ISSUE THREAD

**Issue by Angelus123123** [owid/covid-19-data#378]
Hi. How do you update the data? I can see that Sweden have byes data but it’s not updated here. 

See source 

https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/vaccination-mot-covid-19/statistik-over-vaccinerade-mot-covid-19/
--

**Comment by edomt** [comment]
Hi @Angelus123123 
See #230 
This new data for Sweden was reported this morning, so it'll be included in today's update (~8PM CET).
