### ISSUE TITLE
SPAIN 4302020

### ISSUE THREAD

**Issue by lberke** [owid/covid-19-data#38]
It looks like the Spain data for 4/30/2020 is missing. Is it available?

**Comment by edomt** [comment]
Hi @lberke 

There is unfortunately not much we can do to fix this. We source our data directly from the European Centre for Disease Prevention and Control, and report it without making alterations to its original cases and death figures.

The ECDC has been experiencing issues regarding the reporting of Spanish data for a few days, with a more important lag compared to other countries. They had previously chosen to leave the last day of data empty for Spain in each update, but changed strategy in yesterday's update, by filling the current day with the latest number, and skipping 30 April instead.

But overall, even though there's a gap on 30 April, the numbers are correct and the total should include all cases and deaths reported by Spain.

Edouard
