### ISSUE TITLE
requirements.txt for scripts

### ISSUE THREAD

**Issue by kokes** [owid/covid-19-data#386]
Hi, when setting up my local environment, I stumbled upon [requirements.txt](https://github.com/owid/covid-19-data/blob/master/scripts/requirements.txt), but found it lacking in terms of dependencies for vaccination scripts. Is this requirements file only for ECDC and other helpers?

(Upon installation, I didn't have requests or bs4, among other libs. I couldn't find another requirements.txt for these, had to install all of them manually.)

**Comment by edomt** [comment]
Hi @kokes. Indeed, this list of requirements is mainly for the automated importers (ECDC, JHU, OxCGRT, etc.). I've now added https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/automations/requirements.txt with what should be the only requirements for vaccination scripts.
