### ISSUE TITLE
Canada data incomplete today

### ISSUE THREAD

**Issue by sitrucp** [owid/covid-19-data#390]
Canada daily calculation in vaccinations file not working today?

**Comment by edomt** [comment]
Hi @sitrucp 

Your report is a bit too brief to be easy to understand. I assume you're referring to the vaccination dataset?
Daily data for Canada is in there—but it's less complete than it used to be before January 12. The reason for this is that we now use data coming directly from the official dataset (https://health-infobase.canada.ca/covid-19/vaccine-administration/), where the data on doses administered only starts on January 12.

**Comment by sitrucp** [comment]
Yes sorry was referring to vaccination dataset.

Ok I do see official dataset at that link named "vaccination-administration.csv" which has only 
values for "numtotal_all_administered" available.  (Even though web page explictly states  "COVID-19 vaccination began in Canada the week of December 13, 2020" .. thanks Canadian government and the notes on data include references to data from early Dec 2020 https://health-infobase.canada.ca/covid-19/vaccine-administration/technical-notes.html#a1)

I think OWID was previously using "COVID-19 Canada Open Data Working Group" data which has complete dataset back to Dec 12, 2020. This is probably Canada's most complete dataset. I will go back to using this for now.
 https://github.com/ccodwg/Covid19Canada/blob/master/timeseries_canada/vaccine_administration_timeseries_canada.csv

If any Canadian government folks are reading this, can you please provide complete official vaccination dataset!!

**Comment by edomt** [comment]
Yes, I hope it's only temporary and that the rest of the time series will be added retrospectively.
