### ISSUE TITLE
Excess mortality layout and data

### ISSUE THREAD

**Issue by eagleoneandrea** [owid/covid-19-data#393]
The dataset comes out with different column headers than defined in the documentation (and compared to what was delivered until a few days ago). There's also some issues with the output data and some inconsistencies between 2020 deaths and deaths in previous years that I've seen in Italian subset.

**Comment by edomt** [comment]
Hi @eagleoneandrea 

I found a difference in one of the column names between the CSV and the documentation (`average_deaths_2015_2019_all_ages`) which I've fixed now.

The fact that the data has changed is normal: the transition to 2021 made it impossible to keep the exact same structure.

Can you explain what the other issues are?

**Comment by eagleoneandrea** [comment]
Exactly the column is that one. I've done a double check and the data is ok.

Thank you!
