### ISSUE TITLE
vaccination data the Netherlands - dashboard got updated

### ISSUE THREAD

**Issue by mzelst** [owid/covid-19-data#394]
Hi folks,

Little update from my side: dashboard got updated today and the vaccine delivery data is now properly stored in the source data of the official dashboard. I've updated the vaccine scripts to do two things:

- Get the vaccines that are expected to be delivered straight from the source data
- The vaccines used per organization (hospitals / public health org's / elderly homes) are still scraped from the website (as they are not (yet?) in the source data.

Be aware: as soon as new data gets added for double doses (since the current data is still single-dose only), the dashboard might change (or not, because the data handling in the Netherlands is pure evil) and the scripts as well. Regularly monitoring the scripts might help ;)

Marino

@edomt @EwoutH

**Comment by edomt** [comment]
Hi @mzelst, and thank you for letting us know! We've now adapted our collection to use the new format… and hopefully they'll add second-dose data very soon :)
