### ISSUE TITLE
Adding Active Cases

### ISSUE THREAD

**Issue by statshero** [owid/covid-19-data#40]
There are numerous stats on cases and deaths, but why not active cases? It makes it useful with the active cases data to show which countries are improving/passed their peak.

**Comment by edomt** [comment]
Hi @statshero,

Our current data source on this is the European CDC (https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide) which do not currently provide figures on active cases.

For now, we focus on confirmed cases and deaths, but may think about extending this work in the future.

Edouard
