### ISSUE TITLE
Netherlands switched to dose estimate instead of actual doses

### ISSUE THREAD

**Issue by Sikerdebaard** [owid/covid-19-data#408]
Hi all,

Sorry to inform you that the Netherlands has yet again changed something.

The Netherlands has switched from reporting actual doses administered (heavily delayed, wildly inaccurate according to the gov.) to an estimate produced by a mathematical model based on the amount of doses delivered to facilities that administer the doses.

This new method causes a huge increase in the number of doses administered and the gov. states it is probably closer to the actual number of doses administered. However, this new mathematical method has yet to be verified and is somewhat controversial.

In any case: here's a scraper for this number. If you choose to use this new number please revert the Netherlands dataset to an older version first because the current scraper removed a lot of datapoints that it deemed invalid.

```python
import dateparser
import requests

data = requests.get('https://raw.githubusercontent.com/minvws/nl-covid19-data-dashboard/master/packages/app/src/locale/en.json').json()

doses = int(data["vaccinaties"]["data"]['kpi_total']['tab_total_estimated']['value'])

date = data["vaccinaties"]["data"]["sidebar"]["last_value"]["date_unix"]
date = dateparser.parse(date).date()

print(date, doses)
```

**Comment by edomt** [comment]
Hi @Sikerdebaard!

We are indeed aware that two numbers are now made available by the Dutch government. Given the way that they're described in the official documentation, we've decided to stick to the "Gemeld aantal" ("Reported number") version, as it's much closer to the number we collect for all other countries (i.e. doses administered and reported as such).

Edouard
