### ISSUE TITLE
Historical data expanation request

### ISSUE THREAD

**Issue by hjstein** [owid/covid-19-data#41]
I pulled the history of the updates to the data file `public/data/owid-covid-data.csv` and compiled them all into one large file so I can compare changes in counts for a given date as newer reports come in (like I did for the NYC data - https://www.linkedin.com/feed/update/urn:li:activity:6658517451480805376/).  The results are in the file `public/data/history.csv` in my fork of your repository (https://github.com/hjstein/covid-19-data).

In looking at the United States data, I noticed that the reports all have the same number for each date.  For example, the data shows 30,613 `new_cases` for 4/8 in every update from 4/16 through the present.  I'm surprised by this because when I did the same for the NYC data, I found the reported new cases for 4/8 kept increasing as newer reports came in (data and analysis available at https://github.com/hjstein/coronavirus-data).  So, I would have thought if the counts for NYC for 4/8 aren't fully known until about 3 weeks later, then the totals here for the USA should be getting revised in later reports as well.

So, my question is, how is the `new_cases` count being calculated, and where is the data coming from?

Thanks.

**Comment by edomt** [comment]
Hi @hjstein,

For confirmed cases and deaths, our data comes from the European Centre for Disease Prevention and Control (ECDC). We discuss how and when the ECDC collects and publishes this data [here](https://ourworldindata.org/coronavirus#our-world-in-data-relies-on-data-from-the-european-cdc).

Importantly, the ECDC follows a general rule of not changing past values in its data. If cases/deaths are reported with a lag—a general lag, as you described, or occasional ['blocks' of new data](https://www.theguardian.com/us-news/2020/apr/15/new-york-city-coronavirus-death-toll-jumps-revised-count)—these new cases/deaths will be added **on the date that the country reported them to the ECDC**.

Edouard

**Comment by hjstein** [comment]
@edomt - Thanks for the information.  So that means that the ECDC data misstates the actual number of cases and deaths for a given day.  When a site is late enough in reporting a count, the numbers will be reduced for that date and increased for a later date.  This will likely flatten out the data, making the growth rate appear slower than it actually is, and make the peak appear later.  That's unfortunate.
