### ISSUE TITLE
VACCINATIONS: Missing data for Mexico

### ISSUE THREAD

**Issue by CovidMexico** [owid/covid-19-data#412]
Can you add the total_vaccinations data for:

2020-12-31
2021-01-01
2021-01-02
2021-01-03

Rigth now is empty and I think it should be 24998 (the same from the previous day). This is for the vaccinations.csv

Thanks.

**Comment by edomt** [comment]
Hi @CovidMexico 

When figures are exactly the same as the previous day, we don't add a new row with the same data but rather leave it blank. We let our users decide whether they want to fill the missing rows with methods such as forward-fill or linear interpolation.
