### ISSUE TITLE
VACCINATIONS: Sweden data

### ISSUE THREAD

**Issue by lucasrodes** [owid/covid-19-data#415]
Hi!
Just a small doubt regarding Swedish data.

I have checked your [script](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/automations/batch/sweden.py) for Sweden, and have observed that currently, you are mapping the week number to its corresponding Sunday date. However, the [source web](https://fohm.maps.arcgis.com/apps/opsdashboard/index.html#/db66ef8a6b714b3f93ae0516b8950feb) states the following:

> Statistiken omfattar givna vaccinationer till och med föregående vecka och kommer att uppdateras varje torsdag 14:00.

Translated:

> The statistics include given vaccinations up to and including the previous week and will be updated every Thursday at 14:00. 

So, shouldn't this mapping maybe use Thursdays (or prior day, i.e. Wednesdat) instead?

**Comment by lucasrodes** [comment]
Well, now, reading a bit more carefully, it actually states that the data is from the previous week (i.e. last available day = Sunday)

So nevermind, closing this!

**Comment by thkeeper** [comment]
Please unsubscribe me 
I tried to unsubscribe me on GitHub many times but I still receiving tons of email 

Tks

**Comment by edomt** [comment]
@thkeeper There should be an "unsubscribe" button at the bottom of each email.
You should also click "Unwatch" at the top of this page.
