### ISSUE TITLE
VACCINATIONS: Mexico's source

### ISSUE THREAD

**Issue by CovidMexico** [owid/covid-19-data#420]
Hello, first of all I want to thank you for all the effort you put into this, it is really appreciated.

I have recently seen some inconsistency in the data and that is because, here in Mexico, we do not have a reliable source. The most accurate and reliable data are the tweets provided by the Undersecretary of Health that can be found here: https://twitter.com/HLGatell and the most recent: https://twitter.com/HLGatell/status/1356418307608481793
Maybe this helps with the data.

**Comment by edomt** [comment]
Thank you @CovidMexico!
I've also noticed that the "Versión estenográfica" pages in the press release section have also more information.
