### ISSUE TITLE
C19 Vaccination ID Datasource

### ISSUE THREAD

**Issue by ivanwilliammd** [owid/covid-19-data#422]
FYI on another Indonesian Vaccination Datasource that may be helpful

02 Feb: https://covid19.go.id/berita/data-vaksinasi-covid-19-update-2-februari-2021
01 Feb: https://covid19.go.id/berita/data-vaksinasi-covid-19-update-1-februari-2021

**Comment by edomt** [comment]
Thank you @ivanwilliammd, we'll add these two data points.
