### ISSUE TITLE
Faroe Islands misspelled

### ISSUE THREAD

**Issue by Sikerdebaard** [owid/covid-19-data#424]
Hi all,

Looks like theres a small spelling mistake for the  Faroe Islands.

ISO alpha3: FRO
ISO notation: Faroe Islands
ISO page: https://www.iso.org/obp/ui/#iso:code:3166:FO

In the OWID dataset Faeroe Islands is used.

https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Faeroe%20Islands.csv#L2

**Comment by Sikerdebaard** [comment]
Here's a small script that might assist in checking country names using pycountry. :)

```python3
import pycountry

df_countries = pd.read_csv('https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/locations.csv', index_col='iso_code')

for alpha3 in df_countries.index.dropna():
    country = pycountry.countries.get(alpha_3=alpha3).name.lower()
    owid_country = df_countries.loc[alpha3]['location'].lower()
    if country != owid_country:
        print(alpha3, country, owid_country)
```

**Comment by edomt** [comment]
Hi @Sikerdebaard 
Both spellings are actually allowed :) https://en.wikipedia.org/wiki/Faroe_Islands
And the standard spelling in our database in `Faeroe Islands`, so we need to keep it that way so that things work correctly once the data is deployed to ourworldindata.org
