### ISSUE TITLE
the earliest date

### ISSUE THREAD

**Issue by noranekonobokkusu** [owid/covid-19-data#427]
Hello,

I've noticed January 21 is the earliest date for which data is available in 'owid-covid-data.csv'. Is there statistics for earlier dates?

**Comment by edomt** [comment]
Hi @noranekonobokkusu 

It depends on which type of data. Cases & deaths come from [JHU](https://github.com/CSSEGISandData/COVID-19/) and start on January 22. For the number of tests, we have earlier data in some countries (going back to January 1, 2020 at the earliest for Argentina).
