### ISSUE TITLE
Canada's vaccination data minor issue

### ISSUE THREAD

**Issue by cjones27** [owid/covid-19-data#428]
Hi! 

First, thanks for the incredible work!

I found a minor issue that may cause trouble to someone onwards. Canada's vaccination [data](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv) in the total_vaccination column has no data in the first row (it's not 0 or more like other the countries, it's a NaN). It changed specifically in this commit 0852259e017ad0a331789c43a35af87243b0f8cf. I don't know if this is suppose to be like that or not. Also, may I ask why Canada's vaccination data changed so drastically?

Thank you all very much!

**Comment by edomt** [comment]
Hi @cjones27 and thank you :)

Thanks for flagging this—it'll be fixed during today's update.
