### ISSUE TITLE
Slovakia vaccination data

### ISSUE THREAD

**Issue by kajbo92** [owid/covid-19-data#431]
Hello, not sure about vaccination data from Slovakia

in your csv data: 
total 179029, first dose 160860, second dose 18169

but official https://covid-19.nczisk.sk/sk
total 160860, first 142691, second 18169

thanks

**Comment by edomt** [comment]
Hi @kajbo92 

142691 is those with _only_ 1 dose (as opposed to those with _at least_ 1 dose).
If you go to https://covid-19.nczisk.sk/sk and expand the vaccination chart (button with 4 arrows pointing outwards) you can see this:

![image](https://user-images.githubusercontent.com/7103774/106877081-a9a40580-66d8-11eb-8e8b-22f1eff17429.png)

**Comment by kajbo92** [comment]
Thank you, i understand now ... i used Total as people, not as doses
