### ISSUE TITLE
String values on number expected fields

### ISSUE THREAD

**Issue by jmarcio** [owid/covid-19-data#441]
Hello,

The strings "people tested", "tests performed", "samples tested" and "units unclear" appear sometimes at (it seems) "tests_units" field.

Is this the expected behavior ?

$ awk -F, '{print $34}' data/owid-covid-data.csv | sort | uniq -c | tail
  31303 
   7417 people tested
   6128 samples tested
  21404 tests performed
      1 tests_units
    715 units unclear
$

Best regards

**Comment by edomt** [comment]
Hi @jmarcio 
Yes, this is expected, see https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-codebook.csv
