### ISSUE TITLE
VACCINATIONS: "CNBG" is the same as "Sinopharm"?

### ISSUE THREAD

**Issue by dbaroncelli** [owid/covid-19-data#445]
What's the difference between the CNBG and the Sinopharm vaccine?
CNBG is actually the arm of Sinopharm that develops vaccines.
Do you mean two separate vaccines or is it actually the same?

**Comment by edomt** [comment]
Hi @dbaroncelli 
Those are indeed the same vaccine. I'll harmonize the names in today's update. Thanks for flagging the issue.

**Comment by dbaroncelli** [comment]
@edomt
On the WHO website,
there are 2 Sinopharm vaccies:
https://www.who.int/publications/m/item/draft-landscape-of-covid-19-candidate-vaccines

one is by the Wuhan Institute of Biological Products
and one by Beijing Institute of Biological Products

it would also be interesting to know which each country uses,
or if it's exactly the same

**Comment by edomt** [comment]
@dbaroncelli Yes, that's right. We've now differentiated in the data between `Sinopharm/Beijing` and `Sinopharm/Wuhan`.
