### ISSUE TITLE
VACCINATIONS: a csv file with fields: country, vaccine, start_date, num_doses

### ISSUE THREAD

**Issue by dbaroncelli** [owid/covid-19-data#446]
It would be very useful to also have a CSV file with the following fields:
- country
- vaccine
- start_date (first day it started public inoculations in that country)
- tot_doses (total doses of such vaccine inoculated in that country)
- people_fully_vaccinated (the number of people fully vaccinated in that country with that vaccine)

Even if the fields "tot_doses" and "people_fully_vaccinated" is not available for all countries, a record with the other 3 fields will already be very useful.

I guess it would also be useful a csv file with simply the list of all vaccines, stating:
- vaccine name
- vaccine producer
- number of doses required for fully vaccinating a person
- total doses shipped
- total doses inoculated
- people fully vaccinated
- list of countries that started public inoculations of that vaccine

**Comment by edomt** [comment]
Hi @dbaroncelli 

Thank you for the suggestion.
We've now made available a file on doses by manufacturer here: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations-by-manufacturer.csv
Unfortunately we're far from having access to all the information that you've listed, but that's a start!
