### ISSUE TITLE
HDI data is outdated

### ISSUE THREAD

**Issue by Ceciliaca** [owid/covid-19-data#454]
The HDI data included in the COVID19 dataset is outdated (it was published in 2018). Updated HDI data was subsequently published in 2019 and in December 2020. The complete HDI time series is always revised.
The most recent version of the HDI data can be found here http://hdr.undp.org/en/indicators/137506

It would be great to have the COVID19 database with the most recent HDI values (which refer to 2019).

**Comment by edomt** [comment]
@Ceciliaca Thank you for the suggestion—this has now been updated in 90d0553a54cb50e0cdfa02314c54cef04c354edc

**Comment by Ceciliaca** [comment]
Thanks so much @edomt !
As part of the team that calculates the HDI, it is great to see this index included in the COVID19 database.
