### ISSUE TITLE
Clarify data range for Number of COVID-19 tests per confirmed case

### ISSUE THREAD

**Issue by AJamesPhillips** [owid/covid-19-data#46]
Regarding #45 I think it would reduce confusion to add a foot note saying that data is "always averaged from the beginning of records" or some wording like that.  When you take a smaller range of time [the title says for example](https://ourworldindata.org/grapher/number-of-covid-19-tests-per-confirmed-case?yScale=log&time=2020-05-06..2020-05-07&country=FRA+DEU+NZL+KOR+GBR+USA):

> Number of COVID-19 tests per confirmed case, May 6, 2020 to May 7, 2020

But the data is actually an average from a larger range.

Thank you again for this great resource and for your consideration of this proposed change.

p.s. I just released this is the data repo so not the right place for this suggestion.  If you could direct me to the correct place for these suggestions I'd be grateful.  Thank you.

**Comment by edomt** [comment]
Hi @AJamesPhillips 

Following the publication of the short-term version of tests-per-case (see #47), we've made the cumulative version less prominent on our site, and we've explained the method in the `Sources` tab:

> The total number of tests to date divided by the total number of confirmed cases. Tests may refer to the number of tests performed or the number of people tested – depending on which is reported by the particular country.

Best,
Edouard
