### ISSUE TITLE
Vaccine doses per manufacturer for the Netherlands

### ISSUE THREAD

**Issue by Sikerdebaard** [owid/covid-19-data#469]
Here's a scraper for the doses administered per manufacturer as reported weekly by the RIVM.

```python3
import pandas as pd
import requests
from bs4 import BeautifulSoup


req = requests.get('https://www.rivm.nl/covid-19-vaccinatie/cijfers-vaccinatieprogramma')
req.raise_for_status()

page = req.text

soup = BeautifulSoup(page)


table = soup.find_all('table')[0]
[el.decompose() for el in table.find_all('span')]  # remove span tags in the table, they mess up pandas read_html

# first, group by vaccine, then sum on axis 0, then sum over axis 1
df_doses_per_manufacturer = pd.read_html(str(table), thousands='.', decimal=',')[0].groupby('Vaccin').sum().sum(axis=1).to_frame()

df_doses_per_manufacturer.columns = ['doses']

mappings = {
    'COM': 'Pfizer/BioNTech',
    'MOD': 'Moderna',
}

df_doses_per_manufacturer.rename(index=mappings, inplace=True)

print(df_doses_per_manufacturer)
```

**Comment by edomt** [comment]
Hi @Sikerdebaard

Many thanks for the code, but for now we'll only be adding vaccine-by-manufacturer data for the countries that make it available in a clean time series. Adding this data on top of everything else we already track can easily become time-consuming, so we won't add "snapshot" values like the one published by the Netherlands (where I'm very confident that the format will change several times, and we'll have to fix the scraper each time).

But please do let me know if they publish a full time series with this data at any point :)
