### ISSUE TITLE
Request for daily or moving average of Number of COVID-19 tests per confirmed case

### ISSUE THREAD

**Issue by AJamesPhillips** [owid/covid-19-data#47]
The data for the (excellent) [Number of COVID-19 tests per confirmed case](https://ourworldindata.org/grapher/number-of-covid-19-tests-per-confirmed-case?yScale=log&time=2020-05-06..2020-05-07&country=FRA+DEU+NZL+KOR+GBR+USA) is averaged since the "beginning of records" (#45).

As time goes on, if a country has an outbreak in cases, this average will take a long time to move (#46).  Whilst this data is valuable, another version of the data that shows a daily or 7-day moving average over the data has the opportunity to inform debate and represent the situation in a timely and responsive manner.

Would it be possible to have a graph showing this daily or 7-day average?  Or indeed extend the existing graph with a second slider to select the max days to average over?

I appreciate this is the data repo so not the right place for this suggestion.  If you could direct me to the correct place for these suggestions I'd be grateful.  Thank you very much for your hard work, excellent resource and your consideration of this suggestion.

**Comment by edomt** [comment]
Hi @AJamesPhillips 

This "short-term" version of tests-per-case is now available [on our site](https://ourworldindata.org/coronavirus-testing#tests-per-case-how-many-tests-to-find-one-covid-19-case).

Best,
Edouard
