### ISSUE TITLE
Vaccination data for Peru

### ISSUE THREAD

**Issue by Sikerdebaard** [owid/covid-19-data#470]
Peru is now reporting on number of people vaccinated. Could someone that speaks the language comment on where to find doses administered, people vaccinated and people fully vaccinated? :)

https://gis.minsa.gob.pe/GisVisorVacunados/buscar/index

**Comment by Sikerdebaard** [comment]
A kind internet stranger on Twitter provided some translations.

https://twitter.com/AlejandrodeBar1/status/1359604059393638400

```text
On the right hand side of the site you will find the information in the image

"Vacunados" = vaccinated

You have the information for 1st dose (8,008 up to 3:43pm Perú Time) and 2nd dose (no one yet).
```

![image](https://user-images.githubusercontent.com/801853/107570119-67535a80-6be9-11eb-9e2e-bc30ef86ec7e.png)

**Comment by Sikerdebaard** [comment]
Seems like this scraper does the trick, for now.

```python3
import requests
import pandas as pd

headers = {'Content-type': 'application/json', 'Accept': '*/*'}
json = {
    "DisaCodigo": 0,
    "IdDepartamento": "",
    "IdDistrito": "",
    "IdEstablecimiento": 0,
    "IdFase": 1,
    "IdProvincia": "",
}

request = requests.post('https://gis.minsa.gob.pe/WebApiProd/api/ActVacunasResumen/ResumenFasePublico', json=json, headers=headers)
request.raise_for_status()

data = request.json()

df = pd.DataFrame(data['Data'][0]['Vacunas'])

first_dose = df[df['NroDosis'] == 1]['Vacunados'].sum()
second_dose = df[df['NroDosis'] == 2]['Vacunados'].sum()

print(first_dose, second_dose)
```

**Comment by Sikerdebaard** [comment]
The vaccine of choice in Peru seems to be Sinopharm. Not sure if it's Sinopharm/Beijing or Sinopharm/Wuhan. Actually, whats the difference between the two? Seems like both produce the bbibp-corv vaccine.

**Comment by nicoponcho** [comment]
It is Sinopharm/Beijing

shorturl.at/hDJKL

**Comment by edomt** [comment]
Thank you @Sikerdebaard! I've now pushed an automation based on your code.
Yes it's Sinopharm/Beijing (BIBP means Beijing Institute of Biological Products)
