### ISSUE TITLE
Slovakia weekly deaths, total deaths, Swedish population

### ISSUE THREAD

**Issue by freedomlives** [owid/covid-19-data#474]
Hi,

Yesterday the data on weekly mortality for Slovakia was brought up to date through all of 2020.
http://datacube.statistics.sk/#!/view/en/VBD_URBANAUDIT/om3003tr/v_om3003tr_00_00_00_en

The population of Sweden is 10.38 million as of November 2020, not 10.10 million.
https://www.scb.se/en/finding-statistics/statistics-by-subject-area/population/population-composition/population-statistics/

To the English speaking world, the only information on deaths in Slovakia are "deaths of a SARS-CoV-2 positive individual, where it was the primary cause of death". On a government portal, only in the Slovak language, there is also information on number of "deaths of a SARS-CoV-2 positive individual, where the primary cause of death was another illness". This information can be found on https://covid-19.nczisk.sk/sk  Right now the first number is 5629 deaths "from" COVID, while the latter is 1213 deaths "with" COVID, which works out to a total deaths per million of 1253, moving Slovakia up the list by nine countries.
I have written details how to navigate that portal here: https://blog.freedomlives.net/node/2

**Full disclosure:** I live in Slovakia, and from early on I've felt like the government has been choosing very non-standard ways to measure deaths which minimize the severity of the situation. These non-standard ways, like at first doing full autopsies of victims and only counting those where the cause of death was the respiratory form of COVID-19, probably have some scientific validity. But if you're going to compare how your country is doing to others, you need to use a similar measurement.

**Comment by edomt** [comment]
Hi @freedomlives 

We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues

For the population statistics, in order to keep things manageable we source all of our data from the latest edition of the United Nations World Population Prospects. You can see these estimates here: https://github.com/owid/covid-19-data/blob/master/scripts/input/un/population_2020.csv

**Comment by freedomlives** [comment]
Hi @edomt 

I will open the issue there. It is weird that they state that they no longer use ECDC as a data source, but there is no source given for Slovakia.

Very strange with the UN population estimate for Sweden. I emailed them along with a link to the table on Swedish statistics site. Surprisingly, I have gotten a reply back already, that they used data available in 2019, which at the time was from 2017, and that would explain the differences in estimation from reality. I have replied back, because even their figure for 2017 doesn't line up with the data from the Swedish statistics office of actual population. Eurostat has Jan. 1st population of most European countries for 2020 now. I will compare them later today, to see if Sweden was just an outlier, perhaps got higher immigration than expected.

**Comment by freedomlives** [comment]
Oh, now I see that Johns Hopkins gets data from Worldometers, and Worldometers gets data from one Slovak government page in English, where I didn't notice till now, but they literally lie by calling the number they are presenting as "Number
of COVID-19 associated deaths" when it is actually the number of deaths with the primary cause being COVID-19. So I've contacted Worldometers also. 
(https://korona.gov.sk/en/coronavirus-covid-19-in-the-slovak-republic-in-numbers/)
