### ISSUE TITLE
Error in Total Cases data for Irealnd on 28/1/2021

### ISSUE THREAD

**Issue by Padraig-Mac-Carthaigh** [owid/covid-19-data#480]
OWID entry for Total Cases for Ireland on Jan 28th is 193645
This is exactly 1000 cases more than the Irish Government update for that date which appears on this page:
https://www.gov.ie/en/publication/67ada-updates-on-covid-19-coronavirus-from-january-2021/

Relevant extract:
28 January
The latest news as of 6.15pm on Thursday 28 January
47 deaths and 1,466 cases confirmed:

the Health Protection Surveillance Centre (HPSC) has been informed of 47 additional deaths among people with COVID-19 in Ireland. 46 of these deaths occurred in January
there have been 3,167 COVID-19 related deaths in Ireland
1,466 additional cases of COVID-19 have been confirmed
there have now been 192,645 confirmed cases of COVID-19 in Ireland
as of 2pm today (Thursday), 1,567 COVID-19 patients are hospitalised, of which 216 are in ICU. There have been 69 additional hospitalisations in the past 24 hours

**Comment by edomt** [comment]
Hi @Padraig-Mac-Carthaigh 

We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues
