### ISSUE TITLE
📢 JOB: Our World in Data is hiring a new Data Analyst

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#481]
**Our team at @OWID is looking for a new Data Analyst to work with us on collecting, transforming, documenting and disseminating the data on the many topics that we cover.** This is a remote position, available from anywhere in the world.

_All details and how to apply: https://ourworldindata.org/data-analyst_ 

Who is the ideal candidate for this? Someone who will be passionate and skilled in data analysis and data engineering, interested in learning about many research topics they may not have previously worked on, and capable of understanding academic publications and datasets.

But beyond the technical skills for quantitative analysis and data management, we are also looking for someone with an unusual ability to understand what this data tells us about the world, and how to use it to communicate this to our millions of users. 

Importantly, this is *not* a position where you'll be working on machine learning projects or dealing with terabyte-sized databases. Our datasets are typically small by industry standards, and what we do isn't necessarily at the cutting edge of data science and cloud services.

But we are strong believers that ML isn't the most urgent next step to make progress on many of the large global problems. Much more often, the world needs clean, reliable & well-documented CSV files that can be the basis of clear, easy-to-understand, and accurate visualizations.

We look for people who are passionate about our mission and can demonstrate excellence in the areas we've listed.
If you meet the essential criteria (at least partially) we would really like to hear from you. We especially encourage applications from women and minorities.

**Comment by edomt** [comment]
Although they're slightly less related to the work done in this repo, we have also opened two other positions this week:

**Technical Team Lead**: https://ourworldindata.org/technical-team-lead

**Full-Stack Developer**: https://ourworldindata.org/full-stack-developer

**Comment by Mellyorawalker1** [comment]
Ok
