### ISSUE TITLE
Bangladesh updated Vaccination number (13.02.2021)

### ISSUE THREAD

**Issue by Shapod** [owid/covid-19-data#485]
Here are the official data of COVID-19 vaccination of Bangladesh. You can find the latest data of every day(i.e. total number of doses administrated that day). 
Follow the first release to get the latest data. By 13 February 2021, Bangladesh administrated total 736680 doses of vaccine. [link 1]

Also added English News link from a renowned National news portal as official data is in Bengali language. [link 2] 

( please let me know if I have to update here regularly or you have automated process to add data) 

[OFFICIAL DATA]
https://www.dghs.gov.bd/index.php/bd/component/content/article/80-english/5649-2021-02-08-14-21-17

[English News link to verify]
https://www.dhakatribune.com/bangladesh/2021/02/13/nearly-200-000-get-covid-19-vaccine-shots-in-a-day

**Comment by edomt** [comment]
Thank you @Shapod 
Do you know if these PDF reports are available in English anywhere?

**Comment by Shapod** [comment]
I searced on all official website of Bangladesh that contains information/stats of tge vaccination.  And dghs.gov.bd is the only official site which provide official data everyday. Unfortunately i found no English version of it.  I'm willing to provide updated data if you face any sort of problem. Please let me know.

**Comment by Shapod** [comment]
> Thank you @Shapod
> Do you know if these PDF reports are available in English anywhere?

I searced on all official websites of Bangladesh that contains information/stats of the vaccination. And dghs.gov.bd is the only official site which provide official data everyday. Unfortunately I coudn't found any English version of it. I'm willing to provide updated data frequently. if you face any sort of problem. Please let me know.
