### ISSUE TITLE
When is US vaccination data updated?

### ISSUE THREAD

**Issue by mr-devs** [owid/covid-19-data#489]
I am creating a dashboard that utilizes the `us_state_vaccinations.csv` data, updating it on a daily basis. Can you please estimate at what time the newest day's data should be updated on GitHub?

To be clear, the file I am referencing is: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/us_state_vaccinations.csv

**Comment by edomt** [comment]
Hi @mr-devs

We fetch the data automatically from the CDC each hour. They seem to have a somewhat stable schedule now; for the last week our update times have been:
2pm EST
2pm EST
2pm EST
3pm EST
3pm EST
2pm EST
3pm EST

It seems that you can bet on 3:10pm EST as a time when the dataset _should_ be updated. If you need to be extra careful, maybe 4:10pm EST would be preferable.

**Comment by mr-devs** [comment]
Thank you!
