### ISSUE TITLE
Update Covid-19 vaccination policy map for Bangladesh.

### ISSUE THREAD

**Issue by Shapod** [owid/covid-19-data#493]
Currently, Covid-19 vaccines are available for all of the vulnerable groups in Bangladesh.

[ Availability for ALL of following: key workers/ clinically
vulnerable groups / elderly groups ]

source: Official website of Bangladesh to enroll for Vaccine.
https://surokkha.gov.bd/enroll

**Comment by edomt** [comment]
Hi @Shapod 

This data on vaccination policies is sourced from the Oxford Coronavirus Government Response Tracker (OxCGRT).

The data presented is taken directly from the OxCGRT project; Our World in Data do not track policy responses ourselves, and do not make additions to the tracker dataset.

OxCGRT is an ongoing collation project of live data. If you see any inaccuracies in the underlying data, or for specific feedback on the analysis or another aspect of the project please contact OxCGRT team: https://forms.office.com/Pages/ResponsePage.aspx?id=G96VzPWXk0-0uv5ouFLPkVPwT6t5-mtCnZ6_s5yQ4ppUME9NOUtYRkxLVldLUVFERTRTMEJSRkZITC4u
