### ISSUE TITLE
New testing data source of Lithuania

### ISSUE THREAD

**Issue by garas** [owid/covid-19-data#499]
Previous testing data source had stopped updating.

New Source URL: https://open-data-ls-osp-sdg.hub.arcgis.com/datasets/d49a63c934be4f65a93b6273785a8449_0
CSV: https://opendata.arcgis.com/datasets/d49a63c934be4f65a93b6273785a8449_0.csv?where=municipality_code%20%3D%20%2700%27

Fields:
- date
- dgn_pos_day - Positive diagnostic tests per day
- dgn_prc_day - Positive diagnostic tests per day, %
- dgn_tot_day - Total diagnostic tests per day

**Comment by camy125** [comment]
Pull request opened here: https://github.com/owid/covid-19-data/pull/509

**Comment by edomt** [comment]
Thanks @garas
