### ISSUE TITLE
questions about data

### ISSUE THREAD

**Issue by AbbyHN** [owid/covid-19-data#503]
Data "time_series_covid19_deaths_glob" showed no space, each country had a specific death number every day. However, in the owid-covid-data, the variables such as "total_deaths" "new_deaths"  "new_deaths_smoothed"  had a lot of null values. Did the the null values represent no relevant death report, or  real zero death? 

![1](https://user-images.githubusercontent.com/79238635/108303048-1f7f9500-71e0-11eb-88fe-b3eff203420b.png)

**Comment by edomt** [comment]
We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues

**Comment by edomt** [comment]
(Most likely, given how early in the pandemic this was, I'd say they were days _with_ reports but without any death.)
