### ISSUE TITLE
Japan vaccination data

### ISSUE THREAD

**Issue by awh-tokyo** [owid/covid-19-data#504]
Japan's vaccinations started yesterday; the data is published by the Ministry of Health, Labour and Welfare here:

https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/vaccine_sesshujisseki.html

Sorry for submitting the information here; I didn't know what the proper procedure was.

**Comment by awh-tokyo** [comment]
Sorry, I'm going to close this and move it to #230 because I'm an idiot and didn't see that.

**Comment by edomt** [comment]
Haha, no need for the self-criticism @awh-tokyo :)
Thank you for providing the data! We'll add it this morning.
