### ISSUE TITLE
New per day vaccinations

### ISSUE THREAD

**Issue by draqsko** [owid/covid-19-data#510]
Ran into a bit of an issue using the table with new per day vaccinations, the display of the CSV new_vaccinations_raw data.

Currently the website table displays previous/next day amount for days where the data is interpolated with the disclaimer that there is no data. But that really isn't correct. For example on January 19th for the US data it makes it appear as though there was no reported vaccinations but there was vaccinations reported as the CSV has a total vaccinations column.

Perhaps a better way to display the table would be to include the daily_vaccinations_raw values with the disclaimer that they are interpolated. As it appears right now, it may confuse some into thinking that there was no vaccinations that day which makes the 7 day moving average start to look sideways in comparison.

**Comment by edomt** [comment]
Hi @draqsko
Can I ask exactly which table you're referring to? Can you maybe post a screenshot here?

**Comment by draqsko** [comment]
Sorry had a busy weekend shoveling snow and didn't see response. Screenshot is here.

https://imgur.com/a/tQqQmuP

First image is the top bar to show what data I'm looking at, it's on the table format. New per day vaccinations.

Second image shows the issue, January 19th should have some new vaccinations but it's pulling the data from January 20th and saying there is no data but that is not correct. Vaccines were administered that day however the CDC wouldn't have reported the day before and therefore you cannot calculate directly. Saying there is no data is incorrect and showing the January 20th data is misleading. You have an interpolated value for this, display it and put a disclaimer that it may not be accurate because it's interpolated. Because right now if I try to do a 7 day average from January 13th through January 19th manually, I will get a value that does not match your numbers for a 7 day moving average. If I pick a start or end date for a 7 day moving average that is one of these points, I will never get a 7 day moving average that matches yours.

I discovered this by trying to calculate the 7 day average during the last full week of the Trump Administration which ran from Jan 13 to Jan 19. When I did this, I got a value of roughly 832k for a 7 day average, the real value is what you have as a 7 day average which is 911k. If you displayed the interpolated values, which I pulled from the CSV file after discovering that, I would get 911k. So the better way to display that is to display the interpolated values with a disclaimer that the values are interpolated and not actual.

**Comment by edomt** [comment]
@draqsko See our documentation: https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations

`daily_vaccinations_raw`: daily change in the total number of doses administered. It is only calculated for consecutive days. This is a raw measure provided for data checks and transparency, but we strongly recommend that any analysis on daily vaccination rates be conducted using `daily_vaccinations` instead.

So `daily_vaccinations_raw` is the "untouched" difference between one report and the previous one, without any kind of interpolation or rolling average. **This is what's shown as "New per day" in our data explorer.**

Then, we make available `daily_vaccinations`, which is both interpolated linearly and smoothed over 7 days:

`daily_vaccinations`: new doses administered per day (7-day smoothed). For countries that don't report data on a daily basis, we assume that doses changed equally on a daily basis over any periods in which no data was reported. This produces a complete series of daily figures, which is then averaged over a rolling 7-day window. An example of how we perform this calculation can be found [here](https://github.com/owid/covid-19-data/issues/333#issuecomment-763015298). **This is what's shown as "7-day average" in our data explorer.**

**Comment by draqsko** [comment]
See my screenshots. Jan 19 is showing the data for Jan 20th, not daily_vaccinations_raw

I've already looked over your documentation, I am saying that anyone looking at your table as displayed on the website will think either one of two things, there's no actual data for that day which is wrong because there is a cumulative total reported on Jan 19th, it just includes several days' worth, or they will think that the data for Jan 20th is actually the data for Jan 19th as well because the text can be hard to see. Grey on grey isn't the best contrast but I don't believe that needs to be changed. Display no data instead of daily_vaccinations_raw if you like but it would be better to display daily_vaccinations_raw for that day rather than the daily_vaccinations_raw for the next closest day.
