### ISSUE TITLE
New scraper for the Netherlands

### ISSUE THREAD

**Issue by Sikerdebaard** [owid/covid-19-data#515]
Hi all, looks like the Netherlands has changed formats yet again. Here's a scraper for the new format. The new data is time-series data that is json encoded.  

latest_doses_administered_reported == the reported number of doses administered  
latest_doses_administered_estimated == the reported number of doses administered + mathematical approximation for instances that don't report the number of doses administered (yet) or that are heavily delayed  

```python3
import pandas as pd
import requests


data = requests.get('https://coronadashboard.rijksoverheid.nl/json/NL.json')
data.raise_for_status()

df = pd.DataFrame(data.json()['vaccine_administered_total']['values']).set_index('date_unix').astype(pd.Int64Dtype())
df.index = pd.to_datetime(df.index, unit='s')
df.sort_index(inplace=True)

latest_doses_administered_reported = df.iloc[-1]['reported']
latest_doses_administered_estimated = df.iloc[-1]['estimated']

print(latest_doses_administered_reported, latest_doses_administered_estimated)
```

**Comment by edomt** [comment]
Ha, that's very nice, thank you! I noticed that earlier today and looked into it for a few minutes but couldn't find a source to replace it with. I'll update the automation.

**Comment by edomt** [comment]
@Sikerdebaard This doesn't work locally for me, as I don't see any `vaccine_administered_total` key in the JSON, I only see `vaccine_delivery`. Is that the case for you as well now?

**Comment by Sikerdebaard** [comment]
The data is still there. Are you using the correct json? Is there some sort of cache or proxy between you and the data?

Alternatively I'm mirroring the data here: https://github.com/Sikerdebaard/netherlands-vaccinations-scraper/blob/main/vaccine_administered_total.csv

**Comment by edomt** [comment]
Yes, I'm going directly to https://coronadashboard.rijksoverheid.nl/json/NL.json but nothing like `vaccine_administered_total` in there. Very odd.
Thanks! We'll use your CSV for now then :)

**Comment by Sikerdebaard** [comment]
Hmm that is very odd indeed. It doesn't seem to be a geo lock as my scripts mostly run on servers outside of the Netherlands.

**Comment by edomt** [comment]
Yep - nothing seems to work (browser, force-refresh, curl…)
