### ISSUE TITLE
403 Forbidden when downloading CSV data with Python

### ISSUE THREAD

**Issue by lgommans** [owid/covid-19-data#519]
Hi! Is there any reason that [the CSV export](https://covid.ourworldindata.org/data/owid-covid-data.csv) is now 403 Forbidden for Python? Browser works, curl works, and last time I downloaded it (4 days ago) with Python that also still worked. It doesn't matter which IP address I use, it doesn't seem like I was rate limited (which would be weird anyway given that I download it once every couple days).

To reproduce in plain Python 3:

    import urllib.request
    urllib.request.urlopen('https://covid.ourworldindata.org/data/owid-covid-data.csv')

Will this be resolved or should I, um, spoof user agent or accept some terms or use a new URL or something?

Edit: for the record, another user agent works, not sure if this is the desired solution (so far I did just 1 request with this and am not planning on doing more currently):

```
r = urllib.request.Request('https://covid.ourworldindata.org/data/owid-covid-data.csv', headers={'User-Agent':'paiton but you seem to not like me anymore'})
r = urllib.request.urlopen(r)
```

**Comment by danielgavrilov** [comment]
Thanks a lot for reporting this! It was a problem on our end which should be fixed now.

**Comment by lgommans** [comment]
Works again, thank you!
