### ISSUE TITLE
Please check https://github.com/owid/covid-19-data/blob/master/public/data/ecdc/full_data.csv

### ISSUE THREAD

**Issue by ET2020-Italy** [owid/covid-19-data#52]
Today we are not able to read data. Is there any change or issue in the file

https://github.com/owid/covid-19-data/blob/master/public/data/ecdc/full_data.csv

tks

**Comment by edomt** [comment]
Hi @ET2020-Italy,

This file's format has not changed today or recently. Without more information than the above, we'll be unable to help.

Best,
Edouard
