### ISSUE TITLE
Japan vaccination data miscalculated?

### ISSUE THREAD

**Issue by AnnaNishino** [owid/covid-19-data#520]
Hello! Thank you always for your amazing work.

I found the total vaccination records you scraped might be miscalculated?
![image](https://user-images.githubusercontent.com/65237882/108583738-2a246080-737f-11eb-99f7-cf6016280524.png)
It looks like 486 shots were not cumulative numbers, but daily new shots for 2/18.
For 2/18, total vaccinations is supposed to be 611 (125+486).

![image](https://user-images.githubusercontent.com/65237882/108583745-36102280-737f-11eb-86b1-5bdc39a90c71.png)
As you see here at [the Health Ministry](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/vaccine_sesshujisseki.html), the bottom line shows the latest cumulative shots.
The second column (接種回数) means the daily shots for a certain day.
(FYI, data for weekdays right after Saturdays, Sundays and any holiday will include shots for the holidays as well since they skip updating on Sat/Sun/holidays)
Please do let me know if you need any assistance about Japanese.

Best,

Anna

**Comment by edomt** [comment]
Many thanks @AnnaNishino! We'll fix this in today's update.

**Comment by AnnaNishino** [comment]
@edomt Thank you very much for such a quick correction!
