### ISSUE TITLE
Data for Serbia for Feb 19th miscalculated

### ISSUE THREAD

**Issue by goranopacic** [owid/covid-19-data#525]
Hi,
it seams that you've added total number of re-vaccinated people (694488.0) to the total number of administered vaccines (1111000.0) so instead of 1111000.0 as total number of administered vaccines web site shows 1805488.0 for Feb 19th.

Latest data for Feb 19 *reported this morning Feb 20* show:
Total number of administered vaccines 1.136.131
Total number of re-vaccinated: 418.917

which means that yesterday's report by National tv about re vaccinations was miscalculated too.

Source: National TV of Serbia 

https://www.rts.rs/page/stories/sr/%D0%9A%D0%BE%D1%80%D0%BE%D0%BD%D0%B0%D0%B2%D0%B8%D1%80%D1%83%D1%81/story/3134/koronavirus-u-srbiji/4265914/korona-srbija-podaci-zarazeni.html

In Serbian: 
"Prema najnovijim podacima Vlade, u Srbiji je dato 1.136.131 doza vakcina protiv kovida. ...
U našoj zemlji drugu dozu cepiva primilo je 418.917 građana."

Also, Presindent of Serbia confirmed these numbers of about 420,000 revaccinated people at his press conference
"https://www.danas.rs/drustvo/vucic-po-broju-revakcinisanih-srbija-prva-u-evropi-uskoro-ce-biti-i-po-broju-vakcinisanih/"

**Comment by edomt** [comment]
Hi @goranopacic 

We're finding it very difficult to understand the numbers coming from the Serbian government and media.
In [this official press release](https://www.srbija.gov.rs/vest/521457/zdravstveni-sistem-suocen-sa-velikim-izazovom.php),  they mention 1,111,000 as the number of people vaccinated, and 694,488 as the number of people re-vaccinated. Which would mean a total of 1,805,488 doses administered.

**Comment by edomt** [comment]
A few people on Twitter have confirmed that this meaning is the right one: https://twitter.com/redouad/status/1363058166435622913
But that doesn't exclude the possibility that the person who wrote that press release got confused and described the numbers in the wrong way.

**Comment by goranopacic** [comment]
no, that person on twiter (Barrcöde XVII @barrcode01) is not reliable / making political jokes.
@fingerbandaged translated it properly.

There is no consistent way of reporting from the gov. I'm trying to make a contact to get data in a proper format.

**Comment by goranopacic** [comment]
translation is good but yesterday's number was miscalculation in that report.

**Comment by goranopacic** [comment]
Serbia managed to get 1,500,000 Sinopharm vaccines, about 100,000 Sputnik and similar number of Phizer so far.
Maximum number of vaccinations per day is about 70,000-100,000 so it is technically impossible that there was a jump from 1 mil to 1.8 mil in a few days.

**Comment by edomt** [comment]
There's now a statement from the director of the government's Office for IT and e-government, saying that 1,135,000 vaccines have been given so far: https://www.blic.rs/vesti/drustvo/vise-od-milion-prijavljenih-za-vakcinaciju-revakcinisano-skoro-420000-ljudi/0hcrs3q

Given these contradictions in the official reporting for Serbia, we have now removed the last data point for February 19th. We'll wait for new data that will hopefully make the situation clearer.

**Comment by momcilo78** [comment]
@goranopacic please try to tweet to @SerbianPM (I just did). I think she is the most likely to take an tackle the issue.
