### ISSUE TITLE
CFR?

### ISSUE THREAD

**Issue by CholoTook** [owid/covid-19-data#54]
Hello,

Where can I get CFR figures per geographic region?

Many thanks,
Dan.

**Comment by edomt** [comment]
Hi @CholoTook 

CFR figures are available in the following graph: https://ourworldindata.org/grapher/coronavirus-cfr

However, during an outbreak of a pandemic the CFR is a poor measure of the mortality risk of the disease. 

Edouard

**Comment by CholoTook** [comment]
Thanks. However I was curious about getting the cfr from (or in) the raw data dump. I guess I just divide the deaths by the cases to derive the cfr?

Many thanks,
Dan.

**Comment by CholoTook** [comment]
BTW, what's a better measure?
