### ISSUE TITLE
total_vaccinations_per_hundred Calculation

### ISSUE THREAD

**Issue by msgoussi** [owid/covid-19-data#549]
total_vaccinations_per_hundred: total_vaccinations per 100 people in the total population of the country
how do you calculate this indicator for (England, Wales, Scotland, North Ireland), since the population you provided via World Population Prospects is covering United Kingdom. 

country| date | indicator | value
England | 22/01/2021 | total_vaccinations_per_hundred | 9.82
Northern Ireland | 22/01/2021 | total_vaccinations_per_hundred | 9.35
Scotland | 22/01/2021 | total_vaccinations_per_hundred | 7.06
Wales | 22/01/2021 | total_vaccinations_per_hundred | 7.64

England | 22/01/2021 | total_vaccinations | 5,526,071.00
Northern Ireland | 22/01/2021 | total_vaccinations | 177,026.00
Scotland | 22/01/2021 | total_vaccinations | 385,855.00
Wales | 22/01/2021 | total_vaccinations | 241,016.00

population of UK is 67,886,004

Please Advise

**Comment by edomt** [comment]
Hi @msgoussi 

You can find these subnational populations separately here: https://github.com/owid/covid-19-data/blob/master/scripts/input/owid/subnational_population_2020.csv
