### ISSUE TITLE
Population of Guernsey

### ISSUE THREAD

**Issue by CholoTook** [owid/covid-19-data#55]
Not sure why this value is blank in the data. Gugu suggests the value of 67,052 from the CIA world factbook.

I found a value of 97,857 for Jersey.

**Comment by CholoTook** [comment]
Also 1,810,366 for Kosovo

**Comment by edomt** [comment]
Thank you @CholoTook—we have now added population for these countries.

**Comment by CholoTook** [comment]
Great!
