### ISSUE TITLE
Testing data not updated

### ISSUE THREAD

**Issue by garas** [owid/covid-19-data#553]
Many countries testing data have not updated for 2 days.

It seems like R scripts broken after https://github.com/owid/covid-19-data/pull/517. There are also now  `Costa Rica.csv` and `Costa_Rica.csv` in `scripts/scripts/testing/automated_sheets`

**Comment by edomt** [comment]
Hi @garas 

Thanks for letting us know about the output file for Costa Rica; this is now fixed.

The update of the testing data, on the other hand, is unrelated to this. Our testing data is updated twice per week (on Mondays and Fridays).
