### ISSUE TITLE
US Vaccinations by State columns not correct

### ISSUE THREAD

**Issue by gilj2021** [owid/covid-19-data#555]
The CDC changed their available fields two days ago. Administered_Dose1_Recip, Administered_Dose2_Recip are what is showing up on the CDC's front end website. In the .py file, these are "Adminstered_Dose1", etc (without _Recip).

**Comment by edomt** [comment]
Hi @gilj2021 

Given that the other two fields are still provided, is there a reason why we'd want to switch over to the new ones? My understanding is that the reporting method is different between the two types of field, so should we not stick to `Adminstered_Dose1` and `Adminstered_Dose2` to ensure continuity with the data previously collected?

**Comment by gilj2021** [comment]
I see what you are saying and agree on keeping things consistent. On the other hand, from what I can tell the CDC changed which metric they are publishing on the front-end, so there is the argument for keeping continuity with the front-end dashboard. I thought I would bring this to attention if interested and/or you agree.
