### ISSUE TITLE
The data for Virginia and Maryland is not matching the official site. 

### ISSUE THREAD

**Issue by colleenmcdougal98** [owid/covid-19-data#557]
I noticed that the data for Maryland and Virginia under the US data isn't matching the local state websites (https://www.vdh.virginia.gov/coronavirus/covid-19-vaccine-summary/ and https://coronavirus.maryland.gov/#Vaccine) even though it's supposed to come from those sites through the CDC website. Any idea why this is?

**Comment by edomt** [comment]
Hi @colleenmcdougal98 

There has recently been a major change in methodology in how the CDC counts and reports vaccination data. You can find more information documented by the Bloomberg data team here: https://www.bloomberg.com/news/live-blog/2021-01-21/methodology-and-analysis-for-the-covid-19-vaccine-tracker#60319089B2240006
