### ISSUE TITLE
Weather?

### ISSUE THREAD

**Issue by CholoTook** [owid/covid-19-data#56]
Hi,

Can you add monthly average temperature and humidity for each country for the given month?

Many thanks,

**Comment by edomt** [comment]
Hi @CholoTook 

This would take a significant amount of time, since we don't have this weather data at our disposal. Unfortunately we most likely won't add this, but you should be able to gather it from weather APIs or Wikipedia.

Edouard

**Comment by CholoTook** [comment]
Thanks.

How does your data integration work? I wonder if I could add a module to
your existing code...
