### ISSUE TITLE
World vaccination data in JSON file

### ISSUE THREAD

**Issue by RiccardoBorchi** [owid/covid-19-data#563]
Hi @edomt,

the world data are missing in the JSON file. Could you insert them?

Thanks!

_Originally posted by @RiccardoBorchi in https://github.com/owid/covid-19-data/issues/500#issuecomment-786104613_

**Comment by edomt** [comment]
Hi @RiccardoBorchi 

I'll try to add it today.

**Comment by edomt** [comment]
Should be okay now!

**Comment by RiccardoBorchi** [comment]
Hi @edomt,

yes, now it's ok!

Thank you!
