### ISSUE TITLE
Data on lockdown?

### ISSUE THREAD

**Issue by CholoTook** [owid/covid-19-data#57]
Do have data on when lockdown policies were affected per country?

**Comment by edomt** [comment]
We have an article on [Policy Responses to the Coronavirus Pandemic](https://ourworldindata.org/policy-responses-covid), with data and research from the Coronavirus Government Response Tracker (OxCGRT), published and managed by researchers at the Blavatnik School of Government at the University of Oxford.

We'll be looking into a way to add their stringency index to our complete dataset.

**Comment by CholoTook** [comment]
Thanks, it's hard to flatten I guess. What you would like is a stringency + date range per country.

i.e. China, 1st January to 15th of January stringency 2, China, 16th January to 21st February stringency 3, etc...


Cheers,

**Comment by edomt** [comment]
@CholoTook The `stringency_index` has now been added to our complete COVID dataset.

**Comment by CholoTook** [comment]
Many thanks. Is it a one off value or does it come with a date range?
