### ISSUE TITLE
Bahrain's population is incorrect 

### ISSUE THREAD

**Issue by hamodcraft22** [owid/covid-19-data#574]
hey first of all thanks to all of you guys for the amazing effort. 

ok so the population of Bahrain listed in the stats (I know its an estimate ) is a bit higher than the official number 😅

the official population of Bahrain is "1501635" rather than the extra 200000 added to the estimate, if you guys can fix that I would be ao thankful for that 

sources: "https://www.bna.bh/en/ArchiveDetails.aspx?archiveId=579833" 

"" The Cabinet adopted the 2020 population census in the Kingdom of Bahrain, presented by the Minister of Interior. The census indicated that the Kingdom’s population on the night of the reference time, which corresponds to 17 March 2020, amounts to 1,501,635 individuals, of whom Bahrainis constitute a total of 712,362, or 47.4%, while the number of non-Bahrainis reached 789,273 people, or 52.6%.  ""

**Comment by edomt** [comment]
Our population estimates for all of our COVID-19 work are based on the last edition of the United Nations World Population Prospects. In this source, the population for Bahrain is estimated at 1,701,583.

We understand that some figures in the UNWPP data may differ from the last census conducted by a country — but for the sake of simplicity and transparency, we have to stick to using one consistent source for all countries.
