### ISSUE TITLE
Countries figures are not adding up to World figures

### ISSUE THREAD

**Issue by msgoussi** [owid/covid-19-data#599]
Hi... 
If i exclude England, Northern Ireland, Scotland, Wales, European Union from the data I realized that the sum of total_vaccinations of all countries (189654826) is not equal to World total_vaccinations (244907748) on Feb 28, 2021.

Please advise.

[Book2.xlsx](https://github.com/owid/covid-19-data/files/6073743/Book2.xlsx)

--

**Comment by adamredfern92** [comment]
You are only including countries that have had an update to the data on the 28th of Feb so you are not calculating the true result for 28th. The world total_vaccinations is the correct value.

For example China's last update was on 9th of Feb so you would need to include that as well along with any other country that was not updated on the 29th.

**Comment by msgoussi** [comment]
So accordingly, the data is cumulative not a a daily new cases....

**Comment by adamredfern92** [comment]
Yes, total_vaccinations is total as of that date. There is a seperate field for daily new cases:

See https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations for info on each field.

**Comment by Mellyorawalker1** [comment]
Mellyora walker
