### ISSUE TITLE
Request to add Active and Recovered Cases.

### ISSUE THREAD

**Issue by kngoyal** [owid/covid-19-data#61]
Hi team,

Is it possible to add Active and Recovered Cases to the dataset.

Also I see -ve `new_cases` for some rows. Are those anomalies or recovered/death cases.

Thanks
Kamal

**Comment by statshero** [comment]
It is already issued/requested. Currently, the ECDC does not yet provide Active Cases & Recovered Data.

Quote - "Our current data source on this is the European CDC (https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide) which do not currently provide figures on active cases.

For now, we focus on confirmed cases and deaths, but may think about extending this work in the future."
