### ISSUE TITLE
Ireland Latent Data

### ISSUE THREAD

**Issue by mmcrey** [owid/covid-19-data#611]
Seeing that the data for Ireland is latent over the past few days, wondering if there's awareness?

**Comment by Mellyorawalker1** [comment]
Ok

**Comment by Mellyorawalker1** [comment]
Mellyora walker

**Comment by edomt** [comment]
Hi @mmcrey 

We take our data from https://covid19ireland-geohive.hub.arcgis.com/, which indeed has data with some delay. Right now the number of first doses stands at 297899, with "Vaccine Data up to Sun, 28 Feb 2021".
