### ISSUE TITLE
Dominican Republic UPDATE

### ISSUE THREAD

**Issue by enmanuelrm** [owid/covid-19-data#612]
Goverment annouce today a total of 161,827 already vaccinated, as this:

16-02-2021 | 385
17-02-2021 | 1,379
18-02-2021 | 5,328
19-02-2021 | 10,200
20-02-2021 | 13,087
21-02-2021 | 14,264
23-02-2021 | 19,117
24-02-2021 | 26,400
27-02-2021 | 60,000
28-02-2021 | 72,596
01-03-2021 | 105,984
02-03-2021 | 161,827

https://www.diariolibre.com/actualidad/salud/salud-publica-informa-que-161827-personas-han-sido-vacunadas-contra-el-covid-19-OH24760385

**Comment by Mellyorawalker1** [comment]
Ok

**Comment by Mellyorawalker1** [comment]
Mellyora walker

**Comment by edomt** [comment]
Thank you! We've added this.
