### ISSUE TITLE
Missing Column Data

### ISSUE THREAD

**Issue by kiphenglim** [owid/covid-19-data#62]
[owid-covid-data-2.xlsx](https://github.com/owid/covid-19-data/files/4665436/owid-covid-data-2.xlsx)

On fresh download of _owid-covid-data.xlsx_: 
Missing all data in columns: total_tests, new_tests, new_tests_smoothed, total_tests_per_thousand, new_tests_per_thousand, new_tests_smoothed_per_thousand, tests_units, extreme_poverty, cvd_death_rate, female_smokers, male_smokers,handwashing_facilities, hospital_beds_per_100k

Noticed as of 21 May 2020; was not present in 19 May update.

**Comment by edomt** [comment]
Hi @kiphenglim 

I cannot reproduce this issue, the file has data in all of those columns. Can you check again please?

Best,
Edouard
