### ISSUE TITLE
Vaccination data appears incorrect for Israel

### ISSUE THREAD

**Issue by michaelmanus** [owid/covid-19-data#621]
While reviewing the chart on the website, I noticed that it reports a much higher total vaccination rate than the Israeli government seems to.

https://datadashboard.health.gov.il/COVID-19/general
 
https://ourworldindata.org/covid-vaccinations

Israel's government website shows a vaccination rate of 51.39% as of Sunday whereas 93.82 percent for the same Sunday is displayed on the our world in data website for Israel.

It's very likely I am missing something here. However, the vaccination rate is displayed on the website is either extremely misleading or simply wrong. 
  
The data appears to be wrong as well:

https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Israel.csv

"total_vaccinations" for Sunday shows 8120609 whereas the israeli website claims only ~4778000 for the first dose administered.

**Comment by edomt** [comment]
In our entry dedicated to COVID-19 vaccinations, we display different metrics:

1/ The number of COVID-19 vaccination doses that have been administered
This is the total number of doses administered. This is counted as a single dose, and may not equal the total number of people vaccinated, depending on the specific dose regime (e.g. people receive multiple doses). If a person receives one dose of the vaccine, this metric goes up by 1. If they receive a second dose, it goes up by 1 again.

2/ The number of people who received at least one dose of COVID-19 vaccine
This is the total number of people who received at least one vaccine dose. If a person receives the first dose of a 2-dose vaccine, this metric goes up by 1. If they receive the second dose, the metric stays the same.
This data is only available for countries which report the breakdown of doses administered by first and second doses.

3/ The number of people fully vaccinated against COVID-19
This is the total number of people who received all doses prescribed by the vaccination protocol. If a person receives the first dose of a 2-dose vaccine, this metric stays the same. If they receive the second dose, the metric goes up by 1.
This data is only available for countries which report the breakdown of doses administered by first and second doses.
