### ISSUE TITLE
Romania - New doses starts with -289,998 

### ISSUE THREAD

**Issue by Sergiu-Marginean** [owid/covid-19-data#627]
Romania - New doses starts with -289,998 
This breaks the graph a bit to show negative values. From what I see Romania does not have a start date with 0 doses/vaccinations.

**Comment by edomt** [comment]
Hi @Sergiu-Marginean 

Can you let me know exactly where you're seeing this? I'm not seeing this in https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv

**Comment by Sergiu-Marginean** [comment]
Hello @edomt ,
Here is a screenshot from the website: 
![image](https://user-images.githubusercontent.com/8039457/110699844-f60ec380-81f7-11eb-958b-7808929cc391.png)

From what I see on the website, on the 2020-12-28 - it shows 2066 new doses with a total of 2066 (ignoring the 965 from 2020-12-27).
In the csv the data appears correct with new doses for 2020-12-28 being 1101.

**Comment by edomt** [comment]
@Sergiu-Marginean That's not our website 🙂
