### ISSUE TITLE
Canada testing data stuck at January 31, 2021

### ISSUE THREAD

**Issue by craigthusiast** [owid/covid-19-data#630]
Hello OWID team,

Thanks for your ongoing efforts to help everyone stay well informed! 

On January 31, 2021, the data source you're using to collect testing data for Canada changed the way they report daily tests. On that day, they stopped populating the Daily Tests column (column J - numtested) and instead began incrementing the Total Tests column (column K - numtests) on a daily basis. I believe you need to switch your collection method to calculate and save the daily tests value by way of the daily change in the Total Tests (numtests) value rather than continuing to use the now-empty Daily Tests (numtested) column. 

[https://health-infobase.canada.ca/src/data/covidLive/covid19-download.csv](url)

I'm using the Canada testing data to report on Daily Tests vs. Daily Cases as well as Daily Deaths vs. Daily % Positivity. Both are very important comparisons. 

[https://c19charts.com/charts/country/CAN](url)

I'm hoping you can make this change because, if not, the Canada testing data on OWID will no longer be updated beyond January 31, 2021. 

Thank you! 

Craig

**Comment by edomt** [comment]
Hi @craigthusiast 

It just so happens that we've done this today (43cac720c73b5e341e47f3f914e02541f451e2e5)

Thanks for letting us know!

**Comment by craigthusiast** [comment]
Hi Edouard, thanks so much for your very prompt action on this! However, there's an issue with your update. If you look at the two columns I mentioned in the data source, they "switched" FROM using the column J - "numtested" TO using column K - "numtests" as of January 31st. So prior to that date, column K is nil. 

Unfortunately, they're not making it easy on you/us. To calculate the OWID "new_tests" column, you'll have to use the "numtested" column J up until January 31st and then use column K after January 31st. 

I just had a look and currently in the OWID dataset, the testing data for Canada only exists back until February 1st 2021 since it's being sourced only from Column K in the source dataset.

**Comment by edomt** [comment]
Hi @craigthusiast 

Yes, this change was deliberate — we never mix different units in our testing data. Given that the official units is now `numtests`, we can only show data starting in February 2021. Note that if you need both time series, they're available in our complete testing dataset here: https://github.com/owid/covid-19-data/blob/master/public/data/testing/covid-testing-all-observations.csv
