### ISSUE TITLE
Error when importing .csv into Excel 

### ISSUE THREAD

**Issue by jarnold231** [owid/covid-19-data#64]
When I add the .csv as a data source in MS Excel I get an error:

"[Expression.Error] The column 'male_smokers' of the table wasn't found"

**Comment by edomt** [comment]
Hi @jarnold231 

We cannot reproduce this issue, the file opens correctly on our end. Please note that we have [this xlsx version](https://covid.ourworldindata.org/data/owid-covid-data.xlsx), which might work better if you intend to open it directly in MS Excel.

Best,
Edouard

**Comment by jarnold231** [comment]
Thanks for the response. I managed to resolve this issue by adjusting the content types on each column. Not sure why some were correctly importing and others were not.
