### ISSUE TITLE
Uruguay vaccination monitor accessible to the world (not an issue)

### ISSUE THREAD

**Issue by 3dgiordano** [owid/covid-19-data#653]
This not is an issue. It's an informative message for @edomt 

Uruguay has made its portal public to the world to consume his vaccination information.
There is no official report, just from one moment to another the entire portal changed and the new one is public (available from outside of UY)

https://monitor.uruguaysevacuna.gub.uy/

@edomt you can continue consuming my spreadsheet that is updated almost in real time with the official data (the one consumed from batch for Uruguay)

I am migrating what I had about OCR for the new portal to keep the spreadsheet automatically updated.
As soon as I have a python source code that may be useful I will share it with you.

I will continue to keep the information updated for OWID using that spreadsheet.
My idea es to bring at future an alternative option to my worksheet (possibly a GitHub repository where there will be more information related to vaccination data in csv format, and the source code related how to extract the data from the source).

I do not know if the portal will be private again in Uruguay in the near future.
We have to be careful, I think that it is still safer to consume from my spreadsheet until we know what will happen with the new portal.

Now you will have a portal to corroborate the data, while it remains public to the world.

Regards
David

**Comment by 3dgiordano** [comment]
Unfortunately the portal is not stable, and the information that is published may at times be incorrect or inaccessible.
It is not a good source for an automatic reading process.

Using my spreadsheet is still valid, the update and data verification process that I follow does not allow erroneous data to be published to OWID.

**Comment by edomt** [comment]
Hi @3dgiordano 

Thank you for this update — for now we'll indeed keep using your spreadsheet to simply the data collection process on our side. Many thanks for doing this!
