### ISSUE TITLE
Negative Cases and Deaths

### ISSUE THREAD

**Issue by nigelc00l** [owid/covid-19-data#66]
I noticed that some of the data consists of negative values for cases or deaths. For example GBR United Kingdom 2020-05-21

How is this interpreted?

Thanks!

**Comment by edomt** [comment]
Hi @nigelc00l 

Negative values in cases and deaths can sometimes appear when a country sends a correction to the ECDC, because it has overestimated the number of cases/deaths. For the UK, those –525 cases on 21st May are therefore people that had been misclassified (or maybe counted twice) as COVID-19 cases.

Edouard

**Comment by HebeHH** [comment]
Is this also the case for Spain's new deaths data for May 25? It just looks very weird.

![image](https://user-images.githubusercontent.com/15617243/90168915-670c0b00-ddd0-11ea-9a6a-258673449820.png)

**Comment by edomt** [comment]
Hi @HebeHH 
Yes, that's also the same issue (see https://github.com/owid/covid-19-data/issues/84). Unfortunately we don't have enough information (such as the exact days on which too many deaths were counted) to correct past values, so our only solution is to keep the ECDC's –1918 value for that day.
Edouard

**Comment by ospinag** [comment]
great, thanks!

**Comment by George6328** [comment]
Why is it the 'total cases and total deaths' do not change with respect to collection date, but the 'total tests' do change?

**Comment by edomt** [comment]
@George6328 This is because the source and collection methods are completely different for cases/deaths and tests.

**Confirmed cases and deaths**: our data comes from the European Centre for Disease Prevention and Control (ECDC). The number of cases or deaths reported by any institution—including the ECDC, the WHO, Johns Hopkins and others—on a given day does not necessarily represent the actual number on that date.

**Tests**: we aggregate testing data ourselves by collecting it directly from national governments and health authorities. This allows us to adjust the full time series if it is published by the source.

**Comment by sjshamji** [comment]
Thanks for the data, it's awesome. I noticed a few other negative values. Not sure if this helps but in case it does, here they are:

<img width="346" alt="Screen Shot 2020-11-04 at 3 36 13 PM" src="https://user-images.githubusercontent.com/60599525/98179391-7ec8cc00-1eb3-11eb-9d29-7187b2973073.png">

**Comment by George6328** [comment]
Thank you for the data.  I am comparing the ECDC and GitHub data on total deaths and confirmed cases vs daily and weekly intervals as well as the US CDC weekly data.  One data set that is missing from JHU, ECDC, and GitHub is the age group death rate vs time.  Only the CDC publishes this dataset.  I find it disingenuous the media amplifying the total cases while the death rate has flattened.  Additionally, the 65+ age group has become the dominant COVID-19 death sentence (especially with preexisting maladies).  Can you provide me with any other datasets with respect to COVID-19 and age similar to the CDC?

George Gasparian
Sales/Applications Engineer​
GPD Optoelectronics Corp
7 Manor Parkway | Salem, NH | 03079

Visit us at booth no. at SPIE BIOS on 6-7 March 2021 at the Moscone Center, San Francisco, CA.
Visit us at booth no. at SPIE Photonics West on 9-11 March 2021 at Moscone Center, San Francisco, CA.
________________________________

**Comment by edomt** [comment]
Hi @George6328 
It's almost impossible to calculate a perfectly reliable 'death rate' at the moment, for many reasons but particularly the following ones:

* If by 'death rate' you mean case-fatality rate (CFR), i.e. deaths / cases, then this is entirely dependent on testing, and you won't be able to compare the successive waves of infections, as the share of cases captured by testing has become completely different over time (cases were very largely underestimated in March/April).

* If by 'death rate' you mean infection-fatality rate (IFR), i.e. deaths / infections, then you'd need to know the true number of infections, which is of course very hard to do. Your best bet might be to try to use total estimated infections provided by several modeling teams, which we gather here: https://ourworldindata.org/grapher/daily-new-estimated-infections-of-covid-19?tab=chart&stackMode=absolute&time=earliest..latest&country=~USA&region=World

I don't know of many datasets that provide age-specific data as we don't aggregate this data on OWID, but off the top of my head I can think of the French dataset here: https://www.data.gouv.fr/fr/datasets/r/08c18e08-6780-452d-9b8c-ae244ad529b3 (`reg` is the area number, you can sum them all up for a given day to get the national count, and `cl_age90` is the age group with `0` as the sum of all age groups).

**Comment by George6328** [comment]
Dear Edouard,
Thank you very much for your information.  I will review the French data.
Sincerely,
George

George Gasparian
Sales/Applications Engineer​
GPD Optoelectronics Corp
7 Manor Parkway | Salem, NH | 03079

Visit us at booth no. at SPIE BIOS on 6-7 March 2021 at the Moscone Center, San Francisco, CA.
Visit us at booth no. at SPIE Photonics West on 9-11 March 2021 at Moscone Center, San Francisco, CA.
________________________________
