### ISSUE TITLE
Vaccination data of Uruguay outdated

### ISSUE THREAD

**Issue by 3dgiordano** [owid/covid-19-data#661]
Hello, I previously contributed a batch to keep the Uruguay data up to date.

https://github.com/owid/covid-19-data/pull/632

However, I have not seen your updated data.

Something is missing?

Can I help with something?

**Comment by edomt** [comment]
Hi @3dgiordano 

Yep, sorry about that, I forgot to turn on the automated version for Uruguay. It's done now, we'll run a manual update.
