### ISSUE TITLE
Standardized country names

### ISSUE THREAD

**Issue by kurval** [owid/covid-19-data#67]
Hi, I noticed that you have standardized country (refering Data alterations) names but column names differs from those names for example in new_cases.csv. It would be really helpful if all the names including column names are standardized.

**Comment by edomt** [comment]
Hi @kurval 

Have you had a look at our [complete dataset](https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv)? All country names are standardized in it, with a 3-letter ISO code as well.

Best,
Edouard

**Comment by kurval** [comment]
Hi! That is exactly what I need. Thanks @edomt 

br,
Valtteri
