### ISSUE TITLE
Azerbaijan Vaccine data March 10 and 11

### ISSUE THREAD

**Issue by TheRalacator** [owid/covid-19-data#685]
Azerbaijani Vaccination Numbers for March 10 and 11 have been added as a pull request, processing needed.

**Comment by edomt** [comment]
Hi @TheRalacator 

- There's currently no PR created for this data: https://github.com/owid/covid-19-data/pulls. Are you sure you've created it correctly?
- I automatically get an email when someone creates a PR, so you don't need to also create an issue each time :)
