### ISSUE TITLE
Philippines data error

### ISSUE THREAD

**Issue by lawgimenez** [owid/covid-19-data#686]
Based here: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Philippines.csv

On row 4, the link came from the Singapore government with the link: https://www.moh.gov.sg/news-highlights/details/covid-19-vaccination-brought-forward-for-all-seniors-extended-to-essential-services-personnel-and-higher-risk-groups

**Comment by edomt** [comment]
Thanks for spotting this! Will be fixed today.
