### ISSUE TITLE
Maintain selected countries across graphs

### ISSUE THREAD

**Issue by agur** [owid/covid-19-data#7]
#### Feature: ####

Suggest to implement the following:

- [ ]  1. The set of Countries selected is kept across all graphs.
  - This is the default.
- [ ] 2.  Allow a mode to split - to allow the user to  one wants to split it back to One way to
  - Disabled by default.
  - Consider if to implement and when.  (less useful and less important than no. 1)

#### Implementation: ####

Could be storing states on cookies, or url redirects/parameters

**Comment by edomt** [comment]
Hi @agur 

We have a partial way to do that already: when accessing one of our graphs, you can add the `?country=X+Y+Z` URL parameter to pre-select the countries shown on the graph. For example: https://ourworldindata.org/grapher/full-list-cumulative-total-tests-per-thousand?country=AUS+FRA+ITA

(I'll close this issue, as this repo is dedicated solely to our work on COVID-19. If you want to make a suggestion or pull request for our grapher, the GitHub repo is at https://github.com/owid/owid-grapher.)

Edouard
