### ISSUE TITLE
nan ISO codes

### ISSUE THREAD

**Issue by szelesaron** [owid/covid-19-data#702]
Hi all,

The ISO codes for Wales, England Northern Ireland and Scotland are all nan.
Can this be solved?

**Comment by lucasrodes** [comment]
Hi @szelesaron,
Do you refer to file [vaccinations.csv](../blob/master/public/data/vaccinations/vaccinations.csv)?

If so, thing is, field `iso_code` refers to [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) standard, which defines three-letter country codes. However, in the case of Wales, England, Northern Ireland, and Scotland they don't  have such code but have [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2:GB) instead.

We could however add "custom codes" , as proposed in https://github.com/owid/covid-19-data/issues/500#issuecomment-782757052

**Comment by szelesaron** [comment]
Hi @lucasrodes ,

Yes, I refer to vaccinations.csv.

I support having custom codes as in #550

**Comment by edomt** [comment]
I've now added custom ISO codes for UK nations: `OWID_ENG`, `OWID_NIR`, `OWID_SCT`, `OWID_WLS`.
