### ISSUE TITLE
Issue in File name : Special Character present in File Name

### ISSUE THREAD

**Issue by GDGauravDutta** [owid/covid-19-data#708]
I was trying to work on this data in kaggle, unable to work in it. Issue lies in  using a file name as '

**Comment by edomt** [comment]
Hi @GDGauravDutta 

I don't think anyone has ever encountered this issue before - can you be a little more specific on which file is causing the issue, and what you're doing exactly when the error occurs?

**Comment by GDGauravDutta** [comment]
Oh no! Upload failed
Unfortunately we could not create your dataset.
File name contains invalid character ('): Cote d'Ivoire.csv

**Comment by edomt** [comment]
I don't know how upload on Kaggle work, but can't you simply not upload this file? It comes from the `country_data` folder, which includes individual country-level files, so presumably not the most practical for analysis. Everything that's in the `country_data` folder can be found in `[vaccinations.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv)`
