### ISSUE TITLE
Non-existent daily new cases spike in Russia

### ISSUE THREAD

**Issue by Sadler2** [owid/covid-19-data#71]
Your graphs and data has "2020-06-02,Russia,17898,344,423741,5037" whereas [the official data](https://xn--80aesfpebagmfblc0a.xn--p1ai/ai/html/3/attach/2020-06-02_coronavirus_government_report_v2.pdf) is "+8863 new cases, +182 deaths" , and we never ever had daily numbers around 18k. It already lead to a huge spike on daily new and deaths graph, please fix it.

**Comment by edomt** [comment]
Hi @Sadler2 

There is unfortunately not much we can do to fix this. We source our data directly from the European Centre for Disease Prevention and Control, and report it without making alterations to its original cases and death figures.

We asked the ECDC to double-check Russia’s data for today, and they confirmed that the government had reported a total 423,741 cases. They added that it might be possible that their website had not been updated yesterday at the time of the ECDC's data collection, and they thus would have more cases than usual for 1 day.

Edouard
