### ISSUE TITLE
Re: US Vaccination Data/Spreadsheet

### ISSUE THREAD

**Issue by JustaNormalGuy230** [owid/covid-19-data#719]
(Request, not an Issue, sorry.  Also, I cannot set the label(s) on my end, so please do that, thanks!)
Would it be possible to differentiate between Date of Reporting and Date of Record in the Spreadsheets, by introducing a Date of Record Column?  I realize that (for the most part), it's a subtraction of 1 day (in the US Case), but it would clear up a lot of issues with the US CDC way of reporting vaccinations.  Also, many of us use Centered, 7-Day Moving Averages to determine peak positions in the data.  AFAIK, the US Spreadsheet is a rolling, 7-Day Average, which results in a 3-Day shift of the data/peaks... (Side Note: in Data Packages like Statistical "R" Programming Language, this routine is in the "filter" section versus the rolling average routine section, if I recall correctly.)

I'm not sure that I am addressing the right party or parties that can make these type of modifications/additions, so please excuse my request if so!

Thanks for providing your services, by the way!

**Comment by edomt** [comment]
Hi @JustaNormalGuy230 

Unfortunately for most countries, we don't really know whether the date shown is the date of report, or the date of vaccination:
* Some countries report by date of report only
* Some countries report by date of vaccination, with retrospective corrections for past days at each update

Our smoothed time series are indeed all right-aligned 7-day rolling averages — so the value for March 23 is the average of the 7 values from March 17 to March 23.
