### ISSUE TITLE
Wrong label for hospital beds

### ISSUE THREAD

**Issue by Hax2kon** [owid/covid-19-data#72]
Hi,

The codebook and column name on the number of hospital beds ("hospital_beds_per_100k") indicate that this is beds per 100 000 population. Looking at the numbers, I believe this is the number per 1 000 population.

Here is the OWID source for hospital beds: https://docs.google.com/spreadsheets/d/1nSDwFWmnqvcP5Ut_epcntxjZrR8PcnU6enupT8G5d0s/edit#gid=0

To take an example, Israel have 299 beds per 100 000 in this sheet.
In the COVID-dataset the number is 2.99.

**Comment by edomt** [comment]
Hi @Hax2kon 

You're right! This was indeed a mistake on our end. We've just fixed it now.
Thanks for flagging it.

Best,
Edouard
