### ISSUE TITLE
Data quality

### ISSUE THREAD

**Issue by digimen-ch** [owid/covid-19-data#73]
Does someone has contact to the European Centre for Disease Prevention and Control? It looks like the data quality is not that good. For example:

Spain: -372 new cases at 2020-05-25 but nothing like this to find on the official numbers here: https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_126_COVID-19.pdf

Sweden: 2214 new cases at 2020-06-04 but on the official page they report only 194 (!!!) see: https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa

Or do I get something wrong about the numbers?

**Comment by edomt** [comment]
Hi @digimen-ch,

* On the case of Sweden and more generally the way the ECDC reports data, see https://github.com/owid/covid-19-data/issues/58#issuecomment-631738301 for a detailed explanation;
* Regarding negative cases, see https://github.com/owid/covid-19-data/issues/66#issuecomment-635933530.

Best,
Edouard
