### ISSUE TITLE
Israel % of vaccinated people

### ISSUE THREAD

**Issue by sapomnia** [owid/covid-19-data#730]
Hi there!
In thanking you once again for this great work, I'm opening this issue because in the last few days the percentage of people vaccinate in Israel has ben higher than 100%. I was wondering if you might know why this is happening.
Thnaks, regards

**Comment by edomt** [comment]
In our entry dedicated to COVID-19 vaccinations, we display different metrics:

1/ The number of COVID-19 vaccination doses that have been administered
This is the total number of doses administered. This is counted as a single dose, and may not equal the total number of people vaccinated, depending on the specific dose regime (e.g. people receive multiple doses). If a person receives one dose of the vaccine, this metric goes up by 1. If they receive a second dose, it goes up by 1 again.

2/ The number of people who received at least one dose of COVID-19 vaccine
This is the total number of people who received at least one vaccine dose. If a person receives the first dose of a 2-dose vaccine, this metric goes up by 1. If they receive the second dose, the metric stays the same.
This data is only available for countries which report the breakdown of doses administered by first and second doses.

3/ The number of people fully vaccinated against COVID-19
This is the total number of people who received all doses prescribed by the vaccination protocol. If a person receives the first dose of a 2-dose vaccine, this metric stays the same. If they receive the second dose, the metric goes up by 1.
This data is only available for countries which report the breakdown of doses administered by first and second doses.
