### ISSUE TITLE
data request

### ISSUE THREAD

**Issue by hadihonarvar** [owid/covid-19-data#74]
Is it possible to provide, number of tests, total active, new active, total recovered and new recovered?

**Comment by edomt** [comment]
Hi @hadihonarvar 

* Data on tests is already available, see https://github.com/owid/covid-19-data/tree/master/public/data/
* For active and recovered cases, see https://github.com/owid/covid-19-data/issues/2

Edouard

**Comment by hadihonarvar** [comment]
Yes but would you please provide it in .json. CSV is way expensive. Thanks,
