### ISSUE TITLE
Adding an external ID for named entities

### ISSUE THREAD

**Issue by metasj** [owid/covid-19-data#76]
It's great to see the sheet of [standard entity names](https://github.com/owid/covid-19-data/blob/master/public/data/ecdc/locations.csv).  

Please consider adding a column for the Wikidata QID where one exists.  This may make it slightly easier for people to connect your entities to their localizations + other extended properties.

**Comment by edomt** [comment]
Hi @metasj 

I don't really know anything about Wikidata QIDs—we already have 3-letter ISO codes in the complete dataset, does the QID add anything more precise to that?

Thanks,
Ed

**Comment by metasj** [comment]
If you search for any of these terms on Wikidata, you'll find an entry for it, with a QID and a name translated into many languages.  It will include the ISO 3166-1 3-letter code as a property, where one exists [e.g., for everything but https://www.wikidata.org/wiki/Q1208722 (Diamond Princess) ], but also gives one a path into the web of linked open data around that topic.

Not more precise than the ISO code, just convenient in a different way.
