### ISSUE TITLE
Wrong reading data

### ISSUE THREAD

**Issue by caslan34** [owid/covid-19-data#763]
if you check this JSON code, it has a problem. Location, date and vaccine are ok, but source_url, total_vaccinations ... are not ok.
Can you check this?  I think name of vaccine includes comma (,). 

`{"location":"Montenegro","date":"2021-03-19","vaccine":"\"Sinopharm/Beijing","source_url":" Sputnik V\"","total_vaccinations":"https://www.covidodgovor.me/","people_vaccinated":"6849","people_fully_vaccinated":"6517"} `

**Comment by edomt** [comment]
Hi @caslan34 

Where does that come from? The only JSON file we make available is https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.json, and it doesn't include things like `source_url` or `vaccine`

**Comment by caslan34** [comment]
Hi @edomt 

`https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/country_data/montenegro.csv`

when I request from this adress, and program creates `datacsv[datacsv.length-2]`.

**Comment by edomt** [comment]
As you can see in the file here, there is nothing wrong with the current format: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Montenegro.csv

I don't know what program or language you are using to import this data, but there must be something wrong on your side.
