### ISSUE TITLE
Adding other countries for testing

### ISSUE THREAD

**Issue by metasj** [owid/covid-19-data#77]
Of the ~80 countries for which there's not currently any [testing data
](https://ourworldindata.org/coronavirus-testing#other-countries), some now have official COVID-19 sites that report tests as well as cases, though not always machine-readable.  I know some off-hand (GU, VI).  In some cases (LB), the Wikipedia article includes an external link to a suitable government site.

Is there interest in revisiting + including those countries?  It would make a fine afternoon task for a crowd.

**Comment by edomt** [comment]
Hi @metasj 

We are actually in the process of reviewing those countries (and we'll do so around once a month) to check which one have started publishing testing data. So you should start to see new countries included in the dataset very soon.

Best,
Edouard
