### ISSUE TITLE
Date Innacuracy with Colombian Data

### ISSUE THREAD

**Issue by juanpisuribe13** [owid/covid-19-data#772]
March 19th (automated) data was reported as March 20th data on automations/output.
![image](https://user-images.githubusercontent.com/57115669/111932272-1574de80-8a8b-11eb-9791-771afa6ed53d.png)
![image](https://user-images.githubusercontent.com/57115669/111932274-160d7500-8a8b-11eb-9393-26246ed34646.png)

I assume it's because the script while calculating the date subtracts one day instead of two days and the person who's running it is two days ahead of the latest data available, not sure about it.

I could make a pull request and fix this, but as I said I am not sure about it which is why I'm submitting an issue instead.

**Comment by edomt** [comment]
Thanks @juanpisuribe13, this has now been fixed in 87d3e3539759f347c705d7e08c0380d1274114c0

I'm indeed running the script in the morning (European time), so the date needs to be set to D–2.
