### ISSUE TITLE
Excess deaths versus confirmed deaths

### ISSUE THREAD

**Issue by LaurenDM** [owid/covid-19-data#79]
All countries use a different way of counting covid-19 deaths. This data is inaccurate. You should be looking at excess deaths, as was done by the NY times: https://www.nytimes.com/interactive/2020/04/21/world/coronavirus-missing-deaths.html

**Comment by edomt** [comment]
Hi @LaurenDM 

We have been looking into this, and will try our best to add excess mortality to the data we provide. This is however not a trivial effort, especially for OWID's small team, as there isn't a single place where data can be collected easily for all countries.

We'll update this GitHub issue if/when we manage to make progress on this enhancement.

Best,
Ed

**Comment by edomt** [comment]
On 14 October 2020, we added data on excess mortality during the pandemic in the `excess_mortality` folder, sourced from the Human Mortality Database and the UK Office for National Statistics: https://github.com/owid/covid-19-data/tree/master/public/data/excess_mortality
