### ISSUE TITLE
MEX Data are broken

### ISSUE THREAD

**Issue by Felarof23** [owid/covid-19-data#80]
Hello, first let me congratulate you, this is a great job!!

The CSV data in MEX corresponding to June 16, 17, 18, and 19 is divided into two lines in the date column, just before the day, this csv cause is broken. 

Again, thank you very much for your effort.

**Comment by edomt** [comment]
Hi @Felarof23,

I'm unable to reproduce the issue—the file looks fine on my end.

<img width="1004" alt="Capture d’écran 2020-06-20 à 10 24 35" src="https://user-images.githubusercontent.com/7103774/85197274-3df36080-b2e0-11ea-8ed2-9bdae6b91193.png">

Could you maybe check that everything has been downloaded and imported correctly by the software you're using?

Edouard
