### ISSUE TITLE
Australia people_vaccinated_per_hundred

### ISSUE THREAD

**Issue by Nishan-Pradhan** [owid/covid-19-data#800]
Hi, it looks like Australia people_vaccinated_per_hundred has stopped updating the last few days. Is this an error?

**Comment by edomt** [comment]
Hi @Nishan-Pradhan 

No, that's our the data is made available directly by our source (https://covidlive.com.au/vaccinations)
My understanding is that the Australia government has (temporarily) stopped reporting the breakdown of 1st and 2nd doses.
See here: https://twitter.com/migga/status/1376447945034194945
