### ISSUE TITLE
[Feature Req] Vaccinations: Daily people fully vaccinated (7-day smoothed)

### ISSUE THREAD

**Issue by CovidMexico** [owid/covid-19-data#806]
Could you add a new column for daily people fully vaccinated (7-day smoothed)? 

Thanks

**Comment by edomt** [comment]
Hi @covidmexico

We won't be adding this in the near future — you can obtain it by taking the difference between `people_fully_vaccinated` and its value on the previous day, and applying a 7-day average to it.

In Python for example: `(df.people_fully_vaccinated - df.people_fully_vaccinated.shift(1)).rolling(7).mean()`
