### ISSUE TITLE
Spain very strange DEATH DATA

### ISSUE THREAD

**Issue by rfreitasbatista** [owid/covid-19-data#81]
Hi, we think that there is something very strange about Spain deaths last data. It's saying they've had  more than one thousand deaths.

**Comment by rfreitasbatista** [comment]
![image](https://user-images.githubusercontent.com/64554771/85213888-a838ef00-b33a-11ea-80d2-b69be996c12d.png)

**Comment by edomt** [comment]
Hi @rfreitasbatista 

This is indeed what was reported by the Spanish government: https://www.aa.com.tr/en/europe/spain-updates-covid-19-death-toll-to-28-315-/1883268

> Spain’s Health Ministry confirmed 1,179 more COVID-19 deaths on Friday, bringing the country’s total death toll to 28,315. The surge of deaths comes after the total death toll had been frozen for weeks at around 27,130. The death toll includes only those who tested positive for the disease before passing away.

Best,
Edouard

**Comment by rfreitasbatista** [comment]
Great Edouard, but there is still a big difference between the total deaths from the site you informed above and the total deaths I printed to you. We totally loved your api, and we re using it in a project to better inform people in Brazil. This little difference could put the whole information on check.

**Comment by edomt** [comment]
@rfreitasbatista This was caused by a temporary issue in the file published by the ECDC. It has now been fixed, both in their file and subsequently in our data.

**Comment by rfreitasbatista** [comment]
Great Edouard, thank you so much for the attention.
