### ISSUE TITLE
Costa Rica data - death report for June 20, 2020 is incorrect (typo?)

### ISSUE THREAD

**Issue by csantosumich** [owid/covid-19-data#82]
I noticed that Costa Rica has remained at 12 deaths and today they jumped to 112.  This appears incorrect, perhaps a typo in the data sheet.  To date, they have one of the best controlled case/death rates in the Americas, with no reporting changes that I'm aware of, making this sudden 100 patient spike suspicious.  Please confirm?

**Comment by csantosumich** [comment]
<img width="870" alt="image" src="https://user-images.githubusercontent.com/4358499/85215399-a6245f80-b33d-11ea-92ca-e4ff75863b18.png">

**Comment by csantosumich** [comment]
https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

No new deaths reported in the ECDC June 20, 2020 sheet...

**Comment by csantosumich** [comment]
Also, THANK YOU for this incredible resource you and your team put together.  We refer to it daily for some of our comparative analytics here in the USA.  Keep up the great work!

**Comment by edomt** [comment]
Hi @csantosumich 

This figure of 100 deaths was present in the file when we imported it yesterday. See row 5203 in this version, archived on our repo: https://github.com/owid/covid-19-data/blob/master/scripts/input/ecdc/releases/2020-06-20.xlsx

You're right however that the ECDC file no longer shows this figure—they probably corrected it yesterday after our update.
This will be fixed when we import the new file today.

Best,
Edouard
