### ISSUE TITLE
Error in Poland data

### ISSUE THREAD

**Issue by mbronkowski** [owid/covid-19-data#829]
Hello i think that poland data is missinterpretated. Polish country posts 3 factors. Total, 1st dose, 2nd dose.
The 1st dose is interpretated as "at least first dose" ind poland.csv file but shoub be interpretated as "only first dose". "At least first dose i actually in the total column. The blue number in the below screenshot.
![Screenshot_2021-03-27-07-07-10-923_com android chrome](https://user-images.githubusercontent.com/2589187/112712011-e9af8980-8ecc-11eb-90b4-050266d00b91.jpg)

**Comment by edomt** [comment]
Hi @mbronkowski 

Do you have any alternative source, or media article, that would confirm this?
`Liczba wykonanych szczepień` seems to translate to `Number of vaccinations performed`, which would mean we're counting this correctly; and no one else has reported this problem even though we've been collecting this data like this for 2 months.

**Comment by mbronkowski** [comment]
Sorry you are right i misinterprted the data. Most of the polish media
report only total number and i asumed it is a total of vactianted people
when in fact this is a total of vactinations. Sory for confusion.

sob., 27 mar 2021, 12:18 użytkownik Edouard Mathieu <
***@***.***> napisał:
