### ISSUE TITLE
Last update date for each country

### ISSUE THREAD

**Issue by Sangdol** [owid/covid-19-data#83]
Hello, 

Thanks for the great dataset.

I'm wondering if there's a way to know the last updated date for each country.

I noticed that some rows are added without new information. For example, when I checked out the data of Sweden today(June 21st) it says that the `new_cases` are 0 for today and yesterday and I believe it must be null not 0.

It'd be nice if
1. there's someplace where I can find the last update date for each country or
2. it doesn't add a new row without data or
3. it says null or something other than 0 for no data

so that I can know what is the trustable latest data.

Thanks.

**Comment by edomt** [comment]
Hello @Sangdol,

Thank you for using our dataset :)

You're right that those two 0s for Sweden are probably temporary values. However, they come directly from the raw data provided by the European CDC—see their June 21st spreadsheet for example: https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-2020-06-21.xlsx

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/7103774/85258174-4d50e600-b467-11ea-8ec6-b0976b304c5d.png">

So there is unfortunately not much we can do to fix this. We source our data directly from them, and report it without making alterations to their original cases and death figures.

You could probably implement a system to reject new data points based on the previous days' trend? (For example if the new data point is below X% of the 7-day rolling average, then you remove it.)

Edouard

**Comment by Sangdol** [comment]
Thanks for the quick answer, Edouard.

> So there is unfortunately not much we can do to fix this. We source our data directly from them, and report it without making alterations to their original cases and death figures.

This is actually what I assumed and thanks for the clarification.

> You could probably implement a system to reject new data points based on the previous days' trend? (For example if the new data point is below X% of the 7-day rolling average, then you remove it.)

Thanks for the suggestion. This is exactly what I thought in case there's no way to handle the empty data on your side.

I'll close the ticket.

Have a nice day.

Sang
