### ISSUE TITLE
UK Test Data

### ISSUE THREAD

**Issue by selsamman** [owid/covid-19-data#85]
I see that you are reporting significantly less tests than other sources (like worldometer) for the UK.  Looking at the date 6-19-20 for GBR in testing/covid-testing-all-observations.csv I see you have a cumulative total of 4,243,159 and reference this source:

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/893815/2020-06-20_COVID-19_UK_testing_time_series.csv which has this data:

Entity | ISO code | Date | Source URL | Source label | Notes | Cumulative total
19/06/2020 | 20/06/2020 | England | Pillar 1 | 34530 | 1,955,264
19/06/2020 | 20/06/2020 | Northern Ireland | Pillar 1 | 1448 | 91,555
19/06/2020 | 20/06/2020 | Scotland | Pillar 1 | 3695 | 239,749
19/06/2020 | 20/06/2020 | Wales | Pillar 1 & 2 | 967 | 147,881
19/06/2020 | 20/06/2020 | UK | Pillar 1 (plus Pillar 2 for Wales) | 40640 | 2,434,449
19/06/2020 | 20/06/2020 | UK | Pillar 2 (excluding Wales) | 92992 | 4,057,940
19/06/2020 | 20/06/2020 | UK | Pillar 3 | 41155 | 764,585
19/06/2020 | 20/06/2020 | UK | Pillar 4 | 55763 | 457,227

It would seem to me that you would add  UK - Pillar 1 (plus Pillar 2 for Wales) (2,434,449) and 
UK - Pillar 2 (excluding Wales) (4,057,940) for a total of 6,492,389 cumulative tests.  Then on top of that one would add the cumulative total for people tests which is 2,144,626 which would be closer to the 8M tests Worldometer is reporting.

**Comment by edomt** [comment]
Hi @selsamman 

Our method for the United Kingdom is more complex than for most other countries. It is documented here: https://ourworldindata.org/coronavirus-testing#united-kingdom

In our time series for “tests performed”, we aggregate the data for the United Kingdom based only on two “pillars”:

– Pillar 1: swab testing in Public Health England (PHE) labs and NHS hospitals for those with a clinical need, and health and care workers;
– Pillar 2: swab testing for the wider population, as set out in government guidance. **For this pillar, we only include “in-person tests”, i.e. tests that have not only been mailed out, but also returned and processed.** <- this is where an important number of tests aren't taken into account in our time series.

In your example of 19/06/2020, we add up 2,434,449 for pillar 1 and 1,808,710 for pillar 2 (`Cumulative In-person (tests processed)`), which results in 4,243,159 tests performed.

Sites such as Worldometer are data aggregators that tend to report the total number without looking into nuances such as tests performed vs. mailed, or PCR tests vs. serology tests, etc.

Edouard
