### ISSUE TITLE
Separation of static and dynamic data in json format to reduce the size of file

### ISSUE THREAD

**Issue by behnsen** [owid/covid-19-data#86]
I would like to suggest to seperate static and dynamic data in the .json format to reduce the amount of data. I will provide an example:

```json
{
            "continent": "Asia",                 --> static
            "location": "Afghanistan",       --> static
            "date": "2019-12-31",
            "total_cases": 0.0,           
            "new_cases": 0.0,
            "total_deaths": 0.0,
            "new_deaths": 0.0,
            "total_cases_per_million": 0.0,
            "new_cases_per_million": 0.0,
            "total_deaths_per_million": 0.0,
            "new_deaths_per_million": 0.0,
            "population": 38928341.0,       --> static?
            "population_density": 54.422, --> static?
            "median_age": 18.6,               --> static?
            "aged_65_older": 2.581,        --> static?
            "aged_70_older": 1.337,        --> static?
            "gdp_per_capita": 1803.987,  --> static?
            "cvd_death_rate": 597.029,     --> static?
            "diabetes_prevalence": 9.59,     --> static?
            "handwashing_facilities": 37.746,   --> static?
            "hospital_beds_per_thousand": 0.5,  --> static?
            "life_expectancy": 64.83    --> static
}
```

For example, the static fields 

```json
"continent": "Asia",  
"location": "Afghanistan",    
"population": 38928341.0,
"population_density": 54.422,
"median_age": 18.6,        
"aged_65_older": 2.581,     
"aged_70_older": 1.337, 
"gdp_per_capita": 1803.987,  
"cvd_death_rate": 597.029,
"diabetes_prevalence": 9.59,
"handwashing_facilities": 37.746,
"hospital_beds_per_thousand": 0.5,
"life_expectancy": 64.83
```
take ~400 bytes space on disk. This data is repeated for each day as I could see. 
`400kB * 165 days ~ 66000 bytes ~ 66 kB per country`
`66kB * 200 countries ~ 13 MB space on disk per file`. 

I we take into account that not each country has data since 2019 there can saved ~ 10 MB per file. 

My suggestion is a format like
```json
AFG: {
     "continent": "Asia",  
     "location": "Afghanistan",    
     "population": 38928341.0,
     "population_density": 54.422,
     "median_age": 18.6,        
     "aged_65_older": 2.581,     
     "aged_70_older": 1.337, 
     "gdp_per_capita": 1803.987,  
     "cvd_death_rate": 597.029,
     "diabetes_prevalence": 9.59,
     "handwashing_facilities": 37.746,
     "hospital_beds_per_thousand": 0.5,
     "life_expectancy": 64.83,
     "data": [
         {
            "date": "2019-12-31",
            "total_cases": 0.0,
            "new_cases": 0.0,
            "total_deaths": 0.0,
            "new_deaths": 0.0,
            "total_cases_per_million": 0.0,
            "new_cases_per_million": 0.0,
            "total_deaths_per_million": 0.0,
            "new_deaths_per_million": 0.0
         },
         {
            "date": "2020-01-01",
            "total_cases": 0.0,
            "new_cases": 0.0,
            "total_deaths": 0.0,
            "new_deaths": 0.0,
            "total_cases_per_million": 0.0,
            "new_cases_per_million": 0.0,
            "total_deaths_per_million": 0.0,
            "new_deaths_per_million": 0.0
         },
         ...
      ]
}
```

But maybe I miss some reason, why it is solved like yet. I'm open for discussions :)

**Comment by breck7** [comment]
I think this might be worth it, now that the dataset size is over 10MB. Over the wire it probably won't make much difference with gzipping but would save space on disk and perhaps some parse time.

Another approach to consider, for this and the csv, is to have 2 tables (maybe in separate files)with normalized data but keep the flat structure.

I think we should profile first though. I can profile the Explorer at some point next week to see if there would be a noticeable gain.

**Comment by edomt** [comment]
@behnsen Thanks for the suggestion! There's no good reason we haven't done this, only that we added the JSON option because it was more convenient for some people, but at the time we didn't think of fully formatting it in a non-relational way.

Unless we see a major downside to this, I think I'll make the change next week @breck7. This will only be for the JSON version though; for the CSV and XLSX files, we discussed this initially and voluntarily decided to denormalize the data, so that users of all skill levels would be able to use the economic & health variables without having to worry about merging files.

**Comment by behnsen** [comment]
Cool thanks, I think JSON is more convenient for developers and all others user can continue using the CSV and XLSX format. :+1: So I can prepare my little viewer app.

**Comment by edomt** [comment]
FYI, this change will be applied this evening. The new format will be:

![image](https://user-images.githubusercontent.com/7103774/86212228-ebcffc00-bb77-11ea-8e0c-d023368e922c.png)

**Comment by behnsen** [comment]
Cool, thank you very much :)
