### ISSUE TITLE
Vaccination/100

### ISSUE THREAD

**Issue by TheSheriff1965** [owid/covid-19-data#866]
What i understand, is you calculating by divide  administrated doses with population, but , is  that right? Healthy  people under age of 18 are not allowed get vaccination yet.

**Comment by edomt** [comment]
Hi @TheSheriff1965 

As you wrote, they are not allowed to be vaccinated **_yet_**. But this could very well change at some point. See for example: https://twitter.com/AP/status/1377212417701244929

Also, some countries currently restrict vaccines to people aged 16+, and others to 18+.

Using the entire population as the denominator also makes things much simpler for us, as this is also the denominator we use for the data on confirmed cases and deaths.
