### ISSUE TITLE
Missing data in victim world record holder Hungary

### ISSUE THREAD

**Issue by d4242** [owid/covid-19-data#867]
I guess JHU are using a scraper to get new data, but quite possibly due to political reasons (PM took a victory lap about 2M inoculated jabs on Monday, that, in fact, happened on Tuesday only, and that would have been revealed by the regular Tuesday morning update) official data update that, for this reason, has been messed up, and you haven't updated the database yesterday. Monday's death toll was 274, source: https://koronavirus.gov.hu/cikkek/orszagos-tisztifoorvos-magyarorszag-oltonemzet and that's missing from the DB.

Today's update was fine.

**Comment by edomt** [comment]
@d4242 We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues

**Comment by d4242** [comment]
Thank you. The identical number of 189 in the # of deaths exactly 7 days apart caused the rolling average to be flat, which was confusing.

There has been a bit of a scandal in Hungary due to the data being kept back and I thought it had the same effect on this data. Apologies for the false alarm.
