### ISSUE TITLE
UAE Data incomplete

### ISSUE THREAD

**Issue by nmprollius** [owid/covid-19-data#869]
Good day. 
The 'People Vaccinated' column for the United Arab Emirates only has two data points.
Is there new data available for this country?
Is there a different way to infer this information from the other available data?

**Comment by edomt** [comment]
Hi @nmprollius 

The column is mostly empty because we're not aware of any other existing data for the UAE that breaks down 1st and 2nd doses. Of course, feel free to let us know if you come across this information.
