### ISSUE TITLE
Tunisia mortality data missing for week 53 in 2020

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#872]
In `excess_mortality.csv` data for Tunisia there's no `53` in `time` column and no `2021-01-03` in `date`.

All other countries with `weekly` `time_unit` have these. Why the difference in case of Tunisia? Missing data at a source, or maybe an error on OWID's part?

I have noticed this when updating my charts at https://github.com/czka/covid_toll_tool/tree/main/covid_toll_ALL recently (a comparison of covid and all-cause mortality around the World). In my [script](https://github.com/czka/covid_toll_tool/blob/main/covid_toll_tool.py), I'm making an assumption that there are no gaps in `date` column, which is met for all countries except Tunisia - after `2020-12-27` (week 52 of 2020) it immediately has `2021-01-10` (week 1 of 2021). There should be `2021-01-03` in between (week 53 of 2020).

**Comment by czka** [comment]
Might be be related to #874.

**Comment by akarlinsky** [comment]
The data for Tunisia is digitized from a figure on their NSO's report. 
This is (most likely) NOT ISO weeks, so there will be no week 53 for 2015 or 2020.

We are keeping track of the monthly figures for Tunisia as well (they are much more delayed than the report), and might correct for iso weeks using it, but for now this is the best we have.

In the future, please open all these issues on [World Mortality](https://github.com/akarlinsky/world_mortality) tracker :)

**Comment by czka** [comment]
@akarlinsky OK, recorder in https://github.com/akarlinsky/world_mortality/issues/7.
