### ISSUE TITLE
Strange data for Russia vaccinations

### ISSUE THREAD

**Issue by crystalbit** [owid/covid-19-data#873]
see [/public/data/vaccinations/country_data/Russia.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Russia.csv)

latest `people_fully_vaccinated` is equal to `people_vaccinated`, but recently it was not

most of the time `people_fully_vaccinated * 2 < people_vaccinated`, it looks fine

![image](https://user-images.githubusercontent.com/12694644/113184664-23cab380-925e-11eb-91a3-59bac016f7e9.png)

**Comment by edomt** [comment]
You're right, thanks for letting us know!
