### ISSUE TITLE
El Salvador missing data in excess_mortality.csv for months 10-12

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#874]
In `excess_mortality.csv` data for El Salvador there's `1`, `2` right after `9` in `time` column, and `2021-01-31` right after `2020-09-30` in `date`.

So there's missing `10`, `11`, `12` in `time` column and `2020-10-31`, `2020-11-30`, `2020-12-31` in `date` column.

**Comment by czka** [comment]
Might be be related to #872.

**Comment by CGiattino** [comment]
Hi,

I'm the researcher at Our World in Data who maintains our excess mortality data.

Neither of these are issues in the sense that they match our source, the World Mortality Dataset. You can see [on their data here](https://github.com/akarlinsky/world_mortality/blob/main/world_mortality.csv) that, for whatever reason (likely to do with data availability), El Salvador only has data for the first 9 months of each year and Tunisia does not have data for Week 53 in 2020.

Best,
Charlie

**Comment by czka** [comment]
Thanks for taking a look, @CGiattino.

In case of El Salvador, it seems that @akarlinsky inherits this September cap from his [source](https://www.laprensagrafica.com/lpgdatos/El-pais-registra-6521-defunciones-mas-que-en-2019-20201116-0083.html). Out of sheer curiosity - any idea why would country officials skip 3 months each and every year 2015-2020 in their reporting?

The reason for a missing week 53 in 2020 of the Tunisia's data seems to be that its resolution was [changed from monthly to weekly recently](https://github.com/akarlinsky/world_mortality/commit/bb3c80e361516a9e63f3f0fab33e37d16de61e33#diff-0513e547437e72be9924e720548e903788c4f33a444785038c8d526248a1c74c) by [digitizing the plot in figure 1](https://github.com/akarlinsky/world_mortality/commit/bb3c80e361516a9e63f3f0fab33e37d16de61e33#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R352) of @akarlinsky's [source for Tunisia](http://www.ins.tn/fr/publication/dynamique-récente-de-la-mortalité-en-tunisie), with that figure being capped at week 52 regardless of how many weeks there actually were in each year 2015-2020.

**Comment by CGiattino** [comment]
@czka Hmm that is a good question about El Salvador — I can't think of a particular reason why the data ends at September. If I were venturing a guess I'd say it has to do with constraints on El Salvador's death reporting infrastructure. And maybe because they only have data through September 2020 they decided they only needed to publish data from 2015–2019 through September. But this is merely a guess.

Good to know about Tunisia, thanks for looking into that.

**Comment by akarlinsky** [comment]
Hi, the source is indeed us. I have also opened an issue about it in our tracker: [https://github.com/akarlinsky/world_mortality/issues/6](https://github.com/akarlinsky/world_mortality/issues/6).

In short, our source for El Salvador is this [news report](https://www.laprensagrafica.com/lpgdatos/El-pais-registra-6521-defunciones-mas-que-en-2019-20201116-0083.html) who obtained information from El-Salvador Population Registry and it only showed data up to September 2020 with the corresponding info from 2015 to 2019. We are in contact with one of the authors of this piece and hope to update El Salvador data sometime soon.

**Comment by czka** [comment]
@CGiattino, @edomt Could you include the missing months for San Salvador as they were recently added in @akarlinsky's dataset [1]?

[1] https://github.com/akarlinsky/world_mortality/commit/11776694cd3a81304b6750185819d307c82d9b5f

**Comment by czka** [comment]
@edomt, @CGiattino 
Could you re-open this ticket so that we don't lose the issue from sight?

**Comment by CGiattino** [comment]
Hi @czka,

Yes, we will include this new data for El Salvador when we update our dataset this week, likely tomorrow but possibly this weekend (depends on when one of our sources, then Human Mortality Database, publishes their new data).

Best,
Charlie

**Comment by czka** [comment]
Hey, that's great! Thank you.

**Comment by CGiattino** [comment]
Hi, this data is now updated on our site to match the World Mortality Dataset data: https://ourworldindata.org/grapher/excess-mortality-raw-death-count?country=~SLV

**Comment by czka** [comment]
@CGiattino Ok. I meanly meant https://github.com/owid/covid-19-data/blob/master/public/data/excess_mortality/excess_mortality.csv though. 

Is it going to be updated, too?

**Comment by CGiattino** [comment]
Yes, @edomt will update that file in the coming days.

**Comment by czka** [comment]
Perfect.

**Comment by edomt** [comment]
@czka The file has now been updated.
