### ISSUE TITLE
Anomalies in people vaccinated corresponding to join with "high priority cdc" data

### ISSUE THREAD

**Issue by free-soellingeraj** [owid/covid-19-data#883]
I am looking at the dataset for US States and finding that there are anomalies in which the total people vaccinates goes down day-to-day.  For example, 2021-02-21 in the District of Columbia has a situation where the number of `people_vaccinated` goes from 109,045 (15.5% of 2019 census) to 71,399 (10.1% of 2019 census).  I looked at the commits and it looks like a special commit was merged in marked as the cdc.  I am in the process of identifying all places where `people_vaccinated` goes down day-to-day.

**Comment by free-soellingeraj** [comment]
Here is the list of all dates/states on which the `people_vaccinated` variable goes non-monotic:
```
{'Arizona': [Timestamp('2021-02-22 00:00:00')],
 'Colorado': [Timestamp('2021-01-23 00:00:00')],
 'Connecticut': [Timestamp('2021-03-13 00:00:00')],
 'Delaware': [Timestamp('2021-02-22 00:00:00')],
 'District of Columbia': [Timestamp('2021-02-22 00:00:00')],
 'Florida': [Timestamp('2021-01-25 00:00:00'),
  Timestamp('2021-02-22 00:00:00')],
 'Georgia': [Timestamp('2021-02-22 00:00:00')],
 'Hawaii': [Timestamp('2021-01-23 00:00:00')],
 'Iowa': [Timestamp('2021-01-14 00:00:00')],
 'Louisiana': [Timestamp('2021-02-22 00:00:00')],
 'Missouri': [Timestamp('2021-02-22 00:00:00')],
 'New Jersey': [Timestamp('2021-01-14 00:00:00')],
 'North Carolina': [Timestamp('2021-02-22 00:00:00')],
 'North Dakota': [Timestamp('2021-02-22 00:00:00')],
 'Tennessee': [Timestamp('2021-02-22 00:00:00')],
 'Texas': [Timestamp('2021-02-25 00:00:00'), Timestamp('2021-03-24 00:00:00')],
 'Utah': [Timestamp('2021-02-22 00:00:00')],
 'West Virginia': [Timestamp('2021-02-22 00:00:00')]}
```
If possible, please advise on the meaning of this?  For example, should I nullify all observations prior to these dates as they indicate a correction?

**Comment by edomt** [comment]
Hi @free-soellingeraj 
See #698
