### ISSUE TITLE
public/data/owid-covid-data.csv

### ISSUE THREAD

**Issue by odadoun** [owid/covid-19-data#89]
Hello,

first of all thanks to provide  Covid data files.
At the end of the owid-covid-data.csv  file there are those lines 
....
,,International,2019-12-31,0.0,0.0,0.0,0.0,,,,,,,,,,,,,,,,,,,,,,,,,,
,,International,2020-01-01,0.0,0.0,0.0,0.0,,,,,,,,,,,,,,,,,,,,,,,,,,
....
Does lines are needed ? is not can you remove it ?
by advance thank you
olivier

**Comment by edomt** [comment]
Hi @odadoun 

These rows are necessary, they refer to deaths that are registered outside a specific country. 696 international COVID-19 cases and 7 international deaths have been registered.

Edouard
