### ISSUE TITLE
UK tests_total blip 2020-06-20

### ISSUE THREAD

**Issue by Luke-Shaw** [owid/covid-19-data#90]
**On 2020-06-20 for United Kingdom total_tests = 2470849 when should be ~ 4300000**. Could be that I've misunderstood something.

Example (R code):

`library(tidyverse)`
`library(lubridate)`
`df <- readr::read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv")`

Query:
`df %>% `
`  dplyr::filter(location == "United Kingdom") %>% `
`  dplyr::filter(date >= lubridate::date("2020-06-19") &`
`           date <= lubridate::date("2020-06-21")) %>% `
`  select(date, total_tests, new_tests)`
Output:
| date | total_tests|  new_tests |
|-------|----------|----------|
2020-06-19  | 4243159 | 70274
2020-06-20  | 2470849 | 36118
2020-06-21  | 4350405 | 43525

**Comment by edomt** [comment]
Hi @Luke-Shaw 

This was due to an error with a date in the CSV file published by the UK government. This has now been fixed—thanks for flagging it!

Edouard
