### ISSUE TITLE
Indonesia Vaccination Data 

### ISSUE THREAD

**Issue by siwalan** [owid/covid-19-data#902]
Since at least 22 March 2021, Indonesia has been using AstraZeneca Vaccine. Indonesia managed to get doses of AstraZeneca via the COVAX distribution mechanism.

https://www.tribunnews.com/corona/2021/03/22/suntikan-perdana-vaksin-covid-19-astrazeneca-di-indonesia-diberikan-kepada-para-kiai-di-jawa-timur

The vaccine used in the Indonesia Vaccination data should be updated to represent the usage of AstraZeneca.

**Comment by edomt** [comment]
Thank you, we'll add this today.
