### ISSUE TITLE
string instead of float value

### ISSUE THREAD

**Issue by odadoun** [owid/covid-19-data#91]
Inside the file
https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
there are 'tests performed' and I think it should be  of a float value.
Con you confirm ?
Thanks
For instance:
ARG,South America,Argentina,2020-05-10,5763.0,165.0,... tests performed ,85.19,...

**Comment by edomt** [comment]
Hi @odadoun 

The column you're referring to is a string column named `tests_units`, which represents the units used by the location to report its testing data. All variables in our complete dataset are defined in our codebook: https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data-codebook.md

Edouard
