### ISSUE TITLE
Portugal vacination data is delayed

### ISSUE THREAD

**Issue by trapko91** [owid/covid-19-data#918]
Since the end of March the vaccination data for Portugal is delayed and it strangely went back from March 29 (or close) to March 22 numbers. I was only using Our World In Data website to track it so I don't know how was the data being stored / sourced here.

Although the current data source ([https://covid19.min-saude.pt/relatorio-de-vacinacao/](https://covid19.min-saude.pt/relatorio-de-vacinacao/)) is official, it is only the detailed weekly report that is always a week (or more) late.

This is the official URL for the daily update [https://www.sns.gov.pt/monitorizacao-do-sns/vacinas-covid-19/](https://www.sns.gov.pt/monitorizacao-do-sns/vacinas-covid-19/) with the current administred 1st doses, 2nd doses and total doses until the displayed date at the bottom. Also, there is an unofficial but widely usued website that closely tracks the official one: [https://www.vacinacaocovid19.pt/](https://www.vacinacaocovid19.pt/).

Cheers!

**Comment by ASGirc** [comment]
Thank you, came here to say the exact same thing!

**Comment by edomt** [comment]
The main issue that makes all of this very complicated is how to account for Azores and Madeira. The weekly reports are the only source that includes them — the daily-updated data is only for continental Portugal. We've been in touch with a government official from the ministry of health, and they asked us to use the weekly reports for now. But they also said that the autonomous regions were in touch with the IT people from the MoH to work on connecting their data, in order to provide real time national updates.

**Comment by trapko91** [comment]
Yes, I later realised that and thought that it was probably the issue because Madeira and Azores data was only recently added.

Althought I do not speak for the Portuguese Government whatsoever, I recommend that you should stick with the continental data for coherence, or just sum the islands' weekly data and the continental daily data, as that would be the more logical and up to date solution until the government provides the full daily update. As it stands, it's a little bit useless for many Portuguese who  use OWID to watch and compare data with other countries.

It's just a suggestion, do whatever you feel is better for the dataset consistency. It's just a little odd to discard the daily data when it accounts for 96% of the vaccinations and make it pointless (literally ahah) because 4% is late.

**Comment by edomt** [comment]
Solved in 6771162d4ba7da19f32e221ba3fdb962943767f3
