### ISSUE TITLE
Percentages question

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#919]
Thanks for all your hard work getting the figures. This is more a question than anything being wrong. I see some countries are putting the vaccination percentages in terms of Adult population (presume 18 years and older) rather  than the population as a whole. For me I think we should do it as the whole population anyone got any thoughts?

**Comment by edomt** [comment]
This is a question that we get asked frequently. For now, we plan to keep using the entire population as the denominator, for 2 main reasons:

- Children transmit can transmit the virus just like adults, so the general estimates that are sometimes given for herd immunity (60-70%) should be understood in terms of the entire population;
- Right now, no vaccine is being given to children, but there's no certainty that this will remain true in the future (some clinical trials are under way to see if the vaccines are safe and efficient for individuals below 16 years old).
