### ISSUE TITLE
Why the sum of all continents total_vaccinations is not equal to World total_vaccinations？

### ISSUE THREAD

**Issue by melissaya** [owid/covid-19-data#926]
location | date | total_vaccinations

Asia | 2021-04-04 | 293300639
North America | 2021-04-04 | 182886733
South America | 2021-04-04 | 40938630
Oceania | 2021-04-04 | 911848
Europe | 2021-04-04 | 134883092
Africa | 2021-04-04 | 11820893

World | 2021-04-04 | 664643866

The sum of all continents total_vaccinations is 664741835, While the World total_vaccinations is 664643866.

Why?

**Comment by edomt** [comment]
Thank you @melissaya for letting us know. @lucasrodes has identified the issue, and the data has now been fixed.
