### ISSUE TITLE
json data is missing testing data

### ISSUE THREAD

**Issue by steveskarda** [owid/covid-19-data#93]
Testing data was lost after the July 1 reorganization of json.   The data is still present in Excel but missing from json.

**Comment by edomt** [comment]
Hi @steveskarda 

Can you please check again this file? https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.json

The testing data is present in the file, and no other use has reported any issue.

![image](https://user-images.githubusercontent.com/7103774/86400641-47e66d80-bca9-11ea-94ba-7151c870e4b1.png)

**Comment by steveskarda** [comment]
The data you are showing below is missing the testing data that was present in the json prior to July 1 and is present in the Excel.

Specifically, total_tests, new_tests, total_tests_per_thousand, new_tests_per_thousand, new_tests_smoothed, new_tests_smoothed_per_thousand, tests_units

**Comment by edomt** [comment]
I can see all of these variables in this file: https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.json
Can you please re-download the file and check? All the testing data is there (when it's available in our dataset of course), in the "data" array for each country.

For example here's what it shows for Belgium on March 27th:

![image](https://user-images.githubusercontent.com/7103774/86401272-3a7db300-bcaa-11ea-9a8a-a9dfcff43dff.png)

**Comment by steveskarda** [comment]
My apologies.  You are correct.      I am using PowerBI and it seems to drop that data when I expand the table under the new format so the problem is indeed on end.

Thank you for all you do providing this data.  It is very important to us and we appreciate it.
