### ISSUE TITLE
United Kingdom new cases −29726,0

### ISSUE THREAD

**Issue by kurval** [owid/covid-19-data#95]
Hi, I noticed that todays  new cases data includes:

2020-07-03 | United Kingdom | −29726,0

Is this bug or correction to data?

**Comment by edomt** [comment]
Hi @kurval 

This is not a bug, but indeed a data correction. More information is available in those tweets by @HannahRitchie:
https://twitter.com/_HannahRitchie/status/1278991659083214848
https://twitter.com/_HannahRitchie/status/1278993237114576907

> Just did today's COVID data update. You will notice massive 'negative' cases for UK today. This is because UK Gov't are undergoing major historical revision of its cases time series. This means today's cumulative cases are much lower than yesterday. Details on UK Gov't dashboard: http://coronavirus.data.gov.uk

Edouard
