### ISSUE TITLE
Adding up European totals

### ISSUE THREAD

**Issue by djbrown13** [owid/covid-19-data#954]
Hello,

First off, this dataset is fantastic and very helpful! And in the grand scheme of things our issue is minor. That said, in the vaccinations CSV there are aggregates for regions, and we are trying to replicate the given totals for Europe by adding together the data of individual countries. On the [OWID site](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=latest&pickerSort=desc&pickerMetric=total_vaccinations_per_hundred&Metric=Vaccinations&Interval=Cumulative&Relative+to+Population=false&Align+outbreaks=false&country=ALB~AND~AUT~BLR~BEL~BIH~BGR~HRV~CYP~CZE~DNK~EST~FIN~FRA~DEU~GRC~HUN~ISL~IRL~ITA~OWID_KOS~LVA~LIE~LTU~LUX~MLT~MDA~MCO~MNE~NLD~MKD~NOR~POL~PRT~ROU~RUS~SMR~SRB~SVK~SVN~ESP~SWE~CHE~UKR~GBR~VAT) you can customize the graphic to "All European countries" and we are using that resulting list (of 43 countries). But doing so we come up just a bit short on the sums for total_vaccinations, people_vaccinated, and people_fully_vaccinated. 

Is there a definitive list somewhere of which individual countries are combined to arrive at the Europe totals? I should also add we are able to perfectly replicate the European Union totals by adding up the EU27 countries.

Thank you!

**Comment by lucasrodes** [comment]
Hi @djbrown13, 
Thanks for your message!

Just to check that I understood you correctly:
What you did was getting the list of 43 countries using our explorer and then added up the numbers for these countries and that number is different than the one for Europe in [vaccinations.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv), right?

Now, on our side, to obtain the numbers for Europe we use [this table](https://github.com/owid/covid-19-data/blob/master/scripts/input/owid/continents.csv) to sum the corresponding countries.


Let me know if you find what's missing and thanks once again for reporting!

**Comment by lucasrodes** [comment]
I just did a quick check and appears that in your chart following locations are missing: 'Faeroe Islands', 'Gibraltar', 'Guernsey', 'Isle of Man', 'Jersey'.

I modified your initial chart to display these: [see here](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=latest&pickerSort=desc&pickerMetric=total_vaccinations_per_hundred&Metric=Vaccinations&Interval=Cumulative&Relative+to+Population=false&Align+outbreaks=false&country=ALB~AND~AUT~BLR~BEL~BIH~BGR~HRV~CYP~CZE~DNK~EST~FIN~FRA~DEU~GRC~HUN~ISL~IRL~ITA~OWID_KOS~LVA~LIE~LTU~LUX~MLT~MDA~MCO~MNE~NLD~MKD~NOR~POL~PRT~ROU~RUS~SMR~SRB~SVK~SVN~ESP~SWE~CHE~UKR~GBR~VAT~FRO~GIB~IMN~JEY~GGY).

**Comment by djbrown13** [comment]
Hi @lucasrodes 
Thanks for the quick response! I was just about to look through the continents.csv file (sorry I hadn't found that before) but you saved me the time! I'll add those five entities to our list.
Thanks again!

**Comment by lucasrodes** [comment]
No problem at all 😄!
I'll close this issue, but feel free to reopen if the problem persists.
