### ISSUE TITLE
Monotonicity Requirement for Total Cases

### ISSUE THREAD

**Issue by SEllersgaard** [owid/covid-19-data#97]
In the total_cases.csv (a cumulative table) numbers can only increase or flatline. Yet on July 2 there were 313483 total cases in the UK and the day after 283757 total cases. Similar issues seen for several other countries.

**Comment by jarib** [comment]
See the note here https://github.com/owid/covid-19-data/tree/master/public/data#our-data-sources

Especially: 

> This also means that negative values in cases and deaths can sometimes appear when a country sends a correction to the ECDC, because it had previously overestimated the number of cases/deaths.

This is exactly what's happening in the the UK data currently, as ECDC notes:

> Note: On 3 July the UK announced an ongoing revision of historical data that may lead to a decreased number of cases. Data will be retro-corrected accordingly.
