### ISSUE TITLE
Number of confirmed new cases shown as sub zero for UK, Ecuador, etc

### ISSUE THREAD

**Issue by teelmo** [owid/covid-19-data#98]
Number of confirmed cases is sub zero for 16 rows in total in the open data. 

Can be also seen here:
https://ourworldindata.org/coronavirus/country/united-kingdom?country=~GBR

and here:
https://ourworldindata.org/coronavirus/country/ecuador?country=~ECU

location | date | total_cases | new_cases
-- | -- | -- | --
United Kingdom | 2020-07-03 | 283757 | -29726
Ecuador | 2020-05-07 | 29420 | -2461
Ecuador | 2020-05-09 | 28818 | -1480
France | 2020-06-03 | 151325 | -766
Spain | 2020-04-19 | 193252 | -713
United Kingdom | 2020-05-21 | 248293 | -525
Spain | 2020-05-25 | 235400 | -372
Benin | 2020-05-20 | 130 | -209
Portugal | 2020-05-03 | 25190 | -161
Italy | 2020-06-20 | 238011 | -148
Uganda | 2020-05-21 | 145 | -115
Lithuania | 2020-04-29 | 1344 | -105
Ecuador | 2020-05-12 | 29509 | -50
San Marino | 2020-05-11 | 628 | -9
International | 2020-03-10 | 696 | -9
Uganda | 2020-06-02 | 457 | -1

**Comment by edomt** [comment]
See https://github.com/owid/covid-19-data/issues/66
