### ISSUE TITLE
Is it equivalent to use people tested, samples tested, and tests performed?

### ISSUE THREAD

**Issue by qgallea** [owid/covid-19-data#984]
Dear Madam, Sir, in the testing data, for the entity field, you have the country name and then: people tested, samples tested, or tests performed. How should we deal with this? the total cumulative and positivity rate are comparable across those categories or not?

Have a pleasant day,
Quentin

**Comment by edomt** [comment]
Dear Quentin,

Generally, the testing data is probably the type of COVID-19 data that has the lowest comparability across countries: there are many ways in which the counting methods can differ (including units, but also whether quick antigen tests are counted or not). This data can be used for:

- very broad comparisons: regardless of different counting methods, a country that has a positive rate of 0.5% is obviously in a better situation than a country with a positive rate of 25%;
- monitoring the trend inside a country: for a given country where the methodology stays constant, the data can be used to evaluate how the epidemic evolves.

Beyond these two cases, users should be very careful about cross-country comparisons when positive rates are broadly in the same order of magnitude.
