### ISSUE TITLE
Question re: vaccines administered vs authorized

### ISSUE THREAD

**Issue by technickle** [owid/covid-19-data#989]
Hi - in [vaccinations.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/locations.csv), the metadata explains that the `vaccines` field is a list of vaccines administered in the country up to the current date.

Recently [several European countries have suspended the use of the Oxford-AstraZeneca vaccine](https://www.itv.com/news/2021-04-07/astrazeneca-vaccine-timeline-of-whats-happened-since-european-countries-suspended-use-of-covid-jab). Since the above dataset and definition doesn't account for this event, are you tracking information such as authorized vaccines anywhere/elsewhere?

Thanks!

**Comment by edomt** [comment]
Hi @technickle 

No, we're not tracking this type of short-term change anywhere on our side. Our `vaccines` field is meant as helpful metadata to get a sense of which vaccines have started to be used by each country, but it's unfortunately very difficult to accurately keep track of this for all countries in real time.

I know that a few other websites are tracking this more regularly, e.g. https://covid19.trackvaccines.org/, but we haven't really checked how good their data is.
